app.py
requirements.txt
static/sass/styles.scss
templates/404.html
templates/snap-details.html
tests.py

Fixes #3
Fixes #4
- A snap details template
- A default view to process all URLs matching `/<something>`
- Only look for public snaps in the stable channel
- Cause a 404 with a custom error message if snap not found
- Use vanilla markup syntax ready for merging with #10
Could the relevant people please comment on these implementation details to let me know if they seem sensible.
I am only passing through certain data to the template, according to what @matthewpaulthomas listed in https://github.com/CanonicalLtd/snappy-design-squad/issues/69#issuecomment-320259725 - I am providing all the data with ticks next to them, except the geo location data which isn't yet available.
The data that's passed through can easily be updated in `app.py`, but each datum should always be explicitly passed …

Snap details page

---

package.json
static/sass/styles.scss
templates/404.html
templates/_layout.html
templates/snap-details.html
yarn.lock

Adds simple responsive layout to snap details page.
Fixes #14
```
python3 -m venv env3
source env3/bin/activate
pip install -r requirements.txt
yarn install
FLASK_APP=app.py FLASK_DEBUG=true flask run
```
Now browse to:
http://127.0.0.1:5000/canonical-livepatch/
http://127.0.0.1:5000/documentation-builder/
http://127.0.0.1:5000/non-existent-snap/
And check each page shows what is expected.

Added basic grid layout to snap detail page

---

run

The old node image was actually preventing node-sass installing properly. So we use the new node image which *downgrades* to Node 7.
QA
--
``` bash
./run clean
./run
```

Use latest node image in ./run

---

templates/snap-details.html

Updated styles for snap description and details table.
Fixes #18 
Fixes #19 
- ./run
- Visit http://localhost:8022/gnome-calculator/ or http://localhost:8022/dwarf-fortress/
- Snap description and details table should have vanilla styles as per design

Vanilla styling for description and snap details

---

static/sass/styles.scss
templates/snap-details.html

Added Vanilla styling for snap details banner (icon, name & install button).
Fixes #17
Designs: https://github.com/CanonicalLtd/snapcraft-design/issues/54#issuecomment-326014685
From the designs it looks it was meant to be similar to Media Pattern (https://docs.vanillaframework.io/en/patterns/media-object), but Media Pattern is much smaller (icon and heading) and simply doesn't look good as a main object on the top of the page.
We probably need a bigger variant of media pattern for that.
I added a proposal for that (https://github.com/vanilla-framework/vanilla-framework/issues/1315)

Vanilla styling for snap details and install button

---

app.py
templates/snap-details.html

I noticed that we were using the `title` for both the "heading" and in the snap URL (`snap://{{ name }}`). This was my mistake - because `title` and `package_name` happened to be the same for `canonical-livepatch` I thought they were always the same.
I'm now passing through `snap_title` and `package_name` separately, and using them where appropriate.
QA
--
`./run` and visit <http://0.0.0.0:8022/dwarf-fortress/>. Check the "install" link works.

Rename title and add package_name

---

app.py
package.json
requirements.txt
static/sass/styles.scss
templates/snap-details.html
yarn.lock

**Proposal**. I don't know if we want this feature, but here's an example of how we might handle markup and URLs in snap descriptions.
This will:
- Remove any dangerous tags (e.g. `<script>`) from descriptions
- Allow safe markup tags (e.g. `<strong>`) in descriptions, and render them properly
- Add `<a rel="nofollow">` tags to URLs found in text
- Add `rel="nofollow"` to existing link tags
QA
--
`./run`, then visit <http://0.0.0.0:8022/dwarf-fortress/> and see the links are clickable! I'm not sure if there's an example of a snap with markup in its description, but if one exists we could try it out as well.

Sanitise and linkify markup

---

static/sass/styles.scss
templates/_layout.html

Simple Vanilla footer.
Doesn't include social icons as there is currently no pattern to do them without additional custom styles.
Fixes #16

Simple Vanilla footer

---

static/sass/_patterns_media-object--large.scss
static/sass/styles.scss
templates/snap-details.html

Added variant classes to current Vanilla Media Object pattern according to snap details page design.
This includes `--large` variant of media image and `--large` variant of media content (for correct spacing).
Large screen:
Small screen:
Fixes #43 
QA:
- ./run serve
- Go to any snap details page
- Snap details (icon, title, etc) should use modified Vanilla media pattern

Added large variant for media object pattern for snap details

---

static/sass/_patterns_table-key-value.scss
static/sass/styles.scss
templates/snap-details.html

Added new key-value table pattern.
- ./run
- Go to any snap page
- Snap details table should have new style
As discussed, implemented a design with borders between the rows (but no border at the bottom of the table).

Table key value pattern proposal

---

package.json
yarn.lock

Updated Vanilla to 1.5.2 (that includes white heading).
Fixes #40 
- ./run
- Go to snap details page
- Heading should be white

Updated Vanilla to 1.5.2 (including white heading)

---

app.py
templates/snap-details.html

This makes use of the public geodata API that @cprov built.
At present I'm requesting a month of historical data about the percentage of users of a specific snap in each country.
The API returns the data broken down into days, so I am averaging all the days of data returned over the last month to return a single figure. This should hopefully help to avoid anomalous activity that might have happened e.g. in the last 24 hours.
Fixes #52 
QA
--
``` bash
./run
```
Go to a snap page, e.g. <http://0.0.0.0:8022/lxd/>, and view source. You should see the geodata precentages pretty clearly in the source code.

Expose geodata to the template

---

templates/snap-details.html

Added install info for non-linux systems as described in #45 
Fixes #46
- ./run
- Go to snap details page on Mac or Windows
- Info text should be displayed with a link to Ubuntu
Alternatively use demo: http://snapcraft-flask-pr-57.run.demo.haus/gnome-calculator/

Added info for non-linux systems

---

static/sass/styles.scss
templates/_layout.html

Implements footer updates as defined in #47
Fixes #48 
- ./run
- open snap details page
- Footer should have updated styles

Updated footer styles

---

Dockerfile

This is for building production images for deployment on Kubernetes
QA
--
``` bash
./run build  # Build CSS files
docker build --build-arg commit_id=`git rev-parse --short HEAD` -t snapcraft.io .  # Build the image
docker run -ti -p 8077:80 snapcraft.io  # Run the image
```
Visit <http://127.0.0.1:8077/lxd/>, see that the site looks as it should.

Dockerfile similar to www.ubuntu.com

---

.sass-lint.yml
app.py
static/sass/index.scss
templates/index.html
tests.py

**Please review https://github.com/canonical-websites/snapcraft-flask/pull/58 first**
Since K8s won't let me do the routing quite as I wanted, it's easier to just move the homepage into this app.
Ultimately this app should serve the homepage anyway. The way it's done here isn't ideal, so I've filed https://github.com/canonical-websites/snapcraft-flask/issues/59 to do soon, and made it high priority.
QA
--
``` bash
./run
```
Go to <http://127.0.0.1:8022>, see that it looks identical to <https://snapcraft.io>.
Now go to <http://127.0.0.1:8022/lxd/> and see a snap details page. Also go to <http://127.0.0.1:8022/missing> and see a 404 page.

Move homepage from snapcraft.io-static-pages

---

app.py

Redirect /community to the homepage, as it was in the old
[snapcraft.io-static-pages repo](https://github.com/canonical-websites/snapcraft.io-static-pages/).
Redirect /docs to docs.snapcraft.io. This is in preparation for when
docs.snapcraft.io becomes the home of snapcraft docs. It won't effect
anything right now, because [kubernetes takes care of](https://github.com/canonical-webteam/k8s-deployments/blob/master/staging.snapcraft.io/snapcraft.io-ingress.yaml#L27) routing /docs to
the docs application, before it hits this application.
QA
--
Run the server in one terminal window:
``` bash
$ ./run
```
In a different terminal window, check `/community/` redirects to the 
homepage, and `/docs/some/page` redirects to `docs.snapcraft.io`:
``` bash
$ curl -sI 127.0.0.1:8022/community/ | grep …
```

Redirects for docs and community

---

templates/index.html

Updated 'Get crafting' paragraph with rocket chat instead of IRC
Fixes #64 
- ./run
- go to home page
- Get crafting section should contain link to rocket chat instead of IRC

Updated community links (rocket chat instead of IRC).

---

Dockerfile

QA
--
``` bash
./run build
docker build --tag snapcraft.io .
docker run -ti -p 80:80 snapcraft.io
```
Now go to <http://127.0.0.1:80>, and then check back in the terminal and see you get output telling you that `/` has been hit.

Add logging to stdout/stderr production units

---

package.json

Updated build script to add prefixes both to `styles.css` and `styles.min.css`.
- ./run build
- both  `styles.css` and `styles.min.css` should contain browser prefixes
Or:
- ./run
- go to snap page in Chrome
- external links icon should show up properly

Using autoprefixer both in minified and non-minified styles

---

package.json

With update of ./run script watch task was updated and started pointing at incorrect scss folder.
This fix reverts watch script back to point to correct static/scss path.
`./run watch`
Files in static/scss should be built and watched for changes

Fixing watch script to look at correct scss path

---

app.py
requirements.txt
templates/snap-details.html

Now we pass through:
``` python
{
"{ 3-digit code }": {
"name": "{ country name }",
"code": "{ 2 letter code }",
"percentage_of_users": "{ percentage of users of this snap from this country }"
},
...,
"unknown": {
"name": None,
"code": None,
"percentage_of_users": "{ percentage of users without country data }"
}
}
```
Fixes #74
QA
--
``` bash
./run
```
Now browse to <http://0.0.0.0:8022/lxd/> and view source to see the table of new country data.

Provide more country data to templates

---

templates/index.html

These now 404. Step one is to drop these links. A follow on PR will find apps we can link to replace these.

Drop links to JetBrains snaps

---

Dockerfile

Provide the ID of the commit at which point the code was built, as a HTTP header in the response from the docker container.
For production - so we can easily see which version of the code is running on a unit.
QA
--
``` bash
$ docker build .  # Check it complains without COMMIT_ID
The command '/bin/sh -c test -n "${COMMIT_ID}"' returned a non-zero code: 1
$ docker build --tag snapio --build-arg COMMIT_ID=`git rev-parse HEAD` .  # Build with COMMIT_ID
$ docker run --rm --name snapio-throwaway --daemonize --publish 8097:80 snapio
$ curl -I localhost:8097 | grep 'X-'
X-commit-ID: 018f47199c3709e9d0bceb33bef30546ee76e820
X-Hostname: 096dbd5ae462
$ docker kill snapio-throwaway
```

Make sure COMMIT_ID is an environment variable

---

app.py
templates/snap-details.html

I've just put it at the bottom of the key-value table for snap info at the moment.
However, this will need a UX review to check it's okay.
Fixes #77
QA
--
`./run`, go to e.g.: http://0.0.0.0:8022/dwarf-fortress/.
It's probably also worth trying a few different snaps just in case one of them has a long license, to see if that looks okay.
If it doesn't look okay, maybe I should comment out the template change to get this PR merged, and then let a frontender take over.

Show license information

---

templates/snap-details.html

Fixes #99 
Hiding snap details map until we can show correct data.
- ./run serve
- go to snap page (http://localhost:8022/dwarf-fortress/)
- map should not be visible

Hiding snap details map until we get correct data from API

---

app.py
templates/search.html
templates/snap-search.html

Added the search endpoint on the server. It renders a temporary page that diplays a JSON of the searched result. For the moment the search response isn't modified from what I receive from the [snapcraft search API](https://search.apps.ubuntu.com/docs/#id5).
- `./run`
- http://0.0.0.0:8004/search?q=web&limit=2&offset=60
- Play with the limit and the offset (on the url :smile:) and check that the results are different.

Add search endpoint

---

app.py
templates/search.html

Fixes #107 
Added basic HTML for search input and only showing useful info in search results.
- ./run serve
- Go to http://localhost:8022/search?q=core
- Use search input to search for something else

Basic HTML for search input

---

templates/index.html

Link to docs, not tutorials.ubuntu.com, for "Learn to craft your first snap"

---

templates/search.html

Added basic Vanilla based HTML for search results.
- ./run
- Go to search https://localhost:8004/search
- Search for some snaps
- Results should show up as Vanilla Media object pattern
Or try demo:
http://snapcraft.io-pr-141.run.demo.haus/search?q=gnome&limit=10&offset=0

Simple HTML for search results using Vanilla media object pattern

---

static/sass/_search-form.scss
static/sass/styles.scss
templates/search.html

Fixes #109 
Done:
- added Vanilla form styling to search input
- truncating snap descriptions to 200 characters
- improved pagination styling
QA:
- ./run
- go to search page: http://localhost:8004/search
- search with results: http://localhost:8004/search?q=gnome
- search without results: http://localhost:8004/search?q=nothing
Or try demo at: http://snapcraft.io-pr-142.run.demo.haus/search

Added Vanilla styling to search form, improved styles of results.

---

templates/search.html

Fixes #147
As discussed on review meeting:
- removed URL from under snap name
- moved publisher info up under snap name
QA:
Go to: http://snapcraft.io-pr-149.run.demo.haus/search?q=phone
- in search results under snap name there should be a publisher name (not linked URL)

Removes URL and moves publisher up in snap search results.

---

templates/snap-details.html

Fixes #153 
Brings the map back to snap details page.
Go to any snap page:
http://snapcraft.io-pr-154.run.demo.haus/core/
http://snapcraft.io-pr-154.run.demo.haus/gnome-calculator/
Map should be shown.

Adds map back to snap details page

---

static/sass/_patterns_sticky_footer.scss
static/sass/styles.scss
templates/_layout.html

Fixes #146 
Adds new pattern to make footer stick to the bottom of the page when there is little content on the page.
QA:
Go to:
http://snapcraft.io-pr-151.run.demo.haus/search
or
http://snapcraft.io-pr-151.run.demo.haus/core/
Footer should be at the bottom of the screen.

Adds sticky footer pattern

---

app.py

In Flash, if you define a route as `/something` it will *only* apply
*without* the slash.
If you define it as `/something/` (with a slash on the end) it will
redirect /something -> /something/. This is what we want in most cases,
and in this case.
QA
--
``` bash
$ ./run serve --detach
$ curl -I http://127.0.0.1:8004/discover/
HTTP/1.0 200OK
...
```

Accept /discover with or without slash

---

app.py
templates/discover.html

Add function to get the featured snaps
When the discover page is added the return of this function needs to be added to the template.
This pr is in prerparation for the discover page, so not possible to QA for now. 
You can print the return of the function on the homepage to see that you get a result.
But basically I am just calling this endpoint:
```
curl "https://api.snapcraft.io/api/v1/snaps/search?confinement=strict,classic&q=&section=featured"
```

Add get feature snaps function

---

package.json
yarn.lock

Update the Vanilla dependency to v.1.6.3
- I struggled to get this site to run well on my machine
- After running `./run` the minified file is not created and have a different filename (index.css vs styles.css)
@bartaz @nottrobin do you know why?
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1470

Update the Vanilla dependency to v.1.6.3

---

app.py

The map was previously showing usage averaged over the preceding month.
@cprov was concerned that this might not show fresh enough data for new
snaps, so I'm changing it to show an average over the last week.
Fixes #167
QA
--
``` bash
./run
```
go to e.g. <http://0.0.0.0:8004/lxd/> and check the map still works.
Try to find cases of fairly new snaps where the data looks different than on live. Or if you can't find any, just trust that it's working ;)

Average map data over a week

---

app.py
templates/discover.html
templates/index2.html
templates/search.html
templates/snap-details.html

Adds featured snaps from store API to discover page.
Also updates featured snaps on home page to make them clickable as a whole block.
Fixes #162 
- ./run
- Go to http://localhost:8004/discover
- Featured snaps should be shown
Or: http://snapcraft.io-pr-166.run.demo.haus/discover/

Discover featured snaps

---

templates/index.html

snapcraft.io was deployed with the wrong set of quotes. [The spec has](https://docs.google.com/document/d/1f0JLEcM3d9eAbM-adKaN96E9wWYGCyUSsmjQDbTa0l8/edit) Heroku, .NET, and Sea Machines.
This branch fixes it:

Replace Elementary with .NET quote

---

app.py
templates/_layout.html
templates/index.html

Updates footer copyright notice on directory pages (discover, search, snap details) so it contains full copyright of Canonical and Ubuntu.
- ./run serve
- go to http://localhost:8004/discover http://localhost:8004/lxd
- footer should contain "© 2017 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd."

Fixes copyright notice in footer of directory page layout.

---

templates/index.html

[The spec](https://docs.google.com/document/d/1f0JLEcM3d9eAbM-adKaN96E9wWYGCyUSsmjQDbTa0l8/edit) has the language guides as the target for the main call to action. However, the site currently points at tutorials.ubuntu.com (which tells them to install Ubuntu Core, amongst other erroneous things).
This branch fixes the CTA to point at the language guides.

Match the spec by pointing at the language guides

---

templates/discover.html

Fixes #163
Adds "Why use snaps?" section to discover page.
Copy doc: https://docs.google.com/document/d/1ZSlu1S8qgiXoL8p95smo7ZWaAkTxlems8NANsk2w30k/edit
Visual design: https://github.com/canonicalltd/snapcraft-design/issues/197#issuecomment-351370582
- ./run serve
- go to https://localhost:8004/discover
- "Why use snaps?" section should be visible in the bottom of the page
or http://snapcraft.io-pr-184.run.demo.haus/discover

Adds "Why use snaps?" section to discover page.

---

templates/index.html

This branch adds the missing language guides to the front page.

Add missing language guides to the front page

---

templates/index.html

Suggestion from @jamiebennett. Say "language or framework" instead of "language" as we have guides for Electron, MOOS, ROS, and ROS 2.

Say language or framework, not just language (covers ROS, Electron, etc)

---

templates/index.html

Fixes #179 
- go to home page (http://snapcraft.io-pr-211.run.demo.haus/)
- Ubuntu logo in OS section should have correct aspect ratio (not look squashed).

Updates Ubuntu logo to fix its aspect ratio.

---

templates/_layout.html
templates/discover.html
templates/index.html
templates/promoted.html
templates/snap-details.html

Fixes https://github.com/canonicalltd/snappy-design-squad/issues/313
Adds Open Graph meta tags to snapcraft.io pages.
- go to snap detail page (http://snapcraft.io-pr-212.run.demo.haus/brave/)
- view source
- additional meta tags should be there
- try sharing demo page on facebook - nice preview should appear

Adds social media meta tags for nicer sharing.

---

app.py
authentication.py
templates/publisher/market.html

Add market endpoint with basic html page
- `./run`
- If you are logged in: http://0.0.0.0:8004/logout
- http://0.0.0.0:8004/account/snaps/INSERT A SNAP YOU HAVE ACCESS TO/market
- Should redirect to login
- There is a bug in the openid library we use so the next url is /account
- http://0.0.0.0:8004/account/snaps/INSERT A SNAP YOU HAVE ACCESS TO/market
- You should see a JSON with the metadata of you snap

Add market endpoint

---

app.py
templates/publisher/release.html

Added backend endpoint to access the release page with a basic template
- `./run`
- `http://0.0.0.0:8004/account/snaps/SNAP YOU OWN/release/`
- See data about the releases

Add realease enpoint for publishers

---

.env
app.py
requirements.txt

Added CSRF protection for the website, for this I used this [library](http://flask-wtf.readthedocs.io/en/stable/csrf.html#html-forms). Now when building forms we should add this: http://flask-wtf.readthedocs.io/en/stable/csrf.html#html-forms
This will be really tested when writing our firsts forms.
-`./run`
- No errors

Add CSRF protection library

---

app.py

Exempt CSRF protection for login view
- `./run`
- Login should work

Exempt CSRF protection for login view

---

app.py
static/js/public/snap-details/map.js
static/sass/_map.scss

Based on the mail discussion. The colors are now generated: the country which has the biggest percentage of users has the darkest color, and the rest of thecountries color adapts from the biggest country.
- `./run`
- http://0.0.0.0:8004/atom/
- Admire the beautiful use of colors

Improve colors map

---

app.py

This allows us to avoid conflicts between Dashboard modifications and s.io

Use PUT instead of POST to avoid conflicts

---

app.py
templates/publisher/market.html

Fixes #214 
Adds basic market page to edit title, summary, description and contact URL of the snap.
- Go to market page of your snap (in stable channel): http://snapcraft.io-pr-229.run.demo.haus/account/snaps/SNAP_NAME/market
- Form should appear
- You should be able to edit snap metadata

Basic snap market page

---

app.py

Add screenshots and icons to the template.
- `./run`
- http://0.0.0.0:8004/account/snaps/lukewh-test/market/
- The template should receive an object of screenshots and icon:
```
[{'hash': '...', 'filename': 'blue.png', 'type': 'screenshot', 'url': 'https://dashboard.snapcraft.io/site_media/appmedia/2018/01/blue.png'}, {'hash': '...', 'filename': 'blue.png', 'type': 'icon', 'url': 'https://dashboard.snapcraft.io/site_media/appmedia/2018/01/blue.png'}, {...}] 
```

Get screenshots on market page

---

README.md

This PR explains how to use this issue: https://github.com/canonical-websites/snapcraft.io/pull/239
- Read README and make sure there is no typo.
- Once https://github.com/canonical-websites/snapcraft.io/pull/239 is merged:
- Follow instructions to use staging apis
- `./run`
- Urls used should be stagings urls and data

Update README with stagings URLs

---

app.py

Fixes #207 
- ./run
- visit snap details page on android phone (or emulator in Chrome)
- install button should not be visible

Removed install button from Android.

---

app.py

When using HTTPS and trying to connect to an external service (here login.ubuntu.com) the external service reads our http host.
To fix this we need to add `X-Forwarded-Proto` in the header. The solution comes from:
https://stackoverflow.com/questions/23347387/x-forwarded-proto-and-flask/23504684#23504684
To QA you can use caddy locally with this configuration and try to login to your account: https://gist.github.com/WillMoggridge/545a71c21f7162bdd6aa8dcd47aff6c3

Fix redirections to http problem

---

app.py
templates/publisher/market.html

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/245 and https://github.com/CanonicalLtd/snapcraft-design/issues/247
- ./run
- snap details such as publisher, size, version, etc should be visible together with the form

Adds snap details to market page

---

app.py
requirements.txt

The library used (Flask-OpenId) is not stateless. We are going to use the fork that fixes this problem: 
https://github.com/nward/flask-openid
This should be removed if the PR is merged in the future:
https://github.com/mitsuhiko/flask-openid/pull/50
- `./run`
- Make sure you can still login and access your account page

Use flask-openid stateless version

---

templates/_layout.html
templates/index.html

As BSI includes 'Store' without an external link, it seems only fair for SI to include 'Build' without an external link.
- `./run`
- Goto http://0.0.0.0:8004/ and http://0.0.0.0:8004/store/ and ensure the navigation looks the same
- Approve this PR.

Remove external icon link from build

---

static/js/publisher/market/market.js
static/js/publisher/publisher.js
static/sass/_snapcraft_market.scss
static/sass/_utilities_margin-sizing.scss
static/sass/styles.scss
templates/publisher/market.html

Fixes #248
Adds a UI for editing icon on snap market page.
NOTE: there is currently no backend API done for saving the icon, so it wont actually change when saved
UPDATE: icon editing code is there but is disabled so we can merge it without making functionality available yet
- ./run
- go to market page of a snap you own
- click on an icon to edit it
- choose different image to replace icon with
- icon should update on the page

UI for editing icon on market page

---

app.py
static/js/publisher/market/market.js
templates/publisher/market.html

First part of https://github.com/CanonicalLtd/snapcraft-design/issues/249
Adds flash notification message when market page form is saved or reverted.
It currently doesn't check if there were any changes in the form. Just shows a message based on which button was used.
Also, follow up PR will be added later to remove the notification after some delay and when changes are made in the form.
- ./run
- go to market page of a snap you own
- click Apply or Revert
- proper message should appear
- edit form, message should be removed
- click Apply or Revert
- message should appear
- wait 20 seconds, message should be removed

Adds flash notifications when market page form is saved or reverted

---

README.md

`.env` is *committed to the codebase*. Therefore it should only contain
environment variables that are intended to *always be used* in local
development, for everyone.
The staging API server is intended to be a temporary setting that should
*not be committed* to the repository. So `.env.local` (which is in
.gitignore) should be used
instead.
QA
--
Try using `.env.local` instead of `.env`, check it still works for connecting to the staging API server instead of the live one.

We should use .env.local instead

---

templates/_layout.html

This change makes the tutorials link more relevant for snapcrafters.
https://tutorials.ubuntu.com/ -> https://tutorials.ubuntu.com/?q=snap

Adjust tutorials link to query snap tutorials

---

app.py
templates/account.html
templates/publisher/measure.html
tests.py

- Tidy code slightly
- Fix redirection error
- Correct URL paths for URLs without slashes
QA
--
``` bash
./run
```
Then navigate to `/account` and `/account/`, with and without being already logged in. Check everything still works, and that `/account/` is now *not* a 404.

Routing fixes

---

app.py
static/js/public/snap-details/map.js
static/js/publisher/metrics/filters.js
static/js/publisher/metrics/metrics.js
static/js/publisher/publisher.js
static/sass/_map.scss
templates/publisher/measure.html

- Installs graph removed
- Measure territories grey for lowest shade
- Territories changed to weekly metric
- `./run`
- Visit http://0.0.0.0:8004/account
- Click on a snap with metrics data
- The top 'Installs' graph should not longer be there
- The 'Territories' map should have grey as the lowest colour scale and the tooltips should show exact numbers

Measure territories and remove installs

---

app.py
templates/publisher/market.html

Fixes #263 
- ./run
- click on an icon and choose an image bigger than 256px
- click Apply
- error notification should appear

Adds error notifications to market page

---

package.json
templates/publisher/market.html
yarn.lock

Updates Vanilla to latest version and removed unnecessary workarounds.
- ./run
- go to any page, it should look fine
- go to your snap market page
- edit something, apply or revert
- notification should appear correctly (in full width)

Updates Vanilla to latest version and removed unnecessary workarounds

---

yarn.lock

Seems that yarn.lock has different version of vanilla then package.json

Fixes vanilla version in yarn lock

---

templates/index.html

QA
--
`./run`
Go to homepage, click tutorials link in header. Check it matches the same link in the header of the other pages on the site.

Update tutorials link on homepage

---

modules/public/api.py
modules/publisher/api.py
modules/publisher/views.py
templates/account.html
templates/publisher/market.html
templates/publisher/measure.html

Access private snaps for publisher
- `./run`
- http://0.0.0.0:8004/account/snaps/PRIVATE_SNAP/measure/
- http://0.0.0.0:8004/account/snaps/PRIVATE_SNAP/market/
- http://0.0.0.0:8004/account/snaps/SNAP/measure/
- http://0.0.0.0:8004/account/snaps/SNAP/market/
- Access a non uploaded snap:
- http://0.0.0.0:8004/account all non uploaded snaps shouldn't have a link to the market/measure page
- http://0.0.0.0:8004/account/snaps/NOT_UPLOADED_SNAP/measure/
- Should display page with an error message
- http://0.0.0.0:8004/account/snaps/NOT_UPLOADED_SNAP/market/
- Should display page with error message, and all fields in readonly mode
- If you force HTML to send a request, the request shouldn't be proccessed

Access private snaps on market and measure pages

---

modules/publisher/views.py
static/js/publisher/market/market.js
static/sass/_snapcraft_market_screenshots.scss
static/sass/styles.scss
templates/publisher/market.html

Adds basic screenshots UI to market page form.
- Currently it's only possible to add screenshots.
- Because of current backend implementation added screenshots **override** screenshots added previously when saved
- Not possible to move or delete screenshots yet
- No validation on number of screenshots yet
- ./run
- existing screenshots should appear (if you have any)
- add some screenshots
- screenshots should show up
- click "Apply" to save - screenshots should be uploaded and saved in dashboard

Market page - adding screenshots (step 1)

---

templates/_header.html
templates/_layout.html
templates/index.html

Fixes #252 
Updates logo in header to a new branding.
Also extracts header navigation to a partial template to keep it consistent between different layouts used in the app.
- ./run
- go to home page
- go to any other page
- header should have new logo branding

Updates snapcraft logo (and extracts header into partial template).

---

modules/publisher/views.py

Allow upload screenshots with already existing screenshots
Fixes #262 
Fixes #267 
- `./run`
- http://0.0.0.0:8004/account/snaps/SNAP/market
- Choose some screenshots to be added
- Apply
- Screenshots should be visible
- Add some more screenshots
- You should have the previous screenshots in the market page
- You can verify in dashboard page for same snap that screenshots are uploaded

Send already existing screenshots in info

---

package.json

Adds JS files to watcher.
Watch all:
1. ./run watch
2. change any SCSS file - CSS files should be rebuilt
3. change any JS file - JS files should be rebuilt
Watch JS only
1. ./run exec yarn run watch-js
2. change any JS file - JS files should be rebuilt
Watch SCSS only
1. ./run exec yarn run watch-scss
2. change any SCSS file - CSS files should be rebuilt

Adds JS files to watcher

---

templates/publisher/market.html

Fixes showing snap name in page title and adds read only snap name to market page (below editable snap title).
- ./run or http://snapcraft.io-pr-297.run.demo.haus/
- browser page title (tab), page header and editable title should show same value (snap title)
- read-only snap package name should be shown below snap title

Adds snap name to market page (and fixes page title)

---

static/js/publisher/market/market.js
static/sass/_snapcraft_market_screenshots.scss

Fixes #285 
- ./run or http://snapcraft.io-pr-301.run.demo.haus/
- add some screenshots
- click on a screenshot - it should get selected
- click on other screenshot - it should get selected
- click anywhere else on the page - screenshots should not be selected anymore

Adds selecting screenshots to market page

---

templates/_layout.html
templates/index.html
templates/snap-details.html

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/284
Fixes showing ubuntu image when sharing snapcraft.io
- Try sharing http://snapcraft.io-pr-302.run.demo.haus/ on Facebook or use https://developers.facebook.com/tools/debug/sharing/
- Preview should show snapcraft logo (not Ubuntu logo)
- Same result should be for store page: http://snapcraft.io-pr-302.run.demo.haus/store
- Snap page should show given snap icon: http://snapcraft.io-pr-302.run.demo.haus/spotify

Adds snapcraft logo to social share meta data

---

modules/public/views.py

Common names are more politically neutral, so use those if possible.
Fixes #310.
Signed-off-by: 林博仁(Buo-Ren Lin) <Buo.Ren.Lin@gmail.com>

snap details: Use common_name if available in map regions

---

modules/publisher/api.py
modules/publisher/views.py
templates/publisher/market.html
templates/publisher/measure.html

When user tries to acces market page for a snap he doesn't own, redirection to 404 page
- `./run`
- http://0.0.0.0:8004/account/snaps/toto0/market
- Should display a 404 page
- Try to acces the same page but for a non uploaded snap
- Should diplay the same message: upload needed...

Display 404 page when snap not found for market page

---

templates/snap-details.html

- Changed the 'Developer website' link to 'Developer contact' as sometimes developers put their email address in. This is a short term solution until we implement the new fields.
- `./run`
- Go to a snap and ensure the 'Developer website' link now says 'Develop contact'
- Try a few more snaps

Developer website > Developer contact

---

app.py
requirements.txt
run
tests.py

Tentative proposal for testing publisher pages using response doubles.
Minor fix included for login redirects (previously pointing to non-evaluated route, e.g `.../<snap_name>/market` and ending up on `/account` because of the redirect in `verify_response()` ... kinda crazy)

Testing publisher pages (with authentication).

---

app.py
modules/authentication.py
modules/public/views.py
modules/publisher/api.py

This PR fixes small problems on s.io:
- We requesting page behind auth, login redirects to page and not to the /account page
- On bad verification (40* http code) redirect to account page
- Fix https://github.com/canonical-websites/snapcraft.io/issues/315 search problem with special charcaters 
- `./run`
- http://0.0.0.0:8004/search?q=test%23test
- http://0.0.0.0:8004/logout
- http://0.0.0.0:8004/account/snaps/YOUR_SNAP/market
- should ask for login and then redirect to the page you requested

Small fixes 

---

app.py
static/sass/_snapcraft_snap-list.scss
static/sass/styles.scss
templates/account.html

This pull request satisfies the remaining 'Phase 1' items in https://docs.google.com/document/d/1L6Dj77LGUJnbngyzceZcDrkf8iygx2HNAc471xjRaQE/edit#heading=h.q0rl1q8l4z1o:
1. User details (editable) - Links off to SSO (login.ubuntu.com)
2. Snap list - Registered names vs actual snaps
This should also satisfy https://github.com/CanonicalLtd/snappy-design-squad/issues/358 in it's current state (@Greggless to confirm).
- `./run`
- View your account page:
- 'Username' should have an 'Edit' button that links to https://login.ubuntu.com
- Spacing of icon, snap name and 'private' flag should be better
- The 'Status' column should indicate whether a snap is a registered name.

Further account updates

---

README.md
modules/public/api.py

search.apps.ubuntu.com is deprecated; the endpoint we use is now provided by api.snapcraft.io.
(same modification that is in b.s.io https://github.com/canonical-websites/build.snapcraft.io/pull/1061 )

Change search API URL

---

static/js/publisher/market/lightbox.js
static/js/publisher/market/market.js
static/sass/_patterns_maas_modal.scss
static/sass/_snapcraft_market_screenshots.scss
static/sass/styles.scss
templates/publisher/market.html

Fixes #287 
Adds previewing screenshots in lightbox to market page
- ./run or http://snapcraft.io-pr-314.run.demo.haus/
- go to market page of a snap you own
- if it doesn't have screenshots add some (you don't have to upload them)
- click on a 'fullscreen' button next to screenshots
- screenshots should open in lightbox
- you should be able to navigate through screenshots (clicking next/prev buttons)

Market page screenshots lightbox

---

static/js/publisher/metrics/graphs/activeDevices.js

- Better vertical alignment of active device labels
This partly fixes https://github.com/CanonicalLtd/snapcraft-design/issues/278
Follow up issue:
- https://github.com/canonical-websites/snapcraft.io/issues/321
- `./run`
- Visit a snap measure page http://0.0.0.0:8004/account/snaps/SNAP_NAME/measure
- Have a look at the labels - do the work?

Measure: Improved label positions

---

static/js/publisher/metrics/graphs/activeDevices.js
static/js/publisher/metrics/tooltips.js
static/sass/_snapcraft_graph-tooltip.scss

Fixes https://github.com/canonical-websites/snapcraft.io/issues/321
- `./run`
- Visit http://0.0.0.0/account/snaps/SNAP_NAME/measure
- Or visit http://snapcraft.io-pr-330.run.demo.haus/account/snaps/SNAP_NAME/measure
- Hover over the active devices graph and see the labels go bold, signifying which area you are over.
Sometimes the labels aren't bold - this, as far as I can tell is to do with the labels that will be removed as part of https://github.com/canonical-websites/snapcraft.io/pull/322

On hover, embolden the appropriate label

---

modules/public/views.py
modules/publisher/views.py
static/sass/_snapcraft_market.scss
templates/publisher/market.html
templates/snap-details.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/317
- Added both contact and website fields to market page
- Added both fields (if present) to snap details page
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/SNAP_NAME/market
- Update the Developer contact and Developer website fields.
- Save your changes and ensure the change have persisted
- Go to http://0.0.0.0:8004/SNAP_NAME
- Make sure the Developer website and Developer contact link go to the correct places
- Repeat if you fancy it
Apologies if there are designs/ wireframes for any of this that I've ignored - point me in the right direction and I'll update the PR thanks!
Snap market page:
Snap details page:

Add both Developer contact and website fields

---

modules/public/views.py

When user agent not defined in header the detail page should be accessible
- `./run`
-  curl -H "User-Agent:" http://0.0.0.0:8004/skype

Fix error no HTTP-AGENT in header

---

app.py
templates/publisher/market.html
templates/publisher/measure.html
templates/snap-details.html

- Added Raven from the sentry CDN
- Checks for `SENTRY_PUBLIC_DSN` in `.env.local`
- Setup an account on https://sentry.io and get a public DSN
- Add the public dsn to your `.env.local` (or create one):`SENTRY_PUBLIC_DSN=<public_dsn>`
- Change the name of a variable in the JS
- `./run`
- Visit the page with the bad JS
- Check your sentry dashboard, you should see the error immediately
- Rejoice

public sentry

---

static/js/publisher/market/market.js

In some cases there were JavaScript errors thrown about `removeNode` being called on `null`.
Possibly `setTimeout` script was trying to remove the notification that is not showing anymore.
This fix makes sure notification node is still available before trying to remove it from DOM.
1. Go to market page of some snap
2. Change some values
3. 'Apply' notification should show
4. Make some changes again and 'Apply'
5. Repeat couple of times
There should be no error in JS console.

Fixes JS error when removing non-existent nofitication.

---

.env
app.py

We want to use the environment variable so that we don't have to worry
about people cloning and hosting this site elsewhere, and polluting our
sentry logs.
We now `strip()` the variable contents, so newlines or extra spaces
shouldn't break anything.

Move back to using the SENTRY_PUBLIC_DSN env var

---

templates/publisher/market.html
templates/publisher/measure.html
templates/snap-details.html

Added snapcraft.io and run.demo.haus as white listed urls for error reporting.
- Wait for the demo to start.
- Go to a measure page.
- See an error in the page - d4 is not defined.
- See an error in sentry - d4 is not defined.
- Check the count of NS_ERROR_UNKNOWN_PROTOCOL errors in sentry
- Go to http://snapcraft.io-pr-364.run.demo.haus/slack
- Click the install button (on an OS that doesn't support snap urls)
- Make sure the NS_ERROR_UNKNOWN_PROTOCOL error count doesn't increase.

Sentry whitelist

---

templates/snap-details.html

To prevent `ga is not defined` when clicking on Install button when GA is blocked.
- go to snap details page (on Linux)
- in browser console `delete ga`
- click on Install button
- there should be no JS error

Fixes errors when GA is blocked

---

static/js/public/snap-details/map.js

To avoid unhelpful `world is undefined` errors in sentry we need to properly handle topojson loading error so we know why it happens and if we can do something about it.

Better error handling when world map data fails to load

---

app.py
modules/public/api.py
modules/public/views.py
templates/404.html
tests.py

* Remove flask dependency from api public layer.
* First draft for a better error handler in the api layer
* Work on public snap access
- `./run`
- `./run test`
- 0.0.0.0:8004/toto
- Should have a snap
- 0.0.0.0:8004/qsdfsqdfqsdf
- Should return 404 page

Remove flask dependency api layer

---

static/sass/_snapcraft_custom-typography.scss
static/sass/_snapcraft_footer.scss
static/sass/styles.scss
templates/_footer.html
templates/_layout.html
templates/index.html

Update footer on snapcraft.io to new design.
Part of https://github.com/CanonicalLtd/snapcraft-design/issues/273
Because we need additional discussion on headers, footer can be merged separately.
- ./run
- go to home page - footer should have a new design
- go to store page or snap details page - footer should have new design

Updates footer design

---

modules/publisher/views.py
templates/account.html
tests.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/348
- `./run`
- Visit http://0.0.0.0:8004/account or http://snapcraft.io-pr-395.run.demo.haus/account
- The page should look like the screenshot below (but with your details obviously)

Account dedupe and use of correct fields

---

static/sass/_snapcraft_banner.scss
static/sass/_snapcraft_p-navigation.scss
static/sass/styles.scss
templates/_header.html
templates/index.html
templates/search.html
templates/store.html

Fixes #273 
Adds new dark header to snapcraft.io, removed Tutorial link, added My snaps (linking to dashboard).
Designs:
https://github.com/canonicalltd/snappy-design-squad/issues/387 (header)
https://github.com/canonicalltd/snapcraft-design/issues/287 (footer)
- ./run
- Go to home page
- It should have new dark navigation
- Go to snap details page
- It should have new dark navigation

New consistent header

---

static/sass/_snapcraft_footer.scss

Fixes #402
Removes unnecessary margins from links in footer in Firefox.
1. Use Firefox
2. Go to any page
3. Footer should not have unnecessary spacing (compare with Chrome)

Removes unnecessary spacing from footer links in Firefox

---

static/sass/_snapcraft_p-navigation.scss

Fixes #406 
Removes dark hover from mobile navigation to make it readable.
- ./run
- make small screen (mobile navigation)
- open navigation
- hover any item, click on it (it should not have black hover background)

Fixes dark hover on mobile navigation

---

static/sass/_snapcraft_custom-typography.scss
templates/snap-details.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/405
- Overrides the `*+*` style from vanilla, specifically for `<br />` elements.
- Fixes a spacing issue caused if the contact field is defined, but the website isn't.
- `./run`
- Visit http://0.0.0.0:8004/spotify or http://snapcraft.io-pr-408.run.demo.haus/spotify in Firefox
- Ensure the error reported is fixed

Ensure br's don't have the * + * spacing applied

---

app.py
modules/authentication.py
modules/publisher/api.py
modules/publisher/views.py
static/sass/styles.scss
templates/developer_programme_agreement.html
templates/username.html

- Handle errors when a user is new:
- Create a snap store username
- `./run`
- Create new account on login.ubuntu.com
- you should be redirected to the create username page
- http://0.0.0.0:8004/account/username
- Create username
- You should land on account page, Namespace should be the username choosen

Create username if user doesn't have one on snap store

---

modules/publisher/views.py

Functions from public has been moved, needed to reimport those functiosn in the publisher views
- `./run`
- http://0.0.0.0:8004/account/snaps/toto/measure

Fix wrong import publisher metrics

---

templates/index.html

“runs and manage” > “runs and manages”

Fixes typo on front page

---

modules/cache.py

We've been getting a number of api timeout errors in production, intermittently.
This should hopefully help to reduce the chance of that happening, without allowing the API to bring down the site by waiting for too long.
QA
--
`./run`, check the site works

Extend timeout to 3 seconds

---

.env

Add `DEVEL=true` to the environment variables.
When this is set, Talisker adds pretty colours to the terminal logs.
Start `./run` and look at the logs

Add DEVEL to .env variables

---

templates/snap-details.html

- ./run
- go to snap details page
- install instructions should be correctly displayed
- all tags should be correctly closed

Fixes typo in install instructions HTML

---

static/js/publisher/market/market.js
static/js/publisher/market/market.test.js
static/js/publisher/market/screenshots.js
static/js/publisher/market/screenshots.test.js
static/js/publisher/market/state.js
static/js/publisher/market/state.test.js
templates/publisher/market.html

Refactors market page front-end logic to allow saving only data changed by user.
Adds `changes` field to the form which contains JSON with only values changed by the user.
Needs backend update to use diff instead of form input values, but can be merged for front-end changes only, as is backwards compatible (only adds new hidden data field to the form)
- ./run
- go to market page
- change some values, save
- market page should be saved as before
- additional `changes` field is sent to backend

Market page - only save changed fields

---

static/sass/_snapcraft_metrics.scss
static/sass/_snapcraft_p-tabs.scss
static/sass/styles.scss
templates/publisher/market.html
templates/publisher/measure.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/432
- `./run`
- Visit the publisher pages
- Check them against the prototype
- Note the '< Snap list' link - this is for convenience while developing, it will be removed on release as 'My snaps' in the header will link to the snap list.

Smaller headings

---

.env

Reverts canonical-websites/snapcraft.io#434
This is just too ugly in my terminal I'm afraid. Could we not enable this until talisker has fixed the colours?

Revert "Add DEVEL to .env variables"

---

static/js/public/snap-details/screenshots.js

There was a 'bunch' of errors in Sentry cased by recent public screenshots release.
Most common are 2 types:
- `screenshotsEl` is null - very common case because it happens when snap doesn't have any screenshots, in such case we should not try to run screenshots related code...
- `Array.from` is not a function - it seems that we still have quite a lot of people with older or not mainstream browsers that don't yet support this function, so we need to get back to older solutions
This PR addresses both of issues listed above.
- ./run
- go to a public snap page with screenshots (everything should work as expected, no errors in console)
- go to a public span page without screenshots (everything should work, no errors in console)

Fixes screenshots JS errors from sentry

---

templates/snap-details.html

Wrapped everything with `if` statements.
A small number of browsers (IE) seem to support `.key` but provides strings from an older spec.... However looking at the shim (https://github.com/shvaikalesh/shim-keyboard-event-key/blob/master/index.js) we're using none of the strings effected.

Defend against undefined vars

---

static/sass/_patterns_media-object.scss
templates/search.html

Fixes https://github.com/canonicalltd/snapcraft-design/issues/301
- Removed left padding from publisher name
- Removed description
- `./run`
- Visit http://0.0.0.0:8004/search?q=test and http://0.0.0.0:8004/search?q=lukewh
- Ensure the description is not there and the publisher name is left aligned with the snap name

Update search results

---

modules/publisher/api.py
modules/publisher/views.py

- Remove `flask.abort` from API
- Handle 404 in views instead of api module: I added the function `process_response` in the api module. The idea is to move this function in another module once every API response is handled by this function. (This function was copied/paste from the public API)
- `./run`
- http://0.0.0.0:8004/account/snap/<SNAP_YOU_OWN>
- browse in market, measure, release -> should work as usual
- http://0.0.0.0:8004/account/snap/aaaaaaaaaaaaaaaaaaaaaaa
- - browse in market, measure, release -> should return a 404 page

Move flask.abort from API module

---

modules/publisher/views.py

`website` and `contact` fields are missing in context when posting market page has errors.
Because of that when you post market page with errors you get 500 internal server error.
This PR fixes that.
- ./run
- change something that will cause error (make title longer then 64 chars or icon that is not 256x256)
- post
- page should render correctly with error message on the top

Adds missing market fields when there are post errors

---

templates/publisher/market.html

- ./run
- go to snap market page that doesn't have screenshots
- 'Add images' grey field should have width of the page not whole screen

Fix width of empty screenshots box on market page

---

static/js/publisher/market/market.js
static/sass/styles.scss
templates/publisher/market.html

First pass of #399 
This PR adds basic marking of invalid fields with Vanilla styling.
Possible improvements for next PRs:
- showing error messages next to fields instead of top notification
- ./run
- go to market page
- update any of text fields to invalid value (make title or summary too long, make contact or website invalid URL)
- save the form (click `Apply`)
- Error notification should show up on top of the form, invalid field should be marked red
- Change the value in invalid field
- Field should be unmarked when you leave it

Adds basic Vanilla style validation to market input fields

---

static/js/polyfills.js
static/js/public/public.js
static/js/public/snap-details/screenshots.js
static/js/publisher/publisher.js

Because usage of `Array.from` is causing us some sentry errors and possibly `Element.closest` can also be problematic in older browsers we can add a polyfill for those functions.
This will allow us to use new DOM API without loosing compatibility with older browsers.
NOTE: Possibly we could use `babel-polyfill` which should include these, but it also includes many more that may make our files unnecessary big at the moment. Also I had some troubles with using it in our current rollup setup.
- ./run
- go to snap details page (with screenshots)
- everything should work normally
- try it in older browser (possibly IE) still there should be no errors in console

Polyfill for Array.from and Element.closest

---

modules/authentication.py
modules/exceptions.py
modules/publisher/api.py
modules/publisher/views.py
tests.py

~~This PR should be merged before: https://github.com/canonical-websites/snapcraft.io/pull/431~~
- Remove last flask dependency from publisher API module
- Remove useless validation checks for the frontend. Only check if the macaroon needs to be refreshed in the headers. If yes raise an exception to handle it.
- `./run`
- http://0.0.0.0:8004/account/
Hard to QA because the macaroon is valid for 1 year...

Remove flask dependency from validation

---

modules/publisher/views.py
tests_publisher.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/445
- I disabled CSRF for testing, not useful to test a library :)
- Add entire integration test suite for the /account/username page (POST, GET)
- `./run test`
The tests should pass!

Test username endpoint

---

modules/publisher/views.py
tests_publisher.py

- Add entire integration test suite for the /account/agreement page (POST, GET)
- `./run test`
The tests should pass!

Add integration tests for /account/agreement

---

app.py
modules/publisher/views.py
static/js/publisher/market/market.js
static/js/publisher/market/publicMetrics.js
static/js/publisher/market/state.js
templates/publisher/market.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/436 and https://github.com/canonical-websites/snapcraft.io/issues/443
- Added Public Metrics global checkbox and Territories specific checkbox to the Market page
- Made the backend pass the data through
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/<snapname>/market
- Scroll down to the bottom and see the checkboxes
- When toggling the public metrics checkbox the items below should be disabled
- If you disable all metrics but have a specific metric checked, the specific metric should still be checked, but disabled
- Save changes and check the state when the page reloads

Public metrics toggles

---

.env
modules/cache.py

- Add custom UserAgent request to the storefront for every request.
**Format**
- development: `storefront (commit_id; devel)`
- staging: `storefront (fc78bfaa6f36bff9e09450b88441701ad8600740; staging)`
- production: `storefront (fc78bfaa6f36bff9e09450b88441701ad8600740; production)`
- `./run`
- Browse s.io make sure it still works
(- you can print the header in cache.py to make sure the header has all the information :sweat_smile: )

Add custom User-Agent headers for the storefront

---

modules/public/logic.py
templates/snap-details.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/437
- Wrapped map initialiser with `try... catch` to stop displaying territories title if there's a JS error
- Made the backend return an empty object if there's `NO DATA` from the API
- `./run`
- Disable public metrics on a snap
- Visit the snap details
- The map will not be displayed
BONUS:
- If you have a snap without any users but public metrics turned on
- Visit the snap details and see no map or title

Don't display map when 'NO DATA'

---

modules/publisher/views.py
static/js/publisher/market/market.js
templates/publisher/market.html

Fixes #399 
- Shows validation errors next to input fields (or in notification in case of icon or screenshots)
- When there is validation error the invalid value is shown in the input, so user understands what caused the error
- Focuses first invalid input (so that the page scrolls down when error is in contact or website)
- ./run or http://snapcraft.io-pr-467.run.demo.haus/
- enter invalid title (longer then 64 letters) and Apply
- Title should be marked invalid with message under the input
- Invalid title should still be the value of the field
- Page title header should show old title (as from API), not invalid one
- Edit the title, when focus moves out of the field it should be not marked as error anymore
- Add invalid icon (bigger then 256px) or invalid …

Show validation errors next to input fields

---

Dockerfile

- Add COMMIT_ID as an environment var to the docker image on build
- This will allow s.io to catch use this var for sentry, the headers and the css cache problem
- `docker build --build-arg COMMIT_ID=test --tag test-sio .`
- `docker run --rm -p 80:80 -it -e SECRET_KEY=adsf test-sio`
- in another terminal : docker ps
- get the container ID
- `docker exec -it CONTAINER_ID /bin/bash`
- `echo $COMMIT_ID`
- Should display `test`

Add COMMIT_ID as env var in docker file

---

app.py
modules/helpers.py

- When requesting invalid snap name return 404
- Add /favicon.ico endpoint
- `./run`
- http://0.0.0.0:8004/robots.txt
- Should return 404 with message: Invalid snap name
- http://0.0.0.0:8004/toto
- http://0.0.0.0:8004/favicon.ico
- Should redirect to https://assets.ubuntu.com/v1/fdc99abe-ico_16px.png

Return 404 on invalid snap name

---

app.py
modules/publisher/views.py
templates/_layout.html
templates/index.html
templates/publisher/market.html
templates/publisher/measure.html
templates/snap-details.html

I've done a few things here, but the main one is that I made it so static files will have URLs of the form:
`/static/file.ext?v=a23ef45`
The hash at the end will be generated from the contents of the file, so whenever the file's contents changes, the hash will change. This should prevent old (cached) CSS or JS being applied to new versions of the site. It should also mean that we can in future extend the cache time on static files (currently set to 12 hours - [the flask default](http://flask.pocoo.org/docs/0.12/api/#flask.Flask.default_config)).
Things done:
- [Fix ApiResponseErrorList error handling](https://github.com/nottrobin/snapcraft.io/commit/6061093f3776e8cb027a94654731c4aeec2ef0ad) - this was causing 500 error rather than 502 as it should
- [Use standard _layout.html template for …

Cache-busting URLs for static files

---

modules/publisher/views.py
static/js/publisher/market/market.js
static/js/publisher/market/publicMetrics.js
static/js/publisher/market/screenshots.js
static/sass/_snapcraft_market.scss
templates/publisher/market.html

Fixes #391 
Fixes #469
Adds basic HTML level restrictions/validation of market page fields and client-side validation to mark invalid fields and allow submitting only when form is valid.
- adds required fields (title and summary)
- adds max length limits (title, summary, website, contact) - if user types too long text field is marked as error and number of characters over the limit is shown
- adds URL type for website and contact
- removes SVG from accepted image formats for screenshots
- ./run
- go to market page
- try to enter too long title
- field should be marked red and number of characters to remove should be shown
- remove title
- field should be marked invalid as title is required
- try to enter and submit invalid URL (website or contact)
- try to add SVG screenshots - SVG files …

Market page client-side validation

---

modules/publisher/views.py

Makes sure we only save in API data that was changed by user.
Fixes: #441 
- ./run
- change some text value (title, summary, description)
- Apply - API should only save given value (print in backend to debug)
- change some image (icon, screenshot)
- Apply - API should only save images

Market page - save only changes

---

modules/publisher/views.py
static/js/publisher/market/state.js

Fixes #356 
Store API doesn't allow control characters in description. This includes `\r` in line breaks.
Browser form data encodes line breaks in textarea as `\r\n` which is invalid for API.
This caused an error, because for descriptions containing new lines (`\n`) browser was rendering and sending it back as `\r\n` which caused validation in store to fail.
This PR fixes this by making sure that both in front-end side validation (to correctly detect if description changed) and in back-end before sending description to API we remove invalid `\r` characters from line breaks.
- ./run
- go to a snap with new lines in the description
- change any value (not description), `Apply`
- value should be saved without validation error for description
- change description (make sure there are some new …

Removes invalid new line chars from description

---

templates/publisher/market.html

Description field is required by store API, but was not marked as required on market page form, so it was possible to post empty description which resulted in API validation error.
This PR fixes it by marking description field as required in the form, so it's not possible to save empty description.
- ./run
- remove description
- field should be marked red and Apply should be disabled
- you should only be able to save the data when description is not empty

Marks description as required on market page

---

modules/publisher/api.py
modules/publisher/views.py

Refresh macaroon if needed on every api call
- `./run`
- browse the `/account`s endpoints

Refresh macaroon on every api call if needed

---

modules/publisher/views.py

See https://dashboard.snapcraft.io/docs/api/snap.html#obtaining-information-about-a-snap for more information.

Stop using deprecated snap-info fields.

---

modules/publisher/views.py
templates/publisher/_header.html
templates/publisher/market.html
templates/publisher/measure.html

- Created `publisher/_header.html` template
- Modified `publisher/market.html` and `publisher/measure.html` to use the new template
- Made sure `snap_title` is consistent throughout (some places was `title`)
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/SNAP_NAME/market and http://0.0.0.0:8004/account/snaps/SNAP_NAME/measure and ensure the title and tab bar still display correctly

Publisher header template

---

app.py
decorators.py
template_functions.py

Add standard caching headers to public routes:
- Cache pages for 30 seconds
(allows Squid to take significant load of the app)
- Serve stale pages while revalidating the cache for 5 minutes
(allows Squid to response instantly while doing cache refreshes)
- Show stale pages if the app is erroring for 1 day
(gives us a 1 day buffer to fix errors before they are publicly visible)
These caching headers should now be included on /, /store, /search,
/{snap-name}
All private routes should now have `Cache-Control: private`.
I also restructured the code a bit to separate out decorators and template functions from `app.py`, to keep things more focused.
Fixes #424
QA
--
``` bash
$ curl -sI http://127.0.0.1:8004/ | grep 'Cache-Control'
Cache-Control: max-age=30, stale-while-revalidate=300, …
```

Cache-control for public and private endpoints

---

app.py
modules/publisher/views.py
tests_basic.py
tests_publisher.py

Instead of using the data received from login.ubuntu.com we use the data from dashboard
This will fix https://github.com/canonical-websites/snapcraft.io/pull/498#discussion_r180426317
- `./run`
- http://0.0.0.0:8004/logout
- The username and display name should be the same
- http://0.0.0.0:8004/logout
- http://0.0.0.0:8004/account/snaps/toto/market
- login
- The username and displayname should be OK

Use username, fullname from API instead of l.u.com

---

templates/_footer.html

Fixes: #501
- Updated the snapcraft report link to https://bugs.launchpad.net/snapcraft
- Updated the snapd report link to https://bugs.launchpad.net/snapd 
- `./run`
- Visit http://0.0.0.0:8004/
- Go to the footer and check if the links direct users to the correct report links, described in this issue: https://github.com/canonical-websites/build.snapcraft.io/issues/1078

update report links in footer

---

modules/publisher/views.py
tests/endpoint_testing.py
tests/tests_market.py

- Add tests for the market endpoint Fixes #480 
- Refactor test to get a generic test class for authenticated endpoints
- `./run test`

Test get market page

---

static/sass/_snapcraft_p-form-help-text.scss
static/sass/styles.scss
templates/publisher/market.html

Partially fixes https://github.com/canonicalltd/snapcraft-design/issues/309
- Toggle doesn't make sense yet, until we have single field saving
- Distribution chart is not implemented yet, so the switch doesn't exist
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/SNAP_NAME/market
- Ensure the market toggles work as expected in reference to https://github.com/canonicalltd/snapcraft-design/issues/309

Market toggles UX tweaks

---

modules/publisher/views.py
package.json
static/sass/_snapcraft_p-beta-notification.scss
static/sass/styles.scss
templates/account.html
templates/developer_programme_agreement.html
templates/publisher/_beta-notification.html
templates/publisher/_header.html
templates/username.html
yarn.lock

Fixes https://github.com/canonical-websites/snapcraft.io/issues/394
- Updated vanilla to 1.6.7
- Added `_beta-notification.html` template for the notification
Depends on https://github.com/canonical-websites/snapcraft.io/pull/491
- `./run`
- Visit http://0.0.0.0:8004/account
- See the notification, click the links in the notification, close the notification
- Visit other account pages and see the notification

Cross link notification

---

templates/publisher/market.html

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/322
Makes description field on market page bigger (to encourage longer descriptions).
- ./run
- go to market page of your snap
- description field should be visually bigger then other fields (enough to contain couple of lines of text).

Make description field bigger

---

modules/publisher/views.py
tests/endpoint_testing.py
tests/tests_market.py
tests/tests_post_binary_metadata.py
tests/tests_post_market.py

- Add tests for POST endpoint
- Seperated in 2 files:
- One for fields updates
- One for screenshots/icon uploads
- `./run test`

Add tests post market page

---

templates/publisher/market.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/531
- Removed non-editable 'License' on the market page.
- `./run`
- Visit `/account/snaps/<snap_name>/market`
- Make sure license decleration isn't there

Remove license field from market page

---

templates/publisher/account-snaps.html

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/358
- Added `target="_blank"` to tutorials link on 'no snaps' page
- `./run`
- Create new account/ modify `publisher/views.py` for a user/ object with no snaps
- Visit http://0.0.0.0:8004/account/snaps
- Click the 'Try the tutorial' link, it should open a tutorial in a new window/ tab.

Open tutorial in new window

---

static/js/public/snap-details/map.js

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/323
- Removed the word 'devices' from the territories tooltip
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/<snap_name>/measure where <snap_name> is the name of a snap with users
- Make sure the tooltip says 'x active'

Dropped the word 'devices' from tooltip

---

modules/publisher/views.py
templates/_header.html

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/353
- Added `page_slug: 'my-snaps'` to each context where required
- Added `is-selected` class if the navigation item should be selected
- `./run`
- Visit http://0.0.0.0:8004/account/snaps, http://0.0.0.0:8004/account/snaps/<snap_name>/market, https://0.0.0.0:8004/account/snaps/<snap_name>/measure ensure 'My snaps' in the header is highlighted on each page!

Highlight 'My snaps' and all sub-pages

---

modules/publisher/views.py

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/362
Redirect to /account/agreement if user hasn't signed the agreements
- `./run`
- Create new account on login.ubuntu.com
- Access those pages
- http://127.0.0.1:8001/account
- http://127.0.0.1:8001/account/snaps/toto/market
- http://127.0.0.1:8001/account/snaps/toto/measure
- http://127.0.0.1:8001/account/snaps/toto/release
- On all those pages you should be redirected to /account/agreement

Redirect to sign agreement on request

---

templates/publisher/market.html

(Partially) fixes: https://github.com/CanonicalLtd/snapcraft-design/issues/382 and https://github.com/CanonicalLtd/snapcraft-design/issues/381
- Added help text to 'Developer website' and 'Contact <publisher_name>' fields on /market
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/<snap_name>/market
- Scroll to the bottom and check the help text

Add help text for contact fields

---

templates/publisher/_header.html

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/370
- Added 'my snaps' link to snap pages
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/<snap_name>/market and http://0.0.0.0:8004/account/snaps/<snap_name>/measure
- Click the '< My snaps' link

Link back to 'my snaps'

---

templates/publisher/account-snaps.html

Changes the link to point at [the “Build your first snap” hello world tutorial](https://docs.snapcraft.io/build-snaps/your-first-snap) instead of [the “Create your first snap” hello world tutorial](https://tutorials.ubuntu.com/tutorial/create-your-first-snap).
Since the link is now to a page on snapcraft.io, removes the external-link icon.
Fixes [snapcraft-design#420](https://github.com/CanonicalLtd/snapcraft-design/issues/420).

Changes “Hello world” tutorial link

---

app.py
decorators.py

Make the logic to apply Cache-Control headers apply to *all* responses,
and use the existence of a `flask.session` cookie to decide whether it's
"public" or "private".
QA
--
``` bash
./run
```
Now check the headers in the command-line:
``` bash
$ curl -I http://0.0.0.0:8004 | grep 'Cache'
Cache-Control: max-age=61, stale-while-revalidate=300, stale-if-error=86400, public
```
Now open the browser, go to the homepage, check the "network" tab in developer tools to inspect the response headers. Check again the cache-control is as above.
Now to go http://0.0.0.0:8004/account and login. Check the response headers now have "Cache-Control: private".
Go back to the homepage, check the response headers, should still have "Cache-Control: private".

Give all session responses Cache-Control: private

---

static/js/publisher/market/screenshots.js

Fixes #518 
Because we use event delegation to capture clicks on screenshots and buttons we need to make sure disabled buttons are ignored.
- ./run or http://snapcraft.io-pr-558.run.demo.haus/
- go to market page
- add 5 screenshots (add button should be disabled)
- click on disabled button
- nothing should happen, you should not be able to add more screenshots

Make sure to ignore clicks on disabled buttons

---

modules/publisher/api.py
modules/publisher/views.py
tests/endpoint_testing.py
tests/tests_account_details.py
tests/tests_account_snaps.py
tests/tests_market.py

- Handle errors on account endpoint
- handle errors on `/account/snaps` and `/account/details` endpoint
- Update tests by using BaseTesting structure
Fixes canonical-websites/snapcraft.io#539 
- `./run`
- 0.0.0.0:8004/account/snaps
- 0.0.0.0:8004/account/details
- Try with different accounts (just registered etc.)

Handle errors account details and snap page

---

app.py
modules/publisher/views.py
templates/publisher/_header.html
templates/publisher/account-snaps.html
templates/publisher/listing.html
templates/publisher/metrics.html
tests/test_get_metrics.py
tests/tests_listing.py
tests/tests_post_binary_metadata.py
tests/tests_post_listing.py
tests/tests_publisher.py

- Renam the `market` endpoint `listing`
- Rename `market.html` to `listing.html`
- Rename the `measure` endpoint `metrics`
- Rename `measure.html` to `metrics.html`
- Update python function names
- Update tests
- Update references in templates
- Update JS variables and function names
- `./run`
- Visit http://0.0.0.0:8004/account and click around:
- There should be no reference to 'market' or 'measure'
- Visit http://0.0.0.0:8004/account/snaps/<snap_name>/market and http://0.0.0.0:8004/account/snaps/<snap_name>/measure, you should be redirected to the appropriate page

Market > Listings, Measure > Metrics

---

static/sass/_snapcraft_market.scss
templates/publisher/listing.html

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/377
- Added `snapcraft-p-sticky` class
- Removed some padding/ margins from around the buttons
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/<snap_name>/market
- Scroll down and see the buttons 'stick'

Sticky Revert and Apply buttons

---

modules/publisher/api.py
modules/publisher/views.py
tests/endpoint_testing.py
tests/tests_agreement.py
tests/tests_publisher.py

- Handle errors on POST agreement
- Add test class for POSTs endpoints
Fixes #540
- `./run`
- Create a new user
- access account page
- Confirm agreement
- Should be redirected to /account page

Handle errors POST agreement errors

---

static/sass/_snapcraft_details_heading.scss
static/sass/styles.scss
templates/snap-details.html

Fixes #526 
Updates the design of snap details heading section.
Design: [desktop](https://github.com/CanonicalLtd/snapcraft-design/blob/master/public-facing/Channel%20map%20%5Bclosed%5D%20-%20V23.jpg) [mobile](https://github.com/CanonicalLtd/snapcraft-design/blob/master/public-facing/Channel%20map%20%5BClosed%5D%20-%20320%20(Wireframe).png)
- ./run or http://snapcraft.io-pr-571.run.demo.haus/
- visit couple of snap details pages (featured snaps, etc)
- try different screen sizes
- make sure everything is fine

Updates snap details heading for upcomming channel map

---

modules/public/api.py
modules/public/logic.py
modules/public/views.py
tests/tests_public_logic.py

Send channel map to template on snap details page
- `./run`
- 0.0.0.0:8004/toto
- should work
This is the structure sent to the template: https://pastebin.canonical.com/p/d4qs6fMRZJ/

Get channel map and send to template

---

templates/publisher/account-snaps.html

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/398 and https://github.com/CanonicalLtd/snapcraft-design/issues/402
- Updated messaging for when first snap is uploaded:
> You've just uploaded <snap_name>!
> - Is your snap ready to release? Release it [1]
> - Want to improve the listing in stores? Edit store listing [2]
- Updated messaging for when first snap is release:
> You've just uploaded <snap_name> to the "<channel>" channel!
> - Want to improve the listing in stores? Edit store listing [2]
Where [1] links to release docs and [2] links to listings page
You will need:
- An account with 1 snap that has been uploaded, but not released.
- An account with 1 snap that has been uploaded and released.
- `./run`
- Visit http://0.0.0.0:8004/account/snaps
- …

Improve first snap experience

---

modules/publisher/views.py
static/sass/_snapcraft_market.scss
templates/publisher/listing.html
tests/tests_listing.py
tests/tests_post_listing.py

Partially fixes https://github.com/CanonicalLtd/snapcraft-design/issues/405
Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/328 and https://github.com/CanonicalLtd/snapcraft-design/issues/383
- Changed padding around the buttons
- Changed 'Apply' to 'Save'
- Added notification text for the following cases:
- Is not released to stable
- Is released to stable but is not public
- Is released to stable and is public
**Note** There is currently no way of knowing which store the snap is released to on this page. Once the field is added we can do some magic with that information. I'm not sure it's an issue for now though as there is only a small number of brand stores with exclusive snaps, afaik.
You'll need:
- A snap that has not been released to stable, but has the .snap file …

Listing page notice/ link to public store

---

app.py
package.json

Fixes #577.
QA
--
Break the application by e.g. adding `    sdfgsdf` to [line 93 of app.py](https://github.com/nottrobin/snapcraft.io/blob/add-back-werkzeug-debugger/app.py#L93).
Then `./run`, and load http://0.0.0.0:8004/ in the browser, and check you see:
> builtins.NameError
> NameError: name 'sdfgsdf' is not defined

Add werkzeug debugger in development mode

---

modules/publisher/api.py
modules/publisher/views.py
tests/endpoint_testing.py
tests/test_get_metrics.py

- Add missing test on test framework
- Handle errors get_metrics
Fixes #542 
- `./run`
- http://0.0.0.0:8004/account/snaps/toto/metrics
- `./run test`

Handle errors get_metrics

---

modules/publisher/api.py
modules/publisher/views.py
tests/test_get_metrics.py
tests/tests_post_listing.py

- Handle errors get_metadata
- Reove useless function
Fixes #543
- `./run`
- http://0.0.0.0:8004/account/snaps/toto/listing
- Do a modification 
- Should work
- Manage to do a invalid modification
- Should display the error message
- `./run test`

Handle errors metadata

---

templates/publisher/account-details.html

Be consistent with punctuation.

Full stop after publicly to match other field descriptions on the page

---

modules/public/logic.py
modules/public/views.py
static/js/publisher/market/publicMetrics.js
static/sass/_snapcraft_distro-chart.scss
static/sass/styles.scss
templates/publisher/listing.html
templates/snap-details.html
tests/tests_public_logic.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/534
Fixes https://github.com/canonical-websites/snapcraft.io/issues/533
- Added distro graph - without JS :open_mouth: shocker
- Added checkbox to listings page (fixes: https://github.com/canonical-websites/snapcraft.io/issues/524)
- `./run`
- Visit http://0.0.0.0:8004/snap_name
- Make sure the distro chart shows at the bottom of the page
- Visit Some other snaps
- See if the chart shows at the bottom of the page or not (won't show if no users)
- Go to http://0.0.0.0:8004/account/snaps/snap_name/listing
- Check/ uncheck the checkbox at the bottom of the page - visit the public page and see what happens with the graphs

Distro chart

---

static/sass/_snapcraft_details_heading.scss
templates/snap-details/_channel_map.html

Fixes #529 
Adds Vanilla help tooltips to explain what 'Architectures' 'Tracks' and 'Channels' are to channel map.
- ./run or http://snapcraft.io-pr-606.run.demo.haus/
- go to a public page of a snap (ideally one with several tracks) like skype or webstorm
- open channel map (by clicking on 'Show all versions')
- help icons should be visible next to 'Track' and 'Channel' labels
- hovering these icons should reveal tooltip with explanation

Add help tooltips to channel map

---

modules/publisher/logic.py
modules/publisher/views.py
tests/tests_publisher_logic.py

- Remove logic from view in account snaps endpoint
Fixes #550 
- `./run`
- http://127.0.0.1:8004/account/snaps

Remove logic from view account snaps endpoint

---

modules/publisher/logic.py
modules/publisher/views.py
tests/tests_publisher_logic.py

- Remove logic listing page (get)
Fixes #552 
- `./run`
- http://127.0.0.1:8004/account/snaps/toto/listing
- Test on snaps not on stable

Remove logic listing page

---

static/js/publisher/market/screenshots.js
static/js/publisher/market/screenshots.test.js
static/sass/_snapcraft_market_screenshots.scss

Fixes #414
Makes screenshots in listing form focusable (also with keyboard).
Focused screenshot has blue border (just like any other focused input). To make screenshots selection visible checkboxes where added on top of screenshots, so that selected screenshots have checkbox checked.
Multiple screenshots can be selected (multiple checkboxes checked) and therefore multiple screenshots can be deleted at once (by selecting them and clicking delete button).
- ./run or  http://snapcraft.io-pr-623.run.demo.haus/
- go to listing page of any snap (ideally with screenshots already)
- use keyboard tab to tab through the form (and screenshots)
- once screenshot is focused hit space to select/unselect it
- use mouse to click on screenshots to select/unselect it
- select multiple screenshots and …

Focusable screenshots in listing form

---

modules/public/logic.py
templates/snap-details.html
tests/tests_public_logic.py

On snap details pages, for the distro graph we currently show:
`distro - version`
nobody uses this format to describe their version, this PR changes it to:
`distro version`

Remove - from distro labels

---

modules/public/api.py
modules/public/logic.py
modules/public/views.py
templates/snap-details.html

Semi-temporary hack to ensure the latest nodejs shows on snapcraft.io.
Node don't use the 'Latest' track for their stable track, instead they use `:version:/stable` (currently '10/stable'). This is temporary until default tracks are implemented in the store.
- `./run`
- Visit http://0.0.0.0:8004/node or http://snapcraft.io-pr-636.run.demo.haus/node
- Ensure the page loads

Make sure nodejs shows up on the store

---

modules/publisher/logic.py
modules/publisher/views.py
static/sass/_snapcraft_snap-list.scss
templates/publisher/account-snaps.html
tests/tests_account_snaps.py
tests/tests_publisher_logic.py

- Added some more logic: If the oldest upload was over 30 days ago - it's not longer classed as 'new'
- Added close button that's persisted with a cookie
- Improved 'what to do next' from a list to paragraphs
You'll need:
- An account with 1 newly created snap
- An account with 1 snap that's over 30days old (or hack the code as described below)
To QA:
- `./run`
- Visit https://0.0.0.0:8004/account/snaps
To test different cases, edit the following code:
`/modules/publisher/logic.py:26` add `user_snaps = {'snap_you_have': user_snaps['snap_you_have']}`

Improved first snap experience

---

static/sass/_snapcraft_details_heading.scss
templates/snap-details/_channel_map.html

Fixes #618
Updates channel map layout for upcoming tabs and install button.
Install button on separate tab is part of another PR, not in scope of this issue.
- ./run or http://snapcraft.io-pr-641.run.demo.haus/
- go to detail pages of some snaps ([android-studio](http://snapcraft.io-pr-641.run.demo.haus/android-studio) [webstorm](http://snapcraft.io-pr-641.run.demo.haus/webstorm))
- open channel map
- it should have updated layout, X close icon, bigger cli install instructions

Update channel map layout

---

static/js/public/snap-details/channelMap.js

Fixes #646
Adds possibility to close channel map overlay by clicking anywhere outside of channel map (top navigation bar or dark overlay) or by pressing Escape key.
- ./run or http://snapcraft.io-pr-648.run.demo.haus/
- go to snap details page of any snap
- open channel map with 'Show all versions' button
- close it by clicking anywhere outside
- open again
- close it by pressing Esc
- open again
- close it by clicking X button in top right
- open again
- try to click around channel map (dropdowns, copy instructions) - it should not be closed by accident when using it

Close channel map when clicking outside or on Escape

---

app.py
modules/publisher/api.py
modules/publisher/views.py
templates/publisher/register-name.html
tests/tests_register_name.py

Add register name endpoint with basic template
Fixes https://github.com/CanonicalLtd/snappy-design-squad/issues/481
- `./run`
- http://127.0.0.1:8004/account/register-name
- Try to register a snap
- Go on my snaps and check if name is well registered

Add register name endpoint with basic template

---

templates/_layout.html

Now that the SEO stuff is live, **NOW** the google checker says that URL is required for an organization.
This adds the URL field.

Missing url from schema

---

static/js/public/snap-details/channelMap.js
static/sass/_snapcraft_details_heading.scss
templates/snap-details.html
templates/snap-details/_channel_map.html

Fixes #619 
Adds new tab to channel map overlay with install instructions for stable version and 'View in store' install button, that on supported system will open native store application.
- ./run or http://snapcraft.io-pr-653.run.demo.haus/
- go to details page of any snap
- open channel map via 'Show all versions' button
- on top there is a new tab with snap name and current version
- click it to open install tab
- you should see CLI install instructions for stable version (same as on snap details page)
- you should see 'View in store' button
- if you are on supported system clicking on a button should open store app for given snap

Adds install tab to channel map overlay

---

templates/publisher/account-snaps.html

Fixes https://github.com/canonicalltd/snapcraft-design/issues/417
- Added `is-shallow` to `p-strip`
- `./run`
- Visit http://0.0.0.0:8004/account/snaps with 1 new snap uploaded
- Ensure the spacing is smaller

Reduce spacing at the top my snaps page

---

templates/publisher/_beta-notification.html

Fixes #596 
- Updated beta bar notification from:
`BETA: Snapcraft.io is in Beta. Can't find something? Go back to the old version`(link to dashboard.snapcraft.io) 'or report an issue' (link to github snapcraft.io issues)
to:
`Thanks for trying out these new pages. Use dashboard for other functions` (link to dashboard.snapcraft.io) `report an issue` (link to github snapcraft.io issues) `or give us your feedback` (link to forum)
- `./run`
- Visit http://0.0.0.0:8004/account/
- Ensure the copy is updated

Updated beta bar notification copy

---

static/js/publisher/market/market.js
static/sass/_patterns_button_spinner.scss
static/sass/styles.scss
templates/publisher/listing.html

Fixes #602
Makes 'Save' button disabled when submit/upload is in progress. Also adds spinner to the button when loading takes more then 2 seconds.
- ./run or http://snapcraft.io-pr-664.run.demo.haus/
- go to listing page of any snap
- 'Save' button should be disabled until any change is made
- modify something (and possibly add some screenshots to upload)
- 'Save' button should become enabled
- click 'Save'
- 'Save' should become disabled
- after 2 seconds if save/upload didn't finish spinner should appear on button

Add spinner to save button (when saving)

---

static/js/public/snap-details/channelMap.js
static/sass/_snapcraft_details_heading.scss
templates/snap-details.html

Fixes #666  
- Move `command-line instructions` from the header to below the snap description
- Make `Install` a primary call to action
- Reduce copy from `Show All Versions` to `All Versions`
- `Install` and `All versions` open their relevant tabs on the Channel map
- `./run`
- Visit http://0.0.0.0:8004/vlc
- Ensure copy and layout is updated
- Ensure `Install` and `All versions` open the relevant tabs on the channel map

Make Install more prominent and remove duplication #666

---

templates/publisher/register-name.html
tests/tests_register_name.py
webapp/app.py
webapp/publisher/views.py

Fixes https://github.com/CanonicalLtd/snap-squad/issues/482
- Implement design for reserve name endpoint
- Add template to claime a dispute
- Stores not handled yet
Designs provided:
**Register name**
**Name dispute**
- `./run`
- http://127.0.0.1:8004/account/register-name
- Register a new snap
- Should redirect to `/account`
- http://127.0.0.1:8004/account/register-name?snap_name=SNAPNAME&is_private=True
- Fields should be filled
- Register a new snap
- Should redirect to `/account`
- http://127.0.0.1:8004/account/register-name
- Register a snap that already exists and that you don't own (I made one for you :heart: `test-register-snap-qa`)
- Should redirect your to: http://127.0.0.1:8004/account/register-name?snap_name=test-register-snap-qa&is_private=False&conflict=True
- Claim a …

Add style to reserve name templates

---

templates/publisher/listing.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/676
- Made 'Developer website' and 'Contact <% publisher_name %>' stacked
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/<% snap_name %>/listing
- Scroll down to see the stacked labels and inputs

Vertically align developer contact fields

---

static/js/public/snap-details/channelMap.js

A quick fix after looking at some stats with Greg. Each time the install button is clicked we send an event, however, if the button didn't work and a user perceives this as "oh, it didn't work I need to press it again maybe?" we'll get 2 events when really there was only a single intent.
You might want to install the browser extension 'Google analytics debugger' for your browser
- `./run`
- Visit a snap details page
- Open the overlay and click the 'View in Desktop store' button
- See the GA event being fired
- Click the 'View in Desktop store' button again
- See that another GA event isn't being sent
- Repeat until your mouse breaks or you get RSI.

Limit intent GA to first click

---

requirements.txt

Fixes #665 
- Upgrade api to v0.3
- Fixes problem for raising exceptions when macaroon is epxired
- `./run`
- Make sure apis calls still work :)

Upgrade api to version 0.3

---

static/js/publisher/market/market.js
static/js/publisher/market/state.js
templates/publisher/listing.html
webapp/publisher/logic.py
webapp/publisher/views.py

- Added `Private` toggle to listings page with some help text
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/snap_name/listing or http://snapcraft.io-pr-705.run.demo.haus/account/snaps/snap_name/listing
- Look at the `Private` section

Toggle snap privacy on listing page

---

static/sass/_snapcraft_p-navigation.scss
templates/_header.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/658
- Added logic to check for search pages and snap pages to the header
- `./run`
- Visit http://0.0.0.0:8004/store, http://0.0.0.0:8004/search?q=git, http://0.0.0.0:8004/spotify and see that 'Store' is highlighted in the navigation

Highlight store on snap and search page navigation

---

templates/blog/index.html
tests/blog/tests_index.py
webapp/blog/api.py
webapp/blog/blog.py

Fixes #699 
Get list of articles from insights API
Pass to the template 
- `./run`
- http://127.0.0.1:8004/blog
- Should see a long list of articles in JSON format

Get list of articles from API

---

static/js/base/polyfills.js
static/js/publisher/market/market.js

Fixes https://github.com/canonical-websites/snapcraft.io/issues/684
As a compromise I've implemented the following:
- When a user enters a website such as 'snapcraft.io', automatically prepend 'http://' in the form field (we should perhaps default to https?)
- When a user enters something that looks like an email address 'email@email.com' (containing 1 @ and at least 1 .) prepend 'mailto:'
Also added `Array.includes` and `String.includes` polyfills
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/snap_name/listing mess around with the contact details. Even if the JS lets you enter crazy data that doesn't seem correct the API should correct it and provide an error.

Better experience for contact inputs

---

templates/blog/post.html
tests/blog/tests_index.py
webapp/blog/api.py
webapp/blog/blog.py

Add article endpoint
- `./run`
- http://127.0.0.1:8004/blog/design-and-web-team-summary-4-june-2018
- Should be ok
- http://127.0.0.1:8004/blog/ubuntu-to-host-containers-in-amazons-eks-for-container-portability
- Should go to 404

Add article endpoint

---

tests/tests_agreement.py
tests/tests_publisher.py
tests/tests_register_name.py
tests/tests_username.py
webapp/app.py
webapp/publisher/views.py

- Add publisher bluepirint
- Fix redirections with function `url_for` to avoid hardcoded urls
- Fix tests to apply with the new redirections (`url_for` adds automatically a `/` at the end of the url)
- `./run`
- Navigate in publiser pages and make sure everything works as usual
http://127.0.0.1:8004/account
http://127.0.0.1:8004/account/details
http://127.0.0.1:8004/account/snaps
http://127.0.0.1:8004/account/username
http://127.0.0.1:8004/account/agreement
http://127.0.0.1:8004/account/snaps/toto/listing
http://127.0.0.1:8004/account/snaps/toto/market
http://127.0.0.1:8004/account/snaps/toto/measure
List of the routes (by running `flask routes`
```
account_page.get_account             GET        /account/
account_page.get_account_details     GET        /account/details …
```

Add publisher blueprint

---

.env
package.json
tests/blog/tests_index.py
tests/endpoint_testing.py
tests/tests_public.py
tests/tests_publisher.py
webapp/app.py
webapp/config.py
webapp/handlers.py
webapp/public/views.py

To help launching the brandstores I added 2 factories to build the app:
- create_snapcraft
- create_brandstore
Those 2 factories uses the same base `create_app` but they instanciate different blueprints.
To help running the tests those factories have a testing parameter so that not all the extensions added to snapcraft are run (prometheus, sentry, csrf)
The functions used in all the project (context_processor, 404) are moved into it's own file.
- `./run`
- Should have access to the usual snapcraft website
- Edit `.env` and change `FACTORY=create_snapcraft` to `FACTORY=create_brandstore`
- `./run`
- The home page should be the search page (might need to `ctrl + shift + r` (because of cached pages)

Use factories to launch snapcraft

---

static/js/libs/mobile.js
static/js/public/snap-details/screenshots.js

Fixes https://github.com/canonicalltd/snap-squad/issues/581
If the screenshots previous button is not visible when attempting to open the lightbox, open in a new tab instead.
This works because on mobile we rely on the horizontal scrolling, so the previous/ next buttons aren't loaded.
- `./run`
- View a snap detail page on desktop, click an image to open in the lightbox, it should work
- View a snap detail page on mobile, click an image and it should open in another tab

Only use lightbox if on a larger screen

---

tests/blog/tests_index.py
webapp/blog/api.py
webapp/blog/logic.py
webapp/blog/views.py

Fixes #703 
- Add rss feeds for s.io
- `./run`
- http://127.0.0.1:8004/blog/feed
- Make sure all links are redrecting to snapcraft.io instead of insights

Add rss feeds for blog

---

.env
templates/404.html
templates/_layout-brandstore.html
templates/blog/article.html
templates/blog/index.html
templates/index.html
templates/publisher/account-details.html
templates/publisher/account-snaps.html
templates/publisher/listing.html
templates/publisher/metrics.html
templates/publisher/register-name.html
templates/search.html
templates/snap-details.html
templates/store.html
templates/username.html
webapp/app.py
webapp/config.py
webapp/configs/snapcraft.py
webapp/handlers.py

Fixes #531
- Add configuration for brandstore.
- For each store we will have a config file in `webapp/configs/<brandstore>.py`
- `_layout_brandstore.html` will be the layout for brandstores, for now it is just a copy/paste from `_layout.html`
- `./run`
- Should have snapcraft as usual
- create file `brandstore.py`:
```python
WEBAPP_CONFIG = {
'LAYOUT': '_layout-brandstore.html',
'STORE_NAME': 'Super store'
}
```
- in `.env` change : `WEBAPP=snapcraft` to `WEBAPP=brandstore`
- `./run`
- Homepage should be `store` page
- You can add this somewhere in a template: `{{ webap_config['STORE_NAME'] }}`
- Super store should be displayed

Add brandstore configuration

---

package.json
requirements.txt

This converts the sync gunicorn worker to the async gevent
worker class. This is to prevent blocking of long requests.
Talisker provides a useful entrypoint when using gevent,
as HTTPS requests are required to be monkeypatched before
any other code is loaded.
`./run` as normal, it should say starting it is using worker gevent.
Click around a bunch, and we can test on staging further.
If you would like to do some heavier testing, I recommend installing `siege` and running this command on master and this branch:
```
siege http://localhost:8004 --concurrent 5 --reps 
```
It should be small number but show a relatively big improvement.
On my computer, the longest transaction went from 1.42 seconds to 0.36

Convert gunicorn worked to a async gevent worker

---

Dockerfile

Add webapp environment var to dockerfile
- `docker build --build-arg COMMIT_ID=test --build-arg WEBAPP=snapcraft --tag test-sio .`
- `docker run --rm -p 80:80 -it -e SECRET_KEY=adsf test-sio`

Add webapp environment variable to dockerfile

---

templates/_header-brandstore.html
templates/_layout-brandstore.html

Adds an example brand store header to layout.
- add a new config that uses _layout--brandstore
- run project with new config
- there should be a brand new header

Add demo brand store header

---

templates/publisher/account-snaps.html
templates/publisher/register-name.html
webapp/publisher/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/693
- Removed supporting message box and link to dashboard.snapcraft.io form instead
- Updated messaging at the top of the page
- Added flash message to top of snap list page when name successfully registered
- `./run`
- Visit http://0.0.0.0:8004/account/
- Click the 'Register name' at the top right of the snap list
- Try registering a name that you already have access to, make sure a message is displayed
- Try and register a name that is registered to someone else 'toto' for example, make sure a message is displayed with a link to the dashboard form
- Register a new name, that is not taken (prefixed with `test-`), make sure a message is displayed when you return to the snap list

Better registration

---

static/sass/_patterns_logo-list.scss
templates/index.html

Fixes #749 
Updates text size and weight on home page, removes unnecessary `u-no-margin` and fixes issue with logos alignment.
- ./run
- go to home page
- it should look nice

Vanilla home page updates

---

static/sass/_snapcraft_p-navigation.scss

**NOTE:** this is PR against Vanilla 1.7 branch, will not go live until other issues from https://github.com/CanonicalLtd/snap-squad/issues/563 are fixed
Fixes #747 
Uses new `$icon-sizes` to correct size of navigation dropdown chevron.
Also fixes rotation of the arrow when dropdown is open.
- ./run or http://snapcraft.io-pr-766.run.demo.haus/
- sign in
- Dropdown arrow should be as big as on current snapcraft.io (.75rem)
- When dropdown is open arrow should rotate

Fix icon size and rotation when dropdown is open

---

static/sass/_snapcraft_footer.scss

Fixes https://github.com/canonical-websites/snapcraft.io/issues/748
- Remove snapcraft override
- `./run`
- Visit a page and compare the footer to snapcraft.io

Equal footer padding above and below

---

static/sass/_base_image-grid.scss
static/sass/_patterns_featured-snaps.scss
static/sass/_patterns_logo-list.scss
static/sass/styles.scss
templates/index.html
templates/store.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/750
- Created featured-snaps pattern
- Removed `grid` `col` layout markup
- `./run`
- Visit http://0.0.0.0:8004/ and http://0.0.0.0:8004/store

Featured snaps

---

templates/index.html
templates/store.html

- go to home page
- featured snaps should be clickable
- go to /store
- featured snaps should be clickable

Adds missing URLs to featured snaps links

---

templates/index.html

Across all testimonials:
- Fixes the ugly Ascii quotes in the headings.
In the first testimonial:
- Drops these sentences: “We had been facing issues with packaging problems for years...snaps seemed it would make my life a lot easier. The auto-updating feature is huge and one that we haven’t seen elsewhere.” The first sentence could easily be misinterpreted as describing two problems with snaps. The second sentence is mostly redundant with the heading. And dropping both sentences brings the length of this testimonial in line with the other two.
In the second testimonial:
- Fixes the accidental “artifacts artefacts”.
- Fixes two grammar errors.
- Splits the paragraph in two.

Tweaks testimonials

---

templates/index.html

Small typo fix in Amazon logo alt attribute.

Typo fix (s/Amazons/Amazon)

---

static/sass/_snapcraft_details_heading.scss

Fixes #753 
- go to any snap details page
- there should be no big spacing between snap name and publisher
- buttons should be aligned with snap name
- it should look nice on all screen sizes

Update spacing of snap details heading

---

static/sass/_patterns_table-key-value.scss

Updates table styles, so there are no oversized borders.
Fixes #755 
- go to any snap detail page
- snap data table should have light dotted borders

Fix key-value table borders

---

static/js/public/snap-details/screenshots.js
templates/snap-details.html

Fixes #754 
- Adds some strips around content boxes on snap details page
- removes unnecessary `u-no-margin` overrides
- corrects the order of screenshots buttons (to fix new Vanilla margins)
- go to snap details page
- spacing should look good
- 'next' screenshot button should be correctly positioned

Fixes spacing on snap details page

---

static/sass/_snapcraft_details_heading.scss
templates/snap-details/_channel_map.html

Fixes #756 
Updates spacing and removes unnecessary styles for channel map overlay.
- go to snap details page
- Click Install or All versions, check if channel map and install looks good

Fix spacing of install/channels overlay

---

static/sass/_snapcraft_p-navigation.scss
templates/_header.html

We had some custom navigation styling that broke (for mobile) after Vanilla 1.7 update. This PR removes unnecessary styling to fix the issue.
- go to store page
- make sure Store is selected in navigation
- make screen small (so navigation turns into dropdown menu)
- make sure Store is still correctly selected

Fixes selected navigation styles (on mobile)

---

templates/publisher/listing.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/669
- Made chcekboxes a single column
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/SNAP_NAME/listing
- Ignore all the other style issues, scroll down to the bottom of the page
- The metrics checkboxes should be nicely aligned

Single column checkboxes

---

static/sass/styles.scss

Fixes #757
Workaround for vanilla bug - making sure img can be vertically centered with flexbox.
- go to snap details page or listing page
- open screenshot in lightbox
- screenshot should be vertically centered

Workaround for incorrect img alignment

---

templates/publisher/metrics.html

Fixes #798 
Adds strip section around each chart for better spacing.
###
- go to metrics page
- there should be reasonable space between the charts

Adds some spacing to metrics page

---

static/sass/_snapcraft_market_screenshots.scss

Fixes #764 
- go to snap market page (with screenshots)
- hover over screenshot - checkbox should be evenly aligned in the corner
- click to select - there should be no unnecessary top padding inside the border

Remove unnecessary padding from screenshot wrapper

---

templates/search.html

Fixes #752
Removes margin from heading in search result to workaround vanilla spacing issue in media object.
- go to search results
- there should be no big spacing between snap name and publisher

Workaround for vanilla media object bug in search results

---

.env
webapp/api/public.py
webapp/app.py
webapp/config.py
webapp/configs/brand.py
webapp/configs/snapcraft.py
webapp/public/views.py
webapp/snapcraft/views.py

Fixes https://github.com/CanonicalLtd/snap-squad/issues/588
Add possiblity to store to add a header in the API calls with `X-Ubuntu-Store`.
To do this I had to refactor the code so that blueprints have a constructor: `store_blueprint()` so that we can store parameters (for example `store_query` which is the store to query)
Same thing has been done for the API module which has been transformed into a class so that the header is built once.
- `./run`
- Should have snapcraft as usual
- In the folder `webapp/configs`, add the file `lime.py`:
```python
WEBAPP_CONFIG = {
'STORE_QUERY': 'LimeNET',
'LAYOUT': '_layout-brandstore.html',
'STORE_NAME': 'LimeNET'
}
```
- ~In `.env` file change `WEBAPP`: `WEBAPP=lime`~
- ~`./run`~
- `./run --env WEBAPP=lime`
- http://0.0.0.0:8004
- Search for lime, you …

Add store conf to have specific ubuntustore

---

.travis.yml

All the tests/lints are made with CircleCI, so I can remove `.travis.yaml`
Make sure the tests pass and travis is not running anymore

Remove travis.yaml

---

run

This is to fix a yarn permissions error on some usage of the run script.
It updates how CircleCI can mount .ssh folders.
./run should work as usual.
The tests in this PR should pass!

Run script Yarn permissions

---

.circleci/config.yml
.env
webapp/config.py

`WEBAPP` is a required configuration variable and should always be set.
We should avoid defaulting it to a value as it could result in a
misconfigured application. This change should not affect ./run script
and we already require this in the Dockerfile.
Any thoughts or disagreements on this?
No changes should be apparent in `./run`
Site should return error about WEBAPP if run with `./run --env WEBAPP=''`

Raise exception if `WEBAPP` is not defined

---

templates/publisher/release-history.html
tests/tests_revision.py
webapp/api/dashboard.py
webapp/publisher/snaps/views.py

Add release endpoint, which diplays the release history
- `./run`
- http://127.0.0.1:8004/account/snaps/toto/release

Add revision history endpoint

---

webapp/public/views.py

Fixes #833 
On details endpoint, if the metrics API fails the page returns an error because of an variable not defined: `metrics_reponses`
If the api fails I want the var to be `None` and I avoid to create the metrics objects.
- At line 197 add this line: `metrics_reponse = None`
- `./run`
- https://0.0.0.0:8004/toto
- The page should display without the metrics part

Fix var not referenced when API fails

---

webapp/publisher/snaps/views.py

The redirection from measure to metrics uses `url_for` and was not used well.
The first argument should be the redirection to have, the other arguments should be the function arguments and should be named (`snap_name=snap_name`)
- `./run`
- http://127.0.0.1:8004/account/snaps/toto/measure
- Should redirect to http://127.0.0.1:8004account/snaps/toto/metrics withour error

Fix url_for call for measure redirection

---

static/sass/_snapcraft_p-navigation.scss
templates/_header-brandstore.html
webapp/configs/lime.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/841
- Added some config for styles
- Implement the style in the navigation
- Updated navigation hover to be transparency based
- Change `.env` `WEBAPP=snapcraft` to `WEBAPP=lime`
- Update `webapp/configs/lime.py` add a URL to `STORE_BRAND LOGO` and a colour to `STORE_BRAND COLOUR`
- `./run`
- The header should have the image you set as the logo and the header background colour you set

Add some styles for brand-store header

---

templates/publisher/listing.html

Removes the implication that you need to include “mailto:” when entering an e-mail address. Fixes [snapcraft-design#437](https://github.com/CanonicalLtd/snapcraft-design/issues/437).
(Captions should normally be sentences ending in periods. I haven’t added a period here to be consistent with the other captions on the same page, but they should all be added at some point.)

Corrects help text for snap listing contact field

---

static/sass/_patterns_logo-links.scss
static/sass/_patterns_logo-list.scss

Fixes https://github.com/canonical-websites/snapcraft.io/issues/775
- `./run`
- Resize the browser narrow and wide
- Logos shouldn't go below 150px width and wrap nicely

Tools logos min-width

---

templates/_footer-brandstore.html
templates/_layout-brandstore.html
webapp/configs/lime.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/842
- Change `.env` `WEBAPP=snapcraft` to `WEBAPP=lime`
- Update `webapp/configs/lime.py` add some text to `FOOTER_TEXT` such as '&copy; 2018'
- `./run`
- The footer should display the 'Back to top' link and the text you've defined

Add footer string variable to brand store

---

static/sass/_patterns_logo-list.scss
templates/index.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/831
- `./run`
- Visit http://0.0.0.0:8004/
- Make sure the top publisher logos look correct

Improved homepage logos

---

webapp/store/views.py

Fixes #614
- Make Details endpoint case insensitive
- When accessing details endpoint with a Uppercase in the snap name, you should be redirect to the details endpoint with lower case snap name
- `./run`
- http://127.0.0.1:8004/firEfox
- http://127.0.0.1:8004/Firefox
- http://127.0.0.1:8004/FirefoX
- Should redirect to: - http://127.0.0.1:8004/firefox

Make details endpoint case insensitive

---

webapp/store/views.py

- Since the custom url route for brandstore's homepage some redirects were broken. Now instead of using the function `url_for` with as argument the name of the function, I use it with the name of the endpoint. Which here are the same for the 2 custom routes.
- `./run`
```
store.discover                     GET      /discover
store.homepage                     GET      /
store.search_snap                  GET      /search
store.snaps_view                   GET      /snaps
```
- search should work with empty search
- Other endpoint should redirect properly
- Make the same tests on brand store

Fix redirection to homage

---

templates/_header-brandstore.html
templates/brand-store/store.html
templates/partials/search-bar.html
webapp/store/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/843
- Added different template for brand store homepage
- Use the `get_all_snaps` method (with a limit) to display on the homepage
- Pull the brand
- Change `.env` `WEBAPP=lime`
- `./run`
- Visit http://0.0.0.0:8004/
- Make sure the lime snaps show and are cickable
- Stop the app
- Change `.env` `WEBAPP=snapcraft`
- `./run`
- Visit http://0.0.0.0:8004/
- Make sure the snapcraft.io site works

Brand store page

---

Dockerfile
entrypoint.sh
package.json

Update package.json and Dockerfile to use the same entrypoint for serving
Try to run locally and also build docker. They should work correctly and display gevent as the worker class.
`./run`
And also
- `docker build --build-arg COMMIT_ID=test --build-arg WEBAPP=snapcraft --tag test-sio .`
- `docker run --rm -p 80:80 -it -e SECRET_KEY=adsf test-sio`
Fixes #839

Add entrypoint.sh for package.json and Dockerfile

---

webapp/api/requests.py

This PR is built on top of #811 
---
When we are experiencing API failures we have load times longer than we would like. In testing this can be greatly improved by setting two timeouts as detailed in the [requests documentation](http://docs.python-requests.org/en/master/user/advanced/#timeouts)
This splits the timouts into:
- Connection timeout
- Read timeout
By setting a lower connection timeout, we can fail fast when the API server is completely unavailable and unresponsive. The read timeout then can be more flexible to allow a slow response to take place when needed.
To disable internet to test, you can turn your internet off or you can modify the `webapp/api/public.py` file. If you change the URL on line 11 to `'https://google.com:81',` all the API traffic will time out.
- `./run` and …

 Update the requests timeout for initial connection and total time 

---

templates/brand-store/store.html
webapp/configs/lime.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/869
- Added config option `STORE_INSTALL_INSTRUCTIONS`
- Added section to `brand-store/store.html` template to show install instructions
- Change `.env` `WEBAPP=lime`
- Change `lime.py` `STORE_INSTALL_INSTRUCTIONS=True`
- `./run`
- Visit http://0.0.0.0:8004/
- See the instructions

Install instructions

---

templates/brand-store/search.html
webapp/api/store.py
webapp/store/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/872
- Added new `brand-store/search.html` to remove unsused categories
- Change `.env` `WEBAPP=lime`
- Run `./run`
- Visit https://0.0.0.0:8004
- Search for something that exists, see the results ('lime')
- Search for something that doesn't, see the message

Add public brand store search

---

templates/store/snap-details.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/870
- Added if and else for brand-store to toggle display of the install button
- If brand store - show the CLI install instructions
- Change `.env` `WEBAPP=lime`
- `./run`
- Visit http://0.0.0.0:8004/limesuite
- Ensure there's not install button and you can copy and paste the CLI instructions

Don't show install buttons for brand stores

---

webapp/api/store.py

- Handle errors in for v2 of the api
- All `_` has bee replaced with `-` in the v2 of the API. I make sure that now we return the right error to the view.
- `./run`
- http://127.0.0.1:8004/greggless
- Should have a 404 page

Handle errors for v2 of the API

---

static/js/publisher/market/market.js
static/sass/_snapcraft_market.scss

Fixes #849 
* Disables revert button when entering a snap listing page
* Enables revert button when any field has been modified on snap listing page
* Pull the branch
* `./run`
* Visit http://0.0.0.0:8004/account/snaps
* View listing page of a published snap
* Revert button should be disabled and become active once a change has been done to any field in the listing page

Disabled revert button addition

---

static/sass/_button-overrides.scss
static/sass/_patterns_carousel.scss
static/sass/_patterns_logo-links.scss
static/sass/_snapcraft_market.scss
static/sass/_snapcraft_p-form-validation.scss
static/sass/_snapcraft_snap-list.scss
static/sass/styles.scss
templates/publisher/account-snaps.html
templates/publisher/listing.html
templates/publisher/register-name.html
templates/publisher/register-snap.html
tests/publisher/tests_register_name.py
webapp/publisher/views.py

Fixes #835 and #883 
- Add extra margin below 'private' on 'Register a snap' form
- Updates copy for CTA and page title for 'Register a snap'
- `./run`
- Visit http://0.0.0.0:8004/account/snaps
- View updated copy on 'Register a name' to 'Register a snap'
- Click on 'Register a snap'
- View updated copy on page title from 'Register a snap name' to 'Register a snap'

Update register snap name title

---

templates/store/snap-details/_channel_map.html

Fixes #891 
- Removed `--channel` reference on snapd install instructions
- `./run`
- Visit http://0.0.0.0:8004/vlc
- Click on `Install`
- Copy install with snapd command line instructions
- Run copied code in terminal
- No error shown by `snapd`

Remove default channel reference

---

static/js/public/snap-details/channelMap.js
templates/store/snap-details.html
templates/store/snap-details/_channel_map.html
webapp/api/store.py
webapp/store/logic.py
webapp/store/views.py

- Enables the `wide` `scope` on the search endpoint
- Hides the install button and associated overlay if there is not a stable version
- `./run`
- Search for `hello-roadmr`
- You should get many more results than https://snapcraft.io/search?category=&q=hello-roadmr
- Click on `hello-roadmr-comm4`
- You should not have the install button in the header and clicking 'all versions' should only have 1 tab

Surface non-stable snaps in search

---

static/js/libs/events.js
static/js/public/snap-details/channelMap.js
static/js/public/snap-details/map.js
static/sass/_snapcraft_details_heading.scss
static/sass/styles.scss
templates/store/snap-details.html
templates/store/snap-details/_channel_map.html
tests/store/tests_public_logic.py
webapp/store/logic.py
webapp/store/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/731
- Refactored `channelMap.js` to be a class
- Refactored `_channel_map.html`
- Added extra styles to `_snapcraft_details_heading.scss`
- Included `vf-u-hide`
- Removed `Size` and `Version` but added `Last updated` in the details table on the snap details page
- Better implemented `defaultTrack` throughought (hardcoded to 'node' for now, until implemented store-side)
- Made `copySuccess` a method on the global `snapcraft` so as to initialize within JS
- Added `get_lowest_available_risk` to find the lowest available risk for the default track
- `./run`
- Click on some snaps, search for snaps and click on them
- For each snap click the 'Install' button, make sure the overlay …

Updated channel map

---

templates/_header-brandstore.html
templates/_header.html

<nav> isn't allowed to have a role of `menubar` so let's remove it. There's a default role for <nav>

Remove bogus role="menubar" from <nav>

---

tests/publisher/tests_account_snaps.py
tests/publisher/tests_publisher_logic.py
webapp/publisher/snaps/logic.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/890
- A simple check around whether any of the snaps are revoked
- `./run`
- Visit http://0.0.0.0/account/snaps
- Any revoked snaps should not be shown

Hide revoked snaps

---

.babelrc
package.json
rollup.config.js
static/js/publisher/release.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss
static/sass/styles.scss
templates/publisher/release-history.html
yarn.lock

Fixes #894 
Adds simple static releases table to publishers snap revisions page
- go to publisher snap revisions page
- above revisions list there should be a table of released revisions
- table should only contain architectures that were released

Add simple release table to revisions page

---

templates/_header.html

Added an external link icon to the forum item in the snapcraft.io main navigation.
1. Go to [snapcraft.io](https://snapcraft.io) or [snapcraft.io/store](https://snapcraft.io/store)
2. Notice the external link icon from vanilla in the forum link
There are pending updates to build and docs that will propagate this change across the different domains:
[s.io#921](https://github.com/canonical-websites/snapcraft.io/issues/921)
[docs#419](https://github.com/canonical-docs/snappy-docs/issues/419)

Added external link icon to forum item on header

---

templates/_layout.html

This PR makes snapcraft.io js whitelisting more specific - by setting the path we should remove unrelated errors on the page, but it does mean that any inline code we have written will not be caught.

Updated whitelisting to make it more specific

---

static/js/public/snap-details/channelMap.js
templates/store/snap-details.html

This PR removes the complicated intent tracking to only fire an event when the green install button is clicked.
@caldav the important part:
```
{
hitType: 'event',
eventCategory: 'Snap details',
eventAction: 'Open install dialog',
eventLabel: `Open install dialog screen for ${this.packageName} snap`
}
```

Simplify install intent GA

---

webapp/store/logic.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/932 and allows certain snap pages to load again (etcd for example)
- `./run`
- Visit http://0.0.0.0:8004/etcd
- It should load and work as expected

Correct python if statement

---

templates/publisher/listing.html

A private snap's Listing page currently links a user to dashboard to manage the snap's privacy settings, but we can manage those settings on the Listing page itself.

Remove link to dashboard.snapcraft.io

---

templates/_layout.html
templates/index.html

Adds copy doc metadata to snapcraft.io home page.
- go to https://github.com/bartaz/ubuntu-copy-docs and install extension for Firefox or Chrome
- with extension installed visit snapcraft home page http://snapcraft.io-pr-936.run.demo.haus
- there should be a link at the bottom that goes to copy doc

[HACKDAY] Add copydocs metadata

---

templates/publisher/listing.html

A snap is available in the store no matter what channel it is in, so I removed that line from non-stable snap's Listing page.
1. Open the demo and head to [a non-stable snap](http://snapcraft.io-pr-945.run.demo.haus/account/snaps/grelementary/listing)
1. See that the message is displayed as the screenshot below

Removed 'stable only' store listing help text

---

templates/blog/article.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/953
- `./run`
- Click on a blog post
- Check the title is a `<h1 class="p-heading--two">`

h1 blog titles

---

tests/publisher/snaps/tests_post_listing.py
webapp/api/dashboard.py

As per
https://bugs.launchpad.net/snapstore/+bug/1782368
https://bugs.launchpad.net/snapstore/+bug/1782368/comments/3
https://code.launchpad.net/~matiasb/software-center-agent/metadata-api-conflict-on-update/+merge/351809
https://code.launchpad.net/~matiasb/software-center-agent/conflict-on-update-docs/+merge/351813
This sets the `conflict_on_update` query param when saving on the listings page and should resolve the issue of metadata being overwritten when pushing a new snap to the store.
Hard to QA before the API update is live

Added conflict_on_update flag for listing PUTs

---

static/js/public/snap-details/channelMap.js

Another attempt to fix the `innerHTML` issue.
This PR doesn't show the 'other versions' button if the template lookup fails. This doesn't fix the issue, but prevents a broken button while we investigate the root cause of the issue.

Don't show 'other versions' if template fails

---

static/js/public/snap-details/channelMap.js
templates/store/snap-details.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/959
- If the channel map overlay isn't present at the start of execution, abandon with a message to sentry
- Start the channel map js on `DOMContentLoaded`
- Extra `try {} catch` around screenshots
Again hard to QA because we can't replicate the issue

Further fixes for innerHTML and more logging

---

static/js/public/snap-details/channelMap.js
templates/store/snap-details/_channel_map.html
tests/store/tests_public_logic.py
webapp/store/logic.py
webapp/store/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/928
- `./run`
- Visit http://0.0.0.0:8004/powershell
- Click the install button, the CLI command should include `--classic`
- Click around the 'Other versions' they should all also contain `--classic` along with their track params
- Visit http://0.0.0.0:8004/slack
- Repeat the above and see similar results
- Visit http://0.0.0.0:8004/surl
- Notice there isn't a `--classic` param
- Squeal with excitement

Show --classic on snap details

---

templates/publisher/_publisher_layout.html
templates/publisher/account-details.html
templates/publisher/account-snaps.html
templates/publisher/developer_programme_agreement.html
templates/publisher/listing.html
templates/publisher/metrics.html
templates/publisher/register-snap.html
templates/publisher/release-history.html
templates/publisher/username.html
templates/store/search.html
templates/store/snap-details.html

Removes copydoc metadata from publisher pages, search and snap details (as they don't and will not have a copy doc).
- have Ubuntu Copy Docs extension installed
- go to publisher pages - there should be no copy doc link in the bottom
- go to search - there should be no copy doc link in the bottom
- go to snap details - there should be no copy doc link
- go to snapcraft.io home page - there should be a copy doc link

Remove copydocs metadata where it's not needed

---

webapp/store/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/971
- Assign `category_results = []` in case `api.get_searched_snaps` fails
- `./run`
- There should be no errors in the terminal
- Remove lines 408 and 409 from `/webapp/store/views.py`
- There should be some an error in the terminal (this is how it used to be)
- Add lines 408 and 408 to `/webapp/store/views.py`
- Change the contents of the `try {` block to be `print('test')`
- No errors on fail! Success!

Declare category_results before use

---

webapp/api/dashboard.py

As suggested in https://github.com/canonical-websites/snapcraft.io/issues/976

Relaxing publisher API timeouts.

---

static/sass/_snapcraft_custom-typography.scss
static/sass/_snapcraft_p-build.scss
static/sass/styles.scss
templates/_header.html
templates/snapcraft/build.html
webapp/snapcraft/views.py
webapp/template_utils.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/919
- Added the content in a more familiar vanilla style
- `./run`
- Visit http://0.0.0.0:8004/build
- Compare the page to https://build.snapcraft.io

Add build.snapcraft.io homepage to snapcraft.io/build

---

webapp/store/views.py

Fixes #901 
If a snap got all its channel map deleted the API responds that the snap exists. On the details page we want to return a 404 so that the user doesn't try to download the snap
- `./run` 
- http://0.0.0.0:8004/mir-kiosk-browser
- Should return a 404

Return 404 if no channel map

---

static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss
templates/publisher/_header.html
templates/publisher/release-history.html

*Work in progress*
Fixes #967 
Done:
- adds undo 'X' button next to promoted release, so single release can be canceled
- adds tooltip with list of all revisions to be released next to confirm button

Add undo release button

---

templates/brand-store/store.html

Updates script commands on LimeNET homepage
- Pull the branch 
- Edit `.env` file to run the LimeNET brand store
- Run `./run`
- Visit https://0.0.0.0:8004
- Compare to the [copy doc](https://docs.google.com/document/d/1EFWYq_RK1IpmuI__3ipmBoFNWNxIbFghdDgKt9DdQcI/edit#)

Fixed LimeNET command instructions on homepage

---

templates/_layout.html

Ignore errors from js modules: took this from documentation: https://docs.sentry.io/clients/javascript/config/

Ignore errors from js modules

---

static/js/publisher/release.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/revisionsTable.js
templates/publisher/release-history.html
tests/publisher/snaps/tests_revision.py
webapp/api/dashboard.py
webapp/publisher/snaps/views.py

Fixes #968 
- Go to releases page of some snaps
- Everything should work as before
- You can compare with public view to see that same revisions are shown as released
Also test locally with RELEASE_UI_ENABLED flag turned off. You may compare with public view

Use releases v2 API instead of revision history

---

static/js/publisher/release/revisionsList.js

Fixes #1010
Uses correct revision date field when displaying list of releases.
- ./run or http://snapcraft.io-pr-1012.run.demo.haus/
- sign in to Developer account
- go to Releases page of any of your snap
- look at revisions date - correct dates should be shown instead of 'few seconds ago'

Fix release date

---

templates/blog/article.html
templates/blog/index.html
templates/snapcraft/build.html

Adds a copy docs links to /build and /blog pages
- have a [ubuntu copy docs extension](https://github.com/canonical-webteam/ubuntu-copy-docs) installed in browser
- go to /build
- there should be correct link to build page copy doc
- go to /blog
- there should be correct link to blog page copy doc
- go to any blog article
- there should be no copy doc link (blog posts don't have copy docs)

Add copydocs to build and blog pages

---

requirements.txt
tests/blog/tests_index.py
webapp/api/blog.py
webapp/app.py
webapp/blog/views.py
webapp/extensions.py

Cache api calls in snapcraft's blog. Use our own caching system
- `./run`
- /blog
- make sure pages are cached

Cache blog api calls

---

templates/store/snap-details.html
webapp/store/views.py

Don't show metrics on public brand store details pages.
- `./run`
- Visit http://0.0.0.0:8004/core
- See the metrics
- Stop the app
- Change `.env` `WEBAPP=limenet`
- `./run`
- Visit http://0.0.0.0:8004/core
- Don't see the metrics

Hide public metrics on brand stores

---

Dockerfile

Currently, building the docker image for snapcraft.io requires that you provide `--env WEBAPP=snapcraft`.
Since this is the "snapcraft.io" repository, this shouldn't be the case. The app should just work for snapcraft.io, with customisations is necessary for the brand stores etc.
So here's I'm doing the quicked possible fix, to just default the `WEBAPP` environment variable to be `snapcraft`.
QA
--
``` bash
docker build --tag snapcraft --build-arg COMMIT_ID=`git rev-parse --short HEAD` .
docker run -ti -p 8099:80 snapcraft
```
Go to http://localhost:8099, and see that the site works.

Default WEBAPP=snapcraft

---

webapp/store/logic.py

Fixes #1021 
`bleach.clean` has a weird behaviour:
```python
from bleach import clean
clean("<IP-Address>") # OUTPUT '&lt;ip-address&gt;&lt;/ip-address&gt;'
```
We just want to escape the html tags, so instead I use the core library: `xml.sax.saxutils` to escape the <  and >
- `./run`
- http://localhost:8004/tvheadend
- Make sure in the description the tag `<IP-Adress>` is well displayed
- http://localhost:8004/tbmb-bsi-test-2
- Make sure links still work

Escape only html tags in description

---

entrypoint
requirements.txt

- Use statsd < 3.3 (fixes https://github.com/canonical-websites/snapcraft.io/issues/1042)
- Only use Talisker development settings in development
QA
--
``` bash
./run
```
Go to http://127.0.0.1:8004, check it works.
``` bash
docker build --tag snapcraft --build-arg COMMIT_ID=`git rev-parse --short HEAD` .
docker run -ti -p 8904:80 snapcraft
```
Go to http://0.0.0.0:8904/, check it works.

Fix talisker entrypoint

---

entrypoint

We had a problem that when FLASK_DEBUG was unset, `if ${FLASK_DEBUG}` would evaluate to true.
I've fixed this by using the better syntax of `if [ "${FLASK_DEBUG}" = true ]`. For discussion see https://stackoverflow.com/questions/2953646/how-to-declare-and-use-boolean-variables-in-shell-script.
I've also added a "RUN_COMMAND" variable so we can more clearly show the difference between development and production settings.
QA
--
First, edit `./entrypoint`, and change the line `set -e` to `set -ex`, so we can see what command is being run.
**Test with FLASK_DEBUG=true**
`./run --env FLASK_DEBUG=true`, or simply `./run`, and check you see the development command in the output:
```
$ ./run --env FLASK_DEBUG=true
...
+ '[' true = true ']'
+ talisker.gunicorn.gevent 'webapp.app:create_app()' …
```

Fix entrypoint logic

---

static/js/public/snap-details/map.js

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1029
- To force the most likely error that occurs:
- Change `static/js/public/snap-details/map.js:9` to a json file that doesn't exist
- `./run`
- Visit http://0.0.0.0:8004/vscode with the console open
- See a useful error

On map error, throw a useful error

---

static/js/public/snap-details/map.js

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1028, hopefully
There's no easy way to reproduce there's no way I've found to reproduce this issue, even with the d3 script removed from the HTML it works as expected. This will hopefully mitigate some of the errors we've been receiving.

Fail fast on not having d3 defined

---

static/js/public/public.js
static/js/public/snap-details/blog-posts.js
static/sass/_patterns_card.scss
templates/blog/index.html
templates/partials/blog-card--minimal.html
templates/partials/blog-card.html
templates/store/snap-details.html
webapp/api/blog.py
webapp/blog/logic.py
webapp/blog/views.py
webapp/store/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1025 and https://github.com/canonical-websites/snapcraft.io/issues/1030
- `./run`
- Open a few snaps from that page, some will have blog posts, others won't
- Give feedback
Waste of space
Not the worse
Description gets lost

Add blog posts to snap details pages

---

static/js/publisher/release.js
templates/publisher/release-history.html
tests/publisher/snaps/tests_revision.py
webapp/publisher/snaps/views.py

Fixes #946
Gets `channel_maps_list` data from published info api to releases page, so we could use it to accurately build releases matrix.
- ./run or http://snapcraft.io-pr-1048.run.demo.haus/
- View source, see if channel map data is passed to `initReleases` JS function on the page.

Get channel maps data into releases template

---

static/js/publisher/release.js
static/js/publisher/release/revisionsTable.js

Fixes #947 
Updates release UI to use channel map data from API instead of (mis)calculating it from incomplete release history.
- ./run or http://snapcraft.io-pr-1053.run.demo.haus/
- go to release page of some snaps (some with many releases, different tracks)
- make sure channel map shows correct versions (compare with details page channel map)
- make sure release UI prototype buttons (promote, cancel) still work

Use real channel map data

---

templates/blog/article.html
webapp/blog/logic.py
webapp/blog/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1058
- `./run`
- Visit http://0.0.0.0:8004/blog/your-first-robot-sharing-with-others-5-5
- You should see the sidebar with related blog posts
- Visit http://0.0.0.0:8004/blog/top-10-linux-apps-for-entertainment-and-leisure
- You should not see the sidebar or any errors in the console

Only initialize blog series if element is present

---

.gitignore
package.json
tests/publisher/endpoint_testing.py
tests/publisher/snaps/tests_listing.py
webapp/helpers.py
webapp/publisher/snaps/views.py

Fixes #1031
We are getting the licenses from this file to always get the last licenses updates: https://github.com/spdx/license-list-data/blob/master/json/licenses.json
- First commit is a little improvement for my tests.
- The file is fetched at build time (`yarn build`)
For now I am just giving the licenses to the frontend, so you can check that the array is well passed to the frontend (by just displaying it for now)

Use licenses from spdx github

---

static/js/public/snap-details/blog-posts.js

- `./run`
- Go to a snap without a related blog post
- The heading 'Related blog posts' shouldn't appear

Don't show related posts if there are none

---

tests/publisher/endpoint_testing.py
tests/publisher/snaps/tests_post_release.py
webapp/api/dashboard.py
webapp/publisher/snaps/views.py

Fixes #948 
Add post release endpoint
I had to adapt the BaseTests to be able to have some api style endpoints
@bartaz you can try to rebase your [PR](https://github.com/canonical-websites/snapcraft.io/pull/1059) on this to try the data you are posting
It uses and returns the same info that the api: https://dashboard.snapcraft.io/docs/api/snap.html#release-a-snap-build-to-a-channel

Add release post endpoint

---

webapp/api/store.py

Add scope wide for featured snaps, allows us to display snaps not on stable (e.g. node)
- `./run`
- http://127.0.0.1:8004/
- Make sure node is displayed in the feature snaps section on the homepage

Add scope=wide for featured snaps

---

tests/blog/tests_index.py
webapp/blog/views.py

There is an issue with the blog api not returning scaled images: https://github.com/canonical-websites/blog.ubuntu.com/issues/405
This PR prevents the `featured_images` being resolved until that issue is fixed.
- `./run`
- Make sure the page loads quicker and doesn't include images for blog posts

Don't show images on blog list page

---

webapp/login/views.py

Redirect to login.ubuntu.com if username is not set
- Create an account without username
- `./run`
- Try to login
- You should be redirected to login.ubuntu.com

Redirect if user has no usernames

---

.env
static/js/publisher/release/revisionsTable.js
templates/publisher/release-history.html
webapp/configs/snapcraft.py
webapp/publisher/snaps/views.py

Removes `RELEASE_UI_ENABLED` feature flag making releasing UI enabled for everyone.
Make sure feature flag is removed or turned off and see if release UI is there on Releases page.

Remove RELEASE_UI_ENABLED feature flag

---

static/js/publisher/release.js

Fixes #1071 
Properly making sure that there are no duplicated entries on channels list. Also ignores releases into branches.
- ./run or http://snapcraft.io-pr-1083.run.demo.haus/
- go to a snap that has some releases into branches
- releases into branches shouldn't show up on releases list in channels column
Example snap http://snapcraft.io-pr-1083.run.demo.haus/account/snaps/currate/release:

Ignore branch releases

---

templates/publisher/developer_programme_agreement.html

in some cases raven is not defined, which blocks the js snippet to enable/disable the continue button on the developer agreement
- Create new user
- Login in mobile view
- on agreement page tick and untick the checkbox
- Make sure button is enabled/disabled

Move script tag to a jinja script block

---

templates/partials/search-bar.html
templates/store/search.html
templates/store/store.html

QA
1. Pull the branch
2. Go to `/store`
3. Check you can access the correspondent [copydoc document](https://docs.google.com/document/d/10j4xltRGXrqp1e3mJicSft3vHpzpnCdCRXMNpspvJ2c/edit)
4. You should notice a new heading intro above the Search bar
**Note:** Make sure you have installed the copydoc extension for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/ubuntu-copy-docs/) or [Chrome](https://chrome.google.com/webstore/detail/ubuntu-copy-docs/cmljegnknolilmjdconnapgllmefigfl?hl=en)

Updated copy and copydoc link on store page

---

webapp/helpers.py

Some custom licenses not part of spdx are missing (Proprietary for ex)
They are added trying to follow the pattern of this [file](https://github.com/spdx/license-list-data/blob/master/json/licenses.json)
- Print the licenses in the listing page
- `./run`
- http://127.0.0.1:8004/account/snaps/toto/listing
- Make sure the licenses added are in the array

Add missing custom licenses

---

static/js/publisher/metrics/graphs/activeDevices.js
templates/publisher/metrics.html

While working on the settings page, I noticed that the active devices graph stopped working.
I realised the selector for the svg on the page wasn't specific enough (it was just finding the first svg).
This fixes that.... And removes the inclusion of billboard and d3.min in the HTML.
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1092
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/<snap_name>/metrics
- Make sure the active devices graph shows.

Metrics selector fix

---

tests/snapcraft/tests_public.py
webapp/snapcraft/views.py

we don't diplay the feature snaps in the homepage
remove the api call
- `./run`
- http://127.0.0.1:8004/
- Homepage should still work

Remove feature snaps api call from homepage

---

static/js/publisher/release.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss
templates/publisher/release-history.html

Fixes #1069 
Adds ability to release unreleased revisions (from Revision history table) to edge
- ./run or http://snapcraft.io-pr-1085.run.demo.haus/
- go to Release page of snap you own
- Click on arrow (Promote) button next to revision from revisions table
- it should be displayed in releases table as pending release
- try to cancel it, or promote to other channel

Release unreleased revisions

---

package.json
rollup.config.js

Use rollup built in watch not to rebuild all JS on every change.
- ./run build
- all should build as before, but without uglifying js
- ./run exec yarn watch-js
- rollup watch should run, uglify plugin should be disabled, when file is changed only one bundle should be rebuilt
- only on production env (based on ENVIRONMENT variable) uglify will be enabled

Use rollup watch

---

webapp/blog/views.py

Fixes #1115 
Fixes https://sentry.io/canonical-bm/snapcraftio/issues/668749462
When API fails the objcet should be an empty array to be iterable for the loop.
You can make sure it works by assigning the variable with an empty array after the try catch and go on http://127.0.0.1:8004/lxd No article should be displayed

Fix undefined var

---

entrypoint
webapp/app.py
webapp/extensions.py

- enable access log on talisker.gunicorn
- Remove sentry dependency that was overwritting talisker"s configuration 
- `./run`
- Navigate in the website and make sure there is more info on the console

Enable access log and remove sentry dependency

---

package.json

On build if `licenses.json` already here, don't download it.
- `yarn clean`
- `yarn build`
- license.json should be downloaded
- `yarn build`
- licenses.json shouldn't be downloaded

Don't download licenses if file already here

---

static/js/publisher/release/promoteButton.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss

Fixes #1119
- Adds possibility to promote whole channel at once (all architectures) - button with dropdown
- Removes buttons from single revisions (we will introduce checkboxes later)
- ./run or http://snapcraft.io-pr-1120.run.demo.haus/
- go to Release page of any snap
- click on arrow button next to channel to prepare for release of whole channel

Release UI: promote channel

---

static/sass/_utilities_crop.scss

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1128
- `./run`
- See the images fit

Ensure images fit on /blog

---

package.json
yarn.lock

Upgrades `rollup` to latest version to fix issues with rollup watch.
- ./run build
- everything should build properly as before
- please note there will be some 'circular dependency' warnings that rollup didn't show before
- ./run exec yarn watch-js
- rollup watch should run and should properly update on change in any JS file that is part of any bundle

Rollup upgrade

---

README.md

Adds missing API v2 staging URLS to README
- Copy instructions to .env file.
- ./run
- check if staging is used everywhere

Add API v2 staging URLs to README

---

tests/publisher/snaps/tests_listing.py
tests/publisher/snaps/tests_post_listing.py
tests/publisher/snaps/tests_post_settings.py
tests/publisher/snaps/tests_settings.py
webapp/publisher/snaps/views.py

Fixes #1130 
Add missing metadata to templates
- `./run`
- Go on listing page and make sure you can display the metadata added
- same for the setitngs page

Add missing metadata to templates

---

tests/publisher/snaps/tests_post_close_channel.py
webapp/api/dashboard.py
webapp/publisher/snaps/views.py

Fixes #1132 
Add close channel endpoint 
https://dashboard.snapcraft.io/docs/api/snap.html#close-a-channel-for-a-snap-package
It's written in the same way as the realease endpoint
@bartaz you can try with the frontend you write
```
POST /SNAP_NAME/release/close-channel
{
info to send to the API
}
```

Add close channel endpoint

---

static/js/public/snap-details/screenshots.js
templates/store/snap-details.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1164
- `./run`
- Visit http://0.0.0.0:8004/skype
- Inspect the screenshots to see the URL's
- View the Network tab and reload the page
- See a lower download size
- Click on an image to open it in the lightbox
- Click through the lightbox
- Make sure everything works and appears as expected

Use cloudinary for snap-details images

---

webapp/snapcraft/views.py

By default talisker's endpoint /_status/check makes a request to the flask app to check if it has this endpoint. This generates a 404 that is not logged by talisker but prometheus logs it. This generates a lot of 404 since this endpoint is hitted every 5sec by k8s
I added a custom /_status/check endpoint to have clean prometheus metrics
- `./run`
- http://127.0.0.1:8004/_status/check
- Should have a page with OK

Add /_status/check endpoint

---

static/js/publisher/release/promoteButton.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/revisionsTable.js

Fixes #1133 
Adds possibility to close a channel from Release UI dropdown.
- ./run or http://snapcraft.io-canonical-websites-pr-1166.run.demo.haus/
- go to Releases page 
- if there are any releases in a channel you should be able to close it from the dropdown button
- try releasing some revisions, closing multiple channels at once, etc

Closing channel in release UI

---

static/js/publisher/release/promoteButton.js

Fixes the issue that channel dropdown doesn't always close properly when clicked outside of it.
- go to Release page of some snap
- open dropdowns on any channel
- click outside, dropdowns should close properly
- close any channel (so it's button dissapears)
- click on any other dropdown
- click outside of it
- it should still properly close

Fix closing dropdown when clicking outside

---

templates/partials/search-bar.html

We added a heading to the /store page, this isn't really relevant for brand stores.

Only show title above search bar if not a brand store

---

static/sass/_snapcraft_custom-typography.scss
templates/index.html
templates/partials/search-bar.html
templates/publisher/_header.html
templates/publisher/account-snaps.html
templates/publisher/developer_programme_agreement.html
templates/publisher/register-snap.html
templates/publisher/username.html
templates/snapcraft/build.html
templates/store/store.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1155
Supercedes https://github.com/canonical-websites/snapcraft.io/pull/1147
- `./run`
- Visit all the pages affected by this PR (see the file list)
- Ensure the h1's and h2's are the thinner weight

Consistent and thinner weight headings

---

static/sass/_patterns_snap-row.scss

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1162
- `./run`
- Visit http://0.0.0.0:8004/store and http://0.0.0.0:8004/iot
- Ensure the space between the snap strips is the same

Ensure spacing below snap lists is the same

---

static/js/public/fsf-language-select.js
static/js/public/public.js
static/sass/_patterns_first-snap-flow.scss
static/sass/_patterns_logo-links.scss
static/sass/styles.scss
templates/home/_fsf_c.html
templates/home/_fsf_electron.html
templates/home/_fsf_go.html
templates/home/_fsf_java.html
templates/home/_fsf_moos.html
templates/home/_fsf_node.html
templates/home/_fsf_pre-built.html
templates/home/_fsf_python.html
templates/home/_fsf_ros.html
templates/home/_fsf_ros2.html
templates/home/_fsf_ruby.html
templates/home/_fsf_rust.html
templates/index.html

Fixes #1135 
Adds more details and examples to languages/tools on home page, as a first step of future first snap flow.
Copy doc: https://docs.google.com/spreadsheets/d/1gN_xcaAFFP_ckDvWeNDpD9ogbRXFgcXN0w0ITZQB0e4/edit#gid=779498506
- ./run or http://snapcraft.io-canonical-websites-pr-1178.run.demo.haus/
- go to 'Snap any application' section of the home page
- click on language/tool - a panel should open with the details
- clicking on 'Continue' button should lead to a docs page for given tool
- click around, make sure panels open and close properly
- try different screen sizes

Home page first snap flow

---

requirements.txt
templates/503.html
webapp/api/exceptions.py
webapp/api/requests.py
webapp/blog/views.py
webapp/handlers.py
webapp/login/views.py
webapp/publisher/snaps/views.py
webapp/publisher/views.py
webapp/store/views.py

Fixes #1142 
- Add circtuit breaker to the requests class. After a 100 failures the requests are blocked and returns an excpection `ApiCircuitBreaker` which when catched goes to a 503 page: 
- in `webapp/api/requests.py` modify `db_breaker = CircuitBreaker(fail_max=100)` to `db_breaker = CircuitBreaker(fail_max=5)`
- Disconnect from network
- `./run`
- reload 5 times page http://127.0.0.1:8004/toto
- you should be redirected after 5 times to the maintenance page :heart:

Add circuit breaker to the application

---

static/js/publisher/release.js
static/js/publisher/release/constants.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss
templates/publisher/release-history.html

Fixes #1134
Adds checkboxes to revisions list, so any unreleased revision can be selected into 'unassigned' channel and then released.
Also makes sure revisions from unreleased architectures can be selected and released, even if they are not currently in channel map.
- ./run or http://snapcraft.io-canonical-websites-pr-1145.run.demo.haus/
- go to Releases page of any snap you own
- you should see checkboxes on the revisions table
- select any revision by clicking on checkbox (or revision number)
- revision should get selected (into 'unassigned' channel)
- revisions from same architecture should be grayed out (as one revision per architecture can be selected)
- select other revisions (from other architectures) if you have them
- release 'unassigned' revisions to any channel using context …

Select revisions into fake unassigned channel

---

templates/store/snap-details.html

Publishers are reporting gifs are no longer working. This fixes it

Show gifs on snap-details pages

---

requirements.txt

Add version to prometheus_client since it makes talikster crash with the latest version of prometheus
- `./run`
- make sure snapcraft still work (no impact on the site just on talikster)

Set version prometheus

---

rollup.config.js

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1197
- `./run build-js`
- Open `static/js/dist/public.js`
- Search for all instances of `class ` (include the space, otherwise there will be way too many)
- Check there isn't a class decleration

transpile node_module dependencies

---

static/js/publisher/release.js
static/js/publisher/release/devmodeIcon.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss

Fixes #1186 
Adds information about devmode revisions (if there are any in history or currently released) and prevents from releasing devmode snaps to stable and candidate.
- ./run or http://snapcraft.io-canonical-websites-pr-1195.run.demo.haus/
- go to Releases page of a snap you owned
- if there are any revisions in history that are devmode they should be marked with an icon
- icon should have a tooltip
- if any devmode/devel revision is released (in edge or beta) warning icon should appear next to it, tooltip should say why the icon is there and notification should appear with links to the docs.

Release UI: detect devmode revisions

---

static/js/config/swiper.config.js
static/sass/_patterns_carousel.scss

Fixes #1200
Makes swiper work correctly with screenshots of different widths.
- go to snap details page of couple of snaps with screenshots (in different sizes)
- make sure spacing is fine regardless of screenshot width
- check it on different screen sizes

Make swiper slides adapt to screenshots widths

---

static/js/publisher/release/channelMenu.js
static/js/publisher/release/contextualMenu.js
static/js/publisher/release/promoteButton.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss
templates/publisher/account-snaps.html

Fixes #1187 
Updates visual style of releases table on Release page.
Design doc: https://docs.google.com/document/d/1DdWKGN22mppdse3jNmQe1p02ebimFO1ww94BXHD9Byg/edit?ts=5bab92e3#
- ./run or http://snapcraft.io-canonical-websites-pr-1206.run.demo.haus/
- look at the release table (it should have new look)
- select some revisions to release
- promote some channels
- close some channels
- check some snap with devmode revisions
- all should work as before with new look

Update styles of releases table

---

templates/index.html

Canonical style is to use sentence case for headings.

Correct capitalisation on front page

---

tests/blog/tests_index.py
webapp/api/blog.py

Cache all blog api calls for an hour
- `./run`
- http://0.0.0.0:8004/blog
- make sure blog still works

All blogs API cache for an hour

---

static/js/publisher/release/devmodeIcon.js

Fixes wrong channel name in devmode icon tooltip.
- ./run or http://snapcraft.io-canonical-websites-pr-1238.run.demo.haus/
- go to Releases page of any snap with devmode revisions
- hover over devmode icon on revision in the revisions list
- it should mention stable and candidate (not beta) channels

Fix restricted channels in devmode icon tooltip

---

webapp/app.py

Remove protheus client initialization from app since it's done in talisker
- in `.env` add `TALISKER_NETWORKS=172.17.0.1`
- `./run`
- http://0.0.0.0:8004/store
- http://0.0.0.0:8004/_status/metrics
- Make sure we are catching metrics

Remove prometheus client initialization

---

static/js/publisher/release/revisionsList.js
static/js/publisher/release/revisionsTable.js

Building React in `release.js` properly in development mode revealed some warning about incorrectly passed props.
This updates the PropTypes declarations to correct types.
- ./run locally in development mode
- go to Release page of any snap
- there should be no errors with React PropTypes warnings in the console

Fix PropTypes in release UI components

---

static/js/publisher/release/releasesController.js
templates/publisher/_header.html
templates/publisher/account-snaps.html
tests/publisher/snaps/tests_post_close_channel.py
tests/publisher/snaps/tests_post_release.py
tests/publisher/snaps/tests_revision.py
webapp/publisher/snaps/views.py

Rename release to releases
- `./run`
- http://localhost:8004/toto/release should redirect to http://localhost:8004/toto/releases
- http://localhost:8004/toto/release updates should still works

Rename release endpoint to releases

---

entrypoint

Use sync workers instead of gevent.
We will deploy 8 workers per pod (5)
- `./run`
- make sure we have 8 workers running
- make sure blog.ubuntu.com still accessible 
- try to play with siege for example to check the number of requests we can handle (`siege http://localhost:8023 --concurrent 10 --reps 5`)

Move from gevent to sync workers

---

static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss

Fixes #1265 
Fixes styles of release table to avoid unnecessary truncating version numbers.
- ./run or https://snapcraft-io-canonical-websites-pr-1273.run.demo.haus/
- go to releases page of any snap (with long version numbers)
- check if they are truncated properly
- go to release page of a snap where release version is shorter then revision id ([juju](https://snapcraft-io-canonical-websites-pr-1273.run.demo.haus/juju/releases))
- check if versions are displayed properly
- select some revisions to release or promote a channel - see if in different states versions are displayed properly

Fix truncating version number in releases table

---

static/js/publisher/release/releasesController.js

Fixes #1274
Fixes getting the name of tracked channel (when more then one channel has revisions)
- ./run or  https://snapcraft-io-canonical-websites-pr-1275.run.demo.haus/
- go to releases page of [juju](https://snapcraft-io-canonical-websites-pr-1275.run.demo.haus/juju/releases) (or any snap that has revisions in stable and candidate but not beta)
- check tooltips when hovering over ↑ in tracking channel
- it should show a name of correct channel

Fixes getting the name of tracked channel

---

static/js/publisher/release/releasesController.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/revisionsTable.js

Part of #1266 
As preparation to show channel history in Release UI this PR moves revisions list component rendering into release table (so later it can be rendered in between the table rows).
Also cleans up a bit of how the state data of release UI is passed into components.
- to go releases page of any snap
- everything should work as before

Refactoring release UI components

---

templates/store/categories/iot.html

Fix missing links on iot page: PC link and missing icon for ammp edge
- `./run`
- Make sure all the icon for ammp edge show up on the snap card
- Make sure snap PC is linked to snapcraft.io/pc

Fix missing links and icons iot page

---

templates/publisher/developer_programme_agreement.html

I was just signing up for a developer account and happen to be one of those users who takes a peep at the privacy policy, but the link went to 404. Looks like a typo - this appears to be the correct URL.

Fix Privacy Notice URL when signing up for developer account.

---

webapp/api/store.py

Extend search for wide architectures
- `./run`
- Search for “rigado-factory-dnsmasq” or “rigado”.
- Search for “pi2-kernel”, or “pi2, or “kernel”.
- Some snaps should show up

Extend search to wide architectures

---

tests/store/tests_details.py
webapp/api/store.py
webapp/app.py
webapp/store/views.py

Fixes #1260 
Fix error when API returns empty response on  500
Add tests to make sure it works well
- To reproduce behaviour:
- at line 80 of file `webapp/api/store.py` add this:
```python
api_error_exception = ApiResponseErrorList(
"The api returned a list of errors",
response.status_code,
[]
)
raise api_error_exception
```
- `./run`
- http://localhost:8004/toto
- Should return a `Bade Gateway` page

Fix missing attribute when no response from api

---

webapp/api/requests.py

Fixes #1233 
On error return last cached api call
- `./run`
- http://localhost:8004/toto
- Disconnect from internet
- http://localhost:8004/toto
- Page should still show (without any images)
- After 5 minutes (time for cache to expire) http://localhost:8004/toto
- Page should still be accessible

Return last cached api call on error

---

webapp/first_snap/content/python/package.yaml

We don't automatically install git in the build VM unless you set `source-type: git`, but if you use `version: git` we try to call it regardless. This works around that problem until we install git when using `version: git`. I've also updated the snapcraft-docs/offlineimap repo to match and confirmed a snap build does the right thing.
Also opportunistically fix a typo that would've prevented offlineimap from running (the path is always bin/offlineimap, regardless of whether you change the snap name and command name).

Workaround LP: #1802899

---

static/js/publisher/release.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss
tests/publisher/snaps/tests_revision.py
webapp/api/dashboard.py

Fixes #1266 
Shows release history when channel/arch cell is clicked in release UI
- ./run or https://snapcraft-io-canonical-websites-pr-1286.run.demo.haus/
- click on any channel/arch cell
- history of releases for this channel in this architecture should show in table below

Shows release history when channel/arch cell is clicked in release UI

---

tests/blog/tests_index.py
webapp/blog/views.py

This will redirect URLs of the following forms:
- `/blog/{year}/{slug}`
- `/blog/{year}/{month}/{slug}`
- `/blog/{year}/{month}/{day}/{slug}`
To the canonical form of `/blog/{slug}`.
This is to provide parity in URL support with blog.ubuntu.com, to help with #1222.
QA
--
`./run` and go to any of:
- http://0.0.0.0:8004/blog/2018/03/09/your-first-robot-the-driver-4-5
- http://0.0.0.0:8004/blog/2018/03/your-first-robot-the-driver-4-5
- http://0.0.0.0:8004/blog/2018/your-first-robot-the-driver-4-5
Check you're correctly redirected to http://0.0.0.0:8004/blog/your-first-robot-the-driver-4-5
Also, check `./run test` passes.

Redirect blog.ubuntu.com URL forms to the blog

---

static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesOverlay.js
static/js/publisher/release/revisionsTable.js
static/sass/_snapcraft_release.scss
templates/publisher/release-history.html

Part of #1267 
Moves some of the layout elements (Vanilla rows) into React components as preparation for moving release history into a full width overlay 'dropdown'.
- go to Release page of any snap
- click around
- everything should work and look as before

Update release UI layout

---

static/js/publisher/metrics/graphs/activeDevices.js

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1309
This PR offsets the hover date by -12 hours so the middle of a day is aligned with the tick.
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/metrics
- Hover over the graph around the last tick
- You should be able to see the last available date (today - 1)

Ensure the last point on the graph is accessible

---

webapp/metrics/helper.py

Also addresses forum.snapcraft.io/t/store-metrics/8434/6 and forum.snapcraft.io/t/publisher-metrics-dont-add-up/8487/1
This PR changes the metrics 'grabbing' period from -1 day and 12 hours to -1 day and 3 hours. As mentioned by @nottrobin [here](https://github.com/canonical-websites/snapcraft.io/pull/616#issuecomment-385981115).
This should enable viewing the previous days metrics a lot sooner (before midday utc)
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/metrics
- You should be able to see the last available date (today - 1)

Get metrics 1 day and 3 hours previously

---

templates/_footer.html

Fixes #1312 
1. Pull the branch / Visit the demo URL
2. Check the footer includes links to Legal information and Data privacy from ubuntu
3. Make sure it happens in every page of the site

Included links to legal information and data privacy in the footer

---

static/js/publisher/market/screenshots.js

Fixes #668
1. Pull the branch or run the demo URL
2. Open a snap from your published snaps
3. Make sure you have no screenshots on that snap
4. `Open full screen` and `delete` screenshots buttons should be disabled

Disabled full screen button on listing page when there are no screenshot

---

static/js/publisher/market/screenshots.js
templates/_footer.html
templates/home/_fsf_go.html

Forgot to land the link to the golang "first snap" flow in #1301.

Add missing link to golang first snap flow

---

tests/blog/tests_index.py
webapp/blog/logic.py
webapp/blog/views.py

@pmahnke helpfully [added a snippet](https://github.com/canonical-websites/blog.ubuntu.com/pull/416/files#diff-e8b4e4b3fe31ecb310658b8a0d0f0c8eR106) to the Ubuntu blog. Here I've copied/ pasted and modified it slightly.
- `./run`
- Click on an article
- Open the network inspector and see how small the inline images are
- Compare to the same post and network inspector on snapcraft.io/blog

Use cloudinary for blog post images

---

static/js/publisher/release/contextualMenu.js
static/js/publisher/release/releasesTable.js
static/sass/_snapcraft_release.scss

Fixes #1308
Designs: https://github.com/canonicalltd/snapcraft-design/issues/552
Done:
- improved grid/spacing of releases table
- updated contextual menu buttons for channels
- smaller cancel release button [X]
- highlights pending releases in 'yellowish' colour
- makes sure it looks nice for 6 archs (no wrapping 'Add revision')
- ./run or https://snapcraft-io-canonical-websites-pr-1328.run.demo.haus/
- check if everything looks nice
- go to releases page of snap with 6 architectures (surl)
- everything should look ok

Release UI - visual updates

---

tests/publisher/snaps/test_release_history_json.py
tests/publisher/snaps/tests_revision.py
webapp/api/dashboard.py
webapp/publisher/snaps/views.py

Adds releases history JSON endpoint
- log in to your publisher accound
- add /json to URL to get JSON response with releases history (/toto/releases/json)
- if snap has longer history it can be requested with ?page= param (/nextcloud/releases/json?page=2)

Adds releases history JSON endpoint

---

static/js/publisher/release.js
static/js/publisher/release/historyPanel.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesState.js
static/js/publisher/release/releasesTable.js
static/js/publisher/release/revisionsList.js

Fixes #1261 
Update revisions list after release to properly show channels where given revision was released.
Done:
- after a release is posted via API fresh release history is fetched to update local state
- data manipulation functions moved out from components
- find a revision that was not released to some channel yet (for example beta)
- release it to this channel
- after release is completed and releases table updated look at 'all revisions' list to see if this revision was updated (has new channel on the list)

Update revisions list after the release

---

templates/publisher/publicise.html

Fixes #1348:
- Adds `alt=` text for each button
- Removes redundant `title=` text for each button
- Makes the markup consistent between the code we provide and the code we use ourselves.

Tweaks markup for Snap Store buttons

---

webapp/publisher/snaps/views.py

The current TW store badge's title, "中華民國國語" is actually "Mandarin
Chinese of Republic of China" which is a political minefield for both
people in PRC and Taiwan, for the following reasons:
* Most PRC people believe ROC is illegal due to one-china blablabla...
* Most Taiwanese people believe ROC is, also illegal, as it is a Chinese
government that only governs Taiwan due to historical reason with no
legal standings
To avoid the Snap Store being boycotted by both users some day in the
future (like the airline companies[1]), this patch changes the title to
the politically neutral "Chinese(Taiwan)".
Refer-to:
[1] China-Taiwan controversy for airlines is coming to a close
<https://money.cnn.com/2018/07/25/news/companies/taiwan-china-airlines/index.html>
Signed-off-by: 林博仁(Buo-ren, Lin) …

Use political neutral title for TW store badge

---

static/js/publisher/release/historyPanel.js
static/js/publisher/release/releasesState.js
static/js/publisher/release/releasesTable.js
static/js/publisher/release/revisionsList.js
static/sass/_snapcraft_release.scss

Fixes #1327 
When clicking on 'Add revision' only revisions not released previously to any channel are visible. All revisions are still accessible under 'Show latest revisions' link.
- ./run or https://snapcraft-io-canonical-websites-pr-1351.run.demo.haus/
- click 'Add revision' link on any architecture
- only unreleased revisions of given architecture should be shown on the list

Shows only unreleased revisions when 'Add revision' is clicked

---

static/js/publisher/release/historyPanel.js
static/js/publisher/release/releasesState.js
static/js/publisher/release/releasesTable.js
static/js/publisher/release/revisionsList.js
static/sass/_snapcraft_release.scss

Fixes #1326 
If there is any pending release it will show as a first highlighted row in a history panel.
- ./run or https://snapcraft-io-canonical-websites-pr-1361.run.demo.haus/
- promote a channel or `Add revision` and promote it to some channel
- click on a cell with pending revision
- pending revision should be listed in the history as a first item

Shows pending releases in history

---

static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesState.js

Fixes #1323 
Instead of showing just released architectures we include all uploaded architectures in releases table, so it's easier to find and release revisions in architectures not yet released.
- ./run or https://snapcraft-io-canonical-websites-pr-1363.run.demo.haus/
- have a snap with no released revisions ([test-snap-toto](https://snapcraft-io-canonical-websites-pr-1363.run.demo.haus/test-snap-toto/releases))
- go to Releases page
- releases table should include architectures of not released revisions, you should be able to click on 'Add revision' and select one
- go to Releases page of a snap that has some releases, but also architectures not yet released (but uploaded) ([android-studio](https://snapcraft-io-canonical-websites-pr-1363.run.demo.haus/android-studio/releases))
- all …

Show all uploaded architectures in releases table

---

static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesState.js

Fixes #1357 
Correctly handles promoting revisions into channel with already pending releases.
- ./run or  https://snapcraft-io-canonical-websites-pr-1369.run.demo.haus/
- go to Releases page of a snap (with more then 1 architecture)
- select a revision `+ Add revision` in one architecture and promote it to one channel
- select revisions in all other architectures as well
- promote 'Unreleased' revisions again to the same channel as before (overriding previously promoted revision)
- all revisions should be correctly marked for release
- there should be no errors on the console
- try selecting/promoting/canceling in different configurations

Fix promoting channel over already pending release

---

webapp/authentication.py

Replace package_upload with new package_* macaroon:
https://dashboard.snapcraft.io/docs/api/macaroon.html#request-a-macaroon
```
package_upload = package_metrics + package_update + package_register + package_release
```
- `./run`
- http://0.0.0.0:8004/
- Try modify snap, access your metrics update release and register a new snap name
- All those actions should still work on all accounts pages

Update macaroon package

---

templates/home/_fsf_python.html

This updates the copy for Python in the first snap flow to be more concise, a collaboration between @therealjuan and myself.

Make the Python pitch more concise

---

templates/home/_fsf_go.html
templates/home/_fsf_node.html
templates/home/_fsf_pre-built.html
templates/home/_fsf_python.html
templates/home/_fsf_ruby.html
webapp/first_snap/content/golang/package.yaml
webapp/first_snap/content/python/package.yaml

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1364#event-1991908187
- `./run`
- Visit http://0.0.0.0:8004/first-snap/golang/linux/package and http://0.0.0.0:8004/first-snap/python/linux/package
- Ensure any mention of the description uses '|'s instead of '>'s

Use pipes instead of chevrons for the fsf descriptions

---

templates/store/snap-details.html
tests/store/tests_public_logic.py
webapp/store/logic.py
webapp/store/views.py

1. Pull the branch or run the demo server
2. Open any snap detail page
3. Channel map actions should be `[ default_track/safest_risk_level  version_number ] [ Install ]` on every snap page
**NOTE:** Some snaps to test with `[node](https://snapcraft.io/node)` , `[skype](https://snapcraft.io/skype)`, `[blender](https://snapcraft.io/blender)`
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

Update channel map to incorporate default track + safest risk level + version

---

.babelrc
.eslintrc.js
package.json
static/js/publisher/release.js
static/js/publisher/release/historyPanel.js
static/js/publisher/release/reducers/index.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesTable.js
static/js/publisher/release/revisionsList.js
yarn.lock

First steps of moving release page state into Redux:
- adds redux and related libraries
- make babel/eslint compile object spread operator `{ ...state }` to make reducers nice
- moves revisions list data from components into Redux state
It's obviously not an ideal Redux setup currently, but it's a first step to start using it.
- install Redux devtools extension
- go Releases page
- open Redux devtools
- you should see actions initializing the data
- state should contain list of all revisions of the snap
- release some revision to a channel
- you should see "UPDATE_REVISIONS" action after successful release
- everything should work as before (try selecting stuff, promoting channels, releasing)

Release UI - introduce Redux to keep the revisions list

---

package.json
yarn.lock

Fixes #1330
Fixes #1249 
Removes prettier/black autoformatting in pre-commit hook. Instead just runs the linters and fails to commit if errors are found.
This should fix #1330 and #1249 
- checkout feature branch
- make sure your yarn dependencies are updated
- make some changes to python file that would fail in linting
- try to commit them (should fail)
- make some changes to JS file that would fail in linting
- try to commit them (should fail)
- make some changes to SCSS file that would fail in linting
- try to commit them (should fail)
- if there are no linting errors commit should pass
- commit and pre-commit hook should work as expected when directory has a space in the name

Remove auto-formatting in pre-commit hook, only lint to fail on error

---

.circleci/config.yml
static/js/publisher/release/actions/revisions.js
static/js/publisher/release/actions/revisions.test.js
static/js/publisher/release/reducers/index.js
static/js/publisher/release/reducers/revisions.js
static/js/publisher/release/reducers/revisions.test.js
static/js/publisher/release/releasesController.js

As part of release UI redux migration (#1384):
- extracts actions to separate module
- adds tests for actions and reducers
- go to Releases page, everything should work as before
- ./run exec yarn test-js
- tests should run for revisions reducers and actions, they should pass
Coverage report should now include JS.
Click on [Continue to review full report at Codecov](https://codecov.io/gh/canonical-websites/snapcraft.io/pull/1386?src=pr&el=continue) to see full report including separate python and js score:

Extract actions to separate module, add tests

---

webapp/api/blog.py

Make blog editable thanks to environment var
- `./run`
- http://127.0.0.1:8004/blog
- Edit `.env` and add line: `BLOG_API=https://httpbin.org/status/504`
- `./run`
- http://127.0.0.1:8004/blog
- Should have a `Gateway Timeout`
- Edit `.env` and modify line: `BLOG_API=https://admin.insights.ubuntu.com/wp-json/wp/v2`
- `./run`
- http://127.0.0.1:8004/blog

Make blog api url available through env var

---

templates/first-snap/package.html
templates/home/_fsf_c.html
templates/home/_fsf_go.html
templates/home/_fsf_node.html
templates/home/_fsf_pre-built.html
templates/home/_fsf_python.html
templates/home/_fsf_ruby.html
webapp/first_snap/content/golang/package.yaml
webapp/first_snap/content/python/package.yaml

Use the `base` keyword in the snapcraft.yaml files in the first snap flow. The use of bases makes snapcraft use a tightly controlled build environment inside multipass to create the snap, _much_ more reliable than relying on whatever is in the developer's host system.
/cc @sergiusens

Use bases in the first snap flow

---

package.json
static/js/publisher/release.js
static/js/publisher/release/actions/history.js
static/js/publisher/release/actions/history.test.js
static/js/publisher/release/actions/releases.js
static/js/publisher/release/actions/releases.test.js
static/js/publisher/release/historyPanel.js
static/js/publisher/release/reducers/history.js
static/js/publisher/release/reducers/history.test.js
static/js/publisher/release/reducers/index.js
static/js/publisher/release/reducers/releases.js
static/js/publisher/release/reducers/releases.test.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesState.js
static/js/publisher/release/releasesTable.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js
yarn.lock

Continuing redux migration of ReleasesList component:
- moves state of history panel into redux reducers/actions
- moves filtering of history into a selector
- adds tests for all functions
- ./run or https://snapcraft-io-canonical-websites-pr-1393.run.demo.haus/
- open Redux dev tools
- click around the table, show history of different channels
- opening/closing of panel should show up as actions in redux dev tools
- all release UI functionality should work as before

Release UI redux:  history

---

static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/releasesTable.js
static/sass/_snapcraft_release.scss

Fixes #1395 
Fixes #1396 
Swaps places of revision and version in releases table.
Improves the tooltips positioning and text (should show for whole table cell including padding, should always show when there is a revision released, etc).
Did also a bit of refactoring (extracting table cell rendering to separate component and splitting it into more manageable chunks). That's why the diff is significantly bigger then the bugs it fixes suggest.
Changes relevant to bugfixes are in commits: https://github.com/canonical-websites/snapcraft.io/commit/6742b3d10490b1e9f6df8549febf6fc0e2c2f185 https://github.com/canonical-websites/snapcraft.io/commit/42f16711b6d0a261e22f5b74fda9c37d68393aa7
- in releases table revision number should be on top with …

Revision vs version

---

static/js/publisher/release/revisionsList.js

Fixes #1399
Updates history panel heading to emphasise architecture and channel names.
- ./run or https://snapcraft-io-canonical-websites-pr-1413.run.demo.haus/
- go to Releases page of any snap with some released revisions
- click on any released version to open releases history
- Heading should say: "Releases history for [architecture] in [channel]" with architecture and channel names in bold

Update history panel heading to emphasise architecture and channel names

---

static/js/publisher/release/actions/pendingReleases.js
static/js/publisher/release/actions/pendingReleases.test.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/historyPanel.js
static/js/publisher/release/reducers/index.js
static/js/publisher/release/reducers/pendingReleases.js
static/js/publisher/release/reducers/pendingReleases.test.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesState.js
static/js/publisher/release/releasesTable.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js

Fixes #1409 
Makes sure canceling pending revisions is properly propagated to revision history component.
Moves `pendingReleases` data from component state into Redux as part of #1384
- promote some revisions or a channel
- click on a cell with pending release (yellow background)
- pending release should appear on top of history of given channel-architecture
- click X in the cell to cancel this release
- promoted release should disappear from the cell and from the top of history
- make sure other functions around releasing work as expected

Fix issue with canceling pending release

---

static/js/publisher/release/releasesTable.js
static/sass/_snapcraft_release.scss

Fixes #1397 
Highlights currently open channel and architecture in releases table
- ./run or https://snapcraft-io-canonical-websites-pr-1414.run.demo.haus/
- click on released version to open release history
- currently open channel name and arch should be highlighted (in bold)

Highlight current channel and arch in releases table

---

tests/tests_badge_counter.py
webapp/handlers.py

Fixes #1394 
Add counter for the number of requests on badges for logged in users and not logged in users
If the requester has a session I don't increment the counter, increment the logged in counter
This will allow us to know how many users request the badge from snapcraft (logged in) and from outside (readme ...)
- `vim .env`
- add line `TALISKER_NETWORKS=172.17.0.1`
- `./run`
- http://0.0.0.0:8004/_status/metrics
- Should have a line: `badge_counter 0.0`
- Should have a line: `badge_logged_in_counter 0.0`
- In a private tab
- http://127.0.0.1:8004/static/images/badges/en/snap-store-black.svg
- GOTO http://0.0.0.0:8004/_status/metrics
- Should have a line: `badge_counter 1.0`
- Should have a line: `badge_logged_in_counter 0.0`
- http://127.0.0.1:8004/toto/publicise
- Should have a line: …

Add counter for the number of requests on badge

---

tests/store/tests_get_store_view.py
webapp/store/views.py

- we use to diplay feature snaps to the store page when no snap was found, not anymore. So removed the api call to get feature snaps
- Pass feature snaps to be able to diplay faster snaps on the store page  instead of having a long list of loaders
- `./run`
- http://127.0.0.1:8004/store
- Should still work
- http://127.0.0.1:8004/search?category=&q=asdfasdfasdf
- Page should still work as usual

Pass feature snaps to store view

---

tests/login/tests_login_handler.py
tests/publisher/tests_publisher.py

Fixes #1144
- Make tests work offline
- One test was hitting the /acl api. This PRs mocks the response with a fake macaroon for tests
- Go offline
- `./run test`
- Every test should pass!

Make tests work offline

---

static/js/publisher/release/actions/history.test.js
static/js/publisher/release/actions/pendingCloses.js
static/js/publisher/release/actions/pendingCloses.test.js
static/js/publisher/release/actions/pendingReleases.js
static/js/publisher/release/actions/pendingReleases.test.js
static/js/publisher/release/components/releasesConfirm.js
static/js/publisher/release/components/releasesHeading.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/reducers/index.js
static/js/publisher/release/reducers/pendingCloses.js
static/js/publisher/release/reducers/pendingCloses.test.js
static/js/publisher/release/reducers/pendingReleases.js
static/js/publisher/release/reducers/pendingReleases.test.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesTable.js
static/sass/_snapcraft_release.scss

Fixes #1398 
Fixes #1424 
- Removes (?) icon from release confirmation. Shows tooltips when hover over releases/closes count.
- Fixes the issue when promoting into channel pending close (#1424)
- Moves closed channels state into Redux
- promote some channel, close some channel
- There should be no (?) icon in confirmation box, hovering over 'X releases' or 'X closes' should show tooltips with details
- Try to reproduce issue #1424 (promote something into channel that is pending close) - it shouldn't be possible anymore

Updates to releases confirmation

---

static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/devmodeIcon.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/revisionsList.js
static/sass/_snapcraft_release.scss

Fixes #1420 
Changes icon of devmode revisions and moves notification into history panel.
- ./run or https://snapcraft-io-canonical-websites-pr-1431.run.demo.haus/
- go to Releases page of a snap with devmode revisions
- devmode icon should be "info" [i] instead of warning
- open history panel of some channel - if any of the revisions in history is in devmode notification should appear with more information about devmode
- if any revision in history panel is not in devmode no warning should be shown

Update styling of devmode not to look like warning

---

templates/first-snap/build.html
templates/first-snap/install-snapcraft.html
templates/first-snap/test.html
webapp/first_snap/content/golang/build.yaml
webapp/first_snap/content/golang/test.yaml
webapp/first_snap/content/python/build.yaml
webapp/first_snap/content/python/test.yaml
webapp/first_snap/views.py

Snapcraft is now working on MacOS without any fiddling, so let's re-enable the MacOS flow. I've fixed a few things along the way and cleaned up the text.

Bring back the MacOS instructions, now that snapcraft 3.0.1 is out

---

templates/home/_fsf_go.html

Following #1366, this moves Golang pitch closer to what we wrote for Python. Unlike Python, app isolation is not a problem in Go. Also less relevant is dealing with native libraries (from my limited experience, someone please correct me). So I've focused the Go pitch on discovery and updates.

Refine the golang pitch

---

static/js/public/public.js
static/js/public/snap-details/videos.js
static/js/publisher/state.js
static/sass/_patterns_carousel.scss
templates/publisher/listing.html
templates/store/snap-details.html
tests/publisher/snaps/tests_listing.py
tests/store/tests_public_logic.py
webapp/publisher/snaps/logic.py
webapp/publisher/snaps/views.py
webapp/store/logic.py
webapp/store/views.py

Fixes https://github.com/canonicalltd/snap-squad/issues/785
- Added a Video field
- Ensured API errors are displayed above the field
- Added temporary youtube output to snap details page for testing
- `./run`
- Visit http://0.0.0.0:8004/:snap_name:/listing
- Add a video URL in the correct format
- Save
- Should succeed
- Visit http://0.0.0.0:8004/:snap_name:/listing
- Add a random string to the video field
- Save
- Should error with a message about formatting
- Visit http://0.0.0.0:8004/:snap_name:/listing
- Add a valid youtube url
- Save
- Visit http://0.0.0.0:8004/:snap_name:
- The first item in the carousel should be the video

Add video field to listing page

---

static/js/public/snap-details/screenshots.js

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1343
Added a hack as described [here](https://github.com/nolimits4web/swiper/issues/2218#issuecomment-388837042), to fix a [reported Swiper issue](https://github.com/nolimits4web/swiper/issues/2218) in Firefox
- `./run`
- Visit http://0.0.0.0:8004/blender
- Hard refresh the page multiple times
- Each time the navigation should appear either immediately or not-noticably delayed.

Missing screenshots navigation

---

templates/publisher/settings.html

2. Log in to your developer account
3. Visit a published snap
4. Collaboration should sit within `Settings` and link to dashboard

Included link to dashboard collaboration section in published snaps

---

static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/reducers/history.js
static/js/publisher/release/reducers/history.test.js
static/js/publisher/release/releasesTable.js
static/sass/_snapcraft_release.scss

Fixes #1457
Updates the styles of releases table:
- changes highlight colour to be more distinct
- fades out inactive cells (when history panel is open)
- no border on hover
- removes -> arrow from pending releases
- closes history panel when channel is promoted or closed
- ./run or https://snapcraft-io-canonical-websites-pr-1470.run.demo.haus/
- select some revisions (cells should be highlighted in yellowish tone)
- open history panel of some cell
- promote some channel - history panel should be closed
- there should be no arrows in pending revisions
- click around, promote, close, etc - everything should work

Update highlight styles of releases table

---

static/js/public/store-categories.js

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1466
We don't need to report these failures to sentry as most of the time it's because someone navigates from the page before all categories have fetched and if a category doesn't load it's not a "failure" as such.
Also any genuine status codes will be shown in Grafana.
I've also added es-lint overrides for these as it's important for debugging for users.

Remove failed fetch throw for store

---

templates/_footer.html

Canonical has changed the brand name of its Kubernetes distribution to the "Charmed Distribution of Kubernetes". See https://www.ubuntu.com/kubernetes/features

Update to new name of CDK

---

tests/publisher/snaps/tests_listing.py
tests/publisher/snaps/tests_post_listing.py
webapp/api/store.py
webapp/publisher/snaps/logic.py
webapp/publisher/snaps/views.py

- Add categories to listing page
- Add possibility to push category to metadata
- Add parameter to `StoreApi` `cache=Bool` too allow to cache or not the calls
- Listing page gets its own instance of StoreApi not cached to get list of categories
- `./run`
- In template `listing.html` add line:
```
{{ categories }}
{{ snap_categories }}
```
- http://0.0.0.0:8004/toto/listing
- Make sure it has the right categories and that the template gets the list of categories
- Try with different snaps
- Try to modify a snap with an error (description with zero width space: https://unicode-table.com/en/200B/ ) 
- When the listing page reloads you should get the same (categories and snap category)

Add served categories

---

requirements.txt
templates/store/snap-details.html
tests/tests_markdown_parser.py
webapp/markdown.py
webapp/store/logic.py
webapp/store/views.py

Fixes #1388 
Fixes https://github.com/canonicalltd/snap-squad/issues/776
Support markdown displaying in description page
Needs to be done:
- `./run`
- http://127.0.0.1:8004/toto
- check if markdown is well displayed in html
- try to modify the desciption of one of your snap and check if you have the markdown well displayed
make sure that only this list of markown elements works:
* Code (text blocks inside ` or ``` pairs)
* Lists (* Foo)
* Italics (_foo_)
* Bold (**foo**)
* Paragraph merging (consecutive lines are joined)
* Literal URLs auto-link https://foo.bar
* URLs with title [title for the link](https://foo.bar)
For each thing that is allowed (or not) please let me know I'll add it in the test suite

Support markdown for description

---

static/js/publisher/form.js
static/js/publisher/form.test.js
static/js/publisher/market/categories.js
static/js/publisher/market/categories.test.js
static/js/publisher/publisher.js
static/js/publisher/state.js
static/js/publisher/state.test.js
templates/publisher/listing.html
tests/publisher/snaps/tests_listing.py
tests/publisher/snaps/tests_post_listing.py
webapp/publisher/snaps/logic.py
webapp/publisher/snaps/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1458
- Added select boxes and interaction as described in https://docs.google.com/document/d/1Teovi34AVAkHtFdO9agsILqS96QVmaDqZ9DMKyFs48U/edit
- Updated the backend to transform the snap categories to avoid reserved jinja2 key
- `./run`
- Visit http://0.0.0.0:8004/snaps
- Select a snap
- You should see a new `Category:` section
- Play around with the categories, adding categories and secondary categories
- You should not be able to select the same category for both the primary and secondary categories
- When you're happy click "Save"
- Visit http://0.0.0.0:8004/search?category=<category_name> for the category(s) you selected
- If you go to the last page you should see your snap (may require patience and …

Self-serve categories

---

templates/publisher/publicise.html

On snapcraft.io we use British English spelling. (I don’t think this is a good idea, but it’s what we do.)
Fixes #1321.
1. Go to [your snaps page](https://snapcraft-io-canonical-websites-pr-1390.run.demo.haus/snaps).
2. Choose a snap.
3. Choose “Publicise”.
4. Scroll to the bottom of the page.
5. See that “license” is now spelled the British way.

“license” > “licence”

---

static/js/publisher/release/components/contextualMenu.js
static/js/publisher/release/components/promoteMenu.js

Vanilla tooltip doesn't work well with contextual menu, so we at least add browser `title` tooltip to make button more clear.
- ./run or https://snapcraft-io-canonical-websites-pr-1487.run.demo.haus/
- hover over promote button [⤴]
- browser tooltip with a title should appear

Add browser tooltip to promote button

---

static/js/publisher/release/components/contextualMenu.js

Vanilla contextual menu is not clickable in Firefox if its configured on 
a button, so we change it back to span.
- go to Releases page in Firefox
- click on contextual menus (available revisions select, promote button, channel menu with close channel)
- make sure menus are clickable, react to hover, etc

Make contextual menus work in Firefox

---

static/js/config/swiper.config.js
static/js/libs/iframeSize.js
static/js/public/snap-details/screenshots.js
static/js/public/snap-details/videos.js
static/js/publisher/market/lightbox.js
static/js/publisher/market/lightbox.test.js
static/sass/_patterns_carousel.scss
static/sass/_snapcraft_details_heading.scss
templates/partials/_snap-screenshot.html
templates/partials/_video.html
templates/partials/blog-card--minimal.html
templates/publisher/listing.html
templates/store/snap-details.html
tests/store/tests_public_logic.py
webapp/store/logic.py

Fixes https://github.com/canonicalltd/snap-squad/issues/786
Fixes https://github.com/canonicalltd/snap-squad/issues/787
and implements https://github.com/canonical-websites/snapcraft.io/pull/1461
- `./run`
- Add an appropriate video to a public snap
- Visit the public snap page
- See the video
- Try with youtube, vimeo and asciinema
- Make sure that the videos are OK with and without screenshots
- Make sure the lightbox works when navigating to the video from another screenshot*
- Remove the video text to ensure the video is removed
- /lukewh-test, /test-lukewh and /test-lukewh-2 all have examples
*I've not hacked a way to open the lightbox by clicking on the videos as this seemed like it was overriding default behaviour.

Autoplay video on details pages

---

static/js/publisher/release/actions/availableRevisionsSelect.js
static/js/publisher/release/actions/availableRevisionsSelect.test.js
static/js/publisher/release/actions/channelMap.js
static/js/publisher/release/actions/channelMap.test.js
static/js/publisher/release/components/availableRevisionsMenu.js
static/js/publisher/release/components/promoteMenu.js
static/js/publisher/release/reducers/channelMap.js
static/js/publisher/release/reducers/channelMap.test.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesState.js
static/js/publisher/release/releasesTable.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js

Part of #1473
Autoselects latest revisions when available revisions dropdown value is changed
- run or demo
- 'Recent' available revisions should be selected by default (if there are any)
- if there are any recent revisions they will be selected by default (show in the table as 'orange')
- Recent option should select revisions only from one most recent version (not from all architectures)
- If there are no revisions in Recent or Unreleased these options should be disabled
- change Recent to 'Unreleased' or 'All'
- selected revisions should be updated based on the choice (note that for Recent and Unrelased selection will be the same, because Recent is subset of Unreleased)
Couple test snaps:
- snap with some recent revisions (not in all architectures): …

Autoselect available revisions

---

templates/store/snap-details.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1494
This was causing some metrics and the footer to be omitted from the page.
- `./run`
- Visit https://snapcraft.io/core
- Open http://0.0.0.0:8004/core in another tab
- Make sure the footer and metrics are displayed on the local version

Close unclosed tag on details page

---

static/js/publisher/release/components/availableRevisionsMenu.js
static/js/publisher/release/components/contextualMenu.js
static/js/publisher/release/components/promoteMenu.js
static/sass/_snapcraft_release.scss

Fixes #1473
Adds descriptions to "Available revisions" dropdown menu
- ./run or https://snapcraft-io-canonical-websites-pr-1497.run.demo.haus/
- go to Releases page 
- Open 'Available' menu
- descriptions should be visible

Show descriptions in available revisions menu dropdown

---

static/js/publisher/release/releasesTable.js
static/sass/_snapcraft_release.scss

Fixes #1486
- ./run on https://snapcraft-io-canonical-websites-pr-1492.run.demo.haus
- go to Releases page
- in place of channel menu there should be a bin icon button
- clicking on a button should mark channel to be closed
- click around, promote some releases, close channel, make sure everything works

Change channel menu into close channel button

---

static/js/publisher/release/actions/availableRevisionsSelect.js
static/js/publisher/release/components/releasesConfirm.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/revisionsList.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js
static/sass/_snapcraft_release.scss

Fixes #1472
Adds possibility to select revisions with same version as currently selected in other architectures.
- ./run or https://snapcraft-io-canonical-websites-pr-1502.run.demo.haus/
- go to releases of any snap with multiple architectures
- open panel with available revisions
- check any revision that is also available in other architectures
- box should appear with information about same version in other architectures
- click on a button to select all revisions with same version in other archs

Select revisions with same version in other archs

---

static/js/publisher/release/revisionsList.js
static/sass/_snapcraft_release.scss

Fixes #1498 
Use the same highlight style for selected revisions as for pending revisions.
Also removes now unnecessary disabled style.
- ./run or  https://snapcraft-io-canonical-websites-pr-1505.run.demo.haus/
- go to Releases page for any snap
- open a panel with available revisions
- click on any revision to select it
- it should appear with orange background

Highlight selected revisions in same colour as pending revisions

---

static/js/publisher/release/components/promoteMenu.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/releasesTable.js
static/sass/_snapcraft_release.scss

Fixes #1504
Showing bigger Promote button (with label instead of the icon)
- ./run or https://snapcraft-io-canonical-websites-pr-1506.run.demo.haus/
- go to Releases page of snap any snap
- promote button should be bigger with "Promote" label instead of the icon

Show bigger promote button

---

static/js/publisher/release/components/releasesTableCell.js

Fixes #1499 
Fixes the issue when Promote dropdown was not closed when clicking on releases table cell.
- click on a Promote button to open dropdown
- click on any release table cell (to open history panel for given channel/arch)
- Promote dropdown should close when history panel is opened

Properly propagate click event from table cell (to close dropdowns)

---

static/js/publisher/release/releasesController.js

Fixes #1171
When the HTML error is returned by API instead of the JSON we now show a more user friendly error message (not exposing internal JSON parsing error).
To properly QA it you need to run it locally and mock an error from API.
To do this for example throw `raise Exception('Test error')` into `publisher/snaps/view.py#post_release` (line ~587).
- ./run
- select some revisions to promote to some channel
- click 'Apply' button to save the changes
- if error response was properly mocked error thought be thrown by server and an error massage should appear

Better messaging for JSON parse errors

---

static/js/publisher/release/revisionsList.js

Fixes an issue where same version selector was shown in history panel of channels, when it should be only visible with available revisions.
Reported by @therealjuan via IRC:
Diff looks bigger because of indent whitespace changes. Review with 'hide whitespace' setting to reveal true diff:
- go to Release page of any snap with multiple architectures
- open available revisions and select some revision (where same version is available in other architectures)
- a box should appear telling that same version is available in other architectures
- open history panel of some channel (beta, etc) of the same architecture
- a box about same version should not be visible there

Only show revision version selector in available revisions panel

---

static/js/publisher/release/components/promoteMenu.js
static/js/publisher/release/releasesTable.js
static/sass/_snapcraft_release.scss

Fixes #1342 
Adds tooltip to disabled promote menu items and to promote menu button itself when it's disabled (when all items are disabled).
- ./run or https://snapcraft-io-canonical-websites-pr-1509.run.demo.haus/
- go to Releases page of any snap (with some devmode revisions)
- select any devmode revision, try to promote it
- hover over disabled channel name in Promote menu
- tooltip should appear saying that devmode revisions can't be released to stable or candidate
- if channel has the same revisions as other channel it will be disabled in promote menu with a tooltip saying that same revisions are already promoted
- if all channels are disabled, Promote button will be disabled with a tooltip showing the reason

Disabled promote menu tooltip

---

templates/publisher/register-snap.html
tests/publisher/tests_register_name.py
webapp/publisher/snaps/logic.py
webapp/publisher/snaps/views.py

Fixes https://github.com/canonicalltd/snap-squad/issues/840
Fixes https://github.com/canonicalltd/snap-squad/issues/841
Fixes https://github.com/canonicalltd/snap-squad/issues/842
- `./run`
- Visit http://0.0.0.0:8004/register-snap
- If you don't have access to any stores, you should see the original page
- If you do have stores, you should see a dropdown that contains the available store, including the Global store

Show available stores on snap registration page

---

templates/index.html

1. Pull the branch or open up the demo url
2. Go to the homepage
3. Check there is no banner about a London event in the homepage
4. #winning

Removed London event banner from homepage

---

tests/store/tests_public_logic.py
webapp/store/logic.py

Fixes  canonical-websites/snapcraft.io#1529
New order for categories in store pages
- `./run`
- http://127.0.0.1:8004/store
- Make sure order matches this order:
```
Featured
Development
Games
Social
Productivity
Utilities
Photo & Video
Server and cloud
Security
Devices & IoT
Music & Audio
...
```

Order new categories in store page

---

requirements.txt
static/js/publisher/market/markdown.js
static/js/publisher/publisher.js
templates/publisher/listing.html
templates/store/snap-details.html
tests/tests_markdown_parser.py
webapp/markdown.py
webapp/store/logic.py
webapp/store/views.py

Add markdown support for description
- `./run`
- Edit the description with some markdown, support and unsupported
- Save your changes and visit http://0.0.0.0:8004/<snap_name>
- Ensure the markdown looks and works as expected

 Markdown support for snap description

---

static/js/public/snap-details/channelMap.js
tests/store/tests_public_logic.py
webapp/store/logic.py
webapp/store/views.py

Fixes https://github.com/CanonicalLtd/snap-squad/issues/855
Convert all dates to human readable format in store pages: 
```
Format of date to convert: 2019-01-12T16:48:41.821037+00:00
Output: Jan 12 2019
```
- `./run`
- http://127.0.0.1:8004/nextcloud
- Make sure all dates (even on the channel map popup) are in the format: Month Day Year

Convert all dates to readable format on backend

---

tests/publisher/snaps/tests_post_binary_metadata.py
webapp/publisher/snaps/logic.py

Fixes #1526 
When uploading some checks weren't done well:
- When checking for current screenshots and the screenshots that we publish, if there was a duplicate the screenshot was added 4 times -> fixed
- if bug in the frontend the user was able to publish a image more than one time -> fixed
Added tests to test those behaviours
- `./run`
- Make sure you can still upload images from listing page

Remove duplicated images uploaded

---

static/js/publisher/metrics/graphs/activeDevices.js
templates/publisher/metrics.html
tests/publisher/snaps/tests_get_metrics.py
webapp/metrics/helper.py
webapp/publisher/snaps/logic.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1359
Added "Past year" and "Past 2 years" options.
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/metrics
- Change the dropdown to Past year or Past 2 years

Enable 12m and 24m metrics

---

templates/store/snap-details.html

Fixes #1453
Moves snap details edit link into a notification
- ./run or https://snapcraft-io-canonical-websites-pr-1540.run.demo.haus/
- sign in and go to snap details page of snap you published
- notification should be visible with link to edit listing page

Move snap listing edit link to notification

---

templates/publisher/settings.html

Fixes #1576 
2. Log in as a publisher in one of your published snaps
3. Go to the published snap settings page
4. Scroll down (you might want to resize the window to test)
5. Check the action bar is sticky and has a drop shadow style
6. #winning

Settings page uses old fixed heading style

---

static/js/libs/channels.js
static/js/libs/channels.test.js
static/js/publisher/metrics/graphs/activeDevices.js
static/js/publisher/metrics/metrics.js
static/sass/_snapcraft_metrics.scss
templates/publisher/metrics.html
webapp/helpers.py
webapp/publisher/snaps/views.py
webapp/store/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1475
It also updates a few things.
- Added a channels module for sorting arbitrary channel strings (will update the channel map to use this at some point).
- Added "defaultTrack" to metrics page (currently hardcoded for [node](https://snapcraft.io/node)
- Moved the hardcoded logic for node to the helpers module.
- Made the tooltip appear above the site navigation
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/metrics?active-devices=channel
- Hover over the graph and move about - the order of channels should only change if there's no data for that channel on that day.

Order channels by track/risk/branch

---

static/js/public/public.js
static/js/public/snap-details/reportSnap.js
static/sass/_patterns_modal.scss
static/sass/styles.scss
templates/store/snap-details.html

Fixes #1556
Adds a modal dialog to report snap on snap details page.
Data is posted to Google Form.
- ./run or https://snapcraft-io-canonical-websites-pr-1568.run.demo.haus/
- go to snap details page of any suspicious snap
- scroll to the bottom of the page, click on 'Report this app' link
- fill the details in the form, Submit
- success message should be shown
- data should be added to [Report snap Google Sheet](https://docs.google.com/spreadsheets/d/1ju2IKRiMsVK17b6Fmtj335sj3xaawXcN4hYGZvxwR6s/edit)

Report snap modal

---

webapp/blog/logic.py
webapp/store/views.py

Since the upgrade of `pycodestyle` to version 2.5.0 flake8 linter has become more strict on certain invalid characters for example: `\g`
> \g is in fact an invalid escape sequence.  In python3.8+ it will be a syntax error (you can enable it earlier by escalating warnings to errors)
Source: https://gitlab.com/pycqa/flake8/issues/474
- Make sure when accessing blog images are still pulled from cloudinary
- Make sure that on /blog/feed the links are snapcraft link (localhost on local machine)
- Make sure linter passes
love

Fix linter with latest version on flake8

---

webapp/publisher/snaps/views.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1528
- Pull branch
- `./run`
- The dropdown of categories should be sorted alphabetically

Sort categories for listing page

---

templates/home/_fsf_java.html
webapp/first_snap/content/java/build.yaml
webapp/first_snap/content/java/package.yaml
webapp/first_snap/content/java/test.yaml

Added Java FSF using the existing template. I did not edit the snapcraft.yaml content or make any changes to the language-common sections.
- DEMO: https://snapcraft-io-canonical-websites-pr-1558.run.demo.haus/
- open Java section of first snap flow on home page
- go through the steps

First snap flow for java

---

templates/first-snap/package.html

We've moved the snapcraft.yaml files to the root of the repos. This message was never right, anyway. You don't begin a snapcraft.yaml, you open the existing one.

Correct a typo: the snapcraft.yaml is in the project root

---

templates/brand-store/search.html
templates/brand-store/store.html
templates/publisher/account-snaps.html
templates/publisher/listing.html
templates/store/_category-partial.html
templates/store/categories/iot.html
templates/store/search.html
templates/store/snap-details.html

Fixes #710
Changes default snap icon into empty circle not to include snapcraft logo.
- go to snap details page of any snap with default icon
- instead of snapcraft logo empty circle should be shown
- find snaps with default icons in search, store page, etc - everywhere default icon should be an empty circle

Remove snapcraft logo from empty default icon

---

templates/store/snap-details.html
tests/store/tests_details.py
webapp/api/store.py
webapp/store/logic.py
webapp/store/views.py

Fixes #1496 
Adds links to categories to snap details pages (under snap name)
- go to any snap with category (for example via Store page)
- list of categories of this snap should be linked under snap name
- go to publisher listing page of any snap you own
- add it to two categories, Save
- see if both categories show on snap details page
- remember to remove any testing categories from test snaps!

Add list of categories to snap details page

---

webapp/blog/logic.py

Remove useless slash in blog logic
- `./run`
- http://0.0.0.0:8004/blog/feed
- Make sure all links are snapcraft links

Remove useless useless slash

---

static/js/base/ga.js

If `base.js` is included on a page that doesn't include GA script it fails with an error that `dataLayer` is undefined.
This PR fixes that making sure `dataLayer` is ignored if not defined.

Ignore GA script if dataLayer is undefined

---

static/sass/styles-embedded.scss
templates/_layout-embedded.html
templates/store/snap-embedded-card.html
tests/store/tests_embedded_card.py
webapp/store/views.py

Fixes #1599 
Adds new endpoint (`/[snap-name]/embedded`) that shows embeddable card with snap details.
Currently only displays snap name for test.
- ./run or https://snapcraft-io-canonical-websites-pr-1613.run.demo.haus/
- go to /[snap-name]/embedded (https://snapcraft-io-canonical-websites-pr-1613.run.demo.haus/toto/embedded)
- basic template should appear with snap name
- it should 404 normally for non existent or private snaps

Basic snap embedded card endpoint

---

static/sass/styles-embedded.scss
templates/_layout-embedded.html
templates/store/snap-embedded-card.html

Fixes #1600 
Adds more data to basic embedded card template.
Not it should contain icon, store button, latest release info.
- ./run or https://snapcraft-io-canonical-websites-pr-1618.run.demo.haus/
- go to `/[snap-name]/embedded` of any public snap (https://snapcraft-io-canonical-websites-pr-1618.run.demo.haus/vlc/embedded)
- simple embedded card content should appear for given snap

Add simple snap embedded card template

---

static/sass/styles.scss
templates/store/_snap-header-information.html
templates/store/snap-details.html

Fixes https://github.com/canonicalltd/snap-squad/issues/905
- `./run`
- Visit http://0.0.0.0:8004/senor-limon or https://snapcraft-io-canonical-websites-pr-1620.run.demo.haus/senor-limon
- Resize the browser and ensure the categories don't wrap

Ensure categories wrap on mobile

---

templates/store/snap-details.html

Fixes https://github.com/CanonicalLtd/snap-squad/issues/909
1. Pull the branch or run the demo service (if available)
2. Visit the public detail page of any snap you own
3. Check there is a notification and says `Ensure you snap stays always relevant...`
4. #winning

Updated copy on notification displead on detail page of a snap you own

---

templates/store/snap-details.html

Fixes #1625 
2. Open a snap that only displays map distribution but not OS distribution metrics i.e. [snap-store-proxy](https://snapcraft.io/snap-store-proxy)
3. Check the map is full width
4. Open another snap displaying world and OS distribution metrics i.e. [skype](https://snapcraft.io/skype)
4. #winning

Fixed layout when a snap shows only world distribution metrics

---

static/js/publisher/publicise.js
static/js/publisher/publisher.js
templates/publisher/publicise/embedded_cards.html
templates/publisher/publicise/store_buttons.html
templates/store/snap-embedded-card.html
tests/store/tests_embedded_card.py
webapp/store/snap_details_views.py

Fixes #1602 
Add snap store button settings to publicise embedded card page.
- ./run or https://snapcraft-io-canonical-websites-pr-1626.run.demo.haus/
- go to publicise page of any snap, choose embeddable card
- there should be a radio button to choose a button style
- choose different button style
- see preview frame update
- see the HTML code update

Embedded snap store button settings

---

package.json
static/js/modules/README.md

Removes unnecessary static/js/modules directory that is just a build artifact
Make sure build works regardless of static/js/modules folder existence:
- ./run build
- ./run clean
- ./run build
- ./run build

Remove unnecessary js modules directory

---

templates/_layout-brandstore.html
templates/_layout-embedded.html
templates/_layout.html

`<link rel="preconnect">` informs the browser that your page intends to establish a connection to another origin, and that you’d like the process to start as soon as possible. 
https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect
- Run site locally
- Run performance audit from Chrome dev tools
- The following warning (4) should not be present in the subsequent report:

Add preconnect to GA, Marketo, Assets Server

---

package.json
yarn.lock

Fixes #1646
Removes cssnano and related dependencies
- pull the branch
- ./run clean
- ./run serve
- make sure build works correctly and cssnano is removed

Remove cssnano dependency

---

static/js/publisher/publicise.js
static/sass/_snapcraft_banner.scss
static/sass/styles-embedded.scss
templates/_layout-embedded.html
templates/publisher/publicise/embedded_cards.html
templates/store/snap-embedded-card.html
tests/store/tests_embedded_card.py
webapp/store/snap_details_views.py

Fixes #1604
Adds optional summary to embedded card
- ./run or https://snapcraft-io-canonical-websites-pr-1653.run.demo.haus/
- go to Publicize page of any snap, Embeddable card section
- "Show summary" option should be available to select
- Select "Show summary", summary should appear in the iframe (embedded code should update respectively)
- Check if summary works with and without the button

Summary option for publicise embeddable card

---

templates/publisher/register-name-dispute-success.html
templates/publisher/register-name-dispute.html
templates/publisher/register-snap.html
tests/publisher/tests_register_name_dispute.py
webapp/api/dashboard.py
webapp/publisher/snaps/views.py

Adds a flow to register name disputes.
- **Set your environment to use the staging APIs**
- **Set your environment to use the staging APIs**
- **Set your environment to use the staging APIs**
- **Are you using the staging APIs?**
- **DO YOU EVEN STAGING APIS?**
- Then go to `/register-snap`
- Try to register a snap name that is already registered. 
- You should then see a message telling you name is already registered and giving you a link to `file a dispute`. Click the link.
- Try and submit the dispute without a message and verify you get an error for a required field.
- Add a message and submit, make sure you land in a success page.
- Navigate to `/register-name-dispute?snap-name=<snap_you_already_own>`
- Try and submit a dispute and see you get an error message saying you already own …

Add name dispute screens

---

static/js/publisher/publicise.js
static/sass/styles-embedded.scss
templates/publisher/publicise/embedded_cards.html
templates/store/snap-embedded-card.html
tests/publisher/snaps/tests_publicise_cards.py
webapp/publisher/snaps/views.py
webapp/store/snap_details_views.py

Fixes #1605 
Adds screenshot to embeddable card.
- ./run or https://snapcraft-io-canonical-websites-pr-1657.run.demo.haus/
- go to Publicise page of any snap (with a screenshot), Embeddable card section
- 'Show screenshot' option should be available
- Click on it, screenshot should appear in preview, height of frame should adapt, code should adapt to show screenshot
- Copy the code (change "snapcraft.io" in URL to demo URL: https://snapcraft-io-canonical-websites-pr-1657.run.demo.haus/) , try if it creates proper card
- go to Publicise page of any snap (without a screenshot), Embeddable card section
- 'Show screenshot' checkbox should be disabled

Embedded screenshot

---

static/js/publisher/publicise.js
templates/publisher/publicise/embedded_cards.html
templates/store/snap-embedded-card.html
webapp/store/snap_details_views.py

Fixes #1603
Add option to show/hide all channels in embeddable card
- ./run or https://snapcraft-io-canonical-websites-pr-1665.run.demo.haus/
- go to Publicise page of any snap
- 'Show all channels' option should be available
- All options should be checked by default
- Uncheck 'Show all channels', channel map should be removed from preview (replaced with version name)
- Try different configurations of options, make sure they work as expected

Add optional channel map to embeddable card

---

static/sass/_patterns_strip_slanted.scss
static/sass/styles.scss
templates/index.html

Fixes #1391 
- ./run or https://snapcraft-io-canonical-websites-pr-1677.run.demo.haus/
- go to store home page
- enjoy brand new slanted strip design
- compare with [design](https://user-images.githubusercontent.com/2741678/48841400-3fb61480-ed89-11e8-81ea-fae097442164.png)
- play with different screen sizes to make sure it works nice
- check in different browsers

Update home page banner to new slanted strip design

---

static/sass/styles-embedded.scss
templates/store/snap-embedded-card.html

Fixes #1667
Improves responsive layout of embedded card (makes the store badge drop to own row on small screens)
- ./run or https://snapcraft-io-canonical-websites-pr-1676.run.demo.haus/
- open embedded card of some snap (with summary and store badge): https://snapcraft-io-canonical-websites-pr-1676.run.demo.haus/skype/embedded?summary=true&button=black
- make sure store badge appears below summary on small screens
- try out different display options on Publicise page, make sure all of them look fine

Improve responsive styles for embedded card

---

static/sass/_snapcraft_dispute-list.scss
static/sass/styles.scss
templates/publisher/account-snaps.html

Fixes https://github.com/CanonicalLtd/snap-squad/issues/921
Implemented as per:
- `./run`
- Visit http://0.0.0.0:8004/snaps
- If you have disputed names, they should be displayed as red with a warning icon
- Other registered snaps (unpublished) should be shown, hovering over the row should show a link to documentation

List disputed names

---

templates/store/search.html
tests/store/tests_search.py
webapp/store/views.py

The store api doesn't send the "total" number of results when searching by publisher ID, so breaks the template.
- `./run`
- Visit http://0.0.0.0:8004/search?category=&q=publisher%3A28zEonXNoBLvIB7xneRbltOsp0Nf7DwS
- See snaps :+1:

Don't break if total not set

---

webapp/store/snap_details_views.py

Fixes #1699 
- Convert dict_keys to list ([source](https://stackoverflow.com/questions/16819222/how-to-return-dictionary-keys-as-a-list-in-python))
- `./run`
- http://127.0.0.1:8004/ubuntu-mate-pi/embedded
- http://127.0.0.1:8004/toto/embedded

Convert dict_keys to list

---

static/js/public/public.js
static/js/public/snap-details/embeddedCard.js
static/js/publisher/publicise.js
static/sass/_snapcraft_embedded_card_modal.scss
static/sass/styles.scss
templates/store/snap-details.html
templates/store/snap-details/_embedded_card_modal.html

Fixes #1678
Fixes #1679 
Adds dialog with embeddable card to snap details page.
- ./run or  https://snapcraft-io-canonical-websites-pr-1695.run.demo.haus/
- go to snap details page of any snap
- click on 'Create embeddable card' button
- modal should appear with options for embedded cards
- click on different options, see how preview adapts
- click on HTML tab to see the code
- copy the code and see it it works as expected

Add embedded card modal to snap details page

---

static/js/publisher/form.js
static/js/publisher/form.test.js
static/sass/_snapcraft_market.scss
templates/publisher/listing.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1682
- New layout (label to the left)
- Added "Change" button (rather then clicking on the image)
- Made the image slightly bigger - why not?
- Added a "Remove" button
- `./run`
- Add remove an icon, reload the page etc.
- See that it works as expected

Allow removing of snap icon

---

requirements.txt
templates/publisher/listing.html
tests/tests_markdown_parser.py
webapp/markdown.py
webapp/publisher/snaps/views.py
webapp/store/snap_details_views.py

Fixes #1675 
Fixes #1693 
Update to latest version of markdown requirements.
- Remove links `[title](url)`
- Remove triple fences handling
- Keep four space for code blocks
- `./run`
- Modify description for snap and try to hack around with fences and links
- You can see the requirements for fences [here](https://github.com/canonical-websites/snapcraft.io/issues/1693)

Update to new markdown requirements

---

templates/store/publisher-details.html

Fixes https://sentry.is.canonical.com/canonical/snapcraftio/issues/1240/
Remove  blog logic in publisher pages since not using it yet
- `./run`
- http://127.0.0.1:8004/publisher/jetbrains
- Should have no errors

Remove blog logic

---

webapp/api/dashboard.py
webapp/api/store.py

Increase timeout to 1 second to avoid the big amount of timeouts we are getting
- `./run`
- Make sure store and publisher pages are still working (shouldn't impact any page)

Increase first call timeout to 1 second

---

static/sass/_patterns_strip_slanted.scss
static/sass/_search-form.scss
static/sass/_snapcraft_store.scss
static/sass/styles.scss
templates/index.html
templates/partials/search-bar.html
templates/store/store.html

Fixes:
https://github.com/canonical-websites/snapcraft.io/issues/1718
https://github.com/canonical-websites/snapcraft.io/issues/1722
https://github.com/canonical-websites/snapcraft.io/issues/1725
2. Visit homepage and notice the P in the front-page has updated style (hint: is bigger)
3. Visit `/store` and notice there is a slanted header, removed category filtering from front-page
4. Scroll down to see a new banner promoting Snap Store snap
5. #winning

Updated content and style on /home and /store

---

templates/partials/fsf_language.html

A few of the landed FSF guides are missing links into the guide.

Add missing links to working FSF guides

---

webapp/first_snap/content/c/test.yaml
webapp/first_snap/content/golang/test.yaml
webapp/first_snap/content/java/test.yaml
webapp/first_snap/content/node/test.yaml
webapp/first_snap/content/pre-built/test.yaml
webapp/first_snap/content/python/test.yaml
webapp/first_snap/content/ros2/test.yaml
webapp/first_snap/content/ruby/test.yaml
webapp/first_snap/content/rust/test.yaml

As observed in https://github.com/canonical-websites/snapcraft.io/pull/1641/files#r262678393 we're missing `--devmode` on `snap install` for devmode snaps.

Add missing --devmode to snap install in the FSF

---

requirements.txt
tests/store/tests_github_badge.py
webapp/store/snap_details_views.py

Fixes https://github.com/canonicalltd/snap-squad/issues/939
Adds basic endpoint to serve GitHub badge SVG
- go to /[snap-name]/badge URL for any snap (https://snapcraft-io-canonical-websites-pr-1731.run.demo.haus/vscode/badge)
- snap badge should be displayed like:

Add snap GitHub badge endpoint

---

webapp/store/logic.py

This PR limit's the number of screenshots displayed on snap details pages to assist in getting https://github.com/canonical-websites/snapcraft.io/pull/1696 landed, once https://bugs.launchpad.net/software-center-agent/+bug/1821151 lands.
It also enforces a notice on the listings page staging "Some images won't be visible" when you have over 5 screenshots (legacy from dashboard.snapcraft.io).

Limit screenshots to 5 on the frontend

---

webapp/first_snap/content/c/package.yaml
webapp/first_snap/content/golang/package.yaml
webapp/first_snap/content/java/package.yaml
webapp/first_snap/content/node/package.yaml
webapp/first_snap/content/pre-built/package.yaml
webapp/first_snap/content/python/package.yaml
webapp/first_snap/content/ros2/package.yaml
webapp/first_snap/content/ruby/package.yaml
webapp/first_snap/content/rust/package.yaml

Discussion here:
https://github.com/canonical-websites/snapcraft.io/pull/1641#discussion_r267969364
This PR makes the warning about needing to change the snap name/command less redundant.

Make the second FSF name warning less redundant

---

requirements.txt

Bumping werkzeug to 0.15 is causing problems in the SSO flow. This PR temporarily pins werkzeug to 0.14.1 until we get to understand what is causing the issue in the new version.
- `./run`
- Make sure the website is functional and that you can login using SSO.

Pin Werkzeug version

---

static/js/publisher/form.js
static/js/publisher/form.test.js

Fixes #1697 
Correctly displays Revert button as disabled until there are any changes on Listing page.
This was caused by a typo in `is--disabled` class from Vanilla.
Reported also as Vanilla issue: https://github.com/vanilla-framework/vanilla-framework/issues/2236
- ./run or https://snapcraft-io-canonical-websites-pr-1738.run.demo.haus/
- go to Listing page of any snap
- Revert button should be disabled after page loads
- do some changes on the page
- Revert button should be enabled
- Revert the changes (by undoing them or clicking Revert)
- Revert should be disabled again
- try it with different fields on the (text, images, checkboxes)

Fix disabled Revert button on publisher listing page

---

templates/publisher/publicise/_publisher_publicise_layout.html
templates/publisher/publicise/github_badges.html
templates/publisher/publicise/store_buttons.html
tests/publisher/snaps/tests_publicise_badges.py
tests/store/tests_github_badge.py
webapp/publisher/snaps/views.py
webapp/store/snap_details_views.py

Fixes #1707 
Adds 'GitHub badges' section to Publicise page for publishers.
- ./run (currently demo doesn't allow to sign in)
- go to publicise page of any snap
- 'GitHub badges' should be available in side navigation
- go to that page
- Preview of badge specific for current snap should be available
- Copy HTML or Markdown and paste it to check if it works (make sure to update 'snapcraft.io' to demo URL: https://snapcraft-io-canonical-websites-pr-1732.run.demo.haus/)
- Make sure badge links to snap details page correctly
Badge markdown test:
[![Android Studio](https://snapcraft-io-canonical-websites-pr-1732.run.demo.haus/android-studio/badge.svg)](https://snapcraft.io/android-studio)

GitHub badges on publicise page

---

static/sass/_patterns_maas_modal.scss

Fixes #455
Hides inactive screenshots navigation button in fullscreen.
- ./run or https://snapcraft-io-canonical-websites-pr-1741.run.demo.haus/
- go to snap details page of any snap with multiple screenshots
- make screen small enough to screenshot 'next' button to appear
- scroll to the last screenshot (button should disappear)
- click on last screenshot to open fullscreen
- 'next' button on full screen should not be visible
- use 'prev' button to move to first screenshot
- 'prev' button should not be visible on first screenshot

Consistently hide disabled screenshot navigation buttons

---

static/sass/_patterns_strip_slanted.scss

Fixes https://github.com/canonicalltd/snap-squad/issues/946
Updates slanted strip styles to make sure background doesn't collide with content (on snap search page) on very large screens.
- ./run or https://snapcraft-io-canonical-websites-pr-1742.run.demo.haus/
- go to the [store page](https://snapcraft-io-canonical-websites-pr-1742.run.demo.haus/store)
- open it on a very large screen (2500px wide or higher)
- there should be enough spacing for search input and button to be on a green slanted background (not overflow with white)

Fix slanted background not to collide with content on huge screens

---

templates/store/store.html

Fixes https://github.com/canonicalltd/snap-squad/issues/947
Moves image to the top of the banner on mobile
- ./run or https://snapcraft-io-canonical-websites-pr-1740.run.demo.haus
- go to the store page
- open mobile view (change width of the window)
- scroll to the bottom of the page, store icon should be on the top of the banner

Move image up in Snap Store banner on mobile

---

static/sass/styles-embedded.scss
templates/store/snap-embedded-card.html

Fixes https://github.com/CanonicalLtd/snap-squad/issues/941
Makes whole embedded card clickable, so it can link to snap details page even if there is no 'Store Button' in it.
- ./run or https://snapcraft-io-canonical-websites-pr-1724.run.demo.haus/
- Sign in, go to Publicise page of any snap, choose Embeddable cards
- Whole card preview should be clickable and link to snap details page
- Turn off store button option, card should be still clickable

Make whole content of a embedded card clickable as a link to the store

---

templates/store/snap-details.html
templates/store/snap-details/_report_snap_modal.html

Fixes #1754 
Hides embeddable card section of snap details page in preview mode.
Also moves report snap modal code to partial template to keep snap details page template a bit more manageable. 
- go to snap details page of any snap
- both "Create embeddable card" and "Report snap" should work as before (modals should open)
- go to listing page of any snap
- open Preview
- there should be no "Report snap" or "Share this snap" sections in the preview, no errors should be reported in sentry

Hide embeddable card modal in preview

---

templates/store/_snap-header-information.html

A big advantage of snaps is that the author and publisher are usually the same person. In the few cases where they aren’t, it’s important that we don’t imply that the publisher is the author: it can upset the real author, and sour them on the platform.
Dropping the “by” from the store page:
- avoids this implication
- marginally simplifies the page
- is consistent with how the publisher is presented on the [App Store Preview](https://itunes.apple.com/us/app/skype-for-iphone/id304878510), [Microsoft Store](https://www.microsoft.com/en-us/p/skype/9wzdncrfj364?activetab=pivot:overviewtab), and [Google Play](https://play.google.com/store/apps/details?id=com.skype.raider&hl=en_US).

Removes “by” from publisher name

---

templates/store/snap-details.html

Fixes #950 
Fixes spacing issues around owner notification by moving it up to the top of the page.
- ./run or  https://snapcraft-io-canonical-websites-pr-1760.run.demo.haus/
- go to snap details page of snap you own
- owner notification should appear on the top
- resize the screen, spacing should be fine on all the widths

Move snap owner banner to the top of the page

---

templates/publisher/account-snaps.html

Fixes #1749 
Correctly check published status in revision not snap data.
Note: This just a quick fix that reverts back to checking status of latest revision. It works just as before the bug was introduced, but has a separate issue when latest revision is published but not released to any channel yet (reported separately in #1765).
- ./run or https://snapcraft-io-canonical-websites-pr-1764.run.demo.haus/
- Sign in to see your snaps list
- Look at 'Latest release' column, any released snap should correctly show channel name

Correctly check published status in revision not snap data

---

tests/tests_markdown_parser.py
webapp/markdown.py

Fixes #1762 
Make sure multiple code blocks on a line are working
- On a snap add the following description: 
```
`this` is `a` line `with` a `lot` of `code`
```
- make sure the snap is well displayed 
- You can also check this snap: http://localhost:8004/b2

Fix multiple code on a line

---

static/js/publisher/form.js
static/js/publisher/form.test.js
static/js/publisher/form/media.js
static/js/publisher/form/media.test.js
static/js/publisher/preview.js
static/js/publisher/state.js
static/js/publisher/state.test.js

Removes deleted screenshot from form state (instead of just changing their status).
This cleans up different parts of code and will help with reordering screenshots.
- go to listing page of any snap
- add screenshots, delete screenshots, just test screenshots from different angles
- everything should work as before

Remove deleted screenshots from state

---

package.json
static/js/publisher/form/media.js
static/js/publisher/form/mediaItem.js
static/js/publisher/form/mediaList.js
static/sass/_snapcraft_market_screenshots.scss
webapp/publisher/snaps/logic.py
yarn.lock

Fixes #1673 
Enables drag and drop to reorder screenshots on publisher listing page.
- ./run or https://snapcraft-io-canonical-websites-pr-1772.run.demo.haus/
- go to listing page of any snap with screenshots
- drag a screenshot to reorder, if you drop it in different place change should be detected (Revert and Save should be enabled)
- if you drag back to same place (old order) Revert would be disabled again
- make sure adding screenshots works (and new screenshots can be reordered)
- make sure removing screenshots work (and dnd works after removing)
- make screen smaller (so screenshots don't fit into one line), make sure reordering works

Drag and drop screenshots to reorder

---

static/js/libs/fileValidation.js
static/js/libs/fileValidation.test.js

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1777
Allows through banner and banner icons that match those names and appropriate widths and heights.

Allow banners

---

templates/publisher/listing.html

2. Visit the `/listing` page of a snap you own
3. Tap/click on Show supported markdown syntax
4. Notice the legend on italics is stating `_foo_`
5. #winning

Updated italics legend markdown

---

package.json
yarn.lock

Update node-sass to fix Circle CI failing
Errors with older version: https://circleci.com/gh/canonical-websites/snapcraft.io/10171
- ./run serve
- everything should work as before
- make sure all Circle CI builds pass on PR

Upgrade node-sass

---

static/js/public/first-snap-flow.js

Fixes #1781 
Automatically selects users operating system in first snap flow install step.
- go to first snap flow, choose language
- on OS selection page your OS should be already selected (if one of MacOS or Linux)
- on Windows nothing should get selected

Detect OS in first snap flow install step

---

templates/home/_fsf_c.html
templates/home/_fsf_electron.html
templates/home/_fsf_go.html
templates/home/_fsf_java.html
templates/home/_fsf_moos.html
templates/home/_fsf_node.html
templates/home/_fsf_pre-built.html
templates/home/_fsf_python.html
templates/home/_fsf_ros.html
templates/home/_fsf_ros2.html
templates/home/_fsf_ruby.html
templates/home/_fsf_rust.html

Fixes #1780
Moves 'Continue' button under the description of languages to make them easier to find and reach.
- ./run or https://snapcraft-io-canonical-websites-pr-1794.run.demo.haus/
- click on any language selector
- continue button should be in the description
- try different (all if you fancy) languages to check everything was updated.

Move 'Continue' button in FSF language selector

---

templates/partials/_video.html

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1763#event-2252195260
- `./run`
- Visit http://0.0.0.0:8004/<snap_with_asciinema>
- Watch the asciinema, see that it doesn't loop

Don't loop asciinema on details pages

---

templates/first-snap/_breadcrumb.html
templates/first-snap/build.html
templates/first-snap/install-snapcraft.html
templates/first-snap/language.html
templates/first-snap/package.html
templates/first-snap/push.html
templates/first-snap/test.html

Fixes #1782
Puts first snap flow breadcrumbs into Snapcraft branded strip to match new design.
Fixes the issue that breadcrumb items were not correctly greyed out on 'languages' page.
- go to first snap flow (via language selector)
- all first snap flow pages should have updated breadcrumbs styling
- breadcrumb should work as before
- go to languages selection page, all items in breadcrumb apart from first one should be greyed out

Update styling of first snap flow breadcrumbs

---

static/js/public/first-snap-flow.js
static/sass/_patterns_pagination.scss
static/sass/styles.scss
templates/first-snap/_breadcrumb.html
templates/first-snap/_layout_fsf.html
templates/first-snap/build.html
templates/first-snap/install-snapcraft.html
templates/first-snap/language.html
templates/first-snap/package.html
templates/first-snap/push.html
templates/first-snap/test.html
yarn.lock

Fixes #1783
Adds pagination links to bottom of first snap flow steps.
- ./run or https://snapcraft-io-canonical-websites-pr-1803.run.demo.haus/
- go to first snap flow
- all steps (apart from language selection) should have a pagination links on the bottom
- pagination on OS selection should link properly to chosen OS
- pagination on 'Publish' step should enable 'next' link when snap is pushed
- all pagination links between steps should work correctly (check both Mac OS and Linux paths)

First snap flow - pagination

---

templates/publisher/account-snaps.html
tests/publisher/tests_account_snaps.py
tests/publisher/tests_api_snaps.py
tests/publisher/tests_publisher_logic.py
webapp/publisher/snaps/logic.py

Fixes https://github.com/canonical-websites/snapcraft.io/issues/1765
- `./run`
- Visit http://0.0.0.0:8004/snaps
- All snaps that have a release should show a channel and version
Note: I expect the tests to fail - my local setup has borked so I couldn't get any meaningful test failure messages.

Show latest release in snap list

---

templates/first-snap/push.html

Fixes #1784
Adds screenshots of publisher pages to publish first snap flow step
- ./run or https://snapcraft-io-canonical-websites-pr-1806.run.demo.haus/
- go to the last step of first snap flow (https://snapcraft-io-canonical-websites-pr-1806.run.demo.haus/first-snap/python/linux/push)
- on top short info about benefits of having account should be visible with some screenshots

Add publisher screenshots to first snap flow publish step

---

entrypoint
requirements.txt
webapp/api/requests.py
webapp/api/store.py
webapp/app.py

- Upgrade to talisker 0.11.1
- Configure talisker metrics for each request.Session; this will allow us to get more metrics
- create `.env.local` with: `TALISKER_NETWORKS=172.17.0.1`
- `./run`
- Check that metrics for requests are there and working on `/_status/metrics`

Upgrade talisker requests

---

static/js/public/accordion.js
static/js/public/public.js
static/sass/_patterns_first-snap-flow.scss
static/sass/styles.scss
templates/first-snap/push.html

Fixes #1805
Adds accordion to hide parts of 'publish' step of first snap flow.
- while not being signed in to store, go through first snap flow to last step
- first step of accordion (asking to create account) should be open and visible
- other steps should be collapsed and disabled
- sign in
- first step should be collapsed and inaccessible
- next step should be open, last step should be accessible

Add accordion to first snap flow publish step

---

webapp/store/logic.py

Banner image and icons are showing on snap details: https://snapcraft.io/skype.
This updated the regex to match those screenshots by making the `_hash` section of the path optional.

banner regex update

---

static/sass/_snapcraft-p_grid.scss
static/sass/styles.scss
templates/brand-store/store.html
webapp/configs/limenet.py
webapp/configs/sdrsatcom.py
webapp/store/views.py

Fixes https://github.com/canonicalltd/snap-squad/issues/962
- Bumped number of snaps shown on homepage to 16
- Updated copyright notice to 2019
- Change `WEBAPP` to `limenet` in `.env`
- `./run`
- visit http://0.0.0.0:8004
- SDRangel should be shown in the list of snaps
- The copyright footer should be 2019

more snaps on brand store

---

webapp/store/snap_details_views.py

1. Pull the branch or runt the demo service
2. Visit a /publicise from a snap you own
3. Click on Github badge /publicise/badges
4. Notice the SVG include the safest risk in the default track as channel plus just the version
5. #winning

Include safest risk in default track channel on SVG badge

---

package.json
tests/publisher/tests_account_snaps.py
tests/publisher/tests_account_snaps_metrics.py
webapp/metrics/helper.py
webapp/publisher/snaps/views.py

Adds an endpoint to retrieve metrics of snaps of a certain publisher
that can be used to render graphs on the publisher snaps page
Fixes https://github.com/CanonicalLtd/snap-squad/issues/971

Add publisher snaps metrics endpoint

---

static/js/publisher/release/components/releasesHeading.js

Fixes #1411 
2. Visit snaps with different version number systems dotted, just letters, numbers...: go, node, code, nextcloud, pycharm-community
3. Notice in the track selector that latest is always first and then all versions are displayed in alphanumeric descending order 
4. #winning
**Note:** I would like to take the opportunity to thank @Lukewh for the amazing library in `/js/lib/channels.js`

Fixed ordering on snaps with dotted version numbers

---

static/js/public/first-snap-flow.js
static/sass/_patterns_first-snap-flow.scss
templates/first-snap/push.html

Fixes #1787
Adds registering name form to "Publish snap" step of first snap flow.
###
- go through first snap flow to the last step
- sign in
- register name form should appear for registering a name
- try typing invalid name (validation should show error, submit should be disabled)
- try registering reserved name, name that you already own, new name etc (proper error or success message should appear)

Register name in first snap flow

---

webapp/app.py

Add service name when logging
- `./run`
- http://0.0.0.0:8004/
- Check logs and make sure every access log finishes by: `service=snapcraft.io`

Add service name in logs to help logging parsing

---

templates/home/_fsf_moos.html
templates/partials/fsf_language.html
webapp/first_snap/content/moos/build.yaml
webapp/first_snap/content/moos/package.yaml
webapp/first_snap/content/moos/test.yaml

This is the new "old" PR for MOOS. Initially we wanted to add code example, but this will be a basic main comms mechanism snap.
The PR includes:
- Changes to build, package and test to reflect MOOSDB command invocation.
- Partials change to point to FSF.
- Template change with the new yaml (separate PR for docs).

MOOS FSF changes after old pr closed and Kyle approved moosdb example

---

templates/index.html

Proposal fix for #1860 
2. Open the homepage
3. Check all logos from different vendors have a link somewhere.
- Mozilla -> Firefox snap
- KDE -> Publisher page from KDE
- JetBrains -> Publisher page from JetBrains
- Spotify -> Spotify snap
- Google -> Google Cloud SDK snap
- Microsoft -> VSCode temporarily
- Heroku -> Heroku snap
Ideally, we would like to have a link to all publisher pages but in the meantime redirecting users from the homepage to relevant snaps seems like a quick fix meanwhile we gather all content and have the right conversations.

Updated index homepage with links to relevant snaps from logos

---

static/sass/styles-embedded.scss
templates/store/snap-embedded-card.html

Fixes #1825
Makes sure all released channels are shown in embedded card.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1874.run.demo.haus/
- go to publicise page of any snap with multiple tracks
- show embedded card
- if 'Show all channels' option is enabled all channels (from different tracks) should be visible

Embedded channels fix

---

static/js/publisher/publicise.js

Fixes https://github.com/canonicalltd/snap-squad/issues/975
Makes sure embedded card preview in publicise page is resized to full content size.
- go to publicise page of a snap with a screenshot (possibly GIF)
- open embedded cards page
- preview should load and resize to correctly fit all the content
- resize the page
- preview should adjust and adapt height

Make sure size of embedded card in publicise page is updated

---

templates/home/_fsf_moos.html
webapp/first_snap/content/moos/build.yaml
webapp/first_snap/content/moos/package.yaml
webapp/first_snap/content/moos/test.yaml

Also update to use the latest MOOS, and stop referring to the "official" moos snap.

MOOS FSF: Remove "ping" references

---

static/js/public/store-categories.js
templates/store/search.html

Fixes the waterfall of sentry issues related to `Cannot read property 'querySelectorAll' of null` since the last release
- `./run`
- Visit http://0.0.0.0:8004/search?category=&q=asdasdasda
- There should be no errors in console

Don't init store-categories on search page

---

static/sass/_patterns_media-object--snap.scss

Fixes https://github.com/canonical-web-and-design/snapcraft.io/pull/1878#issuecomment-487961744
To get around https://github.com/canonical-web-and-design/vanilla-framework/issues/2175 this set's specific image sizes for media-object images.
- `./run`
- Visit http://0.0.0.0:8004/store and http://0.0.0.0:8004/publisher/kde
- Throttle your connection/ browser [chrome](https://css-tricks.com/throttling-the-network/) [firefox](https://blog.nightly.mozilla.org/2016/11/07/simulate-slow-connections-with-the-network-throttling-tool/)
- See that the area icons should be aren't collapsed before the page loads

Force image sizes to prevent load-jumping

---

webapp/store/content/publishers/kde.yaml

All snaps now have icons :+1:
- `./run`
- Visit http://0.0.0.0:8004/publisher/kde
- All snaps have icons, right?

Update for KDE publisher page

---

static/js/public/first-snap-flow.js
static/sass/_patterns_annotated_code.scss
static/sass/_patterns_first-snap-flow.scss
static/sass/styles.scss
templates/first-snap/package-deprecated.html
templates/first-snap/package.html
tests/first_snap/tests_views.py
webapp/first_snap/content/python/snapcraft.yaml
webapp/first_snap/content/snapcraft_yaml_annotations.yaml
webapp/first_snap/views.py

Fixes #1896
Adds annotated snapcraft.yaml viewer to Python tutorial in first snap flow (Package step).
Allows to download snapcraft.yaml file generated with a snap name chosen by user.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1891.run.demo.haus/
- go to Package step of Python first snap flow
- choose name, go to third step (Download your snapcraft.yaml)
- annotated yaml should be shown (with a name chosen before)
- tooltips should be shown when hovering over different sections of the file
- button below it should download the snapcraft.yaml file with a name chosen by user
**Please make sure to read the copy text of "Downloa your snapcraft.yaml" section. My "D" key is misbehaving recently an I may have mae some typos ;)**

Annotated snapcraft yaml

---

templates/first-snap/_install-macos.html

Fixes #1903
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1904.run.demo.haus
- go to [first snap flow](https://snapcraft-io-canonical-web-and-design-pr-1904.run.demo.haus/first-snap/python), choose MacOS
- in the Multipass install instructions link should link to new Multipass site instead of the repo

Update multipass link to new website

---

tests/blog/tests_index.py
webapp/api/blog.py
webapp/blog/views.py

Improve speed of blog pages and reduce the number of HTTP calls to the wordpress API made to render these pages.
- ./run
- Make sure /blog and /blog/<slug> endpoints work as in production.

Improve speed on blog pages

---

webapp/api/blog.py

Wordpress response times ocasionally spike, we are increasing the
timeout times to avoid bad gateways when this happens
- ./run
- Make sure blog still works

Increase timeout on wordpress API

---

static/js/public/fsf-language-select.js

Fixes #1905
In first snap flow language selection page it opens the section corresponding to hash in the URL.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1916.run.demo.haus/
- go to first snap flow
- click on any language
- details should open and hash in URL should change
- see that it works for different languages
- reload the page with URL with hash (https://snapcraft-io-canonical-web-and-design-pr-1916.run.demo.haus/first-snap#c)
- page should load and language details from URL should open
- same should with language selector for first snap flow on home page

Open first snap flow language details based on hash in URL

---

static/js/publisher/release/components/releasesTableCell.js
static/sass/_snapcraft_release.scss

Fixes #1911 Moving devmode icon to right hand side
2. Go to `htop/releases` to see revisions with devmode where the icon is on the right-hand side
3. #winning

Moved devmode icon to right hand side

---

templates/index.html
templates/partials/livestream-notification.html
templates/partials/search-bar.html
webapp/helpers.py
webapp/snapcraft/content/snapcraft_live.yaml
webapp/snapcraft/logic.py
webapp/snapcraft/views.py
webapp/store/views.py

Semi fixes: https://github.com/canonical-web-and-design/snapcraft.io/issues/1854
- `./run`
- Visit http://0.0.0.0:8004/ and http://0.0.0.0:8004/store
- See the notification atop the page
- Edit `webapp/snapcraft/content/snapcraft_live.yaml`
- Set a different time to ensure that the default `lead_time` of 4 days is honoured
- Set a different time to ensure that the default `cooldown_time` of 2 days is honoured
- Set `lead_time` in the yaml to ensure that the local lead time override works
- set `cooldown_time` in the yaml to ensure that the local cooldown time override works

Semi-automate snapcraft live

---

templates/store/snap-details.html

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1893
- `./run`
- Click on any snap
- See that the snap details are in a definition list, as described in https://github.com/canonical-web-and-design/snapcraft.io/issues/1893

Switch to definition list

---

static/js/public/first-snap-flow.js

To reduce the number of idle requests to check if a snap has been uploaded.

Reduce number of requests for getSnapCount in fsf

---

webapp/first_snap/content/c/test.yaml
webapp/first_snap/content/golang/test.yaml
webapp/first_snap/content/java/test.yaml
webapp/first_snap/content/moos/test.yaml
webapp/first_snap/content/node/test.yaml
webapp/first_snap/content/pre-built/test.yaml
webapp/first_snap/content/python/test.yaml
webapp/first_snap/content/ros/test.yaml
webapp/first_snap/content/ros2/test.yaml
webapp/first_snap/content/ruby/test.yaml
webapp/first_snap/content/rust/test.yaml

Fixes #1910 
Updates first snap flow macOS test instructions to correctly display user chosen snap name
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1923.run.demo.haus/
- go to first snap flow, any language, choose mac OS
- go next, choose snap name
-  go to test step
- install instructions in all steps should correctly show entered snap name

Fix first snap flow macOS test instructions

---

static/js/libs/colours.js

Fixes various sentry errors relating to `t is null` `Cannot read property 'style' of null` etc.
- Make sure the featured background colours still load
- Do the same on some category pages

Skip featured colouring if parent can't be found

---

templates/store/_media-object-snap-partial.html

Fixes https://github.com/CanonicalLtd/snap-squad/issues/985
Removes broken verified publisher tooltip.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1925.run.demo.haus/
- go to Store page
- find snap of verified publisher, hover over the verified icon
- Vanilla black tooltip should not appear
- small browser tooltip should appear
- click on a snap (to go to snap page)
- hover over verified publisher, black vanilla tooltip should normally appear

Remove broken verified publisher tooltip from snaps grid

---

templates/store/snap-embedded-card.html

Fixes #1928
Adds "canonical" link URL to embedded card meta data to make it indexed as a snaps details page by search engines.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1929.run.demo.haus/
- go to embedded card page of any https://snapcraft-io-canonical-web-and-design-pr-1929.run.demo.haus/code/embedded
- check the source, `<head>` should contain rel="canonical" link with snap details page URL

Make embedded card indexed by search engines as snap details page

---

tests/publisher/snaps/test_logic.py
tests/store/tests_details.py
webapp/authentication.py
webapp/login/views.py
webapp/publisher/snaps/logic.py
webapp/store/snap_details_views.py

Fixes #1813
Show notification on snap details page for snap owners and collaborators with a link to editing details of listing page.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1919.run.demo.haus/
- go to snap details page of a snap shared with you (that you didn't create yourself)
- snap details page should show notification about editing the snap listing
- go to snap details page of snap you don't own (and are not a collaborator of) - no notification should be on the page

Check if user is snap collaborator for snap details editing

---

templates/store/search.html

Fixes https://github.com/CanonicalLtd/snap-squad/issues/986
No results no pagination
- search for something that doesn't exist
- there should be no pagination
- make sure pagination works fine when there are search results, on category pages, etc

Only show pagination if there are search results

---

static/js/base/ga.js
templates/store/snap-distro-install.html
tests/store/tests_distro_page.py
webapp/store/content/distros/arch.yaml
webapp/store/content/distros/debian.yaml
webapp/store/snap_details_views.py

Fixes #1932 
Fixes #1933
Adds simple snap distro page template with example content for Debian.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1938.run.demo.haus/
- go to /install/SNAPNAME/debian or /arch for any public snap: https://snapcraft-io-canonical-web-and-design-pr-1938.run.demo.haus/install/spotify/debian
https://snapcraft-io-canonical-web-and-design-pr-1938.run.demo.haus/install/slack/arch
- basic template for distro page with install instructions should be shown

Snap distro install page prototype (for Debian)

---

tests/first_snap/tests_views.py
webapp/first_snap/views.py
webapp/helpers.py
webapp/snapcraft/logic.py
webapp/store/snap_details_views.py
webapp/store/views.py

Moved all YAML helper functions to helpers and re-use them across the codebase.
- ./run
- Make sure all features that rely on YAML still work:
- Livestream
- Publisher pages
- FSF
- More snaps feature should work `http://0.0.0.0:8004/pycharm-professional`
Fixes #1948

Move all the YAML logic into helpers

---

static/sass/_patterns_distro_banner.scss
static/sass/styles.scss
templates/store/snap-distro-install.html

Fixes #1950 
Adds suru background with distro specific gradient to distro page.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1949.run.demo.haus
- go to snap distro install page for any snap (/debian and /arch are available)
- check suru background on different page widths
https://snapcraft-io-canonical-web-and-design-pr-1949.run.demo.haus/install/code/arch
https://snapcraft-io-canonical-web-and-design-pr-1949.run.demo.haus/install/slack/debian

Distro page template suru background

---

static/js/libs/fileValidation.js
static/js/libs/fileValidation.test.js

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1936
and supersedes https://github.com/canonical-web-and-design/snapcraft.io/pull/1941
2. Open edit listing page for a snap you own
3. Try to upload this image 1444x482.png as a Featured Banner:
4. You should get an error message: `1941-banner.png (1444 x 482 pixels) does not have the correct aspect ratio: it needs to be 3:1 (e.g., 1446 x 482 pixels)`
5. The tests should also pass and have 100% coverage to cover:
- A suggested image size that would exceed and dimension restrictions (it instead suggests the alternative dimension change)
- A range of allowed aspect ratios for example when trying to use the same image for a media item `1941-banner.png (1444 x 482 pixels) does not …

Show better error message on incorrect aspect ratios

---

templates/first-snap/package.html
tests/first_snap/tests_views.py
webapp/first_snap/views.py

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1937
- `./run`
- Visit http://0.0.0.0:8004/first-snap
- Not logged in, the flow should work as before
- Log in
- Go through the steps as before - the snap name should at the "Package snap" step, should be suffixed with "-USERNAME" instead of "-{name}", but unlike if the name has been previously picked - you still need to "Choose snap name"

If logged in, append fsf snap name with username

---

templates/_header_empty.html
templates/_layout.html
templates/store/snap-distro-install.html

Fixes #1952 
Removes navigation items on distro page.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1971.run.demo.haus/
- go to distro page of any snap (https://snapcraft-io-canonical-web-and-design-pr-1971.run.demo.haus/install/skype/arch)
- navigation should only contain snapcraft logo
- go to other pages (home, store, snap details, publisher pages)
- navigation should work as before

Distro page navigation

---

templates/store/snap-distro-install.html

Fixes #1953 
Adds "More things to do..." boxes to distro page
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1973.run.demo.haus/
- go to distro page of any snap: https://snapcraft-io-canonical-web-and-design-pr-1973.run.demo.haus/install/hiri/debian
- scroll down
- 2 boxes with links to snap store snap and snapcraft home page should be visible

Add "more things..." to distro page

---

static/js/base/ga.js
static/js/public/ga-scroll-event.js
static/js/public/public.js
templates/store/snap-distro-install.html

Fixes #1954 
Adds GA when code snippets are clicked (assuming they are selected to be copied) and when install instructions are scrolled into view.
GA events are not triggered on test environments.
Testing can be done by checking contents of `dataLayer` array in browser console. It should contain all GA events prepared to be sent.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1976.run.demo.haus/
- go to distro page of any snap (https://snapcraft-io-canonical-web-and-design-pr-1976.run.demo.haus/skype/debian)
- check GA events in `dataLayer` (only page loads should be there)
- scroll down to see snap install instructions ("snap install skype")
- check GA events in `dataLayer` (last event should be about visible install instructions)
- click on install instructions input
- …

Distro page GA events

---

static/sass/_patterns_distro_banner.scss
templates/store/snap-distro-install.html
webapp/store/content/distros/arch.yaml
webapp/store/content/distros/centos.yaml
webapp/store/content/distros/debian.yaml
webapp/store/content/distros/elementary-os.yaml
webapp/store/content/distros/elementaryos.yaml
webapp/store/content/distros/fedora.yaml
webapp/store/content/distros/kde-neon.yaml
webapp/store/content/distros/kubuntu.yaml
webapp/store/content/distros/manjaro.yaml
webapp/store/content/distros/mint.yaml
webapp/store/content/distros/opensuse.yaml
webapp/store/content/distros/ubuntu.yaml

Fixes #1975 
Adds content for all other supported distros and fixes couple of design review issues:
- using highlighted card
- dropping chevron icon
- small copy adjustments
- making sure single line commands are not detected as multiline
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1978.run.demo.haus/
- Visit distro page for all the distros and make sure they render fine (try with different snaps):
https://snapcraft-io-canonical-web-and-design-pr-1978.run.demo.haus/install/riot-web/arch
https://snapcraft-io-canonical-web-and-design-pr-1978.run.demo.haus/install/pick-colour-picker/centos
https://snapcraft-io-canonical-web-and-design-pr-1978.run.demo.haus/install/wing7/debian
https://snapcraft-io-canonical-web-and-design-pr-1978.run.demo.haus/install/eric-ide/elementary-os …

Add page content .yamls for all the distros

---

templates/store/snap-distro-install.html
webapp/store/snap_details_views.py

https://snapcraft-io-canonical-web-and-design-pr-1983.run.demo.haus/install/android-studio/debian
- updated heading of install instructions
- showing 12 featured snaps

Updates to distro page template

---

static/js/public/public.js
static/js/public/scroll-to.js
templates/store/snap-distro-install.html

Adds animated scroll to distro install instructions.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1982.run.demo.haus/
- go to distro page of any snap https://snapcraft-io-canonical-web-and-design-pr-1982.run.demo.haus/install/slack/arch
- click on "Install snap" button
- page should scroll smoothly to the install instructions
- there should be a small offset margin above card with instructions

Add animated scroll to distro install instructions

---

requirements.txt
webapp/publisher/snaps/views.py

Fixes #1980 
Previous version of bleach was closing everything that was considered as a tag. The update of bleach fixes this issue.
- `./run`
- http://0.0.0.0:8004/featherpad/preview
- http://0.0.0.0:8004/featherpad
- The email shouldn't be a closed tag at the end of the description

Update bleach to latest version

---

static/js/publisher/release/components/releasesTable.js
static/js/publisher/release/components/releasesTableCell.js
static/sass/_snapcraft_release.scss

Fixes #1958
Fixes #1943
Updates visual style of release UI (as per #1958) in preparation for drag and drop.
Also fixes alignment of devmode icon (see #1943)
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1990.run.demo.haus/
- see that design is updated as described in #1958
- check different states of the UI (promote some cannel, open history panel of any release, hover on things)
- try to promote any devmode revision: devmode icon and cancel icon should appear next to each other not overlapping

Update visual style of release UI (in preparation for drag and drop)

---

templates/store/snap-details/_distro-instructions-for-snap-support.html

It's "openSUSE", not "OpenSUSE"

Fix capitalisation of openSUSE

---

static/js/publisher/preview.js
tests/store/tests_public_logic.py
webapp/store/logic.py

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1994
- `./run`
- Visit a snap listings page http://0.0.0.0:8004/<snap_name>/listing
- Add a youtu.be url (https://youtu.be/3OFhVtqfDBQ)
- Preview the page
- Save the page
- Visit http://0.0.0.0:8004/<snap_name>
- The video should work

Allow youtu.be video urls

---

static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/releasesTableRow.js
static/sass/_snapcraft_release.scss

Fixes #1959 
Shows version under channel name in releases table.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2018.run.demo.haus/
- go to publisher releases page of any snap
- under channel name in each row version should be displayed:
- version number if all revisions in this channel have same version
- "Multiple versions" if revisions have different versions
- nothing if channel has no revisions
- if all revisions have same version in channel versions are not shown in individual cells
- hovering over channel name/version shows tooltip with version breakdown per arch
- this all applies only to 4 channel rows, not to 'available revisions' row at the bottom

Releases common version

---

static/js/publisher/release/components/releasesHeading.js

Fixes #2021
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2023.run.demo.haus
- go to releases page of any snap with multiple tracks (https://snapcraft-io-canonical-web-and-design-pr-2023.run.demo.haus/skype/releases)
- track dropdown should be part of the heading on left side
- track dropdown should work as before
- check snap without tracks to see if they are not affected

Move tracks dropdown to left side of heading

---

static/sass/_patterns_distro_banner.scss
templates/store/snap-distro-install.html
webapp/store/content/distros/arch.yaml
webapp/store/content/distros/centos.yaml
webapp/store/content/distros/debian.yaml
webapp/store/content/distros/elementary.yaml
webapp/store/content/distros/fedora.yaml
webapp/store/content/distros/kde-neon.yaml
webapp/store/content/distros/kubuntu.yaml
webapp/store/content/distros/manjaro.yaml
webapp/store/content/distros/mint.yaml
webapp/store/content/distros/opensuse.yaml
webapp/store/content/distros/ubuntu.yaml
webapp/store/snap_details_views.py

Attempt to fix the problem with #2014 by making use of white version of logos
2. Visit any distro page (i.e. `/install/skype/mint` or `/install/skype/arch`)
3. Check the logo on the top right is white
4. Notice the white logo adapts between mobile and desktop
5. #winning

White logos in distros

---

static/js/publisher/release/components/releasesTableRow.js
static/sass/_snapcraft_release.scss

Fixes #2022
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2025.run.demo.haus/
- available revisions dropdown should be in a heading
- it should work as before
- available revisions dropdown row should show current version as name

Move revisions dropdown from table cell to heading

---

static/js/publisher/preview.js

Fixes #2033
- run or https://snapcraft-io-canonical-web-and-design-pr-2043.run.demo.haus/
- go to listing page of any snap
- edit description to contain code block using fences ```
- preview and make sure code block is not rendered as code block
- use code block using 4 spaces indent
- preview to make sure spaces indented code block is rendered as code block
- make sure inline code in ticks ` works

Disable ```fences``` code blocks in preview

---

templates/store/snap-details/_distro-instructions-for-snap-support.html

Fixes #2039
Updates Fedora logo on distros list on snap details page.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2041.run.demo.haus/
- go to snap details page of any snap
- scroll down to distros section
- Fedora logo should be correct (hi res png)

Fix Fedora logo on snap details page

---

static/js/publisher/publicise.js

Fixes #2004 
Fix embedded card sizing issue in Safari
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2042.run.demo.haus/
- go to publicise page of any of your snaps in Safari
- go to Embedded cards page
- embedded card preview should resize to fit content, but should stop resizing

Fix embedded card sizing issue in Safari

---

package.json
static/js/publisher/release.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/releasesTableRow.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js
static/sass/_snapcraft_release.scss
yarn.lock

Fixes #1961 
Fixes #1962 
Fixes #1963 
Adds drag'n'drop to releases page.
Channels can now be promoted using drag'n'drop.
This is new quite complex feature. Please make sure to QA on different snaps (different number of architectures, devmode revisions, closed channels, etc) and in different browsers (it uses native drag'n'drop, so browser implementations may differ).
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2019.run.demo.haus/
- go to releases page or any snap (many snaps ideally)
- try to promote some stuff using drag'n'drop
- make sure that things that can be normally promoted can also be promoted with drag'n'drop
- make sure that things that can't be normally promoted (empty channel, devmode) can't be promoted with drag'n'drop
- click on things, try drag'n'drop in …

Drag'n'drop to promote channel

---

static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/releasesTableRow.js
static/sass/_snapcraft_release.scss

Fixes #1964
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2045.run.demo.haus/
- individual revision cells in releases table should have a drag handle
- you should be able to drag the revision to other channel in same architecture
- you should not be able to drag revision to different architecture
- you should not be able to drag empty cells (with no revisions)
- you should not be able to drag devmode revisions to stable/candidate
- make sure dragging whole channel still works as before
- try with different snaps in different browsers

Release single revision using drag'n'drop

---

static/js/publisher/release/components/dnd.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/releasesTableRow.js
static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/sass/_snapcraft_release.scss
yarn.lock

Fixes #1965
- Adds possibility for dragging revision from history panel to promote it
- Refactors d'n'd by extracting shared functionality and styles
- ./run or  https://snapcraft-io-canonical-web-and-design-pr-2052.run.demo.haus/
- click on revision cell to open history panel
- drag any revisions in history to promote it to some channel
- make sure dragging revision cells and channel rows still work

Revision history dnd

---

static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/sass/_snapcraft_release.scss

Fixes #2053 
Highlight active (currently released) revision in history panel.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2054.run.demo.haus/
- click on any revision cell, currently released revision (first on the list) should be highlighted in white with bold revision number

Highlight active revision in history panel

---

webpack.config.js

react-dnd since v8 uses ES6 modules. This means we need to include it in babel loader transpilation in webpack.
- ./run --env ENVIRONMENT=production build
- everything should build without errors

Include react-dnd ES6 modules in babel-loader

---

yarn.lock

Previous versions of uglify were breaking React hooks.
- ./run --env ENVIRONMENT=production
- make sure everything builds and server runs
- it should render without errors in console
- make sure drag and drop works
- have a look at other pages (public and publisher), to make sure new build haven't broken anything

Upgrade uglify to fix build errors in new versions of React

---

templates/store/search.html
webapp/store/views.py

Fixes https://sentry.is.canonical.com/canonical/ubuntu-com/issues/2325/?query=is%3Aunresolved
When category not existing and no query paramenter.
- `./run`
- http://127.0.0.1:5000/search?category=toto
- Should get a page telling you couldn't find snaps on this category.

Fix search when category not existing

---

static/js/publisher/release/components/releasesHeading.js

As the default track conversation continues, we don't want people to get stuck in a hole because of the messaging we're providing.

Disable setting and clearing default tracks

---

static/js/libs/mobile.js

From Sentry: https://sentry.is.canonical.com/canonical/snapcraftio/issues/2195
I couldn't reproduce this one, but this makes sure functionality that uses affected function works:
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2064.run.demo.haus/
- go to snap details page on small mobile screen
- click on a screenshot - should open in new tab, no errors in console

Fixes errors when mobile button was not found in DOM

---

static/js/publisher/release/components/revisionsList.js

Sentry: https://sentry.is.canonical.com/canonical/snapcraftio/issues/2531/
Fixes issue with checking if revision is active when there is no active revision (for example channel was closed).
- go to releases page of snap you own
- close some channel
- Save (so that changes are propagated to store)
- click on any empty cell in closed channel
- history panel should open, there should be no errors in console

Fix checking if revision is active

---

static/js/public/accordion.js
static/js/public/first-snap-flow.js

From Sentry: 
https://sentry.is.canonical.com/canonical/snapcraftio/issues/1190/
https://sentry.is.canonical.com/canonical/snapcraftio/issues/1757/
Makes sure all occurrences of document.querySelectorAll are properly wrapped in Arrays.
- ideally use old browser that doesn't support .forEach on NodeList ;)
- go to first snap flow, click on OS picker, click through pages, open accordions
- there should be no errors in console, everything should work

Fix calling forEach on NodeList in older browsers

---

static/js/public/scroll-to.js
templates/store/snap-distro-install.html

From Sentry: https://sentry.is.canonical.com/canonical/snapcraftio/issues/2239/
When accessing distro page via google translate link `href`s are modified. This causes animated scroll script to throw error when href is expected to be id of element on the page but is actually a full `http://` URL.
This PR introduces separate data attribute, so that even with modified href animate scroll script will work without errors.
###
- go to distro page of some snap
- open devtools, find "Install" button, modify the href attribute from "#install" to some random string or URL
- click on the button, animated scroll should work, no errors should be sent to sentry

Don't rely only on href when animating scroll

---

templates/first-snap/_install-macos.html

Tiny first PR..
Fixes #2049
2. Go to the FSF and go to the 'Install Snapcraft' stage of the tutorial
3. The install steps should be re-ordered Homebrew, Snapcraft, Multipass
4. You should be able to `brew cask install Multipass`

FSF- Added brew cask install multipass

---

static/js/libs/colours.js

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2086
- `./run`
- Check the featured banner is not black
- Compare to https://snapcraft.io/store

Fix for pure black and white featured logos

---

static/js/publisher/release/components/devmodeRevision.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/sass/_snapcraft_release.scss

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2077
- `./run`
- Visit http://0.0.0.0:8004/lukewh-test/releases
- There should no longer be an [i] icon, for any revision that's devmode or devel grade
- Instead there should be an * next to the revision
- Hovering over these cells/ revisions should show a tooltip.
- This should also all work within the history tables when you click on a cell.
- Compare with https://staging.snapcraft.io/lukewh-test/releases

Replace devmode icon with asterisk

---

static/js/publisher/release/components/historyIcon.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/releasesTableRow.js
static/sass/_snapcraft_patterns_icons.scss
static/sass/_snapcraft_release.scss

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2080
- `./run`
- Visit http://0.0.0.0:8004/lukewh-test/releases
- Hovering around the table should show the history icon in the top right of cells
- Clicking on the icon should expand the history for that channel/arch combo
- Clicking again should close the history
- Click the "x" in the top right of the history table should also close the history
- If you promote a channel/arch (drag to another cell) the history icon should move to the left to make space for the "x" cancel icon

Release UI: Use history icon to open history panel

---

static/js/publisher/release/components/releasesTable.js
static/js/publisher/release/components/releasesTableRow.js
static/sass/_snapcraft_release.scss

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2082
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2083
- `./run`
- Visit http://0.0.0.0:8004/lukewh-test/releases
- latest/stable should claim to have ~13 branches
- click the branches icon/label
- See 10 branches
- Scroll to the bottom and click the "Show all branches (13)" link
- See all 13 branches
- Scroll to the bottom and click the "Show only 10 branches" link
- The list should compact again
- Dragging and dropping should work as expected with 10 or all branches shown
- latest/edge should have 1 branch, but no link to "see all"
- Joy and happiness in snap-world

Limit branches shown to 10

---

static/js/public/snap-details/channelMap.js
templates/store/snap-details/_channel_map.html
tests/store/tests_details.py
tests/store/tests_distro_page.py
tests/store/tests_embedded_card.py
tests/store/tests_github_badge.py
webapp/helpers.py
webapp/store/snap_details_views.py
webapp/template_utils.py

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1968
- Set your env to point to staging (as described in the README)
- `./run`
- Visit http://0.0.0.0:8004/lukewh-test
- The channel map dropdown at the top should have the updated text
- Clicking the dropdown and clicking "install >" on a row should display the appropriate install instructions:
- As track 2.0 is the default track the install instructions should simple be `snap install lukewh-test`
- The beta version should be `snap install lukewh-test --edge`
- The 1.0/beta should be `snap install lukewh-test --channel=1.0/beta`
- Also inspect the "View in Desktop store" buttons to ensure they have the correct format of `snapname?channel` if required.
- You should also check that any other snaps that …

Use default track for channel map if set

---

static/js/publisher/release/components/revisionsList.js
static/sass/_snapcraft_release.scss

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2078
- `./run`
- Visit http://0.0.0.0:8004/lukewh-test-2/releases
- See how it looks with 1 architecture
- Open things up - look at the branches etc.
- Visit http://0.0.0.0:8004/obs-studio/releases
- See how it looks with 2 architectures
- Visit http://0.0.0.0:8004/lxd/releases
- See how it looks with all the architectures (should be the same as before)

Wider table for fewer archs

---

templates/store/search.html

To fix the XSS issue:
```
https://snapcraft.io/search?q=accesskey=x%20onclick=alert(/XSS/)%20x
<meta property="og:title" content="
Snap search results for "accesskey=x onclick=alert(/XSS/) x"
— Linux software in the Snap Store
"/>
Triggered by Alt+Shift+X in Firefox
```
- On that branch try to reproduce the issue.
- It shouldn't work anymore.

Convert double quotes to single to fix XSS issue

---

static/sass/_snapcraft_p-docs.scss
webapp/docs/views.py

Update the docs index topic to make the redirects work with the new `/docs` prefix.
- Navigate to `/docs`.
- Make sure the navigation links work.
Fixes #2103

Update docs index topic

---

templates/_footer.html

We're calling it "Charmed Kubernetes" now.

Charmed Kubernetes name change

---

requirements.txt
webapp/docs/views.py

Upgrade to canonicalwebteam.discourse-docs v0.6.2 so we get a
/docs/sitemap.txt endpoint.
Change search to return results from snapcraft.io/docs rather than
docs.snapcraft.io.
QA
--
`./run --env SEARCH_API_KEY={thekey}`, go to `/docs/sitemap.txt` and see it in all its glory.
Go to `/docs/search`, search for things, see the results returned are at `snapcraft.io/docs`.

Sitemap and change search to snapcraft.io/docs

---

webapp/docs/views.py

I've updated the content in https://forum.snapcraft.io/t/snap-documentation/11127 to match the changes that were in https://forum.snapcraft.io/t/snap-docs/12443.
So here I'm switching back to using the original topic, so we can delete the temporary new one.
QA
--
`./run`, go to http://0.0.0.0:8004/docs and see that it looks the same as https://snapcraft.io/docs apart from that the title is "Snap documentation" rather than "Snap docs".
Check navigation links still work.

Switch docs index topic back to the original one

---

templates/store/snap-distro-install.html
webapp/store/snap_details_views.py

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1993
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1992
- `./run`
- Visit http://0.0.0.0:8004/install/spotify/debian
- The install area title should be update: ["Enable snaps on Debian and install Spotify"](https://github.com/canonical-web-and-design/snapcraft.io/issues/1992)
- Spotify should not appear in the "Other popular snaps..." section
- Try with a few other snaps, both in the "other popular snaps" and not

Update distro page install title and remove duplicate snap

---

static/sass/_patterns_annotated_code.scss

Fixes styling of annotated code in first snap flow.
- go to first snap flow "package snap" step
- click on generate snapcraft.yaml
- annotated code should look fine, hovering should show tooltips
- compare with production

Fix annotated code styles in first snap flow

---

static/sass/_snapcraft_p-docs.scss
templates/docs/base.html

Fixes #2133 
Fixes width of docs pages with Vanilla 2.0.
- go to /docs
- make sure they have full width of new page width
- browse some docs, make sure they render ok

Vanilla layout fixes for docs

---

static/sass/_patterns_first-snap-flow.scss
templates/first-snap/package.html
templates/first-snap/push.html

Fixes #2134
Updates styles for accordion in first snap flow
- go to first snap flow
- click through steps to get to accordion (Package step and Push step)
- accordion should have 'Step X:' in headings and layout should look good

Fix accordion steps in first snap flow

---

templates/blog/index.html

Fixes #2132
Uses new Vanilla pagination pattern on blog
- go to /blog
- check nice new pagination
- use new pagination
- make sure it works in all the edge cases (first page, last page, etc)
Known issues:
- visited pagination buttons get blue (https://github.com/canonical-web-and-design/vanilla-framework/issues/2458)
- pagination is not exactly centred (https://github.com/canonical-web-and-design/vanilla-framework/issues/2459)

Update pagination on blog to new pattern

---

static/sass/_snapcraft-publicise.scss
templates/publisher/publicise/_publisher_publicise_layout.html
templates/publisher/publicise/embedded_cards.html
templates/publisher/publicise/github_badges.html
templates/publisher/publicise/store_buttons.html

Fixes #2138
- Updates sidebar navigation styles
- Fixes copyable code blocks
- go to publicise page of any snap
- make sure sidebar navigation is visible and works well
- make sure copyable code blocks look good (have no CLI icon) and work
- make sure functionality of the page works good on all sub pages (changing language of badges, changing settings of embeddable card, etc)

Fixes for publicise page

---

templates/docs/document.html

Fixes #2161 
1. Pull the branch or run locally
2. Visit `/docs`
3. Search for something in the docs
4. Results should have different title on results as opposed os current behaviour:

Added title to docs so they appear on search results

---

static/js/publisher/form/AccordionHelp.js
static/js/publisher/form/icon.js
static/sass/_snapcraft_market.scss
static/sass/_utilities_flex.scss
static/sass/styles.scss
templates/publisher/listing.html

Fixes #2135
- fixes positioning of delete icon icon
- fixes spacing of helper text on some fields
- go to listing page of some snaps (with icon, without icon, with screenshots, without, etc)
- check if everything looks and works as expected
- check the preview
- check screeshot/banner drag n drop
- check licences fields
- edit something, save

Vanilla - Fixes for publisher snap listing

---

static/sass/_snapcraft_market.scss
templates/publisher/_header.html
templates/publisher/listing.html
templates/publisher/settings.html

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2139
- `./run`
- Visit http://0.0.0.0:8004/snap_name/settings
- Ensure the page works as before
- The sticky bar should look the same as the listing page
- The sticky bar should be tighter
- Both the listing page and settings page sticky bar buttons should go full-width without margins at mobile size

Publisher settings sticky bar consistent with listings

---

static/sass/_patterns_blog-post.scss

- go to  https://snapcraft-io-canonical-web-and-design-pr-2182.run.demo.haus/blog/top-snaps-in-2018
- see if headings in blog are rendered correctly

Fix td styles for headings in blog posts

---

webapp/first_snap/content/c/build.yaml
webapp/first_snap/content/golang/build.yaml
webapp/first_snap/content/java/build.yaml
webapp/first_snap/content/moos/build.yaml
webapp/first_snap/content/node/build.yaml
webapp/first_snap/content/pre-built/build.yaml
webapp/first_snap/content/python/build.yaml
webapp/first_snap/content/ros/build.yaml
webapp/first_snap/content/ros2/build.yaml
webapp/first_snap/content/ruby/build.yaml
webapp/first_snap/content/rust/build.yaml

Fixes [ss#1046](https://github.com/canonical-web-and-design/snap-squad/issues/1046)
2. Go to the build step of FSF flow and notice there is no reference to unsquashfs on Linux or MacOS
3. Rinse and repeat on all languages
4. #winning

Removed unsquash fs from all language guides

---

static/sass/_snapcraft_p-navigation.scss
yarn.lock

Workaround for issue navigation spacing in Firefox (https://github.com/canonical-web-and-design/vanilla-framework/issues/2483).
Also needed to update `sass-lint` for grid support, so yarn updated a hell of .lock file.
- check navigation in Chrome
- check navigation in Firefox
- they should look the same (no spacing between logo and items in Firefox)

Mind the gap

---

static/js/publisher/form/AccordionHelp.js
static/js/publisher/form/banner.js
static/js/publisher/form/media.js
static/sass/_snapcraft_p-featured-snap.scss
templates/store/_category-partial.html
templates/store/_generated-featured-snap-partial.html
tests/store/tests_get_store_view.py
tests/store/tests_public_logic.py
webapp/api/store.py
webapp/configs/snapcraft.py
webapp/store/logic.py
webapp/store/views.py

Supersedes https://github.com/canonical-web-and-design/snapcraft.io/pull/2116
- `./run --env FEATURED_BANNERS_ENABLED=True`
- See featured banner images and updated generated banners
- Visit http://0.0.0.0:8004/snap_name/listing
- Ensure that clicking "Show banner restrictions" under the banner image lists the recommended size of 1920x640

Featured banners

---

static/sass/_search-form.scss
static/sass/_snapcraft_distro-chart.scss
static/sass/styles.scss

Fixes #2194
Changes navigation breakpoint value to make sure all nav items fit in one line. When they don't mobile nav dropdown should be used instead.
Also updated other components not to rely on navigation breakpoint variable to change layout, but on standard medium breakpoint.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2202.run.demo.haus/
- make screen smaller until mobile navigation pops in
- make sure "Forum" link doesn't drop to second line at any width

Fix navigation breakpoint

---

static/sass/_snapcraft_tour.scss
static/sass/styles.scss
templates/index.html

Fixes #2196 
This PR provides styles for guided tour tooltip cards.
Spec: https://docs.google.com/document/d/1kfpRShJe0tAA-ZCpUrxeaH8z452y_MqChwJGNk08xQY/edit#heading=h.cylvjjuf8ht2
This is only a style test, it's going to be merged to feature branch where work on rest on the functionality will continue.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2203.run.demo.haus/
- check the styling of the tooltips
- in devtools you can change `is-tooltip--` classes to try different positions of arrows.

Add new tour tooltip card pattern styles.

---

static/js/public/fsf-language-select.js

Fixes #2204 
Fixes typo in attribute selectors that causes Safari to fail with error.
Use Safari on a Mac
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2206.run.demo.haus/
- go to snapcraft home page
- there should be no `SyntaxError` in console 
- go to "Learn how to snap in 30 minutes", click on any language, panel should open with details
- go to first snap flow https://snapcraft-io-canonical-web-and-design-pr-2206.run.demo.haus/first-snap
- language panel should also work correctly
- go to language selector with # in URL https://snapcraft-io-canonical-web-and-design-pr-2206.run.demo.haus//first-snap#ruby (reload page with # in URL)
- language selector should open on given language automatically

Fix selectors throwing errors in Safari

---

static/js/publisher/tour.js
static/js/publisher/tour/tour.js
static/js/publisher/tour/tourBar.js
static/js/publisher/tour/tourOverlay.js
static/js/publisher/tour/tourStepCard.js
static/sass/_snapcraft_tour.scss
static/sass/_utilities_flex.scss
templates/index.html
templates/publisher/_header.html
templates/publisher/listing.html

Fixes #2198 
- Moves demo tour to publisher listing page
- Adds support for multiple steps with content provided via JSON
- Adds support for different positioning of tooltips to adjust to different elements on page (2 possible positions for the sake of demo)
This is not a complete feature. It's a minimal functional demo of the tour, merged to a feature branch where the work on it will continue.
-  sign in and go to listing page of any snap you own
- find a tour question mark (?) button in right bottom corner
- click it to trigger the tour
- navigate between the steps
- skip or finish tour to close
- tour should handle scrolling and resizing of the screen

Tour steps functionality

---

static/js/publisher/tour/tourOverlay.js
static/sass/_snapcraft_tour.scss
templates/publisher/listing.html

Makes the highlighted elements interactive during the tour.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2215.run.demo.haus/
- sign in
- go to snap listing page of any snap you own
- click on the tour icon (?) in bottom right
- click through the tour
- while clicking through the tour steps interact with elements that are featured, try to edit them during the tour

Tour with interactive page

---

static/js/public/scroll-to.js
static/js/publisher/tour/tourOverlay.js
static/js/publisher/tour/tourStepCard.js
static/sass/_snapcraft_tour.scss
templates/store/snap-distro-install.html
webapp/publisher/content/listing_tour.yaml

Fixes some issues around scrolling elements into view during the tour.
- ./run or  https://snapcraft-io-canonical-web-and-design-pr-2216.run.demo.haus/
- sign in
- go to snap listing page of any snap you own
- click on tour icon (?) in bottom right
- go through the tour
- make sure highlighted elements scroll into place leaving enough space for a tooltip below or above it

Tour scroll improvements

---

static/js/publisher/tour/metricsEvents.js
static/js/publisher/tour/tour.js
static/js/publisher/tour/tourBar.js
static/js/publisher/tour/tourOverlay.js
static/js/publisher/tour/tourStepCard.js

Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1104
Adds GA event when tour is started, skipped or finished.
No data is sent to GA in test environments. To QA you can use `dataLayer` global variable to check list of events collected by GA.
- sign in
- go to snap listing page of any snap you own
- start the tour by clicking on (?) icon in bottom right
- check `dataLayer` for event about starting the tour
- go to some step, finish or skip the tour
- check `dataLayer` for event about finishing/skipping the tour

Add GA events to starting, skipping and finishing the tour

---

static/js/libs/debounce.js
static/js/publisher/tour/tourOverlay.js

Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1105
Adds possibility to use ESC key to skip the tour.
Fixes some issues around scrolling to current step.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2219.run.demo.haus/
- sign in, go to listing page of any snap you own, click on tour icon (?) in bottom right
- when the tour is open hit ESC, tour should be skipped
- there should be Google Analytics skip event in the `dataLayer`
- press ESC on last step of the tour - GA event should be about finished tour instead of skipped
To QA the scrolling issue:
- open the tour, go to the final step (with the Finish button)
- scroll page up (to make sure contact details form inputs are below the border of the screen)
- click on "<" to go to previous step
- page should …

Use ESC to skip the tour

---

static/js/publisher/publisher.js
static/js/publisher/tour.js
static/js/publisher/tour/tour.js
templates/publisher/listing.html

Fixes #2201 
Tour on listing page will start automatically if less than 50% of fields are completed.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2221.run.demo.haus/
- sign in
- go to listing page of a snap that has little information filled in (or remove icon, images, contact details, categories and any other not mandatory data)
- tour should start automatically when listing page loads (for snap with little data)
- once the tour is skipped or finished it should not start automatically again for the same snap
After tour starts automatically verify if proper GA event is sent (in `dataLayer`):
To remove information that tour was finished from the browser clear local storage (or remove specific `listing-tour-finished-...` key):

Start the tour automatically if the form is less than 50% complete

---

static/js/publisher/market/stickyListingBar.js
static/js/publisher/tour.js
static/js/publisher/tour/tour.js
static/sass/_snapcraft_market.scss
templates/publisher/listing.html
templates/publisher/settings.html

Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1106
Requires #2221 - merge that one first
Only one commit relevant for code review: https://github.com/canonical-web-and-design/snapcraft.io/pull/2222/commits/4a7b2bdf061665e6e171a5ef60f08c7f00bda179
Disables sticky bar during the tour to avoid weird behaviour when scrolling.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2222.run.demo.haus/
- sign in, go to listing page of any snap, start the tour using the (?) icon in bottom right
- click through some steps
- scroll down with a tour step open (so the highlighted mask moves to top of the window)
- sticky header should not be there (as it's disabled during the tour)
- skip of finish the tour
- heading should be sticky again

 Disable sticky bar during the tour

---

static/js/publisher/release/components/revisionsList.js
templates/404.html
templates/410.html
templates/docs/search.html
templates/first-snap/_install-linux.html
templates/first-snap/_install-macos.html
templates/first-snap/package.html
templates/home/_fsf_electron.html
templates/index.html
templates/partials/fsf_language.html
templates/publisher/account-snaps.html
templates/store/categories/iot.html
templates/store/snap-details/_channel_map.html
templates/store/snap-distro-install.html

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2172
- `./run`
- Ensure links to docs go to 0.0.0.0:8004/docs not docs.snapcraft.io
- Visit http://0.0.0.0:8004/<snap>/releases
- Visit http://0.0.0.0:8004/asdvkjhfdbkjh
- Visit http://0.0.0.0:8004/first-snap/python
- Make sure both linux and MacOS links work
- Visit http://0.0.0.0:8004/first-snap/python/linux/package
- Make sure the link under step 3 is correct
- Visit http://0.0.0.0:8004/first-snap#electron
- Make sure continue button goes to the right place
- Links to "Available distro's" should be correct
- Visit http://0.0.0.0:8004/iot
- Visit http://0.0.0.0:8004/spotify
- Make sure channel-map help links go to the right place
- Make sure the install on distro link to …

Update all links to docs.snapcraft.io to /docs

---

static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js

Fixes #2224
Show build request id from revision attributes in release UI (in revisions history and in release table tooltip).
This is currently being merged to feature branch, until we figure out final shape of the feature.
- go to releases page of any snap built by Launchpad (e.g. https://snapcraft-io-canonical-web-and-design-pr-2227.run.demo.haus/surl/releases)
- look for revision attributes in revision history list or in tooltips

Revision attributes basics

---

static/js/publisher/release/components/revisionsList.js

Fixes #2230 
Fixes the issue where revisions from the same architecture were unselected.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2232.run.demo.haus/
- go to releases page of a snap with multiple architectures (and multiple versions)
- show "All revisions" in available revisions
- select same version in all architectures
- unselect one architecture
- open history of another architecture, there should be a button 'Select in all architectures'
- clicking on it should select the missing architecture, but not unselect any
- try different combinations of selected revisions: all selected from different versions, all unselected, etc, make sure that behaviour of selecting same version in all architectures works as expected in different cases

Fix selecting same version in all archs in release UI

---

static/sass/_utilities_disabled.scss
static/sass/styles.scss
templates/publisher/_header.html
templates/publisher/publicise/_publisher_publicise_layout.html
tests/publisher/snaps/tests_publicise.py
webapp/publisher/snaps/views.py

Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1108
Fixes 404 error when accessing publicise page on private snap
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2233.run.demo.haus/
- sign in, go it any snap that is private
- Publicise tab should be available
- going to publicise page should show a grayed out and not interactive publicise page with a message on top
- try to go directly to other pages (via URL) /publicise/badges or publicise/cards - these should 404

Show disabled publicise page for private snaps

---

static/js/publisher/release/components/availableRevisionsMenu.js
static/js/publisher/release/components/dnd.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/releasesTableRow.js
static/js/publisher/release/helpers.js
static/js/publisher/release/helpers.test.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js

Fixes #2225 
Allows promoting all revisions in same build set at once.
Removes Launchpad option from "Available revisions" menu when there are no lauchpad builds.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2249.run.demo.haus/
- go to releases page of any snap with Launchpad builds (like [surl](https://snapcraft-io-canonical-web-and-design-pr-2249.run.demo.haus/surl/releases))
- find any release that is part of a build set (has LP icon)
- try to drag it to promote to different channel
- while dragging architectures of all revisions in the build set should highlight
- you should be able to drop the set on ANY architecture from the set
- when you drop build set all revisions from the set should be promoted to given channel

Revision attributes sets

---

static/js/publisher/release/actions/availableRevisionsSelect.js
static/js/publisher/release/actions/availableRevisionsSelect.test.js

Fixes #2251
When 'Launchpad' is selected in a dropdown, automatically only select revisions from latest build set.
- ./run and  https://snapcraft-io-canonical-web-and-design-pr-2254.run.demo.haus/
- go to releases of snap with multiple build sets (like surl)
- choose Launchpad from 'Available' revisions
- only revisions from one build set should be automatically selected

Select automatically only revisions from same build set

---

static/js/publisher/release/releasesController.js

Fixes #2260 
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2261.run.demo.haus/
- go to release UI of any snap you own
- have a channel to close (or release something to a channel) in latest track
- mark channel to be closed
- click apply
- closed channel should be updated to empty without reloading the page

Fix closing channels in latest track

---

static/js/publisher/release/components/dnd.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/releasesTableRow.js
static/js/publisher/release/components/revisionsListRow.js

Updates release UI drag'n'drop functionality for better handling of build sets.
- removes different drag types implementations - anything being dragged is treated as set of revisions (revision, build set or channel)
- removes single cells as drop targets, making it possible to drop everything on channel level (it will end up in correct architecture anyway)
- during dragging highlights all architectures that will be affected by the drop in given channel
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2262.run.demo.haus/
- go to releases page of any snap (ideally with some revisions build in Launchpad)
- try promoting a single revision to some channel (from releases table)
- try promoting single revision to some channel (from revisions history of any channel)
- try promoting a …

Drag'n'drop updates for revision attributes support

---

static/js/publisher/release/components/dnd.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/releasesTableRow.js
static/js/publisher/release/components/revisionsListRow.js
static/sass/_snapcraft_release.scss

Fixes #2270 
As discussed in Paris we remove some of the special treatment of build sets.
- removed LP icons from cells and rows
- removed dragging whole build set together (with hover effect)
- fixes some regression issues around drag'n'drop
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2272.run.demo.haus/
- go to releases page of any snap with Lauchpad builds
- there should be no icons in rows or cells with LP revisions
- there should be icons in tooltips for LP revisions
- hovering over LP revision should not hover all builds from same revision
- dragging revision from build set should promote only single revision, not whole build set
For a regression of previous functionality make sure:
- everything (channel row, single revision, revision from the history) can be dragged …

Revision attributes cleanup

---

.circleci/config.yml
.env
templates/_layout-brandstore.html
templates/_layout.html
tests/api/test_marketo_api.py
webapp/api/marketo.py
webapp/config.py
webapp/configs/snapcraft.py
webapp/handlers.py

- Remove MARKETO_URL by hard-coding it into marketo.py
- Explicitly require MARKETO_CLIENT_ID and MARKETO_CLIENT_SECRET - as in don't use fake fallbacks
- Since SENTRY_DSN will be a public key anyway (I went and changed this in the k8s secrets), there's no need for SENTRY_PUBLIC_DSN
- Remove mentions of BLOG_ENABLED, which hasn't been used since #879
- Remove mentions of BLOG_CATEGORIES_ENABLED, which hasn't been used since #2119
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2265
Also see ^ for more explanation
QA
--
`./run`, check the site works. Especially check the publisher details page loads fine.

Simplify environment variables

---

requirements.txt

This makes snapcraft.io work with newer-format SENTRY_DSN keys.
QA
--
Check tests pass.
Then try running the site with:
``` bash
./run --env SENTRY_DSN=https://1e82fd54e08142c9978f623cb746b965@sentry.is.canonical.com//3
```

Update raven and talisker

---

static/js/publisher/release/components/releasesTable.js
static/js/publisher/release/components/releasesTableCell.js
static/js/publisher/release/components/releasesTableChannelCell.js
static/js/publisher/release/components/releasesTableRow.js
static/js/publisher/release/constants.js

Refactors release table components to make it possible to add custom rows for build sets.
- everything should work as before (try drag and drop, promote some things, etc)
- go to releases page of any snap with lauchpad builds
- list of all builds from lauchpad should be rendered as rows below the table
- whole rows and individual revisions should be draggable
- contextual menu of build rows should work as expected
- there should be no history icon on the build revisions

Release UI: release table row component refactor

---

templates/_layout-brandstore.html
templates/_layout-embedded.html
templates/_layout.html

Fixes #2286 
Move things around in head to make sure scripts are not blocked by CSS loading.
- make sure pages load correctly
- make sure google tag manager is not waiting for CSS to start downloading

Improve order of tags in head

---

static/js/base/dropdown-menu-toggle.js
templates/_layout-brandstore.html
templates/_layout-embedded.html
templates/_layout.html
templates/blog/article.html
templates/blog/index.html
templates/brand-store/search.html
templates/brand-store/store.html
templates/docs/base.html
templates/first-snap/_layout_fsf.html
templates/first-snap/install-snapcraft.html
templates/first-snap/language.html
templates/first-snap/package.html
templates/first-snap/push.html
templates/index.html
templates/publisher/account-details.html
templates/publisher/account-snaps.html
templates/publisher/developer_programme_agreement.html
templates/publisher/listing.html
templates/publisher/metrics.html
templates/publisher/publicise/embedded_cards.html
templates/publisher/publicise/github_badges.html
templates/publisher/publicise/store_buttons.html
templates/publisher/release-history.html
templates/publisher/settings.html
templates/store/publisher-details.html
templates/store/search.html
templates/store/snap-details.html
templates/store/snap-distro-install.html
templates/store/store.html

Follow up to #2292 (merge that one first)
Fixes #2287 
Moves loading scripts (public.js publisher.js, etc) from the bottom of the body to head.
- make sure scripts are loaded early
- make sure pages still work, there are no errors in console (check EVERYTHING!)

Move scripts loading from bottom of the page to `<head>`

---

templates/store/store.html

Fixes #2290 
Postpones loading of additional categories to page load event
- go to /store page
- categories should load as expected, but performance metrics should improve (as page load should not wait for categories now)

Load categories after page load instead of DOM ready

---

templates/store/_category-partial.html
tests/store/tests_search.py
webapp/configs/snapcraft.py
webapp/store/views.py

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2285
- `./run`
- Visit https://0.0.0.0:8004/store
- The featured section should have a banner
- All other sections aside from "Art and design" should have the generated banner
- Click on the banner should go to the snap being promoted
- Clicking on "See more..." should show a category page (including the banner again)

Make banners live

---

static/js/publisher/release/components/availableRevisionsMenu.js
static/js/publisher/release/components/releasesTable/index.js
static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js

Hides Launchpad related UI from Release page, so we can merge the feature branch without enabling it yet.
Build request id is going to be shown in revision tooltips and history (when available).
This PR is agains feature branch (for easier code review), but is meant as means to make feature branch tested and merged to master.
- go to releases page of snap with launchpad builds
- make sure Launchpad is not available in "Available" dropdown
- click around, see if everything works
- if history of any release cell doesn't have revisions with build id, "Build request" column should not be shown

Release UI - hide launchpad

---

requirements.txt
templates/_layout.html
templates/index.html
templates/partials/_snap-screenshot.html
templates/store/_generated-featured-snap-partial.html
templates/store/_media-object-snap-partial.html
templates/store/snap-details/_snap_heading_data.html
templates/store/snap-distro-install.html
templates/store/snap-embedded-card.html
templates/store/store.html
webapp/store/logic.py

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2306
This also adds conditional image-template usage on snap details pages.
Older screenshots don't have an image and width set in the store - this means we need 3 branches:
- gif: for gifs
- set sizes: we can infer the properties needed for the image-template
- no sizes: we can't use the image-template as the image could be one of multiple ratios and the module requires both width and height (this can be removed when [this issue](https://bugs.launchpad.net/snapstore/+bug/1818065) is closed)
- `./run`
- Visit http://0.0.0.0:8004/skype
- should be the same markup as before - no image template
- Visit http://0.0.0.0:8004/sayonara-player-unofficial
- should have the image template markup
- Ensure the …

Update to image-template v1.0.0

---

static/sass/_snapcraft_p-code-copyable.scss
templates/partials/_code-snippet-multi.html
templates/store/snap-details/_distro-instructions-for-snap-support.html
webapp/store/content/distros/rhel.yaml

Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1133
Adds Red Hat Enterprise Linux distro page.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2314.run.demo.haus/
- go to /install/SNAP/rhel of any snap https://snapcraft-io-canonical-web-and-design-pr-2314.run.demo.haus/install/lxd/rhel
- try different snaps
- check if everything renders well
- check if install instructions are correct (https://snapcraft.io/docs/installing-snap-on-red-hat)
- go to any snap details page, check in distros list in the bottom includes Red Hat
- click on a link, make sure it goes to RHEL distro page

RHEL distro page

---

static/js/libs/channels.js
static/js/publisher/release/components/devmodeRevision.js
static/js/publisher/release/components/progressiveBar.js
static/js/publisher/release/components/releasesTable/cellViews.js
static/js/publisher/release/components/releasesTable/releaseCell.js
static/js/publisher/release/components/revisionLabel.js
static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/js/publisher/release/helpers.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js
static/sass/_snapcraft_p-progressive-bar.scss
static/sass/_snapcraft_release.scss
static/sass/styles.scss

Supersedes(partially) https://github.com/canonical-web-and-design/snapcraft.io/pull/2259
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2240
- `./run`
- Visit http://0.0.0.0:8004/snap/releases for a snap with a progressive release
- Click around and make sure things look ok.
This is just the viewing of a progressive release.
Cell, history closed
History open

View progressive releases

---

static/js/publisher/release/actions/releases.js
static/js/publisher/release/actions/releases.test.js
static/js/publisher/release/api/releases.js

Add progressive info to releases API calls
- it's not used anywhere, so just code review needed if it applies to current API

Add progressive releases to API calls

---

static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/js/publisher/release/reducers/options.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js
templates/publisher/release-history.html

In preparation for enabling progressive releases via feature flag this PR adds a hardcoded feature flag for the UI.
Enabled:
- go to releases page of any snap with progressive releases
- make sure progressive releases work as before (can be viewed)
Disabled: 
- locally disable feature flag (turn it to false in `release-history.html` template)
- ./run
- go to releases page of any snap with or without progressive releases
- make sure any progressive release stuff doesn't show up in the table or history

Add progressive release feature flag support

---

static/js/publisher/release/actions/pendingReleases.js
static/js/publisher/release/actions/pendingReleases.test.js
static/js/publisher/release/components/progressiveConfirm.js
static/js/publisher/release/components/releasesConfirm.js
static/js/publisher/release/reducers/pendingReleases.js
static/js/publisher/release/reducers/pendingReleases.test.js
static/sass/_snapcraft_release.scss

Fixes #2239 
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2327.run.demo.haus/
- go to releases page of any snap you own
- prepare release of any revisions on top of other revisions
- next to apply button there should be a component allowing to change the % of affected devices
- if 100% is chosen standard full release should happen when "Apply" is clicked
- if % smaller than 100% is chosen a progressive release should happen when "Apply" is clicked
- if invalid number is entered "Apply" should not be disabled
- when there is no pending releases (only pending closes) the % input should not show up
- when release to some % is made or canceled, next time release is pending % input should reset to 100%

Progressive release apply

---

static/js/publisher/release/components/releasesConfirm.js
static/js/publisher/release/releasesController.js
static/sass/_snapcraft_release.scss
templates/publisher/release-history.html

As a preparation to making releases confirm sticky and possibly with an accordion with changes, this PR makes the releases confirm bar always visible and consistent with other forms in publisher pages.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2330.run.demo.haus/
- go to releases page
- Save/Revert bar should be always visible and should have styling similar to Listing/Settings page
- Button labels and order should be consistent as well (Revert+Save instead of Apply+Cancel)
- when releases or closes are pending the bar should update as before, showing a summary of changes with tooltips, making buttons enabled, etc
- it should still work (releasing/closing should work as before)

Make releases confirm always visible and consistent with other forms

---

tests/store/tests_details.py
tests/store/tests_distro_page.py
tests/store/tests_embedded_card.py
tests/store/tests_github_badge.py
webapp/api/store.py
webapp/store/snap_details_views.py

Fixes #2323 
- check if GH badge is working as before: https://snapcraft-io-canonical-web-and-design-pr-2331.run.demo.haus/toto/badge.svg
- check if name can be removed from a badge: https://snapcraft-io-canonical-web-and-design-pr-2331.run.demo.haus/speed-test/badge.svg?name=0
- check if trending badge works for trending snap: https://snapcraft-io-canonical-web-and-design-pr-2331.run.demo.haus/kdenlive/trending.svg
- check if trending badge works without the name: https://snapcraft-io-canonical-web-and-design-pr-2331.run.demo.haus/kdenlive/trending.svg?name=0
- check if trending barge is empty image when snap is not trending
https://snapcraft-io-canonical-web-and-design-pr-2331.run.demo.haus/toto/trending.svg
Examples:
/badge.svg
/badge.svg?name=0
/trending.svg (not …

Trending GitHub badge

---

templates/store/_category-partial.html
tests/store/tests_get_store_view.py
webapp/store/views.py

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2334
- Add `featured_snaps = []` to `webapp/store/views.py:79`
- `./run`
- Visit http://0.0.0.0:8004/store - you should receive an error page

Show a message if no snaps are returned on store

---

static/sass/_patterns_carousel.scss
templates/partials/_snap-screenshot.html

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2333
- `./run`
- Visit http://0.0.0.0:8004/remarkable
- Compare the screenshot sizing with https://snapcraft.io/remarkable

Improve screenshot sizes on snap details
