static/js/publisher/publicise.js
static/sass/_snapcraft_p-code-copyable.scss
templates/publisher/publicise/github_badges.html
tests/publisher/snaps/tests_publicise_badges.py
tests/store/tests_github_badge.py
webapp/publisher/snaps/views.py
webapp/store/snap_details_views.py

Fixes #2324 
Adds option to add trending badge on publicise page
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2332.run.demo.haus/
- go to publicise page of any snap (not trending)
- choose GitHub badge, an option to show trending badge should be available
- click to choose trending badge
- preview should show trending badge with a warning message that this is just a preview (because snap is not trending)
- code should update to include additional trending badge
- using the code in external service should not show the trending badge (as snap is not trending)
- go to publicise page of trending snap https://snapcraft-io-canonical-web-and-design-pr-2332.run.demo.haus/kdenlive/publicise/badges
- trending badge should be checked (visible) by default (only if snap is currently …

Add trending badge option to publicise page

---

static/sass/_snapcraft_release.scss

Fix width of releases cells in branch rows.
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2337.run.demo.haus/
- go to releases page of snap with branches (and not many architectures)
- open branches
- cells should align
- try different screen widths

Fix branch cells widths

---

static/sass/_snapcraft_details_heading.scss

Fixes #2338
Updates the width of channel map popover to make sure it adapts to increased font size on largest screens
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2340.run.demo.haus/
- go to /gnome-chess on large screen
- open channel map
- date should fit without truncating
- open channel map on smaller screens as well to see if everything fits

Make channel map window width adapt to font size on large screens

---

static/js/publisher/release/components/releasesTable/releaseCell.js

Fixes #2348
Hides bar with progressive percentage in releases table when channel has pending close
- go to releases page of snap with progressive releases
- mark channel with progressive release in progress as closed
- bar with percentage on the bottom of the cell should not be visible when channel has pending close

Don't show progressive percentage on pending channel close

---

static/js/publisher/release/actions/pendingReleases.js
static/js/publisher/release/reducers/pendingReleases.js
static/js/publisher/release/reducers/pendingReleases.test.js

Fixes #2346 
- make sure everything works as before (around releasing progressive releases and not allowing progressive releases when there is no revision already released)

Change `canBeProgressive` into `previousRevisions`

---

requirements.txt

Update canonicalwebteam.blog to 4.0.2 to fix an issue with the blog feeds
https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/128
- Check out this feature branch
- Run the site using the command `./run clean && ./run serve`
- Ensure that http://0.0.0.0:8004/blog/feed/ works
https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/127

Fix feed issue with articles without category

---

requirements.txt
templates/publisher/_header.html
templates/publisher/build-list.html
webapp/api/launchpad.py
webapp/publisher/snaps/views.py

Fetches snap builds from launchpad, based on the snap's store name.
Passes the builds to the template under `snap_builds` and the build repository under `snap_builds_git`.
TBD
Fixes #2356

Fetch snap builds from launchpad

---

static/js/publisher/release/actions/releases.js
static/js/publisher/release/actions/releases.test.js
static/js/publisher/release/api/releases.js
static/js/publisher/release/components/progressiveBar.js
static/js/publisher/release/components/revisionsListRowProgressive.js
static/js/publisher/release/reducers/pendingReleases.js
static/js/publisher/release/selectors/index.js

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2343
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2362
- `./run`
- Progressively release a revision
- Once released, slide the progressive percentage bar
- Revert the changes
- The progressive release bar should reset to its previous value

Update progressiveBar target % when props change

---

static/js/publisher/release/components/revisionsList.js

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2363
- `./run`
- Do some releases, click around, make sure there is enough space for the "Release date" column of the history table.

Let the release date breath

---

static/js/publisher/builds/index.js
static/sass/_snapcraft_builds.scss
static/sass/styles.scss

Fixes #2347
- go to builds page of any snap with some builds
- status message should show with relevant color
- there should be a build date in the table

Add build status colors and build date

---

static/js/publisher/release/components/releasesTable/cellViews.js
static/js/publisher/release/components/releasesTable/releaseCell.js
static/sass/_snapcraft_release.scss

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2350
- `./run`
- Progressively release a revision (if one does not already exist)
- Save
- Update the progressive release:
- any action should cause the cell to be highlighted
- updating the percentage should show the target percentage when history is closed

Show pending progressive updates

---

webapp/publisher/snaps/views.py

Pass a `snap_builds_enabled` key in context so we can display
the appropriate messagin in the frontend
Go to the builds tab and make sure it still lists builds properly.

Add `snap_builds_enabled` key to context

---

static/sass/_snapcraft_p-docs.scss

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2384
- `./run`
- Visit http://0.0.0.0:8004/docs/remote-build
- Make sure the images look better than in the bug report

Hide discourse docs lightbox

---

templates/store/_category-partial.html

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2382
This will increase the page size slightly, but it's worth it for quality looking images, imo. We ask publishers to upload higher res images, then we compress them!
- `./run`
- At 1x dpi ensure the 0ad banner under the "Games" heading is nice and sharp

Don't resize banners - they should look good

---

static/js/libs/arrays.js
static/js/libs/arrays.test.js
templates/publisher/listing.html
webapp/publisher/snaps/views.py

Fixes #1776 
- `./run`
- Visit http://0.0.0.0:8004/snap_name/listing (the snap should have at least one category set)
- Change anything on listing page (add something to title)
- Save/Revert button should get enabled
- Without saving anything remove the change done before (change the title back)
- Save/Revert button should get disabled (there are no changes to save)

1776 save/revert are not disabled for snap with categories

---

templates/first-snap/_breadcrumb.html

Fixes #1298 
- `./run`
- Visit http://0.0.0.0:8004/first-snap/python/macos/build and see "Publish to store" step is clickable

Make snap test step skip-able from build snap step when on macos

---

static/js/public/formValidation.js
static/js/public/public.js
templates/blog/article.html

Add bot verification to articles on /blog
Fixes #2336 
- View the site locally in your web browser at: http://0.0.0.0:8004/blog/management-of-snaps-in-a-controlled-enterprise-environment
- Inspect the form and find the `<input id="grecaptcharesponse" type="hidden" value="noBot">` and notice there is no `value` filed at the begining and it is added after some time (3 seconds)

Add spam validation for blog whitepapers

---

static/js/public/first-snap-flow.js
templates/first-snap/push.html

- Make `Register snap name` button enabled when loading the page
Fixes #2399 
- Create a new snap
- When you get to the `Publish to store` step, note the `Register snap name` button is enabled, and if you edit snap name a warning message appears

Enable register snap name button initially

---

requirements.txt
templates/_layout-brandstore.html
templates/store/snap-details.html
tests/store/tests_details.py
tests/store/tests_distro_page.py
tests/store/tests_embedded_card.py
tests/store/tests_github_badge.py
webapp/store/snap_details_views.py

Add noindex to unlisted snaps pages
Fixes #2396 
- View the site locally in your web browser at: http://0.0.0.0:8004/core
- Inspect the page make make sure there is no `<meta name="robots" content="noindex" />` in the metadata
- Visit the details page for a snap that is `unlisted` and inspect the page. See that `<meta name="robots" content="noindex" />` is in the metadata.

Add noindex to unlisted snaps pages

---

webapp/markdown.py

Add support for parenthesis inside URLs when we are parsing markdown.
Fixes #2424
* The [issue is present in the markdown library we are using](https://github.com/lepture/mistune/issues/46)
- Check that all the links are displayed correctly here: http://0.0.0.0:8004/toto-fran

Fix markdown issue with URLs

---

templates/store/snap-details.html

- Add 3rd party store links to: `/vlc`, `/standard-notes`, `/plexmediaserver`
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1186
- View the site locally in your web browser at: http://0.0.0.0:8004/snap_name
- Make sure you see the 3rd party app store buttons on `/vlc`, `/standard-notes`, `/plexmediaserver` and not other snap details pages
- https://snapcraft-io-canonical-web-and-design-pr-2434.run.demo.haus/vlc
- https://snapcraft-io-canonical-web-and-design-pr-2434.run.demo.haus/standard-notes
- https://snapcraft-io-canonical-web-and-design-pr-2434.run.demo.haus/plexmediaserver

Add 3rd party store links

---

webapp/store/logic.py

- Added new `format_category_name` method
Fixes #1594 
Fixes #1593
- View the site locally in your web browser at: http://0.0.0.0:8004
- Visit http://0.0.0.0:8004/store compare category names to https://snapcraft.io/store
- Visit http://0.0.0.0:8004/snap_name/listing - the categories dropdown should have the same formatting

Title case categories

---

static/sass/_snapcraft_details_heading.scss
static/sass/_utilities_text-wrap.scss
static/sass/styles.scss
templates/store/snap-details.html

- Make snap title wrap on mobile
Fixes #1999 
- View the site locally in your web browser at: http://0.0.0.0:8004/gimp
- See the page loads correctly and the snap name is wrapped

Make snap title wrap

---

static/js/publisher/form.js

- If there's a global error offset the scroll by the height of the sticky header
Fixes #2436 
- Visit http://0.0.0.0:8004/snap_name/listing try and upload the gif referenced in the connected issue.
- Clicking Save should show an error above the form, but below the sticky header

Ensure global errors are visible on form submission

---

static/js/public/public.js
static/js/public/snap-details/exapandable-distr-chart.js
static/sass/_snapcraft_distro-chart.scss
templates/store/snap-details.html

- Make distro list expandable on `snap details` page
Fixes #2000 
- View the site locally in your web browser at: http://0.0.0.0:8004/spotify or any other snap
- Scroll down to the distro list and click the `Show more` button
- See the list is expanded
- For design check compare to [this comment](https://github.com/canonical-web-and-design/snapcraft.io/issues/2000#event-2950599628)

Make distro list expandable on snap details page

---

static/sass/_snapcraft_p-table-mobile-card.scss
static/sass/styles.scss
templates/publisher/account-snaps.html

- Make the table on `/snaps` mobile friendly
Fixes #2458
- View the site locally in your web browser at: http://0.0.0.0:8004/snaps
- Change the view to mobile and see the table looks better

Make the table on /snaps mobile friendly

---

static/js/publisher/release/components/releasesConfirm.js
static/js/publisher/release/components/releasesConfirmActions.js

- Moved revert and save buttons to own component
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2386
- Use the release UI and make sure the revert and save buttons work as expected:
- disabled when no changes
- active when changes
- revert resets the releases state
- save saves the new releases state

Move confirm buttons to own component

---

tests/store/tests_search.py
webapp/store/views.py

- "Last >>" button link fixed to take you to the last page if you are on the first page 
Fixes #2453 
- View the site locally in your web browser at: http://0.0.0.0:8004/search?category=games&page=1
- Click on the "Last >>" link and see that you are taken to page 6

Use the correct last page link

---

static/js/publisher/release/helpers.js
static/js/publisher/release/helpers.test.js
static/js/publisher/release/reducers/pendingReleases.js
static/js/publisher/release/selectors/index.js

- Moved `JSON.parse(JSON.stringify(arg))` to helper called `jsonClone`
Fixes #2400 
- Ensure tests pass and release UI works as before

Clone helper

---

static/js/publisher/release/components/progressiveBar.js
static/sass/_snapcraft_p-progressive-bar.scss

- Added `is-full` state to bars when percentage is 100%
- Lighten and greyscale bars when `is-disabled`
Fixes #2393 
Fixes #2398 
- Play with the progressive releases/ normal releases - see that the progressive bars are different in the different states

Progressive bar styling - rounded at 100% and greyscale when disabled

---

.gitignore
webapp/api/github.py
webapp/api/launchpad.py
webapp/login/oauth_views.py
webapp/publisher/snaps/builds.py
webapp/publisher/snaps/views.py
yarn.lock

- Replace launchpadlib
- Launchpad API request to create a new Snap
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2421
**Ask @jkfran for the needed environment variables**
- Login as a publisher
- Go to http://0.0.0.0:8004/<your_snap>/builds and check to you can:
- Login with GitHub, select and save
- Check that the repo is now always displayed in the GitHub configuration section

Register GitHub repo with Snap via the Launchpad API

---

templates/_footer.html
webapp/handlers.py

Make year in the footer dynamic
Fixes #2474 
- See the year in the footer is 2020

Make year in the footer dynamic

---

static/js/publisher/release/components/releasesConfirm.js
static/sass/_snapcraft_release.scss

- Open details below the button row
Fixes #2403 
- Visit http://0.0.0.0:8004/snap_name/releaes
- Make some changes and see that the details opens below the buttons

Move the release details below the button row

---

static/sass/styles.scss

Add more vertical spacing for "companion apps" section on `/snap_name`
Fixes #2480 
- View the site locally in your web browser at: http://0.0.0.0:8004/vlc
- Note there is more spacing between the "Last updated" date and "Companion apps"

Add more vertical spacing for companion apps section

---

static/js/publisher/release/components/releasesConfirmDetails/index.js
static/js/publisher/release/components/releasesConfirmDetails/releaseRow.js
templates/publisher/release-history.html
webapp/handlers.py

- Ensure the new details section doesn't reference progressive releases when flag is disabled
- Pass through whether the user is a memeber of canonical on login
Fixes #2450
- If you're part of the canonical group on launchpad you should be able to see progressive releases
- If not, you can't
- You can manually disable the flag in the `releases-history.html` template

Ensure progressive releases are hidden when flag is disabled

---

static/js/base/ga.js
static/js/publisher/release/actions/gaEventTracking.js
static/js/publisher/release/actions/gaEventTracking.test.js
static/js/publisher/release/actions/history.js
static/js/publisher/release/actions/history.test.js
static/js/publisher/release/actions/pendingReleases.js
static/js/publisher/release/actions/pendingReleases.test.js
static/js/publisher/release/components/channelMenu.js
static/js/publisher/release/components/releasesConfirm.js
static/js/publisher/release/components/releasesTable/channelHeading.js
static/js/publisher/release/components/releasesTable/droppableRow.js
static/js/publisher/release/components/releasesTable/releaseCell.js
static/sass/_snapcraft-publisher.scss
static/sass/_snapcraft_p-docs.scss

- Add GA event tracking to release-ui
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1225
- Compare to [events scheme](https://github.com/canonical-web-and-design/snap-squad/issues/1224)
- I think the best way to test what info is sent to Google is to run the branch locally and edit `ga.js` by adding a `console.log("EventAction: " + action + "\nEventLabel:" + label);` on line 36

Add GA event tracking to release-ui

---

static/js/publisher/release/actions/pendingReleases.js

- Set new releases that can be progressive to the percentage of the previously set release that can be progressive
Fixes #1236
- Stage a new progressive release (with a not-100% percentage)
- Stage more progressive releases
- All the table cells below should maintain the bar across the same percentage of the cell

Ensure progressive values align

---

static/js/publisher/market/restrictions.js

- Remove whitelist in media restrictions
- Adding an image to the media section that is called "banner.jpg" that is exactly 1218 x 240 you should receive an error from the client (before submitting the form).

remove legacy banner whitelisting

---

static/sass/_snapcraft_p-build.scss
templates/publisher/builds.html

- Build unauthorised page on `/{snap_name}/builds`
Fixes #2483 
- View the site locally in your web browser at: http://0.0.0.0:8004/{snap_name}/builds
- Compare to [design](https://github.com/canonical-web-and-design/snapcraft.io/issues/2483)
- Click `Log in` button and check the content of the page was changed
- To revoke GitHub token after you finished go to https://github.com/settings/applications

2483 build unauthorised page with build info

---

requirements.txt
tests/api/cassettes/GitHubAPITest.test_get_user_repositories.yaml
tests/api/cassettes/GitHubAPITest.test_get_username.yaml
tests/api/cassettes/GitHubAPITest.test_is_snapcraft_yaml_present.yaml
tests/api/test_github.py
webapp/api/github.py
webapp/authentication.py
webapp/login/views.py
webapp/publisher/github/views.py
webapp/publisher/snaps/views.py

In this PR we are using the GitHub GraphQL API to:
- List all the user repositories and mark the ones with a snapcraft.yaml present:
- Show an error on the builds page when the selected repo for the snap doesnt contain a snapcraft.yaml:
Fixes #2449
- Login as a publisher
- Go to http://0.0.0.0:8004/<your_snap>/builds and check to you can:
- Login with GitHub
- Try to link you snap with a github repo and check that the repos contains a mark when snapcraft.yaml is present
- Check if a snap with a github repo without snapcraft.yaml get the error

Check if snapcraft.yaml is present

---

templates/publisher/builds.html
tests/api/cassettes/GitHubAPITest.test_get_org_repositories.yaml
tests/api/cassettes/GitHubAPITest.test_get_orgs.yaml
tests/api/cassettes/GitHubAPITest.test_get_user.yaml
tests/api/cassettes/GitHubAPITest.test_get_user_repositories.yaml
tests/api/cassettes/GitHubAPITest.test_is_snapcraft_yaml_present.yaml
tests/api/test_github.py
webapp/api/github.py
webapp/app.py
webapp/login/oauth_views.py
webapp/publisher/github/views.py
webapp/publisher/snaps/views.py

- Added route "/publisher/github/get-repos" that return a json
- List of GitHub Orgs passed to the template
Fixes #2486 
- Go to /<snap_name>/builds and login with github
- Now you should be able to see an HTML select with all your GitHub organizations
- Check that http://0.0.0.0:8004/publisher/github/get-repos return a JSON with all your repos
- Check that http://0.0.0.0:8004/publisher/github/get-repos?org=canonical-web-and-design return a JSON with the Canonical repos.

Get GitHub repos filtered by org

---

requirements.txt
webapp/docs/views.py

Upgrade to latest version of discourse docs module
- View the site locally in your web browser at: http://0.0.0.0:8004/docs
-  plya around with docs and make sure it workiworks

Upgrade to latest version of discourse docs

---

static/sass/_snapcraft_tour.scss

- Increase tour background transparency
Fixes #2311 
- View the site locally in your web browser at: http://0.0.0.0:8004/[snap_name]/listing
- Click on the tour button and note the background is not as dark anymore

Increase tour background transparency

---

tests/api/cassettes/GitHubAPITest.test_get_snapcraft_yaml_location.yaml
tests/api/test_github.py
webapp/api/github.py
webapp/publisher/snaps/build_views.py
webapp/publisher/snaps/views.py

Added an endpoint that return the status of a GitHub repo
Fixes #1240
- Ask Fran for the .env.local file
- Login as a publisher and check that this endpoint is working:
http://0.0.0.0:8004/<snap_name>/builds/validate-repo?repo=github_owner/repo_name
Like:
http://0.0.0.0:8004/toto-fran/builds/validate-repo?repo=jkfran/toto-fran

Validate individual GitHub repos

---

static/js/publisher/tour.js

- Improved the type when checking if tour has already been closed
Turns out this should already be working
Fixes #2495
- Go to a snap listing page that doesn't have over 50% of the fields completed
- The tour should appear
- Skip the tour
- Go back to that pages
- The tour should not appear

Make sure to test for bool

---

templates/publisher/_header.html
tests/publisher/snaps/tests_get_metrics.py
tests/publisher/snaps/tests_post_settings.py
tests/publisher/snaps/tests_publicise.py
tests/publisher/snaps/tests_publicise_badges.py
tests/publisher/snaps/tests_publicise_cards.py
tests/publisher/snaps/tests_revision.py
tests/publisher/snaps/tests_settings.py
webapp/publisher/snaps/views.py

Ensure the header for different publisher snap pages show's the snap title, not the snap name.
Also if you're a collaborator include who owns the snap.
Fixes #2538 
- Login, view some snaps - see that the name is consistent.
- Look at some snaps you're a collaborator for and see the different names

Consistent publisher headers.

---

tests/publisher/snaps/tests_get_metrics.py
webapp/publisher/snaps/views.py

- Get latest days metrics to display as the Weekly active devices total
Fixes #2506
- Visit the metrics page for a snap
- View last 7 days and 2 years
- The number in the heading above the graph should be the same

Always get total active devices from most recent 24 hours

---

static/js/public/first-snap-flow.js
templates/first-snap/push.html

- Expand next accordion when clicking register snap name and no errors
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1038
- View the site locally in your web browser at: http://0.0.0.0:8004/first-snap/python/linux/push
- Click on `Register snap name` and see the next accordion panel is expanded automatically.

FSF expand next accordion when clicking register snap name

---

webapp/api/github.py
webapp/api/launchpad.py
webapp/publisher/snaps/build_views.py
webapp/publisher/snaps/views.py

Create an endpoint for GitHub webhooks
Fixes #2522 
- Ask me for the needed environment variables
- Run:
```
curl -H "Content-Type: application/json" -H "X-Hub-Signature: sha1=27a4e453d0dc47fadc33efdf1d8b8fa7942f5f49" -X POST -d '{"repository":{"url": "https://github.com/jkfran/test-snap-fran", "name": "test-snap-fran", "owner": {"login": "jkfran"}}}' http://0.0.0.0:8004/test-snap-fran/webhook/notify
```
- That should trigger builds for that snap:
http://0.0.0.0:8004/test-snap-fran/builds/

Add GitHub Webhook endpoint

---

templates/partials/_video.html

* Changed youtube embed code to specify ?rel=0 - to only show videos from the same publisher
Fixes #2553 

Add &rel=0 to youtube embed code

---

templates/partials/search-bar.html

Drops the placeholder text from the Snap Store search field.
Text field placeholders have many problems with visibitility, interaction, and accessibility: see [Adam Silver’s list](https://adamsilver.io/articles/placeholders-are-problematic/) for example.
In this case the placeholder is gratuitously unnecessary: It says “Search thousands of snaps” when those exact words are already printed in 35.65px font immediately above. And there’s a “Search” button alongside to boot.
(In a brand store, the field apparently says “Search available snaps” instead … as opposed to what? Searching unavailable ones? If it’s important to explain that some snaps won’t be findable, then spell it out separately.)
None
- View the page locally at: …

Drops redundant placeholder from search field

---

static/js/public/first-snap-flow.js
templates/first-snap/push.html
templates/publisher/_header.html
templates/publisher/account-snaps.html
templates/publisher/listing.html
tests/publisher/snaps/tests_listing.py
webapp/publisher/snaps/views.py

- Update `Go to listing` button link depending if the snap is published or not
- Replace `is--disabled` class with `is-disabled` (it seems it was missed when [we upgraded to vanilla v2.0.1](https://github.com/canonical-web-and-design/vanilla-framework/pull/2320))
Fixes #2533 
- View the site locally in your web browser at: http://0.0.0.0:8004//first-snap/python/linux/push
1. Click `Register snap name`
2. See the 'Go to listing` button is enabled. Click it
3. See you are taken to the listing page. Note the message at the top
4. Go back to http://0.0.0.0:8004//first-snap/python/linux/push and click `Register snap name` …

Remove "Go to listing" button

---

webapp/api/marketo.py
webapp/publisher/views.py

- Fix marketo response index error
Fixes #2276 
Error on sentry: https://sentry.is.canonical.com/canonical/snapcraft-io/issues/2776/
- View the site locally in your web browser at: http://0.0.0.0:8004/account/details
- I don't know how to QA this.

Fix marketo response index error

---

static/sass/_patterns_annotated_code.scss
templates/first-snap/build.html
templates/first-snap/install-snapcraft.html
templates/first-snap/package.html
templates/first-snap/push.html
webapp/first_snap/content/c/build.yaml
webapp/first_snap/content/golang/build.yaml
webapp/first_snap/content/golang/snapcraft.yaml
webapp/first_snap/content/java/build.yaml
webapp/first_snap/content/moos/build.yaml
webapp/first_snap/content/node/build.yaml
webapp/first_snap/content/node/snapcraft.yaml
webapp/first_snap/content/pre-built/build.yaml
webapp/first_snap/content/python/build.yaml
webapp/first_snap/content/python/snapcraft.yaml
webapp/first_snap/content/ros/build.yaml
webapp/first_snap/content/ros2/build.yaml
webapp/first_snap/content/ruby/build.yaml
webapp/first_snap/content/rust/build.yaml
webapp/first_snap/content/rust/snapcraft.yaml

- Remove `clone` step from `Package snap`
- Update `Build snap` steps
- Fix `Next step` buttons to be centred on mobile
- Add `version: 1.0` to the yaml files that had `version: git`
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1039
- Go to http://0.0.0.0:8004/first-snap/python/macos/package and compare to [design](https://app.zeplin.io/project/5ca61ca69972713e007a03c2/screen/5d124e3089704a716c8fba9b)
- Go to http://0.0.0.0:8004/first-snap/golang/linux/build and compare to …

FSF - Remove clone step

---

templates/publisher/builds.html

Remove email subscription functionality
- View the site locally in your web browser at: http://0.0.0.0:8004/[snap-name]/builds
- See the email input and button are no more

Remove email subscription functionality

---

package.json

Added `start` script in our package.json so we can use `$ dotrun` to start the project
- Install dotrun snap
- Run: `dotrun` in the project folder

Add start script in packages.json for dotrun

---

webapp/api/github.py
webapp/publisher/snaps/build_views.py

Fixed an issue with the signature for GitHub webhooks
Fixes #2578
- Install ngrok - [snap](https://snapcraft.io/ngrok)
- Run `ngrok http 8004` and copy the generated URL
- Go to repo of a snap and modify the webhook URL to use the ngrok one, like:
`https://8ba32eb9.ngrok.io/testfran123/webhook/notify`
- A new build for the snap should happen

Fix GitHub signature issue

---

webapp/publisher/snaps/logic.py
webapp/publisher/snaps/views.py

Fix an issue after upgrading Flask where we get empty Files from the listing form.
Fixes #2588 
- Upload screenshots in a Snap and see that it works

Fix image upload

---

templates/_header.html

- Developer account link was going to "/account" - it's an old endpoint
Fixes #

Don't link to old endpoint

---

templates/publisher/builds.html

- When adding a repo when the page loads and you get an empty page with a notification saying that the connection was successful, but then nothing happens until you refresh - this fixes that.
Fixes #
- Add a repo to a snap, don't see a blank screen

Show something when repo is added

---

static/js/publisher/builds/helpers.js
static/js/publisher/builds/index.js
webapp/publisher/snaps/build_views.py

- The header "Duration" is specific to the build duration, so renamed at larger screen sizes to "Build duration"
- The time in the last column again is specific to the build so added a header "Build finished"
- Added a spinner icon for "In progress" and "releasing soon"
- Renamed the small screen version of the "Built, releasing soon" from "Built" to "Releasing". "Built" suggests a finished state, "Releasing" suggests something is still happening (which is is)
- Set the snap to releasing soon if the build is "in progress" but also has a "finished" time. It doesn't make sense to have a finished time if it's still in progress.
Fixes #
- Run through the following …

Builds table updates

---

webapp/markdown.py

Allow < and > symbols inside URLs
Fixes #2552
- Check http://0.0.0.0:8004/toto-fran and see that the URLs are displayed correctly

Fix URL markdown issue

---

webapp/publisher/snaps/build_views.py
webapp/publisher/views.py

Ask users to login again when macaroon-permission-required
Fixes #2617
- Difficult to replicate the production issue,  you can follow the same QA instructions: https://github.com/canonical-web-and-design/snapcraft.io/pull/2613

Ask users to login again when macaroon-permission-required

---

static/sass/_snapcraft_release.scss

- Override vanilla default of overflow: hidden; on td and th items.
Fixes #2622
- View a snap release page /<snap_name>/releases
- Open the history of a revision and hover over the date in the final column
- the tooltip should be fully visible

Ensure tooltips are visible within revision history tables

---

static/js/publisher/release/components/releasesTable/cellViews.js

- Add extra text to the tooltip for a revision if an item is either devmode or grade: devel
Fixes #2600 
- Go to /<snap_name>/releases
- If you have a snap that's grade: devel or you have a devmode revision - release it to a channel
- Once release, hovering over the revision should display a tooltip

Improve devel / devmode revision messaging

---

webapp/publisher/github/views.py

Return 401 when no authenticated on GitHub
Fixes #2625
- Go to /publisher/github/get-repos without being logged on GitHub in Snapcraft:
https://snapcraft-io-canonical-web-and-design-pr-2629.run.demo.haus/publisher/github/get-repos

Return 401 when no authenticated on GitHub

---

entrypoint

Temporarily disable gevent. We want to make sure gevent is not causing issues with the user sessions.
- We will track the effect of this change with graylog.

Temporarily disable gevent

---

templates/publisher/builds.html
webapp/publisher/snaps/build_views.py

- Show an error when someone is trying to link a repo twice.
- Hide builds table when not needed
Fixes #2638
- Register a new Snap in Snapcraft
- Try to link it with the repo of another of your snaps, you need to change the name in the snapcraft.yaml to match with the new snap to see the error.

Show error: GitHub repository is being used by another snap

---

static/js/publisher/release/components/releasesTable/cellViews.js
static/js/publisher/release/components/releasesTable/channelHeading.js
static/js/publisher/release/components/releasesTable/droppableRow.js
static/js/publisher/release/components/releasesTable/releaseCell.js
static/js/publisher/release/components/releasesTable/revisionCell.js
static/js/publisher/release/components/revisionsListRow.js
static/js/publisher/release/constants.js
static/js/publisher/release/helpers.js

- If a revision can't be released, add the reason WHY to the tooltip
- Remove the ability to drag revisions that can't be released (and the drag handle)
- In the unreleased section disable the checkbox and don't allow revisions to be dragged.
Fixes #2031 
- Visit http://0.0.0.0:8004/snap_name/releases where snap_name is the name of a snap with a blocked revision (I can share one with you if required)
- See the tooltip for the revision
- Try and stage that revision to be promoted (you shouldn't be able to)

Revision status

---

webapp/metrics/metrics.py

- Split on only the last "/" in OS names. The delimiter between NAME/VERSION
Fixes #2635 
- Visit http://0.0.0.0:8004/powershell/metrics?active-devices=os
- The page should load ok

Handle OS names with a / in them

---

static/js/public/snap-details/blog-posts.js
static/sass/_patterns_blog-post.scss
templates/partials/blog-card--minimal.html
templates/store/snap-details.html
templates/store/snap-details/_templates.html
webapp/blog/content/blog-posts.yaml
webapp/blog/views.py

- Added yaml definition of the articles
- Add logic to the details blog post fetcher
- Updated the "minimal" blog post to include an image
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1190
- Visit http://0.0.0.0:8004/ncspot, http://0.0.0.0:8004/obs-studio and http://0.0.0.0:8004/standard-notes
- See the omgubuntu blog posts
- Visit http://0.0.0.0:8004/vlc - ensure the other blog posts still work

3rd party blog posts

---

webapp/store/content/distros/debian.yaml

`snapd` isn't just available for Debian 9. It's also available for newer versions of Debian. This simple PR attempts to clarify that.

Add instructions for newer versions of Debian.

---

templates/publisher/settings.html
tests/publisher/snaps/tests_post_settings.py
tests/publisher/snaps/tests_settings.py
webapp/publisher/snaps/settings_views.py

- Add Github Webhook url to settings page for snaps - if the snap is on launchpad.
Fixes #
- Visit http://0.0.0.0:8004/snap_name/settings for a snap that is built with launchpad
- You should see a GitHub webhook url.
- Visit http://0.0.0.0:8004/snap_name/settings for a snap that is not build with launchpad
- You should not see a github webhook url

If snap is in launchpad show webhook url on settings page

---

webapp/blog/content/blog-posts.yaml

remove extra slash in blog url

---

webapp/api/github.py
webapp/publisher/snaps/build_views.py

- Remove GitHub webhook
- Try to disconnect a repo from a Snap and check that the webhook is removed when you are authenticated on GitHub

Remove GitHub webhook when disconnecting a repo

---

templates/publisher/metrics.html

- Add 5 year option to metrics page
Fixes #2641 
- Visit http://0.0.0.0:8004/snap_name/metrics?period=5y
- See 5 years of metrics

5 year metrics

---

requirements.txt
webapp/publisher/snaps/build_views.py

Fixes an issue for people who use BSI to register a repo but don't assign a name to the snap when they try to use that repo using snapcraft.io they get an error telling them that the repo is being used for another snap.
Fixes #2647
- Go to BSI and register a repo but don't register a snap name
- Now in snapcraft go to the builds tab in a snap that is not linked to a repo.
- Use the same repo that you used in BSI, everything should be fine

Fix empty store_name issue

---

webapp/api/dashboard.py
webapp/publisher/snaps/build_views.py

Check if the admin user is a Snap collaborator before allowing to link a repo.
Fixes #1291
- Go to: http://0.0.0.0:8004/testfran9/builds
- Try to link one of your repos to this snap
- You should get an error

Link repo only for Snap collaborators

---

requirements.txt

In the new version is possible to change the store API URL with environment variables.
- Create or edit your .env.local
- Add the following value:
```
```
- Use dotrun, you should see only a few snaps from the staging API.

Update Store module to 2.0.1

---

static/js/publisher/release/components/defaultTrackModifier.js
static/js/publisher/release/components/releasesHeading.js

- Uncomment the default track code
- Update your environment to use staging (see [HACKING](https://github.com/canonical-web-and-design/snapcraft.io/blob/master/HACKING.md))
- Visit a snap's release page that has multiple tracks (you may need to ask me to share one with you on staging - just send me a message with your staging email address)
- See that you can change the default track

Enable default track selection

---

static/js/public/expandable-area.js
static/sass/_snapcraft_show-more.scss
templates/store/snap-details/_distro-instructions-for-snap-support.html
templates/store/snap-distro-install.html
webapp/store/content/distros/raspbian.yaml

- Added a raspbian/ Raspberry Pi distro page based on https://snapcraft.io/docs/installing-snap-on-raspbian
Fixes #2667
- Visit http://0.0.0.0:8004/install/rpi-imager/raspbian :exploding_head: 
- See the page
- Visit http://0.0.0.0:8004/rpi-imager
- scroll to the bottom of the page
- see the raspberry pi link

Pi distro page

---

static/js/publisher/builds/components/repoConnect.js
webapp/publisher/snaps/build_views.py

- Small refactor to the way errors are handled to allow backend error messages to be surfaced when we don't want a frontend override.
Fixes #2661
- Create a snap
- Create a repo with an invalid yaml file
- Visit http://0.0.0.0:8004/snap_name/builds
- Try to add that repo
- See the error
- Ensure other errors still work (missing yaml and name mismatch)

Invalid snapcraft yaml

---

static/js/publisher/builds/repoDisconnect.js

- Fix spinner to show in FF
Fixes #2659 
- **Use Firefox please!!!**
- Make sure the snap you look at has a GitHub repo connected. Click on `Disconnect repo` and then click `Confirm`
- You should see the button being disabled and a spinner should be visible, after that you should be redirected and you snap is disconnected from your repo

Fix spinner to show in FF

---

templates/publisher/listing.html

Disable categories dropdown when API call fail
Fixes #2693 
- Use dotrun snap to start the site.
- Edit `.venv/lib/python3.6/site-packages/canonicalwebteam/store_api/store.py`.
- Add `raise StoreApiResponseError("error", 666)` in line 181
- Go to /<snap_name>/listing/ the dropdown should be disabled and you should see a temporary error message.

Disable categories dropdown when API call fail

---

webapp/publisher/snaps/build_views.py

Fix GitHub rate limit issue
Fixes #2700
- Logout if you are logged and log in again.
- As a publisher go to any snap and click in the "Builds" tab, it should be working as expected.

Fix GitHub rate limit issue

---

static/js/publisher/form/icon.js
static/js/publisher/market/restrictions.js
static/sass/_snapcraft_market.scss

- Add icon restriction info
Fixes #2680 
- Note the `Show icon restrictions` button. Click on it to check the restrictions.
- Previously you were not allowed to use an SVG file to set the icon, now you can

Add icon restriction info

---

static/sass/_snapcraft_market.scss
templates/publisher/listing.html
templates/publisher/settings.html
templates/store/snap-details.html

- Fix button spacing on mobile in the sticky header on the following pages: `/<snap_name>/listing`, `/<snap_name>/settings` and `/<snap_name>/preview`
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/940
- Go to `/<snap_name>/listing`, `/<snap_name>/settings` and `/<snap_name>/preview`, and see on mobile layout there is space between the buttons in the sticky header

Fix button spacing on mobile

---

webapp/blog/views.py

Link articles to the ubuntu blog when they are not in the snapcraft.io blog.
Fixes #2692 
- Check that the first blog article in https://0.0.0.0:8004/maas is linking to ubuntu.com
- Check that other blog articles are still linking correctly to snapcraft.io like https://0.0.0.0:8004/vlc

Fix blog links

---

templates/store/_snap-header-developer-information.html
templates/store/_snap-header-information.html
templates/store/snap-details/_snap_heading_data.html
webapp/blog/views.py
webapp/store/content/developers/snaps.yaml
webapp/store/logic.py
webapp/store/snap_details_views.py

- Added the developer for certain snaps
- Visit http://0.0.0.0:8004/gnome-calendar
- The header should include both the developer "Gnome" and the publisher "Canonical"

Show the developer for Canonical and Snapcrafters snapped snaps

---

requirements.txt
static/sass/_patterns_blog-post.scss
webapp/blog/views.py

- Update canonicalwebteam.image-template module to 1.1.0
- Add the fill option to blog posts
- Update CSS to ensure no extra space
- Visit http://0.0.0.0:8004/maas
- Wait for blog posts to load
- See that the images aren't stretched compared to https://snapcraft.io/maas

Fix formatting of snap details blog post images

---

static/js/publisher/builds/components/repoConnect.js
templates/publisher/builds.html

- Remove check for github repos before invoking connect repo JS. This was preventing people not part of an organization from adding repos.
- Create a new github user, and a repo
- Visit the build page for a snap
- You should be able to see that user and the repo in the dropdowns

Allow users without organizations to build snaps

---

webapp/store/content/developers/snaps.yaml

Based on the work in #2705 (nice!), I added information for the LibreOffice snap.
None

Add developer info for the LibreOffice snap

---

static/js/publisher/builds/components/repoConnect.js
static/js/publisher/builds/index.js
templates/publisher/builds.html
webapp/api/github.py
webapp/publisher/snaps/build_views.py

- Remove the requirement for a user to be the owner of a repo to add it
- Update the JS to handle this change:
- In repo list, prefix non-user repos with the organization e.g. org/repo to differentiate between upstream and a fork

Allow builds from collaborators

---

static/js/publisher/release/actions/pendingReleases.js
static/js/publisher/release/actions/pendingReleases.test.js
static/js/publisher/release/actions/releases.js
static/js/publisher/release/components/releasesConfirm.js
static/js/publisher/release/components/releasesConfirmDetails/index.js
static/js/publisher/release/components/releasesConfirmDetails/progressiveRow.js
static/js/publisher/release/components/revisionsListRowProgressive.js
static/js/publisher/release/constants.js
static/js/publisher/release/reducers/pendingReleases.js
static/js/publisher/release/reducers/pendingReleases.test.js
static/js/publisher/release/selectors/index.js

- Removed references to the "key" for progressive releases
- **THIS BREAKS THE UNRELEASED PROGRESSIVE RELEASES FEATURE**
- The main QA steps are to ensure the Releases UI works as before/ expected - **without** the progressive releases feature enabled.

Remove 'key' from 'progressive' following changes in the API

---

static/js/public/snap-details/screenshots.js
static/sass/_patterns_maas_modal.scss

- Fix lightbox opening in a new window on mobile
Fixes #2001 
- View the site locally in your web browser at: http://0.0.0.0:8004/wonderwall
- CLick on the images and see the lightbox appear. Do the same on mobile. The output should be similar.

Do not open lightbox in a new window on mobile

---

templates/store/snap-details/_distro-instructions-for-snap-support.html

- Hiding "Raspberry Pi" from installation instruction  section of snap details page, if "armhf" or "arm64" builds are not available for that snap.
Fixes #2720
- Navigate to: http://0.0.0.0:8004/accountable2you. Raspberry Pi should not be listed as an option.
- Navigate to: http://0.0.0.0:8004/plexmediaserver. Raspberry Pi should be listed as an option.

Fixes #2720: Hiding "Raspberry Pi" from installation instruction

---

package.json
static/js/publisher/builds/repoDisconnect.js

- Remove button spinner from repo disconnect button
Fixes #2719 
- Go to a snap that has a repo connected and click `disconnect repo` link and then `Confirm` button. See the button is disabled once clicked and repo is disconnected.

Remove button spinner on repo disconnect

---

static/js/publisher/builds/components/repoConnect.js
tests/api/test_github.py
webapp/api/github.py

- Added specific error when repo's can't be found
- Updated error rendering method to show generic error if no "type" is defined.
Fixes #2742 
- In `/webapp/api/github.py:219` replace `"repositories"` with `"test"]["test"`
- Visit the build page for a snap that isn't connected to a github repo
- Select an organization
- You should see an error with a link to github

Handle no repos

---

webapp/store/snap_details_views.py

- For raspbian - 404 the install page if the snap isn't available for armhf or arm64
Fixes #2753 
- Visit https://snapcraft.io/install/rpi-imager/raspbian - 200, see the page
- Visit https://snapcraft.io/install/skype/raspbian - 404, don't see the page

Don't show distro pages for non rpi snaps

---

package.json
static/sass/_patterns_form-multiselect.scss
yarn.lock

In preparation for docs pages improvements we need to update Vanilla to latest version.
- Check different pages if they don't break
- check link colors (were updated in Vanilla)
- check form elements
- check docs pages (images, emoji)
- Check any snap listing page for publisher - make sure licence field has matching styles with other form inputs

Update Vanilla to 2.11

---

webapp/blog/views.py

- `get_tag_by_name` doesn't have to be inside a try/except block because it will return `None` if something go wrong.
- Avoid catching generic exceptions when we only want to catch any issues with the WordPress API.
Fixes #2637
- Check that the "Related blog posts" section appear as expected in some snaps, like:
http://0.0.0.0:8004/vlc
http://0.0.0.0:8004/maas

Blog views: Avoid catching generic exceptions

---

templates/partials/search-bar.html
templates/store/search.html

- Autofocus search input on page load
Fixes #2365 
- See that the search bar is autofocused so you can start typing immediately
- Search for something
- On the search results page, see the search bar is autofocused

Autofocus search

---

tests/api/cassettes/GitHubTest.test_check_permissions_over_repo.yaml
tests/api/test_github.py
webapp/api/github.py
webapp/login/oauth_views.py

- Replace the scope `repo` for `admin:repo_hook`
- Update the method `check_permissions_over_repo` to check the user permissions using the repo endpoint instead of the collaborator endpoint.
`admin:repo_hook`: We need this scope to create/remove webhooks.
`read:org`: We need this scope to list the org repos.
More info about scopes:
https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes
Fixes #2752
- Go to http://0.0.0.0:8004/<snap_name>/builds and link your snap with a repository
- Try with you …

Reduce requested permissions from GitHub

---

static/sass/_patterns_form-multiselect.scss
static/sass/_snapcraft_market.scss
static/sass/_snapcraft_market_screenshots.scss
templates/publisher/listing.html

- Add vanilla outline to all elements on the `listing` page
- Align licence `X` icon with the text
Fixes #2757
- `Tab` thorough all the elements and see the new outline from vanilla (thicker and lighter colour)
- Scroll to the license and see more space between the description text and the input element
- Also note the `x` icon is aligned with the text

Add outline to elements to match vanilla

---

requirements.txt
webapp/publisher/snaps/build_views.py

- Update launchpad lib to v0.7.2 and update `_request` to be `request`.
- Added queue_time property when fetching the builds data
Fixes #2771
- Trigger a build and see the JSON data when the table is updated.

Added queue_time when fetching the builds data

---

static/sass/_snapcraft_p-docs.scss
static/sass/styles.scss
templates/docs/_search-bar.html
templates/docs/base.html
templates/docs/document.html

- Updates docs templates to use Vanilla grid layout and side navigation pattern
- Removes unnecessary docs layout styles
- Updates docs search to use Vanilla search box pattern
- Check [updated docs](https://snapcraft-io-canonical-web-and-design-pr-2765.run.demo.haus/docs/)
- Make sure content looks good on different pages (try different type of content, with images, tables, etc)
- Make sure side navigation looks and works as expected
- active item should be marked
- side nav should be sticky and scroll correctly
- on small screens it should hide …

Use Vanilla layout and side navigation in docs

---

requirements.txt
static/js/publisher/builds/index.js

- Add estimated launchpad building queue time on hover over `BUILDING SOON` in the table
Fixes #2744 
- Trigger a new build and you should see `BUILDING SOON` in the table for one of the architectures (if this doesn't happen you are very lucky, and try again later). Hover over `BUILDING SOON` and see a tooltip saying "Queue time: up to $time"
- Keep the page open an see the time is not changing while you still see the `BUILDING SOON` status for that architecture
- The tooltip should disappear when the status is changed

Add estimated launchpad building queue time

---

static/js/publisher/release.js
static/js/publisher/release/components/releasesTable/channelHeading.js
static/js/publisher/release/releasesController.js
static/js/publisher/release/releasesState.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js
static/sass/_snapcraft_release.scss
templates/publisher/release-history.html
tests/publisher/snaps/tests_revision.py
webapp/api/dashboard.py
webapp/publisher/snaps/release_views.py

- Update to use the new channel-map endpoint, instead of the `channel-map` dict from the info endpoint
- Update branches to use the expiration date, not the creation date + 30 days
Fixes #2690 
Fixes #2775
- Check multiple snaps release UI's against production. Everything should be the same.
- Check both small snaps with few tracks branches and revisions (spotify or skype) and larger examples (lxd or nextcloud)

Channel map endpoint

---

tests/api/cassettes/GitHubTest.test_get_snapcraft_yaml_name.yaml
webapp/api/github.py
webapp/publisher/snaps/build_views.py

- Skip push events that are not in the default branch of a GitHub repository
- Update `get_last_commit` method to use the default branch if none is provided
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1519
- Use ngrok to redirect the traffic to your localhost.
- Update the webhook URL in any snap repo and check that you only build the snap when the push is for your default branch.

Check GitHub webhook branch

---

package.json
static/sass/_snapcraft_p-docs.scss
yarn.lock

- Updated to latest Vanilla
- Removed local workaround (now fixed in Vanilla)
- Check if docs pages work as expected (on small screen there should be no issue with global navigation)
- Check if new icons look good

Update to Vanilla 2.12

---

static/js/publisher/release/releasesState.js
webapp/publisher/snaps/release_views.py

- Update the key for default-tracks from the channel-map endpoint
Fixes #2820 
- Visit http://0.0.0.0:8004/maas/releases
- See that the track dropdown is set to 2.7

Fix default tracks on Release UI

---

static/js/publisher/builds/index.js
templates/publisher/build.html

- Ensure build page table is invoked correctly
Fixes #2822 
- Visit http://0.0.0.0:8004/snap_name/builds
- Click on a build
- The table should load correctly and there should be no console errors.

Fix build page

---

requirements.txt
webapp/publisher/snaps/build_views.py

- List builds with status 'Needs building'.
- Include estimated time for 'Needs building' builds.
- Fix pagination.
Fixes #2749
- Go to any snap, trigger a build. Check that builds with the status "Needs building" on Launchpad are listed as "Building soon" in the table.

List Launchpad builds with status 'Needs building'

---

webapp/blog/views.py

Fix some blog articles. 
Fixes #2828
- http://0.0.0.0:8004/blog/api/snap-posts/goland should return a JSON object now instead of an error.

Fix articles error

---

static/js/publisher/builds/index.js

- Show queue time when `needs_building`
Fixes #2781 
- Trigger a new build when Launchpad is busy and you should see `BUILDING SOON` in the table for one of the architectures. Hover over `BUILDING SOON` and see a tooltip saying "Queue time: up to $time"

Show queue time when needs_building

---

static/js/publisher/release/releasesState.js
tests/publisher/snaps/tests_revision.py
webapp/publisher/snaps/release_views.py

- Remove `/info` call for release UI
- Update `title` and `publisher.display-name` to be fetched from `/channel-map` call
- Only pass through the `channel-map` dictionary to the template (rather than the entire response)
- Update `releasesState` to use this reduced `channel-map` dict.
Fixes #2833 
- Visit many snaps release pages, make sure they function as expected

Remove extra info call on releases endpoint

---

static/js/public/snap-details/blog-posts.js
templates/partials/blog-card--minimal.html

- Handle image being "null" - I'll improve this with a default image in a new commit later
- Removed the superfluous _callback param on fetch - just work with the Promise
Fixes #2838
- Visit http://0.0.0.0:8004/intellij-idea-ultimate you should see two blog posts, one with an image, one without

Better handle snap details blog posts that don't have images

---

static/js/publisher/form/AccordionHelp.js
static/js/publisher/form/icon.js

- Make delete icon and show icon/image restrictions links accessible
Fixes #2826 
- Tab through the page and see that the `delete icon` icon and the `show icon/image restrictions` links are accessible with tab key

Make delete icon accessible

---

static/js/publisher/form.js
static/js/publisher/form.test.js
static/sass/_patterns_media-object--snap.scss
static/sass/_snapcraft_market.scss
static/sass/_snapcraft_p-build.scss
templates/publisher/listing.html

- Change listing page title maxlenght to 40 chars to match store restrictions
Fixes #2843 
- Change the title of the snap to a long name. Note a negative count is displayed once the title length is over 40 chars.

Change listing page title maxlenght to 40 chars

---

package.json
static/js/public/accordion.js
static/js/public/first-snap-flow.js
templates/first-snap/build-and-test.html
templates/first-snap/package.html
templates/first-snap/push.html
yarn.lock

Updates Vanilla to 2.13 and updates first snap flow accordions to new updated class names (to use headings within accordion).
- Go to first snap flow, make sure all accordions work and look as expected
- QA other accordions on the site (if any)

Update to Vanilla 2.13

---

templates/partials/_video.html

- Enable captions by default
Fixes #2842 
- There is no easy way to test this, unless you know a snap that has a video and the video has a subtitle/cc (not auto-generated). If you do know `that snap` go to http://0.0.0.0:8004/<that_snap_name> and see the video has the captions `on` by default
If you don't know any snap that has that, just trust me. Here is an example that [has subtitle](https://www.youtube.com/embed/up21mvokyQ4?cc_load_policy=1) and [one that doesn't have](https://www.youtube.com/embed/0FC94Tgz2ho?cc_load_policy=1). Both of these …

Enable captions by default

---

static/js/publisher/tour/tourStepCard.js
static/sass/_snapcraft_builds.scss

- Centre align the icon in the middle for buttons
Fixes #2886 
- Go to http://0.0.0.0:8004/<snap_name>/listing and click the tour button. Note the arrows in the `next` & `previous` buttons are in the centre
- Go to http://0.0.0.0:8004/tutorials/snap-download#1-introduction and note the arrows in the buttons at the button are in the centre

Centre align the icon in the middle for buttons

---

static/js/public/snap-details/channelMap.js
static/sass/_snapcraft_details_heading.scss
templates/store/snap-details.html
templates/store/snap-details/_channel_map.html
webapp/store/snap_details_views.py

- Added some hackery for appliances
Fixes #2882
- Visit http://0.0.0.0:8004/adguard-home, http://0.0.0.0:8004/mosquitto, http://0.0.0.0:8004/nextcloud, http://0.0.0.0:8004/plexmediaserver and http://0.0.0.0:8004/openhab and see the links. Click them - they should take you to the right ubuntu page.

Appliance links

---

Dockerfile

There is an extra ADD not needed in our Docker image, this issue was causing the following problem: https://github.com/docker/cli/issues/2587#issuecomment-644796611
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag test .`
- `docker run -ti -p "8004:80" --env SECRET_KEY=secret_key test`
- Check http://0.0.0.0:8004

Update Dockerfile: Remove unnecessary ADD

---

static/js/publisher/builds/helpers.js

- Shorten build table statuses:
Built and Released → Released
Build, releasing soon → Releasing
Fixes #2891 
- Trigger a new build and notice the statuses: `Releasing` instead of "Built and released" & `Releasing` instead of "Build, releasing soon"

Shorten build table statuses

---

requirements.txt
webapp/publisher/snaps/release_views.py
webapp/publisher/snaps/views.py

Added snap revision JSON endpoint
- Login as a publisher
- `http://0.0.0.0:8004/<your-snap>/releases/revision/<your-revision>`
- The result should be a json object

Added snap revision JSON endpoint

---

static/js/public/snap-details/channelMap.js
templates/store/snap-details/_channel_map.html

- Assign template to a div and use query selector to update the warning string
- Added additional warnings.
Fixes #2898 
Fixes #2900
- Visit http://0.0.0.0:8004/lukewh-test
- Click the channel-map dropdown, click "install >" and "< back" on each risk to ensure the messages are there.

additional messages for risk levels

---

templates/_header.html

- Remove `build with github` link from the navigation
Fixes #2874 
- See there is no `Build with Github` link in the nav

Remove build with github link from navigaton

---

tests/publisher/tests_account_logout.py
webapp/login/views.py

- Remove redirect to BSI on logout
Fixes #2906 
- Logout
- Be redirected to /

Remove logout redirect through BSI

---

static/js/publisher/form/banner.js
static/js/publisher/form/fileInput.js

- Fix bug with banner removal when trying to replace it first with and invalid image
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1018
1. Go to snap listing page (with a banner uploaded or upload and save a banner)
2. With existing banner visible, click Edit to change banner
3. Choose image with wrong aspect ratio
4. See error message
5. Click icon to remove existing banner image
6. See error message has disappeared
7. Click "Save" to save removing to banner
8. See the banner was successfully …

Fix bug with banner removal when trying to replace it first with and invalid image

---

templates/partials/fsf_language.html

Fix flutter Logo that was mirrored on first snap flow languages
Check the link and make sure the logo is the same than the flutter one: https://flutter.dev/ :smile: 
- `dotrun`
- http://0.0.0.0:8004
- Make sure the flutter logo in the list of languages is the correct one
Fixes #2937

Mirror flutter logo

---

package.json
static/sass/_snapcraft_p-tutorials.scss
templates/tutorials/tutorial.html
yarn.lock

- Fix tutorial styling
- Upgrade vanilla to 2.14.0
Fixes #2934 
- View the site locally in your web browser at: http://0.0.0.0:8004/tutorials
- Click on a tutorial and see it looks right compared to https://snapcraft.io/tutorials/snap-download#1-introduction
- Visit various pages and note there are no issues because of vanilla upgrade

Fix tutorial styling

---

static/sass/_patterns_pagination.scss
templates/docs/search.html

- Update pagination for docs search
Fixes #2933
- View the site locally in your web browser at: http://0.0.0.0:8004/docs/search
- Search for a term and see the pagination buttons look good

Update docs search navigation

---

templates/home/_fsf_flutter.html
webapp/first_snap/content/flutter/build.yaml
webapp/first_snap/content/flutter/package.yaml
webapp/first_snap/content/flutter/snapcraft.yaml
webapp/first_snap/content/flutter/test.yaml

The first-snap example for flutter pointed to a source project that wasn't configured to build for linux.  This PR updates it to point to a project that is.

Updated flutter first-snap example to a simplier app that already has a linux target

---

templates/publisher/register-snap.html

- Make snap name max 40 characters
Fixes #
- View the site locally in your web browser at: http://0.0.0.0:8004/register-snap
- See snap name can be no more than 40 chars

Make snap name max 40 characters

---

templates/first-snap/_layout_fsf.html

Remove intercom snippet since not in use anymore.
- View the site locally in your web browser at: http://0.0.0.0:8004/first-snap
- Make sure this is not here anymore (on the bottom right there should be no intercom livechat)

Remove intercom js snippet

---

templates/publisher/builds.html
webapp/api/github.py
webapp/publisher/snaps/build_views.py

- Add message if linked repo does not exists
Fixes #2854 
- The snap should have a repo connected. 
- Delete the yaml file from the repo, then refresh the page. See the error message.
- Delete the repo from GitHub, then refresh the page. See a new error message.
No repo message:
No yaml file message:

Add message if linked repo does not exists

---

tests/tests_templates_utils.py
webapp/helpers.py
webapp/publisher/snaps/metrics_views.py
webapp/store/snap_details_views.py

**This pull request can be merged once Node has setup the default track to be the prefered track**
Now that default tracks are handled by the API we can enter in contact with node so they can set their default track to their latest LTS 12.
At the moment this was coded in the backend as an exception for node and is one LTS late.
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2952
- Go on /node 
- **For now there is no default track so the track is the latest (15)**
- Check that the listing/metrics/releases pages are working

Remove hardcode of default track for node

---

static/js/publisher/form.js
static/js/publisher/form.test.js
static/js/publisher/release/components/contextualMenu.js
static/js/publisher/submitEnabler.js
templates/first-snap/install-snapcraft.html
yarn.lock

- Replace .is--disabled with .is-disabled
Fixes #2966 
- View the site locally in your web browser at: http://0.0.0.0:8004/<snap_name>/settings
- Note the `Revert` button is disabled compared to the live page

Replace .is--disabled with .is-disabled

---

templates/publisher/builds.html
webapp/publisher/snaps/build_views.py

- The warning message for snaps linked with deleted repos is appearing for snaps not linked to any repo.
- Remove not needed code for compatibility with old snaps on BSI.
- Go to a new snap the message shouldn't appear.
- Go to a snap with a deleted repo the message should appear.
Bug:

Bug fixes on builds

---

webapp/api/github.py
webapp/publisher/snaps/build_views.py

Support BSI webhooks secrets
Fixes #2949
- Use ngrok and change an old BSI webhook to your ngrok URL
- Create a push event

Fix issue with BSI webhooks

---

Dockerfile

- `yarn.lock` file is missing before doing the build
1. `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag test .`
2. `docker run -ti -p "8004:80" --env SECRET_KEY=secret_key test`
3. Check http://localhost:8004/

Missing yarn.lock in Docker

---

static/js/publisher/form/multiselect.js

- Fix multiselect always highlighted first option
Fixes #2976
- View the site locally in your web browser at: http://0.0.0.0:8004/<snap_name>/settings
- Navigate to `selected territories` and add some countries using the keyboard
- Refresh the page and do the same thing again using the mouse. See the first item in the list is not always highlighted

Fix multiselect always highlighted first option

---

requirements.txt
tests/publisher/snaps/tests_listing.py
tests/publisher/snaps/tests_post_listing.py
tests/store/tests_get_store_view.py
tests/store/tests_public_logic.py
tests/store/tests_search.py
webapp/store/logic.py

- Update store-api module to use the categories v2 endpoint
- Check as a publisher that you get all the categories in the dropdown when you go to http://0.0.0.0:8004/<snap_name>/listing

Update store-api module

---

static/js/publisher/builds/index.js

- Show queue time only for the 'Building Soon' builds
Fixes #2983 
- Trigger a new build and hover over items in the `Result` column. You should see a `Queue time ...` tooltip only when you hover over a `Building soon` build and not older `Released` builds as currently happens

Show queue time only for the 'Building Soon' builds

---

webapp/snapcraft/views.py

Remove snap that links to 404 on iot page
- View the site locally in your web browser at: http://0.0.0.0:8004/iot
- Make sure all snaps don't 404

Remove snap that links to 404

---

webapp/blog/views.py

Exclude articles that comes from tags `[3184, 3265, 3408]` like on other sites
- View the site locally in your web browser at: http://0.0.0.0:8004/maas
- Check the list of articles, make sure all articles are not 404 :smile: 
- http://0.0.0.0:8004/blog
- Make sure the blog is still working

Exclude tags for blog

---

static/js/public/about/index.js
static/js/public/about/side-navigation.js
templates/_header.html
templates/about/_about_layout.html
templates/about/index.html
templates/about/listing.html
templates/about/publicise.html
templates/about/publish.html
templates/about/release.html
webapp/snapcraft/views.py
webpack.config.entry.js
webpack.config.js
webpack.config.rules.js

- Add about pages infrastructure and basic layout
- Add `/about` page
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1594
- View the site locally in your web browser at: http://0.0.0.0:8004/about
- Compare the page to [copy doc](https://docs.google.com/document/d/1mNCqEBZCv9SAprALkSjlwNVyP52ivsQ-fnDQuIS6kBk/edit#) and [design](https://app.zeplin.io/project/5cc1b1eae442ed2da911b809/screen/5ea836f6574a9325f2d353ce)

Add about page

---

templates/about/listing.html
templates/about/release.html

- Add `/about/release`
-Add `/about/listing`
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1597
- View the site locally in your web browser at: http://0.0.0.0:8004/about/release
- Go to http://0.0.0.0:8004/about/release and compare to [copy doc](https://docs.google.com/document/d/1irw5lVtulOzUK6yNkslJgcocZuomPhpViHu3VgEKVSc) and [design](https://app.zeplin.io/project/5cc1b1eae442ed2da911b809/screen/5ed50412b257ca512de6852b)
- Go to http://0.0.0.0:8004/about/listing and compare to [copy doc](https://docs.google.com/document/d/1Mt_nUa2U95xuimPSTvBuqWm6PEvRffHDUzzHUzMOuSE/edit) and …

Add about/release page

---

templates/about/publicise.html

Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1598
- View the site locally in your web browser at: http://0.0.0.0:8004/about/publicise
- Compare to [copy doc](https://docs.google.com/document/d/1xDFNtlpV8pKcYixVrri-h0LF_1OoRXTK40CYpvRLwe4/edit) and [design](https://app.zeplin.io/project/5cc1b1eae442ed2da911b809/screen/5ea83a7ff932d023c4589e27)

Add about/publicise page

---

webapp/store/content/distros/ubuntu.yaml

Remove the EOL releases and add 20.04
Checked which releases are supported. Removed unsupported ones, and added in 20.04 LTS.
Reported at https://forum.snapcraft.io/t/outdated-snapcraft-info-at-every-ubuntu-package/19316
Did all this! dotrun is rather neat!
Made sure I didn't put a duff link in there, or break existing links.

Update supported releases

---

templates/_header.html

Fixes #
- See there is n external link icon for "Forum" in the nav

Remove external link from navigation "Forum"

---

templates/_header.html

This reverts commit f16c4084a3244cb8792ee118a7ae8f319e3513ef.
Fixes #

Revert "Remove external link from navigation "Forum" (#3005)"

---

templates/about/listing.html

- Replace placeholder images on `/about/listing`
Fixes #
- View the site locally in your web browser at: http://0.0.0.0:8004/about/listing
- See the page looks good

Replace placeholder images

---

templates/home/_fsf_flutter.html

Fixes #2940 
Remove useless space
- Make sure First snap flow for flutter doens't have the space anymore in front of apps
```
apps:
super-cool-app:
command: super_cool_app
extensions: [flutter-dev] 
```

Remove useless space

---

static/js/publisher/release/components/releasesTable/channelHeading.js

- Fix: Parse string to Date object for the date-fns library
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3010 and https://github.com/canonical-web-and-design/snapcraft.io/issues/3021
- Go to http://0.0.0.0:8004/toto-fran/releases and click on the branch icon under the edge channel, it will work as expected.

Fix release branches

---

static/js/public/hero-tabpanel.js
templates/index.html

- Fix the request response order in the carousel
Fixes #
- Go to homepage and see the carousel works as expected. Also throttle your connection and see it works fine.

Fix the request response order in the carousel

---

static/js/public/hero-tabpanel.js
static/sass/_button-overrides.scss
static/sass/_pattern-hero-tab.scss
templates/index.html

- Add "View all ... snaps" button
- Add "Browse all snaps" button
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1606
- Go to homepage and see the new links in the hero

Add browse all and view all buttons

---

templates/about/listing.html

- Update /about/listing headings to be `p-heading--5`
Fixes #3027 
- View the site locally in your web browser at: http://0.0.0.0:8004/about/listing
- See that `Title`, `Subtitle`, etc. look better than before

Update /about/listing headings

---

webapp/store/content/distros/opensuse.yaml

This commit removes references to Leap 42.3.
Additionally, it adds references for Leap 15.1 and 15.2.
The example has been updated to use the latest Leap repository, 15.2.
Fixes #3043 
The repository for Leap 42.3 no longer exists.
Leap 42.3 is no longer supported, so this is not unexpected.
The currently available repositories can be found here:
https://download.opensuse.org/repositories/system:/snappy/
Leap 15.1 and 15.2 are now available in addition to 15.0.
- View the site locally in your web browser at: http://0.0.0.0:8004/docs/installing-snap-on-opensuse
- Verify that the openSUSE repositories named …

Update supported openSUSE Leap versions

---

static/js/public/hero-tabpanel.js

- Show only verified snaps as verified on homepage carousel
Fixes #3046 
- Go to homepage and see that not all snaps are showed as verified, only some of them.

Show only verified snaps as verified on homepage carousel

---

templates/publisher/metrics.html
webapp/publisher/snaps/logic.py

Add metrics graph for weekly architecture
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1680
- View the site locally in your web browser at: http://0.0.0.0:8004/<snap>/metrics
- Chose `By architecture`
- The metrics graph should reflect the architectures

Add architecture metrics on publisher page

---

webapp/store/views.py

Remove `quote_plus` not required to do API request to store.
Fixes #3036
- View the site locally in your web browser at: http://0.0.0.0:8004/store
- Search for snaps with special characters in names like: Xournal++
- Should have results in this case

Remove quote plus not required for API call

---

webapp/store/content/distros/debian.yaml

This brings the "Enable snapd" instructions in line with what is
documented at https://snapcraft.io/docs/installing-snap-on-debian.
The versions of snapd that ship with Debian stable and oldstable do not
fully support base snaps, which is required to successfully install many
snaps.
This commit addresses that issue by asking the user to upgrade snapd as
part of the installation process.
[Screenshot](https://i.imgur.com/vxApYyf.png)

distros: ask debian users to install core snap

---

webapp/docs/views.py

Remove categories for docs since not required
- View the site locally in your web browser at: http://0.0.0.0:8004/docs
- docs should work as usual

Remove hard coded categories

---

static/js/publisher/builds/index.js

- Fetch new builds only after the previous fetch finished
Fixes #2889 
- I don't know how you can QA this. But basically it should only trigger a new builds fetch 30s after the previous one has finished. Previously we were making requests every 30s, even if the last request was not finished

Fetch builds only after the previous fetch finished

---

static/js/publisher/publicise.js

- Remove extra slash for GitHub badge URLs
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3083
- Compare GitHub Markdown badge:
- https://snapcraft.io/testfran4/publicise/badges (There is an extra slash in the URL)
- https://snapcraft-io-3084.demos.haus/testfran4/publicise/badges (The URL should be fine)

Remove extra slash for badge URLs

---

templates/partials/fsf_language.html

Fixes #3030 
Center aligned the text under the logos in the 'how to snap an app' section on the homepage.

Issue 3030 - Center aligned the text under the logos

---

requirements.txt
webapp/blog/views.py

- Fix blog article thumbnails.
https://snapcraft.io/blog
Check the thumbnails, you will notice they do not have the same size.
https://snapcraft-io-3085.demos.haus/blog
Check the thumbnails, you will notice they all have the same size(354x199) and cover the whole width of the block.
Part of: https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/153
Before:
After:

Set width and height to thumbnails

---

static/js/publisher/builds/components/buildsTable.js
static/js/publisher/builds/index.js
static/sass/_snapcraft_release.scss
static/sass/styles.scss

Updates ModularTable in builds view to use new SummaryButton for loading more builds.
Because of CSS class name clash between react-components ActionButton and release UI `p-action-button` scope of release UI CSS selector was changed.
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/904
- Go to builds of some snap
- Make sure table renders correctly
- Make sure loading more builds work correctly
- Make sure summary disappears when all builds are loaded
- Check if buttons in release UI display as expected

Use new summary button for loading builds

---

package.json
run
static/js/base/cookie-policy.js
static/sass/styles.scss
templates/_footer.html
templates/_layout.html
webpack.config.entry.js
yarn.lock

- Integrate cookie-policy v3.0.3
- Bump the docker image for ./run to 1.6.8
- Add link to manage tracking settings to the footer
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3273
- Check the cookie policy appears
- Check the manager opens and works
- Make a selection and the notification should disappear
- Scroll to the footer and click the Manage link in the footer
- See that manager appears again.

Integrate cookie-policy v3.0.3

---

static/sass/_snapcraft_graph-tooltip.scss

Fixes #1848. Moved number of installs little bit to the right, to make room for channel name.

Display full channel name

---

templates/publisher/account-snaps.html

- Show unlisted visibility in the snaps table
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1623
- View the site locally in your web browser at: http://0.0.0.0:8004/snaps
- If you don't have any `Unlisted` snaps, go to http://0.0.0.0:8004/<snap_name>/settings and set it to `Unlisted`
- Now go back to http://0.0.0.0:8004/snaps and see that visibility is `Unlisted` in the table for the snap you've jut changed

Show unlisted visibility in the snaps table

---

templates/_footer.html
templates/publisher/developer_programme_agreement.html

- Update link in the footer [Terms of Service](https://ubuntu.com/legal/terms-and-policies/snap-store-terms)
- Update `/account/agreement` Snap Store Terms of Service and Privacy Notice
Fixes #3114 
- View the site locally in your web browser at: http://0.0.0.0:8004/account/agreement
- See that "Canonical Terms of Service & Privacy Notice" ---> "Snap Store Terms of Service and Privacy Notice"
- See that "Developer Terms and Conditions" ---> "Snap Store Terms of Service" and points to https://ubuntu.com/legal/terms-and-policies/snap-store-terms
- See that "Legal information" in the footer became "Terms of …

Update snap store privacy notice

---

static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.js
static/sass/_snapcraft_graph-tooltip.scss

- Re-order the tooltip content to maximize space
Fixes #my-own-issue
- Hit up your most popular snap
- Hover over the graph
- Be amazed by the New Tooltip Order™️
- Rejoice

Rearrange the tooltip for maximum viewage

---

static/js/public/hero-tabpanel.js

- Fix forEach error for hero tabpanel on homepage
Fixes #3150 
- Perhaps you should open the demo in https://browserstack.com using Chrome 50 version
- Open the console and see there are no errors

Fix forEach error for hero tabpanel on homepage

---

templates/_layout.html
templates/store/snap-details.html

Improve metatags for snap pages
-  Make sure now all snaps have an icon (or give missing icon)
- Test on card validator and facebook debugger if it works well too (use demo for this):
https://cards-dev.twitter.com/validator
https://developers.facebook.com/tools/debug/

Improve metatags for snap pages

---

templates/store/snap-details.html

`applicationCategory` is a required property in the JSON+ld schema
- View the site locally in your web browser at: http://0.0.0.0:8004/toto
- make sure snaps have `applicationCategory` in their JSON+Ld description (see end of html) :)
- You can test here: https://search.google.com/test/rich-results
- Make sure it's all green

Add missing category JSON for snaps

---

static/sass/_snapcraft_p-form-help-text.scss
static/sass/styles.scss
templates/admin/_navigation.html
templates/admin/settings.html
webapp/admin/views.py

Add template for admin store settings
Fixes #3211
- View the site locally in your web browser at: http://localhost:8004/admin/ahnuP3quahti9vis8aiw/settings
- Check that there is a form for the settings
- Check that there is a success notification at the top of the page

Build admin settings page

---

requirements.txt
templates/_header.html
webapp/docs/views.py
webapp/snapcraft/views.py
webapp/tutorials/views.py

- Update to use latest version of discourse  module (canonicalwebteam.discourse instead of canonicalwebteam.discourse_docs)
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3235
- http://0.0.0.0:8004/docs
- http://0.0.0.0:8004/tutorials
- Make sure it all works as usual

Update discourse module

---

package.json

- Generate missing styles-embedded.css file
Fixes #3231 #3246 #3232
- View the site locally in your web browser at: http://localhost:8004/argos-translate/publicise/cards

Add missing styles-embedded.css file

---

templates/store/snap-details/_distro-instructions-for-snap-support.html

- Add distros to cloudinary
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3256
- View the site locally in your web browser at: http://0.0.0.0:8004/eks
- Make sure images come from cloudiary

Add cloudinary to install distro logos

---

static/js/public/homepage.js
templates/index.html
webpack.config.entry.js
webpack.config.rules.js

Removed unused JS from homepage bringing it down from 1.7mb to 47.9kb
- Check that the homepage still works as expected

Remove unused JS from homepage

---

static/js/public/store.js
templates/store/store.html
webpack.config.entry.js
webpack.config.rules.js

Removed unused JS from store page
Fixes #3266
- View the site locally in your web browser at: http://0.0.0.0:8004/store
- Check that the categories still load

Remove unused JS from store page

---

static/js/public/store-details.js
templates/store/publisher-details.html
templates/store/snap-details.html
templates/store/snap-distro-install.html
webpack.config.entry.js
webpack.config.rules.js

Removed unused JS from store details page
Fixes #3265
- View the site locally in your web browser at: http://0.0.0.0:8004/<snap_name> (any snap page)
- Click around and make sure it works as expected

Remove unused JS from store details page

---

static/js/public/fsf.js
templates/first-snap/_layout_fsf.html
templates/first-snap/build-and-test.html
templates/first-snap/install-snapcraft.html
templates/first-snap/language.html
templates/first-snap/package.html
templates/first-snap/push.html
webpack.config.entry.js
webpack.config.rules.js

Removed unused JS from first snap flow
Fixes #3267
- View the site locally in your web browser at: http://0.0.0.0:8004/first-snap
- Go through the process and check that it works as expected

Remove unused JS from fsf

---

static/js/public/distro-install.js
static/js/public/publisher-details.js
static/js/public/search.js
templates/store/publisher-details.html
templates/store/search.html
templates/store/snap-distro-install.html
webpack.config.entry.js
webpack.config.rules.js

Removed unused JS from publisher detail pages
Fixes #3275
- View the site locally in your web browser at: http://0.0.0.0:8004/publisher/kde

Remove unused js from publisher details

---

templates/admin/members.html
templates/admin/snaps.html

Updated page titles for the admin snaps and members pages
- Go to http://localhost:8004/admin/ahnuP3quahti9vis8aiw/snaps
- Check that the page title in the browser tab makes sense
- Go to http://localhost:8004/admin/ahnuP3quahti9vis8aiw/members
- Check that the page title in the browser tab makes sense

Update page titles for brand store admin pages

---

static/js/publisher/builds/index.js
templates/publisher/build.html

- Remove trigger new build button from build details page
Fixes #3276
- View the site locally in your web browser at: http://0.0.0.0:8004/[snamp-name]/builds/
- Go to your builds page see there is a `Trigger new build` button
- Click on one of the builds ID and see there is no `Trigger new builds` button on that page

Remove trigger new build button from build details page

---

static/sass/styles.scss
templates/partials/_snap-details-video-layout.html
templates/partials/_video.html
templates/store/snap-details/_screenshots.html
tests/publisher/snaps/test_post_preview.py
webapp/publisher/snaps/listing_views.py
webapp/store/logic.py
webapp/store/snap_details_views.py

Defer loading of video on snap details page so it isn't render blocking
Fixes #3285
- Go to https://snapcraft-io-3286.demos.haus/code
- Go to https://snapcraft-io-3286.demos.haus/tbmb-bsi-test
- In both cases check that the video loads and the content doesn't jump

Defer loading of videos on details page

---

templates/blog/index.html

- Add rss metatag for blog
Fixes #3294 
- View the site locally in your web browser at: http://0.0.0.0:8004/blog
- Make sure the metatag for rss is here

Add rss metatag for blog

---

templates/admin/_navigation.html
templates/admin/manage_members.html
templates/admin/members.html

- Removed "Models" from admin navigation
- Removed "Snaps in store" column from members table
- Removed scroll bars from the invite members modal
Fixes #3297
- Go to https://snapcraft-io-3296.demos.haus/admin
- Check that "Models" is not present in the side navigation
- Go to https://snapcraft-io-3296.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Check that there is no "Snaps in store" column in the table
- Go to https://snapcraft-io-3296.demos.haus/admin/ahnuP3quahti9vis8aiw/members/manage
- Click the "Add" button and check that the modal has no scrollbars

Tidy up admin UI

---

templates/docs/search.html

Fixed the pagination buttons on the docs search pages
- Go to https://snapcraft-io-3298.demos.haus/docs/search?q=test
- Check that the prev/next buttons at the bottom of the page look good and work as expected
Fixes #2955

Fix docs search pagination buttons

---

templates/publisher/_header.html
templates/publisher/_noscript.html
templates/publisher/account-snaps.html

Added a message for users with JS disabled
- Disable JS in your browser
- Go to https://snapcraft-io-3299.demos.haus/snaps
- Check that there is a message about having JS disabled
- Click through to a snap page
- Check that there is a message about having JS disabled
Fixes #2850

Add no script message to publisher pages

---

templates/admin/_snaps_section.html

Removed the "Weekly active devices" column from the snaps admin table
- Go to https://snapcraft-io-3314.demos.haus/admin
- Check that the snaps table has no column called "Weekly active devices"
Fixes #3315

Remove weekly active devices column

---

requirements.txt
webapp/helpers.py
webapp/publisher/snaps/build_views.py
webapp/publisher/snaps/builds.py
webapp/publisher/snaps/settings_views.py
webapp/publisher/snaps/views.py

- JSON endpoint to summarize snap builds
- Having snaps using automated builds on snapcraft.io and being authenticated request:
- http://0.0.0.0:8004/snap-builds.json
Fixes #3308

JSON endpoint to summarize snap builds

---

static/js/publisher/build-status.js
static/js/publisher/publisher.js
templates/publisher/account-snaps.html

Added a build status column to the snaps listing
- Go to https://snapcraft-io-3318.demos.haus/snaps
- Check that the table has a build status column
Fixes #3309, #3310

Add build status column

---

HACKING.md
konf/staging-api.snapcraft.io.yaml
webapp/api/sso.py

- Our [store API module](https://github.com/canonical-web-and-design/canonicalwebteam.store-api/) is using different env variables to set the staging APIs, these changes will make snapcraft.io use the same ones and fix the k8s config.
- Check the login is working fine.
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3330

Update env var names

---

requirements.txt
webapp/store/snap_details_views.py

- Update flask-base to 0.7.3
- Exclude `/<snap_name>/embedded` route from using this header.
- Do `curl -I http://0.0.0.0:8004/toto-fran/embedded` and `X-Frame-Options: SAMEORIGIN` shouldn't be there
- Do `curl -I http://0.0.0.0:8004/` and `X-Frame-Options: SAMEORIGIN` should be present
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3336

Update flask-base and use exclude_xframe_options_header

---

static/js/publisher/build-status.js
templates/publisher/account-snaps.html

Added an icon and linked status to builds tab if status is `failed_to_build` or `release_failed`.
- Go to https://snapcraft-io-3349.demos.haus/snaps
- Check that any failed statuses have an icon to the left and are linked to the builds tab
Fixes #1767

Add icon and links to build summary

---

static/sass/styles.scss

Changed font display option to swap to improve the Largest Contentful Paint metric
- Go to https://snapcraft-io-3352.demos.haus/code
- Open developer tools and in the network tab, change "Online" to the "Slow 3G" preset
- Check that the text is always visible
Fixes #3344

Change font display option to swap

---

static/js/base/ga.js
templates/first-snap/_layout_fsf.html
templates/partials/_code-snippet.html
templates/store/snap-distro-install.html

- _Fix GA scroll event sentry errors._
- There is no way to QA it on demo
Fixes #

Fix ga sentry erros

---

static/js/public/ga-scroll-event.js

- _Fix https://sentry.is.canonical.com/canonical/snapcraft-io/issues/15743/_
- _Throw error console if the ga-scroll element does not exist._
- Or you can run the project locally using the [dotrun](https://snapcraft.io/dotrun) snap with `$ dotrun` and view it in your web browser at: http://0.0.0.0:8004/install/dbeaver-ce/manjaro
- Open the console and see there is no error
Fixes #3356 

Throw error when ga-scroll element does not exist

---

static/js/publisher/release/components/releasesTable/channelHeading.js

Show "Built at" time for launchpad builds
- Go to https://snapcraft-io-3360.demos.haus/toto-fran/releases
- Click the launchpad tab under the "Revisions available to release" heading
- Click the gear icon and promote to one of the channels
- Hover over the first cell for the updated channel and check that you can see a "Built at" time
Fixes #2985

Show built at time for launchpad builds

---

templates/admin/snaps.html

Fixed misplaced title on snaps admin page
- Go to https://snapcraft-io-3363.demos.haus/admin
- Check that there is no page title above the global nav (compare to https://snapcraft.io/admin)
Fixes #3362

Fix misplaced page title on snaps admin page

---

templates/first-snap/_breadcrumb.html
templates/first-snap/create-account.html
templates/first-snap/install-snapcraft.html
templates/first-snap/push.html
templates/home/_fsf_c.html
templates/home/_fsf_flutter.html
templates/home/_fsf_go.html
templates/home/_fsf_java.html
templates/home/_fsf_moos.html
templates/home/_fsf_node.html
templates/home/_fsf_pre-built.html
templates/home/_fsf_python.html
templates/home/_fsf_ros.html
templates/home/_fsf_ros2.html
templates/home/_fsf_ruby.html
templates/home/_fsf_rust.html
webapp/first_snap/views.py
webapp/first_snap/views_2.py
webapp/first_snap/views_3.py

- _Update content for ABC testing._
- _Redirect `/first/snap/<language>/create-account` to `/first/snap/<language>`_
- Visit the demo in your browser at https://snapcraft-io-3354.demos.haus
- Go to https://snapcraft-io-3354.demos.haus and select "python" from FSF and click continue. It should take you to https://snapcraft-io-3354.demos.haus/first-snap/python
- Go to …

Update content for ABC testing

---

static/sass/styles.scss

Fix the word breaking in the `code` element as it makes commands hard to read/understand.
- Go to https://snapcraft-io-3378.demos.haus/docs/snapcraft-overview
- Find `snapcraft --debug` in the page
- Check that the words and lines are not wrapping
Fixes #3377

Fix word break in code element

---

templates/admin/_snaps_section.html

Added collaborators column to the snaps table in the admin pages
- Go to https://snapcraft-io-3381.demos.haus/admin
- Check that the snaps table has a collaborators column which has a comma delimited list of users
Fixes #3370

Add collaborators col to snaps table

---

templates/admin/_snaps_section.html
tests/tests_templates_utils.py
webapp/handlers.py
webapp/template_utils.py

Added the latest release data to the snaps admin table
- Go to https://snapcraft-io-3384.demos.haus/admin
- Check that there is a latest releases column in the snaps table and that it is populated
Fixes #3368

Add latest release data to snaps admin table

---

static/js/public/first-snap-flow.js
templates/first-snap/_breadcrumb.html
templates/first-snap/build-and-test.html
templates/first-snap/create-account.html
templates/first-snap/install-snapcraft.html
templates/first-snap/package.html
templates/first-snap/push.html
templates/home/_fsf_c.html
templates/home/_fsf_flutter.html
templates/home/_fsf_go.html
templates/home/_fsf_java.html
templates/home/_fsf_moos.html
templates/home/_fsf_node.html
templates/home/_fsf_pre-built.html
templates/home/_fsf_python.html
templates/home/_fsf_ros.html
templates/home/_fsf_ros2.html
templates/home/_fsf_ruby.html
templates/home/_fsf_rust.html
webapp/first_snap/views.py
webapp/first_snap/views_2.py
webapp/first_snap/views_3.py

- _Make all links consistent with the fsf ABC test option._
- _Remove login required from `/first-snap-2/<kanguage>/create-account` and `/first-snap-3/<language>/create-account`._
- _Point fsf links on the homepage to `/first-snap/<kanguage>`._
- Go to https://snapcraft-io-3385.demos.haus/#python and see that the continue button will take you to …

Make fsf links persistent with the fsf ABC test option

---

static/sass/styles.scss
templates/admin/admin_layout.html

Fixed the close button for the app navigation menu on mobile
- Go to https://snapcraft-io-3386.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Open and close the navigation drawer
- Check that it works
Fixes #3382

Fix bug with closing admin page navigation

---

templates/admin/_snaps_section.html

Added the table card pattern to the snaps admin table
- Go to https://snapcraft-io-3387.demos.haus/admin
- Check that the table is using the Vanilla mobile card pattern
Fixes #3383

Make snaps admin table use card pattern

---

static/sass/styles.scss
templates/admin/admin_layout.html

Replace `:focus-within` override with recommended fix from Vanilla for closing the application layout navigation on mobile
- Go to https://snapcraft-io-3389.demos.haus/admin
- Open and close the side navigation
- Check that it works
Fixes #3388

Use Vanilla fix for app navigation pattern

---

tests/__init__.py

- Disable talisker context logger for tests (Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3122)
- `dotrun test-python`
Fixes #3122

Disable talisker context logger

---

templates/admin/_snaps_section.html

If a snap if public and in the global store, link it to it's detail page
- Go to https://snapcraft-io-3390.demos.haus/admin
- Check that snaps in the global store are linked to their detail page
Fixes #3371

Link snap name to page if public

---

static/js/publisher/release/components/channelMenu.js

Changed position of tooltip on releases contextual menu so it doesn't overlap actions
- Go to https://snapcraft-io-3379.demos.haus/<snap-name>/releases
- Click the gear icon on one of the tables
- Hover one of the disabled items within 
- Check that the tooltip is positioned to the right and not covering any of the links in the menu
Fixes #3366

Fix tooltip on release page contextual menu

---

static/js/public/fsf-language-select.js

- _Trigger optimize event when user clicks on a language._
- Click on a language from the FSF
- Check there is an event `optimize.activate` sent to Google Optimize
- To check that you might need to install "GTM/GA Debug" extension
Fixes #

Trigger optimize event when user clicks on a language

---

static/js/public/manage-members.js
templates/admin/_snaps_section.html
templates/admin/manage_members.html
templates/admin/manage_snaps.html
templates/admin/members.html

- Removed "Store" and "Published in" columns from the "Snaps", "Manage snaps" and "Members" tables as it is redundant
- Updated the width of the "Name" column on the "Manage members" table to 40%
- Updated the "Manage members" filter to only filter via display name, username or email address
- Go to https://snapcraft-io-3405.demos.haus/admin
- Check that the "Snaps" table has no "Published in" column
- Click "Manage snaps" and check that the table has no "Published in" column
- Go to https://snapcraft-io-3405.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Check that the table has no is no "Store" column
- Click "Manage members" and check that the name column of the table is 40% width
- Use the filter to search by display name, username or email address (e.g. Steve Rydz, steverydz, …

Remove store column from tables

---

requirements.txt
webapp/handlers.py

Here's why:
The cache has to vary by encoding, as in, if a browser requests "gzip" compression of a page, it clearly can't use the same cache as for a browser requesting "br" (brotli) compression. The cache can't actually do this perfectly, because when a request comes in, it doesn't know which compression the app will respond with, so it has to check with the app. This means it uses the distinct value of the "accept-encoding" header instead. So "accept-encoding: gzip, br" will lead to a different cache from "accept-encoding: br, gzip". It does this by setting the header "vary: accept-encoding".
We [are currently looking into](https://github.com/canonical-web-and-design/maas.io/issues/559) how to change our cache-control headers to ensure pages are effectively cached. To understand this, …

Count accept-encoding instances in prometheus

---

static/js/public/manage-members.js

Added a change count to the save button for the manage members admin page
- Go to https://snapcraft-io-3412.demos.haus/admin/ahnuP3quahti9vis8aiw/members/manage
- Check and uncheck roles
- If there are no changes from the original state the save button should be disabled and read "Save changes"
- If there is one change from the original state the save button should be enabled and read "Save 1 change"
- If there are more than one changes from the original state the save button should be enabled and read "Save x changes", with x reflecting the number of changes from the original state
Fixes #3410

Add changes count to members save button

---

templates/admin/manage_snaps.html

Changed the heading of the manage snaps page to explain what the page is for
- Go to https://snapcraft-io-3413.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps/manage
- Check that the heading explains what the page does
Fixes #3409

Change wording of manage snaps page heading

---

requirements.txt
static/js/public/manage-invites.js
static/js/public/manage-members.js
static/sass/_pattern_p-button-group.scss
static/sass/_snapcraft_p-action-form.scss
static/sass/styles.scss
templates/admin/_manage_invites_form.html
templates/admin/admin_layout.html
templates/admin/invites.html
templates/admin/manage_members.html
templates/admin/members.html
tests/tests_templates_utils.py
webapp/admin/views.py
webapp/handlers.py
webapp/template_utils.py
webpack.config.entry.js
webpack.config.rules.js

Added the ability to resend, reopen and revoke member invites
- Go to https://snapcraft-io-3404.demos.haus/admin
- Click "Members" on the left navigation
- Click the "Invites" tab above the table
- Use the search box to filter the table by each invites email address
- Check that invites are grouped by status
- Use the action buttons to revoke, resend and reopen invites
- Check that the status changes appropriately
Fixes #3375

Add manage member invites form

---

templates/partials/_verified_developer.html

Added width and height attributes to the verified account icon
- Go to https://snapcraft-io-3422.demos.haus/code
- Check that the small green tick icon under the snap title looks the same as on the live site
Fixes #3421

Add width and height attributes to verified account icon

---

templates/_header.html

Added width and height attributes to the snapcraft logo
- Go to https://snapcraft-io-3420.demos.haus/
- Check that the snapcraft logo looks the same as it does on the live site
Fixes #3419

Add width and height attributes to site logo

---

templates/_layout.html

Pre-load the hero background image to improve first contentful paint
- Go to https://snapcraft-io-3424.demos.haus/code
- Check that the pale green suru image still loads
Fixes #3423

Preload hero background image

---

templates/_layout.html

Added a valid `as` attribute to the pre-loaded hero image
- Go to https://snapcraft-io-3426.demos.haus/code
- Check that there is no warning in the console about a missing `as` attribute for `preload`
Fixes #3425

Add missing as attribute to preloaded image

---

HACKING.md
konf/staging-api.snapcraft.io.yaml
requirements.txt
tests/first_snap/tests_views.py
tests/login/tests_login_handler.py
tests/publisher/endpoint_testing.py
tests/publisher/tests_publisher.py
tests/store/tests_details.py
tests/store/tests_github_badge.py
webapp/authentication.py
webapp/first_snap/views.py
webapp/first_snap/views_2.py
webapp/first_snap/views_3.py
webapp/handlers.py
webapp/login/views.py
webapp/publisher/snaps/views.py
webapp/publisher/views.py
webapp/store/snap_details_views.py

- Added Candid login
**Demo link will not work with Candid**
Set up all the staging APIs in the `.env.local`:
```
LOGIN_URL=https://login.staging.ubuntu.com
SNAPSTORE_DASHBOARD_API_URL=https://dashboard.staging.snapcraft.io/
CANDID_API_URL=https://api.staging.jujucharms.com/identity/
```
- `dotrun`
- Visit `localhost:8004/login-candid`
- Please use your SSO staging account
- After you are logged you will see a JSON response will information about your user.
- That's all.
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1835

Added Candid login

---

static/js/public/manage-snaps.js

Fixed a bug with the manage snaps save button state
- Go to https://snapcraft-io-3430.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps/manage
- Uncheck any of the snaps
- The "Save changes" button should not be disabled (do not actually click the button)
- Check the snaps to return the page to it's original state
- The "Save changes" button should be disabled
Fixes #3429

Fix bug with manage snaps save button

---

static/js/public/manage-invites.js

Added the users email address to the invite action confirmation modals
- Go to https://snapcraft-io-3433.demos.haus/admin/ahnuP3quahti9vis8aiw/members/invites
- Click on the "Revoke", "Reopen" and "Resend" buttons
- Check that the modal contains the users email address
Fixes #3431

Add user email address to invite action confirmation modal

---

static/js/publisher/release/components/releasesHeading.js

- _Close history when the track is changed_
- Go to https://snapcraft-io-3444.demos.haus/maas/releases and click on the 🕐 inside any cell to see the history.
- Now change the track from the dropdown and see the history is closed.
Fixes #3417 

Close history when the track is changed

---

tests/store/tests_search.py
webapp/store/views.py

- `searched_results` was a list not a `dict` with the element "results" (fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3434)
- Previous error handling on this view didn't make sense and `error_info` variable is not being used by the template.
Fixes #3434

Fix search exception

---

webapp/handlers.py

- When user agent not defined the app was failing
- Added check to make sure the user agent is defined before doing any calculation
- the site should work as usual
Fixes #3437

Check if user agent defined

---

static/js/publisher/metrics/metrics.js

- _Catch error when continued or new devices do not exist._
- Go to https://snapcraft-io-3454.demos.haus/snaps and see the page loads and there are no console errors.
- Hopefully this will fix the [sentry error](https://sentry.is.canonical.com/canonical/snapcraft-io/issues/2757/), but I'll need to check that after we deploy this piece of code.
Fixes #3436 

Catch error when continued or new devices do not exist

---

webapp/login/views.py

- We are managing 2 identity providers: candid and login, there was a conflict between them
- The pr emptys the macaroon session on login to avoid the conflic
- add those variables in `.env.local`
```
LOGIN_URL=https://login.staging.ubuntu.com
SNAPSTORE_DASHBOARD_API_URL=https://dashboard.staging.snapcraft.io/
CANDID_API_URL=https://api.staging.jujucharms.com/identity/
LAUNCHPAD_API_URL=https://api.staging.launchpad.net/devel/
```
- If you don't have a staging at login.staging.ubuntu.com create one :smile: 
- http://localhost:8004/login
- Should login without issues
- http://localhost:8004/login-beta
- should also login with no issues
- http://localhost:8004/logout
- Try again to login with the 2 endpoints

Empty macaroons in session on login

---

webapp/login/views.py

- Unfortunatly it's hard to QA without testing on production
- There was a mistake in the session objects to pop
- now rremove the login sessions that are the opposite login on the callbacks
- This is a follow up from this PR https://github.com/canonical-web-and-design/snapcraft.io/pull/3465
- add those variables in `.env.local`
```
LOGIN_URL=https://login.staging.ubuntu.com
SNAPSTORE_DASHBOARD_API_URL=https://dashboard.staging.snapcraft.io/
CANDID_API_URL=https://api.staging.jujucharms.com/identity/
LAUNCHPAD_API_URL=https://api.staging.launchpad.net/devel/
```
- If you don't have a staging at login.staging.ubuntu.com create one :smile: 
- http://localhost:8004/login
- Should login without issues
- http://localhost:8004/login-beta
- …

Fix wrong variables to pop

---

konf/site.yaml
static/sass/_snapcraft-p-videos.scss
templates/partials/_video.html
webapp/store/views.py

**Note**: If you are running locally you will need an API key which you can get here: https://console.cloud.google.com/apis/credentials?project=snapcraft-youtube-thumbnails&folder=&organizationId=&supportedpurview=project
Add the API to `.env.local` as `YOUTUBE_API_KEY=<KEY>`
---
- Go to https://snapcraft-io-3442.demos.haus/code
- Check that the video thumbnail looks correct
- Go to https://snapcraft-io-3442.demos.haus/wonderwall
- Check that initially a grey image will load, then the correct image (it won't be full screen because it is too small)
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3441

Add logic to get YouTube thumbnail URL

---

static/sass/_snapcraft_l-application.scss
templates/admin/_navigation.html
templates/admin/admin_layout.html

Changed the admin pages navigation colours and active state
- Go to https://snapcraft-io-3491.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Compare the side navigation to [the design](https://app.zeplin.io/project/5f3170425822f41fc299a330/screen/606c2fda4c199f9300ed9372)
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1995

Change admin navigation colour

---

static/sass/_snapcraft_custom-checkboxes.scss

Added a focus state to the custom checkboxes
- Go to https://snapcraft-io-3499.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Tab to the checkboxes and check that there is a focus outline similar to the text field/filter above
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3497

Add focus style to custom checkboxes

---

webapp/decorators.py
webapp/login/views.py
webapp/publisher/views.py

- Store the last auth method in a cookie
**Demo will not work with Candid authentication**
- http://localhost:8004/login-beta
- Finish the auth flow and check your cookies: `last_login_method:"candid"`
- http://localhost:8004/logout
- Go directly to http://localhost:8004/snaps, it should redirect you to Candid
- Check that the cookie is being set with SSO (/login) and works properly
Fixes #3492

Candid re-auth

---

static/js/public/manage-members.js
templates/admin/manage_members.html

Added a table of changes to the sticky footer on the members page
- Go to http://snapcraft-io-3498.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Make changes and click on the "x changes" button in the sticky footer
- Check that a table listing the changes appears above the sticky footer
- Revert changes and check that the changes table is gone
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2002

Add member changes table

---

webapp/admin/views.py

Default store in admin to settings page
- Go to https://snapcraft-io-3514.demos.haus/admin
- Check you are taken to the settings page of the first store
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3513

Default store to settings page

---

templates/admin/_navigation.html
templates/admin/snaps.html

- Added a side panel which will contain the snaps search
- Drive by: link the store title in the sidebar navigation to the settings page
- Go to https://snapcraft-io-3520.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Click on the "Add snap" button on the top right
- Check that a side panel appears to the right of the screen
- Click the "Cancel" button inside the side panel
- Check that the panel is closed
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2028

Add snap search side panel

---

templates/_header.html

Remove edit your account details from the navigation for Candid users
- Authenticate with candid /login-beta
- Check don't see this option in the dropdown
Fixes #3504

Disable account details for Candid users

---

templates/admin/_navigation.html

Added highlight to members when on the invites page of the admin section
- Go to https://snapcraft-io-3521.demos.haus/admin/ahnuP3quahti9vis8aiw/members/invites
- Check that "Members" is highlighted in the side navigation
Fixes #3519

Highlight members navigation on invites page

---

templates/admin/invites.html

Added a notification if there are no invites
- Go to https://snapcraft-io-3529.demos.haus//admin/test1LaNg1xi6eonae5R/members/invites
- Check that there is a notification explaining that there are no invites
Fixes #3517

Empty invites state

---

templates/admin/snaps.html

Changed the "Collaborators" column name to "Publisher"
- Go to https://snapcraft-io-3532.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Check that the last column in the table is called "Publisher" and not "Collaborators"
Fixes #3530

Change collaborators column name

---

templates/_header.html
templates/publisher/account-details.html

Hide 'Edit details' link instead of the account link
No demo, QA locally
Login with candid (`login-beta1`)
Go to `/account/details` and check that the 'Edit details' link doesn't appear.

Hide 'Edit details' link

---

templates/store/snap-details/_distro-instructions-for-snap-support.html

Fixed the heading size on the "Install <snap> on your Linux distribution" heading
- Go to https://snapcraft-io-3537.demos.haus/boa
- Scroll down to the "Install Wolfenstein | Blade of Agony on your Linux distribution" heading
- Check that it is the same size as the "Where people are using Wolfenstein | Blade of Agony" heading
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3535

Fix heading size on details page

---

static/sass/_patterns_p-password-toggle-input.scss
static/sass/styles.scss
templates/admin/settings.html

Added the Store ID field to the manage snaps settings page
- Go to https://snapcraft-io-3550.demos.haus/admin/test1LaNg1xi6eonae5R/settings
- Check that there is a Store ID field
- Click the show/hide button and check that it toggles the Store ID visibility
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2049

Add store ID field to setting page

---

templates/store/snap-distro-install.html

Updated the button style and h1 of snap distribution page
- Go to https://snapcraft-io-3555.demos.haus/install/bitwarden/kde-neon
- Check that the h1 says "Install Bitwardenon KDE Neon"
- Check that the "Install" button in the top right of the white pane is green
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2074

Update title and button on snap distribution page

---

templates/store/snap-details.html

Removed the "Companion apps" section from snap detail pages
- Go to https://snapcraft-io-3559.demos.haus/standard-notes
- Go to https://snapcraft-io-3559.demos.haus/vlc
- Go to https://snapcraft-io-3559.demos.haus/plexmediaserver
- For each check that there is no "Companion apps" section with app store and Google play badges
Fixes #3486

Remove hardcoded companion apps section

---

templates/store/snap-details.html

Changed the title on the snap details page
- Go to https://snapcraft-io-3554.demos.haus/bitwarden
- Check the the page title in the browser tab is "Install Bitwarden on Linux"
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2073

Change title on snap details page

---

static/sass/_snapcraft_market.scss
static/sass/_snapcraft_patterns_icons.scss
static/sass/styles.scss

Removed overrides for the delete icon
- Go to https://snapcraft-io-3562.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Compare the delete icons to `p-icon--delete` from Vanilla: https://vanillaframework.io/docs/patterns/icons
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2076

Remove delete icon overrides

---

templates/partials/blog-card.html

- Fix `UndefinedError: 'used_categories' is undefined`, [sentry issue](https://sentry.is.canonical.com/canonical/snapcraft-io/issues/18198/?query=is%3Aunresolved)
https://snapcraft-io-3564.demos.haus/blog should work as usual
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2084

Remove undefined template variable

---

static/js/public/utilities/build-snaps-table-row.js
templates/admin/snaps.html

Added a delete button on snap cards on mobile
- Go to https://snapcraft-io-3566.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Resize the browser to mobile view
- Check that the bin icon has turned into a delete button
Fixes #3566

Add delete button on manage snaps page mobile view

---

templates/admin/snaps.html

Reset snaps table when search box is cleared
- Go to https://snapcraft-io-3568.demos.haus/admin/test1LaNg1xi6eonae5R/snaps
- Type "core" in the search box at the top left of the screen
- The table should be filtered
- Clear the search box
- The table should be reset
Fixes #2086

Fix clear search on manage snaps page

---

static/js/public/manage-snaps.js

Remove existing snaps from snap search results
- Go to https://snapcraft-io-3569.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Click the "Add snap" button
- Search for a snap that isn't in the list
- You should see search suggestions
- Search for a snap that is already in the store
- There should be no search suggestions
Fixes #3551

Do not return snaps already in store

---

webapp/publisher/snaps/listing_views.py

- Fix listing preview
- Go to the listing page on any snap as a publisher and click on the preview bottom.
Fixes #3553 and #3548

Fix listing preview

---

static/sass/styles.scss

Fixed the navigation highlight color for the current page
- Go to https://snapcraft-io-3592.demos.haus/
- Click on any of the pages in the top navigation
- Check that there is an orange line underneath the link for the page that you are on
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2115

Fix navigation highlight color

---

static/sass/styles.scss
templates/partials/_verified_developer.html
templates/store/_media-object-snap-partial.html
templates/store/categories/iot.html

Fixed the hidden tooltip on the verified badge on the IoT page
- Go to https://snapcraft-io-3597.demos.haus/iot
- Hover over any of the ticks in the green circles in the "IoT tools and server" section
- Check that you see the tooltip
Fixes #3596

Fix hidden tooltip on IoT page

---

webapp/snapcraft/views.py

- Added verified publisher to all Canonical snaps on the IoT page
- Go to https://snapcraft-io-3599.demos.haus/iot
- Check that any snaps with Canonical as the publisher have the green verification icon next to them
Fixes #3598

Add verified icon to IoT snaps published by Canonical

---

static/js/publisher/form.js
static/js/publisher/state.js
templates/publisher/listing.html
templates/publisher/settings.html
tests/publisher/snaps/tests_listing.py
tests/publisher/snaps/tests_settings.py
webapp/publisher/snaps/listing_views.py
webapp/publisher/snaps/logic.py
webapp/publisher/snaps/settings_views.py

Added a checkbox to the snap settings page which enables or disables the uploading of metadata
- You need a snap on staging
- Go to https://snapcraft-io-3527.demos.haus/SNAP_NAME/settings
- Check that there is a checkbox for uploading metadata
- Check the box and save the form
- Check that the box is still checked
- Uncheck the box and save the form
- Check that the box is still unchecked
- Go to https://snapcraft-io-3527.demos.haus/SNAP_NAME/listing
- If the upload metadata box on the settings page is checked you should see a notification
- If the upload metadata box on the settings page is not checked you should not see a notification
Fixes #3322

Add checkbox for uploading metadata for snap

---

templates/admin/snaps.html

Moved the release date to it's own table column in the manage snaps table
- Go to https://snapcraft-io-3623.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Check that there is a "Latest release" and "Release date" column in the table
- Use the "Filter snaps" search and check that those columns are still there
Fixes #2169

Add release date column to snaps table

---

static/js/base/dropdown-menu-toggle.js
templates/_header.html

- Added a link to "Stores" in the logged in sub menu
- Drive-by: Fixed the styling of the navigation
- Go to https://snapcraft-io-3624.demos.haus/
- Click on the logged in menu in the navigation
- Check that there is a link to "My stores" and that it goes to the stores page
Fixes #2176

Add stores link to logged in menu

---

templates/admin/no-stores.html
webapp/admin/views.py

- Add a page template when a user with no stores visits the admin page
- Login as a user with no stores (a test account)
- Go to https://snapcraft-io-3628.demos.haus/admin
- Check that you see a page that tells you that there are no stores
Fixes #3626

Add a template for no stores

---

templates/_header.html
webapp/handlers.py
webapp/login/views.py
webapp/publisher/snaps/logic.py

Removed the "My stores" link in the logged in dropdown nav if the user has no stores
- Go to https://snapcraft-io-3627.demos.haus/
- Login as a user with stores
- Check that there is a "My stores" link in the logged in dropdown nav
- Login as a user with no stores (a test account)
- Check that there is not a "My stores" link in the logged in dropdown nav
Fixes #3625

Remove my stores link from nav if no stores

---

webapp/docs/views.py

- Avoid authenticated API calls to Discourse
- /docs should work as usual
We are waiting on IS to update the discourse configuration for authenticated calls RT#132688

Temp Fix: Avoid authenticated API calls to Discourse

---

static/js/public/brand-store-search.js
static/sass/_snapcraft_l-application.scss
templates/admin/_navigation.html
webpack.config.entry.js
webpack.config.rules.js

Added a search filter to the brand store side navigation
- Go to https://snapcraft-io-3638.demos.haus/admin/test1LaNg1xi6eonae5R/snaps
- Type in store names in the side navigation search
- Check that the list is filtered correctly
- Clear the search
- Check that the list is as before
Fixes #2168

Add store search filter to brand store

---

webapp/docs/views.py

- Use original discourse topic: https://forum.snapcraft.io/t/snap-documentation/11127
- Use authentication for Discourse API calls
- `/docs` and `/tutorials` should work as usual

Use original topic and authenticated API calls

---

webapp/publisher/snaps/metrics_views.py

- Get are getting from the API `latest/stable` and `stable`, the metrics that we want to show are for `stable` not `latest/stable`
- Visit any snap metrics page: http://0.0.0.0:8004/gimp/metrics?active-devices=channel
- Check that when you hover over the graph, there is a high value on the `stable` channel and `latest/stable` is not mentioned.
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3639

Fix metrics

---

templates/publisher/listing.html
templates/publisher/settings.html

Removed upload metadata on release field in snap settings
- Go to https://snapcraft-io-3676.demos.haus/<SNAP_NAME>/settings
- There should be no checkbox for upload metadata on release
Fixes #3677

Remove upload metadata on release field

---

static/js/brand-store/App/App.js
static/js/brand-store/Members/Members.js
static/js/brand-store/Navigation/Navigation.js
static/js/brand-store/SectionNav/SectionNav.js
static/js/brand-store/SectionNav/SectionNav.test.js
static/js/brand-store/SectionNav/index.js
static/js/brand-store/Settings/Settings.js
static/js/brand-store/Settings/Settings.test.js
static/js/brand-store/Snaps/Snaps.js
static/js/brand-store/Snaps/SnapsFilter.js
static/js/brand-store/Snaps/SnapsTable.js
static/js/brand-store/Snaps/SnapsTableRow.js
static/js/brand-store/brand-store.js
static/js/brand-store/selectors/index.js
static/js/brand-store/slices/snapsSlice.js
static/js/brand-store/store/index.js
static/sass/_snapcraft_l-application.scss
static/sass/styles.scss
webapp/admin/views.py

- Added the basic snaps table with a filter
- Added the tabbed navigation to be shared between all views
**Note**: Tests will come in a follow-up PR
- Go to https://snapcraft-io-3693.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Check that there is a table of snaps on the page
- Check that the search snaps filter filters snaps by name
Fixes #3650, #3651

Add snaps table

---

webapp/api/github.py
webapp/publisher/snaps/build_views.py

- Fix issue when people try to link repositories that don't exist anymore or are private now.
- Go to any of your snaps builds: /<SNAP_NAME>/builds
- Create a GitHub repo
- Search for the repo in the list
- Once selected and before saving make the repo private
- A message should appear with an error and not a 500
Fixes #3694

Fix non-existing repositories issue

---

static/js/publisher/release/actions/releases.js
webapp/publisher/snaps/release_views.py

- Show error message for non-collaborators
- Try to release a snap you don't own: /<snap_name>/releases
- An error message should appear
Fixes #3571

Show error message for non-collaborators on releases

---

static/js/brand-store/Snaps/Snaps.js
static/js/brand-store/Snaps/SnapsTable.js
static/js/brand-store/Snaps/SnapsTableRow.js

- Linked all snaps in the global store to their details pages
- Removed checkboxes on snaps table if user is not an admin
- Go to https://snapcraft-io-3753.demos.haus/admin
- If the global store is part of the store page, all snap titles should be linked to their details pages
- Go to a store where you are not an admin
- There should be no checkboxes in the snaps table
Fixes #3745, #3746

Fix global snaps in brand store

---

static/js/brand-store/Snaps/Snaps.js
static/js/brand-store/Snaps/SnapsFilter.js

- Fix the snaps view being cleared by a location change triggered by the main navigation hash
- Drive by: Refactored `otherStoreIds` so it doesn't need to be converted to an array every time it's referenced
- Go to https://snapcraft-io-3752.demos.haus/admin on a small/mobile screen
- Open the main site navigation
- The main content should still be there
Fixes #3748

Fix brand store mobile

---

static/js/public/hero-tabpanel.js
templates/_footer.html
templates/_header-brandstore.html
templates/_header.html
templates/home/_fsf_c.html
templates/home/_fsf_electron.html
templates/home/_fsf_flutter.html
templates/home/_fsf_go.html
templates/home/_fsf_java.html
templates/home/_fsf_moos.html
templates/home/_fsf_node.html
templates/home/_fsf_pre-built.html
templates/home/_fsf_python.html
templates/home/_fsf_ros.html
templates/home/_fsf_ros2.html
templates/home/_fsf_ruby.html
templates/home/_fsf_rust.html
templates/index.html

Co-authored with @bethcollins92 
- Resolved a number of quick a11y related issues, including:
- Fixed up the heading heirarchy
- Added blank alt text to "verified" badges
- Added a heading for the testimonials section
- Removed redundant skip link
- Open the wave extension, see that there are no errors or contrast errors
Before:
After:

Homepage a11y fixes

---

static/js/public/hero-tabpanel.js
templates/_footer.html
templates/_header-brandstore.html
templates/_header.html
templates/home/_fsf_c.html
templates/home/_fsf_electron.html
templates/home/_fsf_flutter.html
templates/home/_fsf_go.html
templates/home/_fsf_java.html
templates/home/_fsf_moos.html
templates/home/_fsf_node.html
templates/home/_fsf_pre-built.html
templates/home/_fsf_python.html
templates/home/_fsf_ros.html
templates/home/_fsf_ros2.html
templates/home/_fsf_ruby.html
templates/home/_fsf_rust.html
templates/index.html

Co-authored with @bethcollins92 
Co-authored with @sowasred2012 
- Resolved a number of quick a11y related issues, including:
- Fixed up the heading heirarchy
- Added blank alt text to "verified" badges
- Added a heading for the testimonials section
- Removed redundant skip link
- Open the wave extension, see that there are no errors or contrast …

Homepage a11y fixes (#3761)

---

static/sass/styles.scss

Fixed the button margins on the brand store invites table
- Go to https://snapcraft-io-3784.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Open the "Invites" panel beneath the members table
- Resize the browser and check that the margins around the "Resend" and "Revoke" buttons look correct
Fixes #3727

Fix button margins on brand store invites table

---

static/js/publisher/release/actions/releases.test.js

Changed test in the releases actions to be more reliable as it was breaking builds
The `test-js` PR check should have passed
Fixes #3787

Change JS test to make it more reliable

---

templates/store/search.html
webapp/store/views.py

Aliased the publisher names to their IDs for the search
- Go to https://snapcraft-io-3798.demos.haus/
- Search for `publisher:jetbrains`
- Check that the search results are correct
- Search for `publisher:kde`
- Check that the search results are correct
- Search for `publisher:snapcrafters`
- Check that the search results are correct
Fixes #3797

Alias publisher names to IDs in store search

---

templates/store/snap-details/_distro-instructions-for-snap-support.html
webapp/store/content/distros/raspbian.yaml

Fixed the aspect ratio of the Raspberry Pi logo
- Go to https://snapcraft-io-3806.demos.haus/cjp256-openvino-samples
- Check that the Raspberry Pi logo towards the bottom of the page in the grid of logos looks correct
Fixes #3524

Fix aspect ratio of Raspberry Pi logo

---

konf/site.yaml
requirements.txt
webapp/app.py

- Remove previous k8s config
- Added before and after request. This is temporary
- Upgrade Flask-base to v0.9.3 to include PID on logs, https://github.com/canonical-web-and-design/canonicalwebteam.flask-base/pull/53 needs to be merged before this PR
- Check the `dotrun` snap output
- The PID should be present on this kind of logs:
```
2022-01-07 12:55:36.230Z DEBUG gunicorn.error "GET /store/featured-snaps/games" service=snapcraft.io pid=1339778
```
- We should have `START` logs, like:
```
2022-01-07 12:55:36.236Z INFO talisker.wsgi "START view=store.featured_snaps_in_category path=/store/featured-snaps/games" service=snapcraft.io pid=1339778 request_id=1e1f222a-c589-42ee-8019-8368dfbb429e
```

Extra logging

---

.stylelintrc
static/js/publisher/release/components/releasesTable/droppableRow.js
static/js/publisher/release/components/releasesTable/index.js
static/sass/_snapcraft_release.scss

Restyled the release table to resemble a Vanilla table
- Go to https://snapcraft-io-3840.demos.haus/danieltest-snap/releases
- Check that the table style e.g. borders looks like the table in [the design](https://app.zeplin.io/project/61b3231e21194c4a48005226/screen/61b323ca5f87d54d3361b971)
- **Note**: The content/style inside of the table cells will not yet match the design
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2317

Convert release table to vanilla

---

static/js/publisher/release/components/releasesHeading.js

Updated the copy on the release UI track switcher
- Go to https://snapcraft-io-3844.demos.haus/fran-snap/releases
- Check that there is a dropdown with a "Track" label
- Go to https://snapcraft-io-3844.demos.haus/danieltest-snap/releases
- Check that there is a heading "Releases available to install" instead of the dropdown
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2329

Update copy for release UI track switcher

---

static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js

- Updated the date format in the release history table
- Drive by: Removed the launchpad logo from the build request
- Drive by: Replaced `Fragment` with the up to date syntax
- Go to https://snapcraft-io-3858.demos.haus/danieltest-snap/releases
- Click the history icon in one of the "Releases available to install" table cells
- Check that the release date is in the following format: "18 Feb 2017"
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2325

Update release date format in release UI history table

---

static/js/brand-store/Members/InviteModal.js
static/js/brand-store/Members/InvitesTable.js
static/js/brand-store/Members/Members.js
static/sass/styles.scss

- Fixed bug where invite roles weren't cleared when the panel was closed and then reopened
- Add timeout to notifications so they disappear after 5 seconds
- Drive by: Fixed some minor JS errors
- Go to https://snapcraft-io-3859.demos.haus/admin/test1LaNg1xi6eonae5R/members
- Click the "Add new member" button
- Select some roles in the panel
- Close the panel
- Reopen the panel
- No roles should be checked
- Invite someone to the store
- The success (or error) notification should disappear after 5 seconds
Fixes #3850, #3848

Clear new member roles when closing panel

---

static/js/brand-store/Members/Members.js
static/sass/_snapcraft_l-application.scss

Added an overlay behind the side panel so clicking outside of it closes it
- Go to https://snapcraft-io-3860.demos.haus/admin/test1LaNg1xi6eonae5R/members
- Open the side panel by clicking the "Add new member" button
- Click anywhere outside of the panel and it should close
Fixes #3847

Close member sidepanel when clicking outside of it

---

templates/first-snap/_install-macos.html

`brew cask` commands were deprecated in 2.6.0 in favour of using the `--cask` flag: https://github.com/Homebrew/brew/pull/8899
- Replaced deprecated `brew cask install multipass` command with `brew install --cask multipass`

Update macOS install instructions

---

static/js/brand-store/Snaps/Snaps.js

- Close brand store snaps side panel when clicking outside of it
- Remove notifications after 5 seconds
- Go to https://snapcraft-io-3863.demos.haus/admin/test1LaNg1xi6eonae5R/snaps
- Click the "Include snap" button to open the side panel
- Click anywhere outside the side panel and it should close
- Include a snap to the store
- The notification should disappear after 5 seconds

Fix brand store snaps side panel and notifications

---

requirements.txt
webapp/api/exceptions.py
webapp/api/requests.py
webapp/login/views.py
webapp/publisher/views.py
webapp/store/snap_details_views.py
webapp/store/views.py

- Remove pybreaker, since it is not being useful.
- Added `gevent.Timeout` for HTTP requests with a limit close to the gunicorn timeout limit. This should avoid the restarts of the gunicorn worker and we should get the `GeventGreenletTimeout` exception on Sentry every time one was about to happen.
- Demo should work as usual
**This is a temporary change until we analyze the results**

Test with gevent.Timeout

---

static/sass/_snapcraft_release.scss

Changed the highlight colour of changed cells in the releases table
- Go to https://snapcraft-io-3877.demos.haus/danieltest-snap/releases
- Check that any highlighted cells are a light green colour with a dashed border
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2319

Change highlight colour for release table cells

---

templates/publisher/settings.html

Changed the label of the update metadata field on snap settings pages
- Go to https://snapcraft-io-3878.demos.haus/danieltest-snap/settings
- Check that the label for the update metadata field is "Update metadata on release"
Fixes #3879

Update copy for update metadata on release

---

static/js/publisher/release/components/releasesConfirm.js
static/js/publisher/release/components/releasesConfirmActions.js
static/js/publisher/release/releasesController.js
static/sass/_snapcraft_p-release-details-row.scss
static/sass/_snapcraft_release.scss

Added the changes summary of the release UI
- Go to https://snapcraft-io-3890.demos.haus/danieltest-snap/releases
- Make a change
- Check that a bar appears at the bottom of the screen with the number of changes and save/revert buttons
- Click on the changes count and check that the bar expands and shows the list of changes
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2320

Add changes summary to bottom of releases UI

---

webapp/api/requests.py

- Connection close header for API calls
I believe this might fix this issue however there is no way to QA, so we will have to see. Explanation:
> HTTP/1.1 by default allows a client to assume that keep-alive is supported unless the server disables it via 'Connection: close'
However, we need to check Sentry, some references:
https://stackoverflow.com/questions/33895739/python-requests-module-error-cant-load-any-url-remote-end-closed-connection/63641442#63641442
https://github.com/vavarachen/splunk_hec_handler/pull/8/files
https://github.com/psf/requests/issues/4784
Fixes #3875

Connection close header for API calls

---

static/js/brand-store/Publisher/Publisher.tsx
static/js/brand-store/Publisher/index.ts
static/js/brand-store/Reviewer/Reviewer.tsx
static/js/brand-store/Reviewer/index.ts
static/js/brand-store/ReviewerAndPublisher/ReviewerAndPublisher.tsx
static/js/brand-store/ReviewerAndPublisher/index.ts
static/js/brand-store/Snaps/Snaps.js
static/js/brand-store/types/global.d.ts
templates/admin/admin.html
webapp/admin/views.py

Added views for stores where the user is only a reviewer, publisher or both
- Make sure you are a publisher only in a store, a reviewer only in a store, and a reviewer and publisher in a store
- Go to https://snapcraft-io-3889.demos.haus/admin
- On the stores that you are only a reviewer you should see a reviewer page
- On the stores that you are only a publisher you should see a publisher page
- On the stores that you are a reviewer and publisher you should see a reviewer and publisher page
Fixes #3854

Add views for publishers and reviewers

---

static/js/publisher/release/components/contextualMenu.js
static/js/publisher/release/components/historyIcon.js
static/js/publisher/release/components/historyPanel.js
static/js/publisher/release/components/releasesTable/cellViews.js
static/js/publisher/release/components/releasesTable/channelHeading.js
static/js/publisher/release/components/releasesTable/channelRow.js
static/js/publisher/release/components/releasesTable/index.js
static/js/publisher/release/components/releasesTable/releaseCell.js
static/js/publisher/release/components/releasesTable/releaseMenuItem.js
static/js/publisher/release/components/releasesTable/revisionCell.js
static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/sass/_snapcraft_release.scss
templates/publisher/release-history.html

- Added visual changes to the revision cells
- Add menus to promote or release revisions on click rather than drag
- Go to https://snapcraft-io-3892.demos.haus/danieltest-snap/releases
- Hover over a release or revision cell
- Check that there is a "Promote" or "Release" button
- Click the button and select an option from the menu
- Check that the revision/release has been released/promoted
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2316

Revision cell changes to Release UI

---

static/sass/_snapcraft_release.scss

Only show the promote button in the release UI when the cell itself is hovered over
- Go to https://snapcraft-io-3904.demos.haus/danieltest-snap/releases
- Click on a cell in the releases table to expand it
- If you hover the cell you should see a "Promote" button
- The button should disappear when you are no longer hovering over the cell
Fixes #3903

Fix promote button hover state in the release UI

---

templates/publisher/listing.html

Fixed indent in nested options on listings page
- Go https://snapcraft-io-3914.demos.haus/inkscape/listing
- Scroll to the bottom of the page and check that the nested checkboxes in the metrics section are lined up
Fixes #3902

Fix settings options indent

---

static/sass/_snapcraft_release.scss

Fixed padding when releasing a revision
- Go to https://snapcraft-io-3915.demos.haus/danieltest2/releases
- Release a revision by dragging it's cell to the releases table
- The padding should stay the same
Fixes #3908

Fix release cell padding

---

templates/home/_fsf_ros.html
webapp/first_snap/content/ros/build.yaml
webapp/first_snap/content/ros/package.yaml
webapp/first_snap/content/ros/snapcraft.yaml
webapp/first_snap/content/ros/test.yaml
webapp/first_snap/content/ros2/build.yaml
webapp/first_snap/content/ros2/package.yaml
webapp/first_snap/content/ros2/test.yaml

- Remove "test" prefix from ROS examples
- Remove lsb-release dependency for ROS1
- Name ROS1 app with the name of the snap

first_snap(ROS): remove test prefix and update ROS1 snapcraft.yaml

---

requirements.txt
tests/store/tests_details.py
webapp/publisher/views.py
webapp/store/snap_details_views.py
webapp/store/views.py

- Replace some bad gateway to 404s
- Run `dotrun`
- Visit URLs for snaps that should return 404 on the publisher parts (listing, metrics, releases, etc...)
Fixes #3922

Replace some bad gateway to 404s

---

templates/_base-layout.html

- Add `AbortError` to the list of `ignoreErrors` for Sentry - these are triggered when the user aborts a request by either stopping the page loading or navigating away. They're not errors in the sense of something went wrong, but they manifest as 'the network request failed - because of the abort'.
- :shrug: 
Fixes #3933

[Sentry] Ignore AbortError messages

---

templates/publisher/builds.html
webapp/api/github.py
webapp/publisher/snaps/build_views.py

- Check if the GitHub app was revoked for snaps that are linked
- Locally connect your snap to the snapcraft.io GitHub OAuth app
- After that go to your GitHub setting and revoke the app
- Check that you get the following notification:
- And check that the notification goes away after clicking on the link.
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3918

Check if GitHub app was revoked for snaps that are linked

---

static/js/publisher/release/components/releasesTable/cellViews.js

- Added the pipe into a check if a build-request-id is available
- Visit a couple of snaps release pages, if they were built with launchpad a pipe + build id should appear, if not no pipe should appear (just the version number)
- https://snapcraft-io-3945.demos.haus/deno/releases has examples of both
Fixes #3932

Only show pipe if build-request-id is available

---

static/js/publisher/release/components/releasesTable/channelHeading.js
static/sass/_snapcraft_release.scss

- Reduce year representation to the final two digits (I don't think anyone will expect snaps to have been built before 2000 or after 2100 at this point)
- Ensure if the version + date is too long for the cell, don't wrap text, hide it
- Removed tooltip that wasn't being used
- Visit a snaps with many architectures and releases and long version …

Release UI - compact dates

---

static/js/publisher/release/components/releasesTable/cellViews.js
static/js/publisher/release/components/releasesTable/releaseCell.js
static/js/publisher/release/components/revisionLabel.js
static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/js/publisher/release/releasesState.js
static/sass/_snapcraft_release.scss
templates/publisher/release-history.html

- Add progressive release data to releases table cell
- Go to https://snapcraft-io-3949.demos.haus/core/releases
- Check that the progressive releases cell has the arrow between versions
Fixes #2331

Progressive releases table cell

---

templates/store/snap-details/_snap_heading_data.html

- _A changelist description explaining what the change achieves and why you’re making it._
- Visit https://charmhub-io-3955.demos.haus/microk8s and resize the browser - The canonical publisher should only ever be displayed once
Fixes #3953

Fix double publisher in header

---

static/js/publisher/release/components/releasesTable/cellViews.js
static/js/publisher/release/components/releasesTable/releaseCell.js
static/js/publisher/release/components/revisionLabel.js
static/js/publisher/release/selectors/index.js
static/js/publisher/release/selectors/selectors.test.js
static/sass/_snapcraft_release.scss

Added progressive release tooltip to releases table
- Go to https://snapcraft-io-3954.demos.haus/steve-test-snap/releases
- Check that there is a tooltip showing the progressive release status
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2332

Add progressive release tooltip

---

templates/publisher/publicise/embedded_cards.html
templates/publisher/publicise/github_badges.html

- Update checkboxes on the publicise pages
- Visit a snap publicise page and make sure the checkboxes are ok
Fixes #3938

Fix publicise checkboxes

---

static/js/brand-store/Settings/Settings.test.tsx
static/js/brand-store/Settings/Settings.tsx

In the brand store settings form, use the store ID from the URL to prevent the wrong ID being used when state has changed
- Go to https://snapcraft-io-3963.demos.haus/admin
- Go to a number of different stores settings pages e.g. /admin/<store-id>/settings
- Check that the ID in the "Store ID" field always matches the one in the URL
Fixes #3959

Use ID from URL in brand store settings

---

static/js/publisher/release/components/releasesTable/cellViews.js
static/js/publisher/release/components/releasesTable/channelHeading.js
static/js/publisher/release/components/releasesTable/row.js

Fixed the hover state on the release table
- Go to https://snapcraft-io-3968.demos.haus/danieltest-snap/releases
- Hover over the "Channel" cell and check that the whole row is highlighted
- Hover over any of the other cells and only that cell should be highlighted
Fixes #3898

Fix release table row hover state

---

static/js/brand-store/Snaps/SnapsFilter.js

Fixed a [Sentry error](https://sentry.is.canonical.com/canonical/snapcraft-io/issues/24375/) in the brand store
- Go to https://snapcraft-io-3967.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Use the search field to filter snaps and check that it works as expected
Fixes #3965

Fix brand store sentry error

---

static/js/publisher/release/components/contextualMenu.js
static/js/publisher/release/components/dnd.js
static/js/publisher/release/components/releasesTable/cellViews.js
static/js/publisher/release/components/releasesTable/channelHeading.js
static/js/publisher/release/releasesController.js

- Removed actions on release UI on mobile
- Added a notification on release UI on mobile to tell user it's read only
- Go to https://snapcraft-io-3978.demos.haus/notion-snap/releases
- Resize to mobile size
- There should be no drag handles, buttons (except the expand chevron) or tooltips on any of the table cells
Fixes #2479, #2480

Remove release UI actions on mobile

---

static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/js/publisher/release/releasesController.js

Made the release UI history table use the Vanilla card pattern
- Go to https://snapcraft-io-3979.demos.haus/notion-snap/releases
- Expand any of the table cells and resize the browser to mobile size
- The history table should display as the Vanilla cards pattern
Fixes #2328

Convert release UI history table to cards

---

static/js/brand-store/Members/MembersTable.js

Fixed the brand store member roles not showing on mobile
- Go to https://snapcraft-io-3989.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Resize the screen to mobile size
- Check that the roles checkboxes have the appropriate label
Fixes #3986

Show brand store member roles on mobile

---

static/js/publisher/release/components/revisionsList.js
static/sass/_snapcraft_release.scss

Updated the release history table pagination
- Go to https://snapcraft-io-4010.demos.haus/notion-snap/releases
- Expand a table cell
- Check that there are no more than 5 revisions showing and that the "Show more" button works
Fixes #4001

Update release history pagination

---

static/js/brand-store/Snaps/Snaps.js

- Fix missing snaps from the Global store
- Visit the web and design store: https://snapcraft-io-4013.demos.haus//admin/ahnuP3quahti9vis8aiw/snaps
- Check that the global store has a long list of snaps:
Fixes #4012

Admin: Fix missing snaps from the Global store

---

templates/store/snap-details.html

Fixed videos not showing on snap detail pages
- Go to https://snapcraft-io-4014.demos.haus/danieltest-snap
- Check that there is a video on the page
Fixes #3829

Fix video not displaying on snap detail pages

---

static/js/publisher/release/components/ProgressiveReleaseProgressChart.tsx
static/js/publisher/release/components/revisionsList.js
static/js/publisher/release/components/revisionsListRow.js
static/sass/_snapcraft_release.scss

Added the progressive releases progress chart for previous revisions
- Go to https://snapcraft-io-4015.demos.haus/notion-snap/releases
- Expand a release row that has a progressive release
- Check that the previous revision has a chart that shows the inverse of the progressive release chart
Fixes #3973

Add release progress chart for previous revisions

---

templates/store/snap-details.html
templates/store/snap-details/_details.html

Moved the links section on the listing page to the sidebar to bring it closer to the [metadata links design](https://app.zeplin.io/project/60d33b2bc5b9ab16ff7b90a6/screen/6194e2c128de08ab62923837)
- Go to https://snapcraft-io-4018.demos.haus/notion-snap
- Check that the website and contact links are now in the sidebar and not below the description
Fixes [#2605](https://github.com/canonical-web-and-design/marketplace-tribe/issues/2605)

Move listing page links to sidebar

---

static/sass/_snapcraft_metadata-links.scss
static/sass/styles.scss
templates/store/snap-details/_details.html
tests/tests_templates_utils.py
webapp/handlers.py
webapp/store/snap_details_views.py
webapp/template_utils.py

Added metadata links section to the snap details page using dummy data
- Go to https://snapcraft-io-4020.demos.haus/notion-snap?show_metadata_links=true
- Check that there is a "Links" section in the sidebar
- Check that there is a tooltip/title with the full URL on hover
- Check that clicking on one of the links opens a modal
- Check that clicking the "Go back" button closes the modal and keeps you on the page
- Check that clicking the "Proceed" button opens the link in a new tab and closes the modal
- Remove the query string and check that the new implementation of the "Links" section is no longer there
Fixes:
- https://github.com/canonical-web-and-design/marketplace-tribe/issues/2607
- https://github.com/canonical-web-and-design/marketplace-tribe/issues/2608
- …

Add metadata links to listing page template

---

templates/publisher/listing.html
templates/publisher/metadata/_donations.html
templates/publisher/metadata/_issues.html
templates/publisher/metadata/_source-code.html

Added metadata link fields to listing page form. **Note**: These fields do not work until the API is ready
- Go to https://snapcraft-io-4027.demos.haus/notion-snap/listing?show_metadata_links=true
- Check that there are fields for "Donations", "Source code" and "Issues"
- Remove the query string and check that those fields are no longer there
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2609

Add new metadata link fields

---

templates/publisher/settings.html

- Fix styling of webook row
- Add extra help text to explain why you would click the link
- Visit the settings page for a snap that has github set up
- See the help text
Fixes #3393

Add some extra information on the set up webook link in settings

---

static/js/publisher/preview.js

Disallow links in snap previews
- Go to a snap listing page on https://snapcraft-io-4036.demos.haus/
- Put a markdown link in the description e.g. `[This is a link](https://example.com)`
- Use the preview and check that it isn't rendered as a text link, only the URL is linked
Fixes #4035

Disallow markdown links in preview

---

package.json
static/js/publisher/listing/components/App/App.test.tsx
static/js/publisher/listing/components/App/App.tsx
static/js/publisher/listing/components/NavTabs/NavTabs.test.tsx
static/js/publisher/listing/components/NavTabs/NavTabs.tsx
static/js/publisher/listing/components/NavTabs/index.ts
static/js/publisher/listing/components/PageHeader/PageHeader.test.tsx
static/js/publisher/listing/components/PageHeader/PageHeader.tsx
static/js/publisher/listing/components/PageHeader/index.ts
static/js/publisher/listing/components/SaveAndPreview/SaveAndPreview.test.tsx
static/js/publisher/listing/components/SaveAndPreview/SaveAndPreview.tsx
static/js/publisher/listing/components/SaveAndPreview/index.ts
yarn.lock

Added the header, navigation and save/preview bar to the new listing page
- Go to https://snapcraft-io-4037.demos.haus/notion-snap/listing?show_react_listing=true (or any other snap)
- Check that the "Revert" and "Save" buttons are disabled
- Change the text in the field
- Check that the "Revert" and "Save" buttons are no longer disabled
- Undo any changes you made to the text in the field
- Check that the "Revert" and "Save" buttons are disabled
- Change the text in the field
- Check that the "Revert" and "Save" buttons are no longer disabled
- Click the "Revert" button
- Check that the "Revert" and "Save" buttons are disabled
- Check that the "My snaps" link goes to `/snaps`
- Check that the "snap listing page" link goes to the right listing page
- Check that the tabbed navigation go to …

Add header to listing page

---

package.json
snapshots.yml

- Add percy tests for first snap flow, /iot and /build pages 
- Run `export PERCY_TOKEN=[token_here]; node_modules/.bin/percy snapshot snapshots.yml`
- Visit the URL provided when Percy completes

Add some basic percy tests for less-QA'd parts of the site

---

.github/workflows/run-percy.yml

- Create a workflow that runs percy snapshots at 3am tuesday, wednesday, thursday, friday and saturday.
- Why those days? I don't expect anyone to make changes on Sunday, so why bother running it on Monday? Same with Saturday, why run it on Sunday?

Run Percy snapshot tool at 3am tues, wed, thurs, fri and sat

---

static/js/public/hero-tabpanel.js

Fix `undefined` showing on some homepage cards
- Go to https://snapcraft-io-4052.demos.haus/
- Click on the "Featured" slide and check that "Jami" doesn't have `undefined` next to "Savoir-faire Linux"
Fixes #4051

Fix undefined showing on homepage cards

---

static/js/publisher/release/components/releasesTable/releaseCell.js

- `getRevisionsFromBuilds` wasn't being using in the component, so remove it
This should hopefully reduce the overhead of displaying a cell.
- Visit https://snapcraft-io-4055.demos.haus//juju/releases
- Hopefully it loads quicker

Remove getRevisionsFromBuilds from releaseCell.js

---

static/js/publisher/listing/components/App/App.tsx
static/js/publisher/listing/components/MultipleInputs/MultipleInputs.tsx
static/js/publisher/listing/components/MultipleInputs/index.ts
static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
static/js/publisher/listing/utils/getChanges.ts
static/js/publisher/listing/utils/getFormData.ts
static/js/publisher/listing/utils/getListingData.ts
static/js/publisher/listing/utils/index.ts
webapp/publisher/snaps/listing_views.py

Added the metadata links fields to the listing page form
- Go to https://snapcraft-io-4072.demos.haus/notion-snap/listing?show_react_listing=true&show_metadata_links=true
- Check that there are Websites, Contacts, Donations, Source code and Issues fields
- Check that you can add and remove fields and that the form is enabled/disabled as expected
- **NOTE: THIS IS DUMMY DATA SO WON'T ACTUALLY BE SAVED**
- Remove the `show_metadata_links` query string and check that the metadata links fields are not there
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2650
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2610

Add metadata links fields

---

templates/publisher/publicise/_publisher_publicise_layout.html
tests/publisher/snaps/tests_publicise.py
webapp/publisher/snaps/publicise_views.py

- Add check to see if the channel-map has releases
- Update publicise template to disable the page if the snap is private or if there aren't any releases
- Visit the demo
- On a test snap, close all channels on the releases page and ensure the snap is set to "public" on the settings page
- Got to the publicise page and see it's disabled
Fixes #3473

Disable publicise page if snap has no release

---

requirements.txt

- Bump canonicalwebteam.discourse module that includes the following fix: https://github.com/canonical/canonicalwebteam.discourse/pull/140
- Click around docs and make sure things works as expected
Fixes #4068

Bump canonicalwebteam.discourse module to latest version

---

static/js/publisher/listing/components/PreviewForm/PreviewForm.tsx
static/js/publisher/listing/utils/getListingData.ts

Fixed the category display on listing page previews
- Go to https://snapcraft-io-4085.demos.haus/SNAP_NAME/listing?show_react_listing=true
- Use the preview button to launch a preview of the listing page
- Check that the categories are present underneath the snap title
Fixes #4041

Fix snap preview categories on React listing page

---

static/sass/_patterns_media-object--snap.scss

Fixed hidden tooltip on featured snap cards
- Go to https://snapcraft-io-4107.demos.haus/
- Hover over the tick next to the publisher name on any of the featured snaps
- Check that the tooltip is visible
Fixes #4106

Fix homepage card tooltips

---

static/js/publisher/listing/components/App/App.tsx
static/js/publisher/listing/utils/index.ts
static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts

- Fixed an issue where the warning about updating metadata showed when the only change was to images (icon, banner, screenshots)
- Go to https://snapcraft-io-4109.demos.haus/SNAP_NAME/settings
- Make sure that `Update metadata on release` is enabled
- Go to https://snapcraft-io-4109.demos.haus/SNAP_NAME/listing
- Change an icon, banner or screenshot
- Check that you can save the changes without a modal warning first
- Go to https://snapcraft-io-4109.demos.haus/SNAP_NAME/settings
- Check that the `Update metadata on release` is still enabled
- Go to https://snapcraft-io-4109.demos.haus/SNAP_NAME/listing
- Change any field that isn't an image
- Check that when you go to save the images you have a modal confirming that you understand that the update metadata setting will be disabled
- Save …

Fix metadata warning when changing images

---

templates/publisher/account-snaps.html

Removed flash messages from /snaps
- Go to https://snapcraft-io-4133.demos.haus/SNAP_NAME/listing
- Make some changes and save them
- Go to https://snapcraft-io-4133.demos.haus/snaps
- There should not be any "Changes have been saved" messages
Fixes #4132

Remove flash messages from published snaps page

---

webapp/publisher/snaps/listing_views.py
webapp/publisher/snaps/settings_views.py

Stopped setting flash messages on listing and settings pages as they are not used and could be displayed on other pages in error
- Go to https://snapcraft-io-4134.demos.haus/SNAP_NAME/listing
- Make changes and save
- Check that you see a saved successfully notification
- Go to https://snapcraft-io-4134.demos.haus/SNAP_NAME/settings
- Make changes and save
- Check that you see a saved successfully notification
Fixes #4132

Fix flash message consumption

---

static/js/publisher/collaboration/components/App/App.tsx
static/js/publisher/collaboration/components/App/index.tsx
static/js/publisher/collaboration/index.tsx
static/js/publisher/collaboration/types/index.d.ts
static/js/publisher/shared/PageHeader/PageHeader.tsx
templates/publisher/collaboration.html
webapp/publisher/snaps/collaboration_views.py
webapp/publisher/snaps/views.py
webpack.config.entry.js

Added the collaborations tab to the publisher pages
- Go to https://snapcraft-io-4137.demos.haus/SNAP_NAME/collaboration
- Check that there is a page with the snap name, publisher name and the navigation (note that the link for this page is not in the navigation because we don't want to expose this page)
Fixes #4113

Add collaborations tab

---

static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx

Fixed the email validation on the listing page
- Go to https://snapcraft-io-4148.demos.haus/SNAP_NAME/listing
- Check that you can add a query string to the contact email address, e.g. (email@email.com?subject=foo)

Remove email address validation from the listing page

---

tests/publisher/snaps/tests_post_release.py
webapp/publisher/snaps/release_views.py

There is no need to check if the user is the owner or has permission because the API will do it.

Remove check as the API will handle it

---

static/js/brand-store/slices/membersSlice.ts
static/js/brand-store/slices/snapsSlice.ts

Fixed a bug that shows that a store is not found when navigated to from the side navigation following loading a store that you don't have full access for.
- Go to https://snapcraft-io-4153.demos.haus/admin
- Use the side navigation to go to a store that you are a publisher in
- Then use the side navigation to go to a store that you have access to
- You should see the store and not the "Store not found" page
- Change the store ID in the URL to an ID that doesn't exist
- You should see the "Store not found" page
Fixes #4152

Fix no store screen showing

---

templates/partials/_newsletter-signup.html

- fix display of checkbox and its label content in the newsletter on blog page
- visit /blog and check the newsletter signup card
Fixes #4063

fix display of checkbox and its label content in the newsletter on blog page

---

static/js/publisher/release/components/releasesConfirm.js
static/js/publisher/release/components/releasesHeading.js
static/js/publisher/release/releasesController.js
static/sass/_snapcraft_p-release-details-row.scss
static/sass/_snapcraft_release.scss
templates/publisher/release-history.html

- Moved the changes bar from the footer to the top of the releases page
- Go to a snaps releases page, e.g. https://snapcraft-io-4167.demos.haus/steve-test-snap/releases
- Make a change and check that the sticky bar with the changes is just beneath the publisher pages navigation
Fixes #4128 
Fixes https://warthogs.atlassian.net/browse/WD-705

Change position of snap releases change bar

---

static/js/publisher/settings/components/App/App.tsx
static/js/publisher/settings/utils/getFormData.ts
tests/publisher/snaps/tests_post_settings.py
tests/publisher/snaps/tests_settings.py
webapp/publisher/snaps/settings_views.py
webapp/publisher/snaps/views.py

- Settings App.tsx:
- Refactor onSubmit to handle meta `visibility` field from the form
- Refactor onSubmit to handle return of success to construct meta `visibility` field for the form
- Remove notifications of previous saves on submit
- Call new `settings.json` endpoint to avoid a page reload
- Set form data to the data returned by the json endpoint
- Update error message on failure
- Ensure `update_metadata_on_release` is converted to a boolean
- Settings getFormData:
- Ensure `update_metadata_on_release` is always set (temporary)
- settings_views.py
- Add associated json methods for `get_settings` and `post_settings`
- Update `get_settings` and `post_settings` to accept second param `return_json`
- Ensure license is using the `snap_details` `license`. Not an undefined variable
- For …

Refactor settings page

---

webapp/store/views.py

- Fix links
- Visit https://snapcraft-io-4179.demos.haus/publisher/canonical
- Click a snap, you should go to the snap page
Fixes #

fix(bug): Fix snap links for publisher pages

---

templates/partials/_hiri-case-study.html
templates/store/snap-details.html

Removed calls to blog post fetching and related markdown from snap details pages, as agreed with PdM
Visit https://snapcraft-io-4191.demos.haus/code and make sure blog posts don't show
Visit https://snapcraft-io-4191.demos.haus/hiri and make sure that a case study shows, but no blog posts
Fixes https://warthogs.atlassian.net/browse/WD-1196

Remove blog posts from snap details pages

---

requirements.txt
templates/publisher/account-details.html
templates/store/_media-object-snap-partial.html
templates/store/community-publisher-details.html
templates/store/snap-details/_details.html
tests/publisher/endpoint_testing.py
tests/publisher/tests_publisher.py
tests/publisher/tests_publisher_logic.py
tests/snapcraft/tests_public.py
tests/store/tests_public_logic.py
tests/tests_templates_utils.py
webapp/admin/views.py
webapp/handlers.py
webapp/metrics/metrics.py
webapp/publisher/snaps/logic.py
webapp/publisher/views.py
webapp/store/logic.py
webapp/store/snap_details_views.py
webapp/template_utils.py

- Added [emoji](https://carpedm20.github.io/emoji/docs/) dependency
- Added template utility to format display names 
- Load the demo, search for "pdf" the first item should no longer have a checkmark emoji.
- Click the snap, the display name should also not have a checkmark emoji.
- Click the username, on this page the display name should not have a checkmark emoji.
Fixes #
:arrow_down:

Remove specific emoji from display names

---

static/js/publisher/listing/components/ImageUpload/ImageUpload.tsx
static/js/publisher/listing/sections/ListingDetailsSection/ListingDetailsSection.tsx
static/sass/_snapcraft_snap-image-upload.scss
static/sass/styles.scss

Added a dark mode preview for snap icons
- Go to a snaps listing page, e.g. https://snapcraft-io-4202.demos.haus/steve-test-snap/listing
- Check that the icon has a working dark mode preview
Fixes #4193
Fixes https://warthogs.atlassian.net/browse/WD-1891

Enable dark mode preview for icon upload

---

static/js/brand-store/Snaps/Snaps.js

Added a confirmation modal for when a user excludes snaps from a store
- Go to https://snapcraft-io-4204.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Select a snap or snaps to exclude
- Click the "Exclude snap(s)" button
- Check that there is a confirmation modal
- Check that clicking the "Exclude snap(s)" button excludes the snap
Fixes #4203

Add a confirmation modal when excluding snaps

---

redirects.yaml
templates/_header.html
templates/about/publish.html
webapp/template_utils.py

- Redirect all /tutorials to /docs/snap-tutorials
- Update tutorials navigation link
- Update in-page links to removed tutorials to appropriate places
- Ensure "Tutorials" is highlighted when on the /docs/snap-tutorials page
- Visit the [demo](https://snapcraft-io-4205.demos.haus/), attempt to go to the following urls:
- https://snapcraft-io-4205.demos.haus/tutorials
- https://snapcraft-io-4205.demos.haus/tutorials/snap-download
- https://snapcraft-io-4205.demos.haus/tutorials/snap-changes
- https://snapcraft-io-4205.demos.haus/tutorials/advanced-snap-usage
- https://snapcraft-io-4205.demos.haus/tutorials/create-your-own-core-20-image
- https://snapcraft-io-4205.demos.haus/tutorials/create-your-own-core-18-image
- https://snapcraft-io-4205.demos.haus/tutorials/continuous-snap-delivery-from …

Redirect all tutorials from /tutorials -> /docs/snap-tutorials

---

static/sass/_snapcraft_l-application.scss

Fixed z-index bug in brand store include snap sidebar
- Go to https://snapcraft-io-4210.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Click "Include snap"
- Click into the search box
- Check that the sidebar remains open
Fixes https://warthogs.atlassian.net/browse/WD-2386

Fix bug in include snap form

---

templates/_header_empty.html

- Updated the empty header on distro install pages
- Go to https://snapcraft-io-4213.demos.haus/install/pinta/ubuntu
- Check that the header is dark and has the new logo
Fixes #4212
Fixes https://warthogs.atlassian.net/browse/WD-2429

Update empty header

---

static/js/publisher/listing/utils/getFormData.ts
static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts
tests/publisher/snaps/tests_post_listing.py
webapp/publisher/snaps/listing_views.py

Fixed a bug where changing icons or video URLs disabled "update_metadata_on_release"
- Go to https://snapcraft-io-4220.demos.haus/<SNAP_NAME>/settings
- Make sure that "Update metadata on release" is enabled
- Go to https://snapcraft-io-4220.demos.haus/<SNAP_NAME>/listing
- Check that changing the icon, banner or video fields don't disable "Update metadata on release"
Fixes #4159
Fixed https://warthogs.atlassian.net/browse/WD-488

Fix metadata being disabled

---

static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts

Fixed a bug where changing categories on the snap listing page disabled "update_metadata_on_release"
- Go to https://snapcraft-io-4221.demos.haus/<SNAP_NAME>/settings
- Make sure that "Update metadata on release" is enabled
- Go to https://snapcraft-io-4221.demos.haus/<SNAP_NAME>/listing
- Check that changing the category fields doesn't disable "Update metadata on release"

Fix metadata updates

---

webapp/login/views.py

- Removed try-except on login methods – really let's throw and track what's happening
- If the retrieved account has relevant stores, fetch those stores using the admin_api.
- Login to the demo using both https://snapcraft-io-4229.demos.haus/login and https://snapcraft-io-4229.demos.haus/login-beta
- Ensure everything works as expected during the login process
- If you have access to brand stores, "My Stores" should appear in the user menu (and work)
Fixes #3838 hopefully

Improve fetching of brand-stores on login

---

static/js/publisher/listing/components/App/App.tsx
static/js/publisher/settings/components/App/App.tsx
static/js/publisher/shared/UpdateMetadataModal/UpdateMetadataModal.tsx
static/js/publisher/shared/UpdateMetadataModal/index.ts

Added a warning modal to snap settings page when making changes that disable `update_metadata_on_release`
- Go to https://snapcraft-io-4233.demos.haus/<SNAP_NAME>/settings
- Make sure "Update metadata on release" is enabled
- Make a change to the data and try to save the form
- Check that there is a warning modal
Fixes https://warthogs.atlassian.net/browse/WD-2794

Add update metadata warning on snap settings page

---

static/sass/_snapcraft_p-build.scss
templates/snapcraft/build.html

- implemented a build page for Snapcraft.io rebranding
- Go to https://snapcraft-io-4243.demos.haus/build
- Compare to the designs:
[web](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/640f327cfadf3622886ecb31)
[mobile](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/64218ee4d08a97229b1f33f1)
Fixes https://warthogs.atlassian.net/browse/WD-2955

implement a build page for Snapcraft.io rebranding

---

.github/workflows/pr.yml

Latest actions image started defaulting to node 18 and broke some tests. Forcing node 16 as before to get everything back to green.
- Check `test-js` is passing.

Actions: Force node 16 on test-js job 

---

static/js/public/about/listing.ts
templates/about/listing.html
webpack.config.entry.js

Implement new design on about your snap page
- Go to https://snapcraft-io-4254.demos.haus/about/listing
- Compare to the [desktop](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/6410887a0b441d101510d231) and [mobile](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/6421773ea81e5722e0b74fdb) designs
- **NOTE**: The content in the design doesn't match the content available for the tabbed section so some of that section isn't there. Also the vertical line between the navigation and the tab panels is missing because it breaks the grid and therefore needs to be considered more carefully. This can be discussed pre-launch.
Fixes https://warthogs.atlassian.net/browse/WD-2960

Wd 2960 build about your snap page

---

templates/about/release.html

- built a Release your snap page for Snapcraft rebranding
- Go to https://snapcraft-io-4248.demos.haus/about/release
- Compare designs to [web](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/641088808f9ea410a6dcb5f1) and [mobile](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/642177382c854822aeed884c)
Fixes https://warthogs.atlassian.net/browse/WD-2961

built a Release your snap page for Snapcraft rebranding

---

templates/publisher/builds.html
webapp/publisher/snaps/build_views.py

- More defence against current and future bases that do not start with “core” (specifically fix `bare` base).
- [Drive-by] Update message for i386 on core20+.
- Pull the branch/ Visit the demo
- Update one of your test snaps to build from a github repo.
- Update the github repo's snapcraft.yaml with `base: bare` and `build-base: core22` ([example](https://raw.githubusercontent.com/Lukewh/test-lukewh-build/master/snap/snapcraft.yaml))
- Trigger a build
- Success
Fixes #4231 
https://warthogs.atlassian.net/browse/WD-3676

Build: Handle none-core bases

---

requirements.txt

By using the fixed version of canonicalwebteam.discourse.
https://github.com/canonical/canonicalwebteam.discourse/pull/161/files
On the demo. go to https://snapcraft-io-4263.demos.haus/docs. Click around a lot, click back to the same page a bunch of times. Check the navigation always reflects the correct page (unlike on live)

Fix active topic caching in docs

---

static/js/publisher/release/components/releasesConfirm.js

- fixed the chevron icon on releases UI
- Click releases tab in your published snap in https://snapcraft-io-4271.demos.haus 
- Check if the chevron icon is down when release update notification is closed or vice versa.
Fixes #https://warthogs.atlassian.net/browse/WD-3319

fix the chevron icon on releases UI

---

templates/_base-layout.html

Remove default copydoc url
- Install https://github.com/canonical/ubuntu-copy-docs
- Visit https://snapcraft-io-4283.demos.haus/build - see the copydoc link
- Visit https://snapcraft-io-4283.demos.haus/krita - no copydoc link
- Visit https://snapcraft-io-4283.demos.haus/docs - no copydoc link
Fixes https://github.com/canonical/snapcraft.io/issues/4201

Remove copydoc from pages that don't explicitly have a copydoc

---

webapp/authentication.py
webapp/login/views.py
webapp/store/snap_details_views.py

- Remove the fetching of the list from login flow
What this means for end users:
- Allow anyone to see the "trending" badge if they set `?preview=true` to the svg file - not a big deal imo
- Only display the "Ensure your snap always stays relevant..." on the details pages of snaps the user owns (won't show on snaps they're a collaborator on)
- Login to https://snapcraft-io-4286.demos.haus/
- Click a snap you own > Publicise > GitHub Badges > check the "Trending status" checkbox and ensure the "Trending" image appears
- Ffind a snap you own, and one you are a collaborator for.
- Visit the pages for each: https://snapcraft-io-4286.demos.haus/<snap_name>
- The snap you own should display a message at the top of the page "Ensure your snap always stays relevant and compelling. [Update its …

Remove list of snaps a user is a collaborator on from session

---

static/sass/_snapcraft_p-build.scss
templates/snapcraft/build.html

- Added some extra css to ensure build image stays correctly positioned on various screen sizes
- Visit https://snapcraft-io-4296.demos.haus/build
- Resize window, the image at the top should stay well positioned.

Build - ensure image stays centred and segmented

---

templates/partials/fsf_language.html

Fixed a bug where the ROS 2 link wasn't working
- Go to https://snapcraft-io-4297.demos.haus/
- Resize to mobile view
- In the "Learn how to snap an app in 30 minutes" section, change language to "ROS 2"
- It should update the content
Fixes https://warthogs.atlassian.net/browse/WD-4729

Fix ROS 2 not working on mobile

---

konf/site.yaml
konf/staging-api.snapcraft.io.yaml

I've updated https://jenkins.canonical.com/webteam/job/staging-api.snapcraft.io/ to pull the apprioriate registry from the konf file, and https://jenkins.canonical.com/webteam/job/snapcraft.io/ uses the standard deploy script which is already configured that way.

Use PS5 registry

---

static/js/brand-store/brand-store.tsx
static/js/brand-store/types/global.d.ts
webpack.config.entry.js

Converted the brand store root file to TypeScript
- Go to https://snapcraft-io-4305.demos.haus/admin
- Check that the app loads without errors

Convert brand store root to TypeScript

---

static/js/publisher/release/releasesState.js

Fixed logic which displays progressive releases
- Go to https://snapcraft-io-4306.demos.haus/pc/releases
- Change the track in the top left dropdown to "20" or "22"
- There should be no cells that show progressive releases
Fixes #4304

Fix progressive release cells

---

static/sass/_snapcraft_l-application.scss
templates/_header.html

- Changed the label for "About" in the navigation to "About Snapcraft" on mobile
- Drive by: Fixed z-index issue with global nav and brand store side navigation
- Go to https://snapcraft-io-4311.demos.haus/
- Check that the "About" label in the navigation has changed to "About Snapcraft"
Fixes https://warthogs.atlassian.net/browse/WD-4868

Update navigation label

---

static/js/brand-store/components/Snaps/Snaps.tsx
static/js/brand-store/components/Snaps/SnapsFilter.tsx
static/js/brand-store/components/Snaps/SnapsSearch.tsx
static/js/brand-store/components/Snaps/SnapsTable.tsx
static/js/brand-store/components/Snaps/SnapsTableRow.tsx
static/js/brand-store/components/Snaps/index.js
static/js/brand-store/components/Snaps/index.ts
static/js/brand-store/types/shared.ts

Converted the brand store snaps to TypeScript
- Go to https://snapcraft-io-4312.demos.haus/admin
- Check that the snaps still load without errors
Fixes https://warthogs.atlassian.net/browse/WD-4853

Convert brand store snaps to TypeScript

---

static/js/brand-store/components/Snaps/Snaps.tsx

Fixed a bug where a store that includes another store will not load
- Go to https://snapcraft-io-4315.demos.haus/admin
- Check that all the stores you have access to load
Fixes #4314

Fix check for other stores in brand store

---

static/js/brand-store/components/Snaps/Snaps.tsx

Fixed issue where superset brand stores are not loading
Can't QA as we don't have access to any of these stores, however the reporter of the bug has confirmed this fix works (https://github.com/canonical/snapcraft.io/issues/4314#issuecomment-1621728759)
In relation to https://github.com/canonical/snapcraft.io/issues/4314#issuecomment-1620932748

Fix for superset brand stores not loading

---

static/sass/_snapcraft_l-application.scss
static/sass/styles.scss
templates/_header.html
templates/admin/admin.html

Made the header navigation full width on the brand store
- Go to https://snapcraft-io-4330.demos.haus/
- Check that the header is the same as on snapcraft.io
- Go to https://snapcraft-io-4330.demos.haus/admin
- Check that the header is full width

Make header full width in brand store

---

static/js/brand-store/components/Models/Models.tsx
static/js/brand-store/components/Models/ModelsTable.tsx

Fixed a bug where the "Policy revision" column wasn't populated on the models page
- Go to https://snapcraft-io-4347.demos.haus/login-beta and login
- Go to https://snapcraft-io-4347.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that the "Policy revision" column is populated for the "test_model_without_api_key" model (it might take a moment due to doing multiple requests)
Fixes https://warthogs.atlassian.net/browse/WD-5188

Fix bug with missing policiy revision

---

static/js/brand-store/components/Model/Policies.tsx
static/js/brand-store/components/Models/Models.tsx
static/js/brand-store/components/Models/ModelsTable.tsx

- Fixed an issue where the signing keys weren't showing in the policies table
- Drive by: Truncated model names in the models table
- Drive by: Made loading error messages a Vanilla notification
- Go to https://snapcraft-io-4359.demos.haus/login-beta and log in
- Go to https://snapcraft-io-4359.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/test_model_without_api_key/policies
- Check that there are signing keys in the table

Fix name overflow on models table

---

static/js/brand-store/components/Snaps/Snaps.tsx

Fixed a bug where other stores weren't showing in the brand store
- Go to https://snapcraft-io-4366.demos.haus/admin/TestInternalStoreTeam2023/snaps
- Check that "Test Store Team Store" is in the table and contains "newsnapbuild"
Fixes https://warthogs.atlassian.net/browse/WD-5427

Fix other stores not showing in brand store

---

static/js/brand-store/components/Models/ModelsTable.tsx
static/js/brand-store/utils/maskString.test.ts
static/js/brand-store/utils/maskString.ts

Changed the way API keys are masked in the models service
- Go to https://snapcraft-io-4367.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that the API key is displayed in the following format: "...abcdef"
Fixes https://warthogs.atlassian.net/browse/WD-5600

Change display of api keys in models service

---

static/js/brand-store/components/Members/Members.tsx
static/js/brand-store/components/Model/Policies.tsx
static/js/brand-store/components/Models/Models.tsx
static/js/brand-store/components/SigningKeys/SigningKeys.tsx
static/js/brand-store/components/Snaps/Snaps.tsx

- Swapped the order of the search and CTA on the brand store pages
- Drive by: Fixed bug where view stores would redirect to "Store not found" if the members didn't load
- Go to the following pages and check that the search/filter is on the left and the CTA buttons are on the right
- https://snapcraft-io-4370.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- https://snapcraft-io-4370.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/test_model_without_api_key/policies
- https://snapcraft-io-4370.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys
- https://snapcraft-io-4370.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- https://snapcraft-io-4370.demos.haus/admin/ahnuP3quahti9vis8aiw/members
Fixes https://warthogs.atlassian.net/browse/WD-5613

Swap search and CTA in brand store

---

static/js/brand-store/components/Navigation/Navigation.tsx
static/sass/_patterns_icons.scss
static/sass/_snapcraft_l-application.scss
static/sass/styles.scss

Removed the icon from the brand store sidebar
- Go to https://snapcraft-io-4371.demos.haus/admin
- Check that there are no icons next to the store names
- Check that the highlight colour to the left of the store name is black
Fixes https://warthogs.atlassian.net/browse/WD-5628

Update brand store side nav

---

webapp/store/content/distros/opensuse.yaml

Updated 3 years old openSUSE page
Install snap via updated description on both openSUSE versions

Update openSUSE page with new Leap, optimize systemctl commands

---

requirements.txt
static/js/brand-store/components/SectionNav/SectionNav.test.tsx
static/js/brand-store/components/SectionNav/SectionNav.tsx
static/js/brand-store/components/Settings/Settings.test.tsx
static/js/brand-store/components/SigningKeys/DeactivateSigningKeyModal.tsx
static/js/brand-store/hooks/index.ts
static/sass/styles.scss
webapp/admin/views.py

- Show models and signing keys in the brand store navigation if available to the user
- Go to https://snapcraft-io-4385.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that "Models" and "Signing keys" are in the horizontal navigation
- Go to https://snapcraft-io-4385.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Check that "Models" and "Signing keys" are not in the horizontal navigation
Fixes https://warthogs.atlassian.net/browse/WD-4749

Check brand for models navigation

---

templates/snapcraft/build.html

- Updated ubuntu logo on /build page
- Visit https://snapcraft-io-4386.demos.haus/build
- See the new ubuntu logo.
Fixes https://warthogs.atlassian.net/browse/WD-5846

Update ubuntu logo on /build

---

static/js/brand-store/components/Model/Policies.tsx

Fixed issue where the "Create policy" form didn't submit when the enter key was pressed
- Go to https://snapcraft-io-4394.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/alimot_test_model_a/policies/create
- Select a signing key
- Whilst still focused in the signing key field press "Enter"
- The form should submit and a new policy should be created
Fixes https://warthogs.atlassian.net/browse/WD-5589

Make new policy form submit with enter key

---

static/js/brand-store/components/Model/CreatePolicyForm.tsx
static/js/brand-store/components/Model/Policies.tsx
static/js/brand-store/components/Models/CreateModelForm.tsx
static/js/brand-store/components/Models/Models.tsx
static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
static/js/brand-store/components/SigningKeys/SigningKeys.tsx

- Converted "Cancel" buttons to links on the create model/policy/signing key forms
- Clear the create model/policy/signing key forms when closed
- Go to https://snapcraft-io-4399.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/create
- Fill out the form
- Click outside the side panel
- Reopen the side panel
- Check that the form has been reset
- Go to https://snapcraft-io-4399.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/alimot_test_model_a/policies/create
- Fill out the form
- Click outside the side panel
- Reopen the side panel
- Check that the form has been reset
- Go to https://snapcraft-io-4399.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys/create
- Fill out the form
- Click outside the side panel
- Reopen the side panel
- Check that the form has …

Convert model service cancel buttons to links and clear forms on close

---

static/js/brand-store/components/Model/Model.test.tsx
static/js/brand-store/components/Model/Model.tsx

Disable the "Revert" button on the model page unless a new key has been generated
- Go to https://snapcraft-io-4402.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/alimot_test_model_a
- Check that the "Revert" button is disabled
- Generate a new key
- Check that the "Revert" button is enabled
- "Revert" the change
- Check that the "Revert" button is disabled
Fixes https://warthogs.atlassian.net/browse/WD-6232

Disable model key revert button if no change

---

static/js/publisher/builds/components/buildsTable.js

Fixed issue with builds table column duplicating content
- Go to https://snapcraft-io-4412.demos.haus/mindustry/builds
- Resize to mobile/tablet view and check that the "Result" column doesn't have duplicated content
Fixes #4411

Fix duplicated content in build table

---

templates/partials/_video.html
webapp/store/views.py

- Updated the /youtube endpoint to be POST only
- Pass CSRF token from the ajax POST request
- Visit https://snapcraft-io-4416.demos.haus/code
- The youtube thumbnail should not be pixelated
Fixes https://sentry.is.canonical.com/canonical/snapcraft-io/issues/40203/?query=is%3Aunresolved

Add CSRF protection to the free youtube proxy we have created

---

static/js/publisher/settings/components/App/App.tsx

Stop showing modal when changes are made to a snaps distribution settings
- Go to https://snapcraft-io-4422.demos.haus/SNAP_NAME/settings
- Enable "Update metadata on release" if it isn't already and submit the form
- Make a change to the "Distribution" field and save the form
- You should **not** get a warning modal
- This "Update metadata on release" does get disabled which is something the store team are fixing
Fixes https://warthogs.atlassian.net/browse/WD-6609

Only show metadata warning modal for visibility changes

---

static/sass/styles.scss

Fix visual bug where invites modal doesn't cover the whole screen
- Go to https://snapcraft-io-4423.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Go to the invites table and click "Revoke" on one of the invites
- Check that the modal background covers the whole screen
Fixes https://warthogs.atlassian.net/browse/WD-4855

Fix invite modal display

---

webapp/publisher/snaps/build_views.py

If available, use `build-base` from the snapcraft.yaml, fallback to `base` if not available.
Visit the build page for a snap that only has `base` defined – it should work as before (https://snapcraft-io-4435.demos.haus/test-snap-lukewh-7/builds)
Visit the build page for a snap that has `build-base` defined – it should also work (https://snapcraft-io-4435.demos.haus/pc-desktop/builds)
Fixes https://github.com/canonical/snapcraft.io/issues/4427
Fixes https://warthogs.atlassian.net/browse/WD-7002

Use build-base if available, fallback to base

---

templates/store/snap-details/_details.html
tests/store/tests_public_logic.py
tests/tests_templates_utils.py
webapp/store/logic.py
webapp/store/snap_details_views.py

- Added the last updated from `default_track/highest_stability` + the most recently updated channel.
- Updated some tests that were giving a deprecation warning
- Visit the demo
- Click on a lot of different snaps
- Make sure the "Last Updated" metadata makes sense
Fixes https://github.com/canonical/snapcraft.io/issues/4424
Fixes https://warthogs.atlassian.net/browse/WD-7005

Add both highest stable version and most recent updated

---

static/js/brand-store/components/Settings/Settings.tsx
webapp/admin/views.py

Changed the HTTP method of settings updates in the brand store from `POST` to `PUT` as it is only updating existing data rather than creating new data
- Go to https://snapcraft-io-4441.demos.haus/admin/ahnuP3quahti9vis8aiw/settings
- Make a change and save it
- Check that the change is made successfully

Update HTTP method for settings in brand store

---

static/sass/styles.scss

Added styles to make `code` blocks work like `pre` in docs
- Go to https://snapcraft-io-4443.demos.haus/ondra-snap-ssh-debug
- Check that the code blocks don't break out of the text boundaries

Add hack for long code blocks in docs

---

templates/publisher/request-reserved-name.html

- list a store name in a snap name request form
- Go to https://snapcraft-io-4462.demos.haus/snaps
- Click `Register a snap name` and then `request a reserved name` in the form.
- Check if you see your `store name` instead of `Global` in the "Are you sure" message
Fixes #https://warthogs.atlassian.net/browse/WD-7511
Fixes #https://github.com/canonical/snapcraft.io/issues/4398

list a store name in a snap name request form

---

package.json
static/js/store/components/Packages/Packages.tsx
static/js/store/types/index.d.ts
static/js/store/types/shared.ts
templates/store/beta.html
webapp/store/views.py
yarn.lock

Removed all snaps and use featured snaps
- Go to https://snapcraft-io-4469.demos.haus/beta-store
- Check that there is no featured banner
- Check that the featured category is selected by default
- Check that featured snaps have a coloured top border
Fixes:
- https://warthogs.atlassian.net/browse/WD-7666
- https://warthogs.atlassian.net/browse/WD-7667
- https://warthogs.atlassian.net/browse/WD-7668

Showing featured categories

---

static/js/publisher/listing/components/App/App.tsx
tests/publisher/snaps/tests_post_binary_metadata.py
tests/publisher/snaps/tests_post_listing.py
webapp/publisher/snaps/listing_views.py
webapp/publisher/snaps/views.py

- Created `.json` endpoints for the `<snap_name>/listing` endpoint `<snap_name>/listing.json` that supports GET and POST
- Updated the frontend to use the new json endpoints
- Based on the returned data of the API - show more useful error messages.
- Clear all notifications when saving starts.
- Visit demo/<snap_name>/listing
- Play around with the listings page, make changes, reset it, save it, revert changes
- Specifically play with images - use https://github.com/canonical/snapcraft.io/issues/4468#issuecomment-1845009966 to see an error, but add images, remove images, save between adding and removing, refresh the page between different states
- Don't rush it, take some time.
Fixes #4468

Create json endpoints for updating listing data. Handle errors.

---

static/js/store/components/Packages/Packages.tsx

Fixed the syntax of the search results heading
- Go to https://snapcraft-io-4473.demos.haus/beta-store?q=zoom
- Check that the search results heading reads: "Showing 1 to 15 of 38 results for "zoom". Clear search"
Fixes https://warthogs.atlassian.net/browse/WD-7854

Fix search results heading

---

webapp/handlers.py
webapp/login/views.py
webapp/snapcraft/views.py

- Removed `last_login_method` cookie on `/account.json` call as it's no longer used
- Removed all references to `last_login_method`
- Wrapped `get_account_json` in a `try: except` to attempt to log issues
- Return a 502 from `account.json` if there is an error and log it
- Visit the demo
- For most users everything should work as usual.
- Logout
- Login
- Account menu should work
- Going to `/snaps` and individual snap publisher pages should work
Fixes #

Remove last_login_method cookie. Extra logging for account endpoint

---

.eslintrc.js
static/js/publisher/listing/components/App/App.tsx
static/js/publisher/settings/components/App/App.tsx

- Updated settings page to work the same as listings page.
- Make error messages a little more friendly on both
- Drive-by: Updated eslintrc to remove linting warning
- Visit the settings page for a snap without a description and or summary
- Try and update visibility
- ERRORS 🥳 
- The changes made should not be reverted on the page
Fixes #

Fix settings page error messages

---

static/js/base/navigation.js
static/js/publisher/listing/components/App/App.tsx
static/js/publisher/settings/components/App/App.tsx
static/js/publisher/settings/types/SettingsData.d.ts
static/js/publisher/shared/PageHeader/PageHeader.tsx
templates/publisher/_header.html
templates/publisher/settings.html
webapp/publisher/snaps/build_views.py

Ensured the headers for all publisher pages are consistent
- Added some extra data to certain pages and views
- Updated `navigation.js` to set the users displayname in session storage
- Updated PageHeader component to conditionally show "By [publishername]" based on the session storage display name
- Visit a snap you own, go through the publisher pages
- Make sure the header shows the snap title, not the snap name
- Visit a snap you don't own, go through each publisher page
- Make sure the header shows the snap title and "by [publishername]"
Fixes https://warthogs.atlassian.net/browse/WD-7927

Publisher header consistency

---

package.json
static/js/store/components/Packages/Packages.tsx
yarn.lock

Added "See more" categories
- Go to https://snapcraft-io-4486.demos.haus/beta-store
- Check that only 10 categories (inc. featured) are visible
- Check that there is a "See more" button that shows the rest of the categories

Add show more to beta store categories

---

static/js/store/components/Banner/Banner.tsx

Fixed the pagination for beta store searches
- Go to https://snapcraft-io-4499.demos.haus/beta-store?categories=games&page=4
- Search for "code"
- Check that the `page` query parameter has been removed
- Check that the results count above the search results is correct

Fix search pagination

---

webapp/admin/views.py
webapp/decorators.py
webapp/login/views.py
webapp/snapcraft/views.py

- Moved upgrade exchange to decorator only called when a user visits the store admin pages
- Removed `login_upgraded` redirect from `account.json` call.
- Create a new user (in a private session)
- for Canonical employees, you can use the <email>+<identifier>@canonical.com convention.
- Verify your email address
- Visit https://snapcraft-io-4505.demos.haus/ and login
- Follow the subsequent screens
- See the empty dashboard
- Login with your main account
- Visit https://snapcraft-io-4505.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Ensure everything works (the macaroon get's upgraded)
Fixes #4461 https://warthogs.atlassian.net/browse/WD-8210

fix: First login error and loop

---

.github/workflows/pr.yml
yarn.lock

- Ensure lint-python uses the versions of black and flake8 defined in requirements.txt
- The checks should pass for this PR

chore: make lint-python use requirements versions

---

static/js/publisher/listing/components/PreviewForm/PreviewForm.tsx

Fixed contact links not being reflected in the list page preview
- Go to https://snapcraft-io-4522.demos.haus/<SNAP_NAME>/listing
- Add or remove links from the "Contact information" section
- Click the preview button
- Check that those changes are reflected in the sidebar of the preview page
Fixes https://warthogs.atlassian.net/browse/WD-8417
Fixes #4509

Fix preview of links for listing page

---

static/js/publisher/preview.js

Updated how markdownit is imported and initialised.
- Visit any snaps build page / preview
- Everything should work as expected
- Compare with the live site.

fix: markdownit initialisation update

---

static/js/brand-store/components/SectionNav/SectionNav.tsx

- Visit brand stores
- ensure the tabs don't show
Fixes #

fix: dont show models and signing keys tabs

---

static/js/public/snap-details/screenshots.js

Fixed bug with preview screenshot slider caused by broken imports
- Go to https://snapcraft-io-4533.demos.haus/<SNAP_NAME>/listing
- Click on the "Preview" button
- Check that the screenshot/video carousel works as expected
Fixes https://warthogs.atlassian.net/browse/WD-8964

Fix imports for screenshot slider

---

static/js/public/snap-details/screenshots.js
templates/_base-layout.html
templates/admin/admin.html

Removed the header from the brand store layout
- Go to https://snapcraft-io-4534.demos.haus/admin
- Check that there is no header
Fixes https://warthogs.atlassian.net/browse/WD-8956

Remove brand store header

---

templates/home/_fsf_c.html
templates/home/_fsf_electron.html
templates/home/_fsf_flutter.html
templates/home/_fsf_go.html
templates/home/_fsf_java.html
templates/home/_fsf_moos.html
templates/home/_fsf_node.html
templates/home/_fsf_pre-built.html
templates/home/_fsf_python.html
templates/home/_fsf_ros.html
templates/home/_fsf_ros2.html
templates/home/_fsf_ruby.html
templates/home/_fsf_rust.html

- direct first snap flow links to relevant docs pages instead first snap flow contents
- go to first snap flow section on [https://snapcraft-io-4535.demos.haus](https://snapcraft-io-4535.demos.haus/)
- For each language, the `continue` button directs to relevant docs pages as follows:
Python → https://snapcraft.io/docs/python-apps
Pre-built apps → https://snapcraft.io/docs/pre-built-apps
C/C++ → https://snapcraft.io/docs/c-c-applications
Go → https://snapcraft.io/docs/go-applications
Java → https://snapcraft.io/docs/java-applications
Node.js → https://snapcraft.io/docs/node-apps
Electron → https://snapcraft.io/docs/electron-apps
Flutter → https://snapcraft.io/docs/flutter-applications
Ruby → https://snapcraft.io/docs/ruby-applications
Rust → https://snapcraft.io/docs/rust-applications …

direct first snap flow links to relevant docs pages instead of first snap flow contents

---

static/js/publisher/release/components/releasesTable/cellViews.js

Added a warning icon to non-releasable revision cells
- Go to https://snapcraft-io-4536.demos.haus/ght/releases
- Check that non-releasable cells have a yellow warning icon
Fixes https://warthogs.atlassian.net/browse/WD-8970

Add warning icon to release UI

---

templates/_header.html

- move `global-nav` to `l-docs__main` to align with the documentation layout
- go to https://snapcraft-io-4538.demos.haus/docs
- log in and check if `global-nav` is aligned with the rest of the header
Fixes #https://warthogs.atlassian.net/browse/WD-8968

align header to documentation-layout

---

templates/home/_fsf_ruby.html

- remove `<hr>` classname on first-snap-flow Ruby section so that there is margin between `<hr>` and `continue` button
- go to https://snapcraft-io-4541.demos.haus/ and select Ruby for first-snap-flow
- check if there is margin between `<hr>` and `continue` button
Fixes #https://warthogs.atlassian.net/browse/WD-9177

Add margin between <hr> and continue button in the first-snap-flow Ruby section

---

static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.js
static/sass/_snapcraft_graph-tooltip.scss

- Added percentages to graph tooltip
- Added an extra 50pixels to the width of the tooltip
- Made the CSS handle variable strings better
- Visit demo/{snap-name}/metrics - preferably a snap with many users
- Hover over the active devices graph, change the dropdowns etc. and make sure percentages show as expected
Fixes #4543

feat: show percentages in the metrics graph for publishers

---

static/js/brand-store/components/Navigation/Navigation.tsx
static/js/brand-store/hooks/index.ts

Added account actions to the brand store sidebar
- Go to https://snapcraft-io-4549.demos.haus/admin
- Check that your name at the bottom of the side bar takes you to `/account/details`
- Check that the "Logout" link logs you out and takes you to the homepage
Fixes https://warthogs.atlassian.net/browse/WD-8958

Add account links to brand store sidebar

---

webapp/api/github.py
webapp/publisher/snaps/build_views.py

Don't crash on 403 when a build does not exist
- Visit https://snapcraft-io-4553.demos.haus/lukewh-test/builds - you should see the page to connect your github account
- Visit https://snapcraft-io-4553.demos.haus/test-snap-lukewh-7/builds - you should see a list of failed builds
Fixes #4360
Fixes https://warthogs.atlassian.net/browse/WD-9419
Fixes https://forum.snapcraft.io/t/internal-server-error-on-builds-page/39234

fix: build page 503ing when api key access forbidden

---

static/sass/styles.scss

Fixed white headings being displayed as black in the global nav
- Go to https://snapcraft-io-4556.demos.haus/
- Click on global nav ("All Canonical")
- Check that all text is visible

Fix invisible links in global nav

---

static/js/brand-store/components/Members/Members.tsx

Fixed the new members form not being cleared when closed
- Go to https://snapcraft-io-4558.demos.haus/admin
- Go to the "Members" section of a store
- Click "Add new member"
- Enter an email address and select a role
- Close the form by either using the "Cancel" button or clicking outside of the panel
- Re-open the form
- The form should have been cleared
Fixes https://warthogs.atlassian.net/browse/WD-9800

Clear new member form on close

---

static/js/brand-store/components/Navigation/Navigation.tsx
static/sass/_snapcraft_l-application.scss

Added a My snaps overview link to the brand store navigation
- Go to https://snapcraft-io-4566.demos.haus/admin
- Check that the side navigation has a "My snaps" section with a link to /snaps

Add overview link to brand store navigation

---

tests/publisher/tests_account_details.py
webapp/helpers.py
webapp/publisher/views.py

Added an endpoint for publisher data
- Go to https://snapcraft-io-4567.demos.haus/account/publisher
- Check that you can see publisher data which includes `has_stores` and `subscriptions`
- Go to https://snapcraft-io-4567.demos.haus/account/details
- Check that it works as expected ([compare to live](https://snapcraft.io/account/details))
Fixes https://warthogs.atlassian.net/browse/WD-9991

Add publisher data endpoint

---

webapp/admin/views.py

- add an endpoint that allows an admin member to do the following:
- fetch currently featured snaps and delete them
- update a list of new featured snaps
Fixes #

add endpoint to update featured snaps

---

static/js/publisher/release/components/defaultTrackModifier.js
static/js/publisher/release/components/releasesHeading.js
static/js/publisher/release/components/trackDropdown.js
static/sass/_snapcraft_release.scss

Adds custom dropdown box to view tracks for all Snaps, even if they only have one. Displays Default label to show Default track, and tick icon to show which track the user is currently viewing.
https://snapcraft-io-4573.demos.haus/fran-snap/releases and check Tracks dropdown. 
Alternatively, navigate to any Snap release page and check Tracks dropdown.
Fixes https://warthogs.atlassian.net/browse/WD-10009

Add track dropdown on all Snap release pages

---

static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.js

- add a ternary operator to show `0%` instead of `NaN%` on Snapcraft metrics graph
- Go to https://snapcraft-io-4579.demos.haus/snaps
- Check if you see `0%` instead of `NaN%` on a tooltip on a metrics graph.
Fixes #https://warthogs.atlassian.net/browse/WD-9998
Before: 
After:

WD-9998 show 0% instead of NaN% on Snapcraft metrics graph

---

static/js/publisher/release/components/releasesTable/releaseMenuItem.js

Disabled option to promote a release to stable or candidate if in `devmode` or grade `devrel`
- https://snapcraft-io-4594.demos.haus/emacs/releases
- Hover over any of the cells in the "Releases available to install" with an `*` next to the revision number
- Click "Promote" and check that the `stable` and `candidate` options are disabled
- Check that they are not disabled in the other cells (unless the cell is in that track)
Fixes https://warthogs.atlassian.net/browse/WD-10317

Disable promote to promote option for devrel releases

---

static/js/publisher/release/components/releasesHeading.js
static/js/publisher/release/helpers.js
static/js/publisher/release/releasesController.js
static/sass/_snapcraft_release.scss

Allows users to add a new track to a snap that already has more than one track. Users will receive a successful or unsuccessful message depending on the outcome.
- Go to a Snap release page that already has more than one track (e.g. https://snapcraft-io-4596.demos.haus/fran-snap/releases)
- Verify that the side panel opens with add track options
- If you have permissions to add a track to the Snap, try and add a new track and verify that it works
- Otherwise, see screenshots below
Fixes https://warthogs.atlassian.net/browse/WD-10155

Adds "Add track" functionality

---

static/js/publisher/release/components/releasesHeading.js

Provides user with more information about track creation guardrails when creating a new track.
- Go to a Snap release page that has multiple tracks (e.g. https://snapcraft-io-4599.demos.haus/lxd/releases) and click "Add track" in the track dropdown
- Verify that there is a short sentence about TCG in the side panel
- Verify that the "contact us" link points to https://forum.snapcraft.io/c/store-requests/19

Modify track creation guardrails information

---

static/js/brand-store/components/Snaps/IncludedSnapsTable.tsx
static/js/brand-store/components/Snaps/PublishedSnapsTable.tsx
static/sass/styles.scss

Changes `<table>` to React `<MainTable>` and adds sortable columns to the brand store.
- Go to brand store (https://snapcraft-io-4600.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps)
- Check that columns in both tables are sortable and that they sort correctly
Fixes https://warthogs.atlassian.net/browse/WD-10420

Add column sorting to brand store

---

static/js/publisher/release/components/revisionsListRow.js

Fixes https://github.com/canonical/snapcraft.io/issues/4601.
Ensures long version numbers wrap onto a new line in the Releases table.
Fixes https://warthogs.atlassian.net/browse/WD-10673

Fix Releases table line wrap

---

templates/publisher/register-snap.html

- show notification to inform user that registering a snap requires manual review when a user selects global store (notification is hidden for other stores)
- set the default private value to true when global store is selected
- Disable the privacy buttons when global store is selected
- Go to https://snapcraft-io-4603.demos.haus/register-snap
- Select the global store
- Check that the notification displays
- Check that the privacy options are disabled
- Select any other store and check that notification is not displayed and you can select any privacy option of your choice
- Also, QA with an account that has access to only global store.
https://warthogs.atlassian.net/browse/WD-10620
https://warthogs.atlassian.net/browse/WD-10618
Fixes #

Show notification and set private to true

---

static/sass/styles.scss

Modifies the `$breakpoint-navigation-threshold` to avoid the nav bar wrapping onto a new line on smaller screens. The nav bar now switches to mobile version at this new breakpoint instead.
Go to demo and make screen size smaller to ensure the top navigation bar does not wrap onto two lines at any point.
Fixes https://warthogs.atlassian.net/browse/WD-10735
BEFORE:
AFTER:

Modify breakpoint-navigation-threshold

---

templates/publisher/register-snap.html

- Hide privacy section when user has only global store
- Login to  https://snapcraft-io-4607.demos.haus with an  account that has access to only global store (you can use a new account)
- Go to https://snapcraft-io-4607.demos.haus/register-snap and check that the privacy section is hidden
Fixes #

hide privacy section when user has only global store

---

static/js/public/snap-details/reportSnap.js
templates/store/snap-details/_report_snap_modal.html
webapp/store/snap_details_views.py

- Added a honeypot for bots,
- Added a simple check for urls included in the comment
- Moved the actual form submission to the backend so as to implement server-side checks too
- Visit a snap page
- Submit a report with a url in it - let me know what you submitted
- Refresh the page
- Inspect the page and set "#report-snap-confirm" to `checked` to `true`.
- Submit again
- Let me know what you submitted
- Refresh the page
- Submit a "normal" report
- Let me know what you submitted
Fixes #

Add some attempt to reduce spam on report snap form

---

package.json
templates/publisher/register-snap.html
webapp/publisher/snaps/views.py

- Make links in register error message clickable
- Go to https://snapcraft-io-4610.demos.haus/register-snap and try to register a snap name in global store
- Check that the links in the error message returned are clickable
Fixes #

make link clickable in error message

---

static/js/publisher/settings/components/App/App.tsx
static/js/publisher/settings/types/SettingsData.d.ts
templates/publisher/settings.html
tests/publisher/snaps/tests_settings.py
webapp/publisher/snaps/settings_views.py

- Add notification on snap settings page when `visibility_locked` is `true`
- Disable visibility inputs when `visibility_locked` is `true`
- Ensure `private` is `true` when `visibility_locked` is `true`
- QA can only be done on a snap that has visibility_locked set to true, presently all registered snaps have it set to `None`
https://warthogs.atlassian.net/browse/WD-10614
https://warthogs.atlassian.net/browse/WD-10617
Fixes #

Update snap settings page

---

webapp/authentication.py
webapp/publisher/snaps/views.py

Verifies that the backend API endpoint works correctly to unregister a snap name
*Links to https://github.com/canonical/canonicalwebteam.store-api/pull/118*
Check video below where I use Postman to delete `abbie-global-test-snap-3`
(I will add the front-end in a different PR for proper testing)
Fixes https://warthogs.atlassian.net/browse/WD-6772
[Screencast from 06-05-24 14:34:39.webm](https://github.com/canonical/snapcraft.io/assets/74302970/d4758495-9951-46d7-8b7b-af25232a0b5b)

Add delete package endpoint

---

jest.config.js
static/js/store/components/Packages/Packages.tsx
static/js/store/components/Packages/__tests__/Packages.test.tsx

- Fixed `0` being displayed if there are no search results
- Fixed packages not being returned for a search with no categories
- Added tests
- Go to https://snapcraft-io-4624.demos.haus/store?q=nonsensequery
- Check that there isn't a `0` displayed above the "No packages match this filter" heading
- Go to https://snapcraft-io-4624.demos.haus/store?q=code
- Check that there are more than 2 search results and that VS Code is in the results
Fixes https://warthogs.atlassian.net/browse/WD-11332

fix: Remove featured category query param for search queries

---

static/js/public/snap-details/channelMap.ts

Fixed compiler warnings in channelMap.js (no return)

fix: Fix compiler warnings in channel map JS

---

static/js/brand-store/components/Navigation/Navigation.tsx
static/sass/_snapcraft_l-application.scss

Added separators to the brand store navigation and hidden icons when nav bar is collapsed
- Go to https://snapcraft-io-4704.demos.haus/admin
- Check that there are horizontal separators between sections in the side navigation
- Collapse the side navigation
- Check that there are no icons other than the logout/account ones at the very bottom of the nav bar
- Resize to smaller screens and check that there are no icons unless sidebar is hovered/expanded
Fixes https://warthogs.atlassian.net/browse/WD-11687

feat: Add separators to brand store navigation

---

templates/_header.html

- Change the main navigation to`p-navigation__row--25-75 `
- Add highlight on the navigation tab when it's selected 
- Go to https://snapcraft-io-4709.demos.haus/store and check if `snap store` is highlighted when the tab selected
- Check there is spacing between the logo and navigation items
Fixes #https://warthogs.atlassian.net/browse/WD-12307
Fixes #https://warthogs.atlassian.net/browse/WD-12308

fix: use p-navigation__row--25-75 and add highlights on Snapcraft.io navigation

---

konf/site.yaml
tests/tests_helpers.py
webapp/helpers.py

Added a helper to generate the token to be used for DNS verification
- There is no way to check other than the test passing
Fixes https://warthogs.atlassian.net/browse/WD-12520

feat: Add helper to generate DNS verification token

---

konf/staging-api.snapcraft.io.yaml
requirements.txt
webapp/store/snap_details_views.py

Created an endpoint to verify a domain
- Go to https://snapcraft-io-4716.demos.haus/api/steve-test-snap/verify
- Check that the value in the response is `false` - this is because the secret isn't on staging
Fixes https://warthogs.atlassian.net/browse/WD-12520

feat: Create endpoint to verify domain

---

static/js/publisher/listing/components/ListingFormInput/ListingFormInput.tsx
static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
static/js/publisher/listing/utils/__tests__/getChanges.test.ts
static/js/publisher/listing/utils/__tests__/getListingData.test.ts
static/js/publisher/listing/utils/getChanges.ts
static/js/publisher/listing/utils/getListingData.ts

Separated the primary domain from the other domains on the snap publisher listing page
- Go to a snap listing page (https://snapcraft-io-4722.demos.haus/<SNAP_NAME>/listing)
- Check that the "Primary website" field has the first website value (compare to live)
- Check that the remaining domains are in the "Other websites" field
- Check that you can edit and save domains
Fixes https://warthogs.atlassian.net/browse/WD-12522

feat: Separate primary domain from other domains

---

tests/publisher/tests_get_package_metadata.py
webapp/publisher/snaps/views.py

Adds `get_package_metadata` flask endpoint to be able to query for track guardrails. 
Links to [this StoreAPI PR](https://github.com/canonical/canonicalwebteam.store-api/pull/126)
See screenshots below for functioning endpoint (tested locally with Postman)
Fixes https://warthogs.atlassian.net/browse/WD-11398

feat: adds get_package_metadata flask endpoint

---

templates/store/snap-details.html
templates/store/snap-details/_details.html
templates/store/snap-details/_report_snap_modal.html
tests/tests_templates_utils.py
webapp/template_utils.py

- Moved report this snap to be under the rest of the links on the page
- Updated the heading to be more explicit "Report a Snap Store violation"
- Updated report violation modal title to be more explicit
- Added notification to the top of the modal to reiterate what the form is for
- If available provide signposting for the user to contact information and report an issue with the snap directly
- Simplified the thank you message
Also:
Updated the formatting of urls for links:
If the link is github.com, gitlab.com, bitbucket.org, launchpad.net, or sourceforge.net also include the path in the display.
Visit multiple snaps with differnent available links

feat(snapReporting): Update reporting snap violation flow

---

package.json
templates/store/snap-details/_details.html
yarn.lock

Added the verification notification to the primary domain on the snap page
- Go to https://snapcraft-io-4724.demos.haus/steve-test-snap
- Check that there is a verified domain icon and tooltip next to the first domain under "Websites"
- Go to https://snapcraft-io-4724.demos.haus/code (or any other snap)
- Check that there is NOT a verified domain icon and tooltip next to the first domain under "Websites"
Fixes https://warthogs.atlassian.net/browse/WD-12525

feat: Show domain verified status on snap page

---

static/js/publisher/release/components/releasesHeading.js
static/js/publisher/release/helpers.test.js
static/js/publisher/release/helpers.ts

- Refactors Releases page track dropdown
- Instead of checking if a snap has > 1 track, we now query for track guardrails and based on this result:
- If there are track guardrails: shows "Add track" aside panel
- If there are **no** track guardrails: shows "Request track" aside panel
- Tricky to QA as you need to have a snap with > 1 track but NO guardrails, and a snap with guardrails to show the differentiation
- Tests should pass
- Check your published snaps (or snaps that you are a collaborator on)
- If there are guardrails, the track dropdown should show "Add track"
- If there are no guardrails, the track dropdown should show "Request track"
Fixes https://warthogs.atlassian.net/browse/WD-11361

fix: refactor add track logic with track guardrails

---

webapp/store/content/distros/debian.yaml
webapp/store/content/distros/raspbian.yaml

In general, the preferred source of newer snapd is either the distro package, or on distributions where reexecution is enabled and supported (Debian derivatives), the snapd snap, . The core snap will be automatically pulled in by snapd when installing snaps that need it, but in most cases, the snaps have already migrated to using the leaner core18/20/22/24 bases.
Fixes #

webapp/store/content/distros: update instructions to mention installation of the snapd snap

---

package.json
requirements.txt
templates/_header.html
yarn.lock

- Bumps canonicalwebteam.discourse to 5.6.0 and vanilla to 4.14.0
- Removes `p-navigation__row--25-75` as "Sign In" / user's account name wrapped onto a new line with the new Vanilla changes
- Check the changes in Vanilla have not broken anything
- Go to docs (e.g. https://snapcraft-io-4735.demos.haus/docs/managing-updates) and hover over a h2 heading, see the [vanilla anchor link](https://vanillaframework.io/docs/patterns/links#anchor-link) works as expected
- Inspect the heading and see there are no trailing numbers on the heading 
Fixes https://warthogs.atlassian.net/browse/WD-12931

chore: Bump canonicalwebteam.discourse to 5.6.0 and vanilla to 4.14.0

---

static/sass/_snapcraft_l-application.scss

Fixed a padding issue with the status bar in the brand store
- Go to https://snapcraft-io-4753.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Make a change (check or uncheck a checkbox)
- The "Save changes" bar at the bottom of the screen should have padding above and below the button
Fixes https://warthogs.atlassian.net/browse/WD-13134

fix: Fix padding issue on brand store status bar

---

static/js/base/ga.ts

Fixed coding standards warnings in base JS from TiCS dashboard

fix: Fix base JS coding standards warnings from TiCS dashboard

---

requirements.txt
static/js/publisher/release/components/releasesHeading.js
static/js/publisher/release/helpers.test.js
static/js/publisher/release/helpers.ts
static/sass/_snapcraft_release.scss
webapp/publisher/snaps/views.py

Fixed the bugs listed here: https://warthogs.atlassian.net/browse/WD-13131
We now will only show "Add" or "Request" track in the dropdown when a user is the publisher or a collaborator of the snap. Otherwise, we will show:
- If you are a collaborator / publisher:
- if the snap has track guardrails > we show "Add track"
- if the snap has no guardrails > we show "Request track"
- If you are not a collaborator / publisher:
- we show the list of tracks only
1. Open a snap's release page that has no track guardrails - this must be a snap that you are a collaborator or publisher of
1. Open the request track side panel, click cancel, ensure the side panel closes
1. Open https://snapcraft-io-4749.demos.haus/fran-snap/releases and try and click on the track dropdown straight away
1. You will see a …

fix: Self-serve track creation bug fixes

---

static/js/publisher/settings/components/App/App.tsx
static/js/store/pages/Packages/Packages.tsx
static/js/store/pages/Packages/__tests__/Packages.test.tsx

- fixed pagination for featured snaps on snap store
- Go to https://snapcraft-io-4762.demos.haus/store and click `page 2` for featured snaps
- Check if you see `1` remaining featured snap card only
Fixes #https://warthogs.atlassian.net/browse/WD-12777

fix: fix pagination for featured snaps on snap store

---

static/js/brand-store/components/App/App.tsx
static/js/brand-store/components/Model/Model.test.tsx
static/js/brand-store/components/Model/Policies.test.tsx
static/js/brand-store/components/Navigation/Navigation.tsx
static/js/brand-store/components/Navigation/__tests__/Navigation.test.tsx

Only show members and settings in side navigation if the user is an admin
- Go to https://snapcraft-io-4763.demos.haus/admin
- Choose any store that you are an admin of
- Check that you can see "Members" and "Settings" links in the side navigation
- Choose any store that you are not an admin of, e.g. Reviewer, Publisher or both
- Check that you do not see "Members" and "Settings" links in the side navigation
Fixes https://warthogs.atlassian.net/browse/WD-13135

fix: Only show members and settings pages in user has admin role

---

static/js/publisher/release/components/releasesHeading.js

- Updates URL for track request to pre-fill the new topic post on forum.snapcraft.io
- Go to one of your tracks that does not have track guardrails (one where you can see "Request track" in the track dropdown)
- Click "Request track" and ensure you are taken to forum.snapcraft.io with the new topic request pre-filled with the title and category type
- If you have no snaps with "request track", just go to the URL and check that the fields are pre-filled

chore: update URL for request track to pre-fill new forum request

---

static/js/brand-store/components/Navigation/Navigation.tsx

Changed the navigation so models links use brand ID
- Go to https://snapcraft-io-4782.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that models load
- Go to another store and check that the snaps load

fix: Update model routes to use account ID

---

static/js/brand-store/atoms/index.ts
static/js/brand-store/components/Model/CreatePolicyForm.tsx
static/js/brand-store/components/Model/Model.tsx
static/js/brand-store/components/Model/Policies.tsx
static/js/brand-store/components/Model/PoliciesTable.tsx
static/js/brand-store/components/Models/CreateModelForm.tsx
static/js/brand-store/components/Models/Models.tsx
static/js/brand-store/components/Navigation/Navigation.tsx
static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
static/js/brand-store/components/SigningKeys/SigningKeys.tsx
static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
static/js/brand-store/hooks/index.ts

Refactored the brand store so that the model service uses the brand account ID to call the API rather than the store ID.
- Go to https://snapcraft-io-4783.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that the models have loaded
- Go to https://snapcraft-io-4783.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/alimot_test_model_a
- Check that the model has loaded
- Go to https://snapcraft-io-4783.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/alimot_test_model_a/policies
- Check that the polices have loaded
- Go to https://snapcraft-io-4783.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys
- Check that the signing keys have loaded
- Go to any of your stores and check that they look and behave as expected
Fixes …

fix: Refactor models service to use account ID

---

static/js/brand-store/components/Models/Models.tsx
static/js/brand-store/components/SigningKeys/SigningKeys.tsx
static/js/brand-store/utils/getPolicies.ts

Cancel pending requests to the policies endpoint when navigating away from the models view
- Go to https://snapcraft-io-4789.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Open the network tab and see many requests to the `policies` endpoint
- Before they are all complete navigate to "Signing keys" using the side navigation
- Check that any pending requests are now showing as cancelled
Fixes https://warthogs.atlassian.net/browse/WD-13854

fix: Cancel pending policy requests when leaving model view

---

requirements.txt
static/js/publisher/release/components/TrackInfo.test.tsx
static/js/publisher/release/components/TrackInfo.tsx
static/js/publisher/release/components/releasesHeading.js
static/js/publisher/release/helpers.test.js
static/js/publisher/release/helpers.ts
webapp/store/views.py

- Enables Version pattern and Automatic phasing percentage parameters when adding a new track
- Shows a track's version pattern and/or auto phasing percentage (if they have them)
- Go to [`fran-snap/releases`](https://snapcraft-io-4796.demos.haus/fran-snap/releases)
- The following tracks have version patterns or phasing percentages to QA:
- v.09
- v.101
- v.102
- v.104
- You can also create a new track on `fran-snap`, adding in your own version pattern and phasing percentage, then verify this information is displayed when you switch to this track
Fixes [WD-13857](https://warthogs.atlassian.net/browse/WD-13857)
[WD-13857]: https://warthogs.atlassian.net/browse/WD-13857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add optional parameters functionality when adding a new track

---

static/js/publisher/release/components/releasesHeading.js

Removes unnecessary useEffect hook (missed a comment from [previous PR](https://github.com/canonical/snapcraft.io/pull/4796))

chore: remove unnecessary useEffect hook

---

requirements.txt
tests/store/tests_validation_sets.py
webapp/store/views.py

Added endpoints for validation sets
- Go to https://snapcraft-io-4802.demos.haus/api/validation-sets
- Check that there is a JSON response with `success` as `true` and `data` as `[]`
- Go to https://snapcraft-io-4802.demos.haus/api/validation-sets/test-set-id
- Check that there is a JSON response with `success` as `true` and `data` as `{}`
Fixes https://warthogs.atlassian.net/browse/WD-14110
Fixes https://warthogs.atlassian.net/browse/WD-14111

feat: Create validation sets endpoints

---

redirects.yaml
templates/publisher/account-snaps.html

Update /docs/getting-started to docs/quickstart-tour on empty publisher snaps list page
- As a user without any snaps, log in
- The "Getting started with snaps" button should go to the appropriate quickstart-tour page.
Fixes https://forum.snapcraft.io/t/snap-documentation/11127/33

fix: /docs/getting-started update

---

static/js/validation-sets/routes/root.tsx

Used the correct logo style and pin button on the validation sets sidebar as it's not possible within the React Component currently. [An issue has been raised to address this](https://github.com/canonical/react-components/issues/1114).
- Go to https://snapcraft-io-4813.demos.haus/validation-sets
- Check that the sidebar navigation matches [the brand store](https://snapcraft.io/admin) with the exception of the "Stores" section

fix: Fix application layout sidebar for validation sets

---

static/js/validation-sets/components/Logo/Logo.tsx
static/js/validation-sets/components/Logo/index.ts
static/js/validation-sets/components/PrimaryNav/PrimaryNav.tsx
static/js/validation-sets/components/PrimaryNav/index.ts
static/js/validation-sets/routes/root.tsx

Refactored validation sets to use `ApplicationLayout` from [React Components](https://canonical.github.io/react-components/?path=/docs/components-applicationlayout--docs)
- Go to https://snapcraft-io-4817.demos.haus/validation-sets
- Compare layout to https://snapcraft.io/validation-sets

fix: Use ApplicationLayout component for validation sets

---

webapp/handlers.py

- Go to [HTTP header analyzer](https://dri.es/headers?url=https%3A%2F%2Fsnapcraft-io-4829.demos.haus%2F)
- Go to https://snapcraft-io-4829.demos.haus/
- [x ] No testing required (explain why): added security header

feat:add missing csp

---

webapp/handlers.py

- Go to [HTTP header analyzer](https://dri.es/headers?url=https%3A%2F%2Fsnapcraft-io-4830.demos.haus%2F)
- Go to https://snapcraft-io-4830.demos.haus/

feat: add missing csp Part 2

---

webapp/handlers.py

- Go to [HTTP header analyzer](https://dri.es/headers?url=https%3A%2F%2Fsnapcraft-io-4831.demos.haus%2F)
- Go to https://snapcraft-io-4831.demos.haus/

feat:add missing csp - Part 3

---

templates/_header.html

Added a link to validation sets to the logged in menu
- Go to https://snapcraft-io-4832.demos.haus/
- Log in
- Check that there is a link to validation sets in the account dropdown menu (top right of nav)
Fixes https://warthogs.atlassian.net/browse/WD-14117

chore: Add validation sets link to logged in navigation

---

webapp/handlers.py

- Go to [HTTP header analyzer](https://dri.es/headers?url=https%3A%2F%2Fsnapcraft-io-4833.demos.haus%2F)
- Go to https://snapcraft-io-4833.demos.haus/

feat:add missing csp - Part 4

---

webapp/handlers.py

- Go to [HTTP header analyzer](https://dri.es/headers?url=https%3A%2F%2Fsnapcraft-io-4835.demos.haus%2F)
- Go to https://snapcraft-io-4835.demos.haus/

feat:add missing csp Part 5

---

static/js/store/pages/Packages/Packages.tsx
static/js/store/pages/Packages/__tests__/Packages.test.tsx

Fixes https://github.com/canonical/snapcraft.io/issues/4822
Allows user to search for a snap outside of the featured snaps on initial load of the store.
Go to https://snapcraft-io-4843.demos.haus/store and check:
1. Initial load shows featured snaps as normal
1. Selecting a category filters snaps correctly
1. Deselecting a category returns UI to show Featured snaps
1. Entering a search term allows user to search through *all* snaps
1. Selecting a category with a search term filters the search to the chosen category (and vice versa)
Fixes https://warthogs.atlassian.net/browse/WD-14710

fix: improve search UX on initial store load

---

templates/index.html

- Temporarily replace JS content for the blog section with static html for A/B testing
- Added comments regarding this replacement on line 115 and 172
- Go to https://snapcraft-io-4849.demos.haus/ and check if you can see the `Latest news from our blog` section
Fixes #https://warthogs.atlassian.net/browse/WD-14912

chore: replace JS content for blog section with static html for AB testing

---

requirements.txt
templates/publisher/listing.html
templates/publisher/settings.html
tests/first_snap/tests_views.py
tests/login/tests_login_handler.py
tests/publisher/endpoint_testing.py
tests/publisher/snaps/test_post_preview.py
tests/publisher/snaps/tests_post_close_channel.py
tests/publisher/snaps/tests_post_default_track.py
tests/publisher/snaps/tests_post_release.py
tests/publisher/tests_account_logout.py
tests/publisher/tests_account_snaps.py
tests/publisher/tests_agreement.py
tests/publisher/tests_publisher.py
tests/publisher/tests_register_name.py
tests/publisher/tests_register_name_dispute.py
tests/publisher/tests_reserved_name_dispute.py
tests/publisher/tests_username.py
tests/snapcraft/tests_public.py
tests/store/tests_details.py
tests/store/tests_distro_page.py
tests/store/tests_embedded_card.py
tests/store/tests_github_badge.py
tests/store/tests_publisher.py
tests/tests_badge_counter.py
webapp/app.py
webapp/docs/views.py
webapp/publisher/snaps/listing_views.py
webapp/publisher/snaps/settings_views.py

Bumps `canonicalwebteam.search` module version. This also relied on bumping `flask-base`, which caused over 180 test failures - so the majority of changes are fixing those
- Click around and make sure the site works as usual
- All tests should pass
Fixes [WD-15006](https://warthogs.atlassian.net/browse/WD-15006)
[WD-15006]: https://warthogs.atlassian.net/browse/WD-15006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: bump canonicalwebteam.search version

---

static/js/publisher/listing/components/LicenseInputs/LicenseInputs.tsx

Updated the SPDX specification link
- Go to https://snapcraft-io-4858.demos.haus/defold/listing (or any other snap listing page)
- Scroll down to the license field
- Click "Custom SPDX expression" radio button
- Check that the SPDX specification link works
Fixes #4856

Update link to SPDX specification on listing page

---

static/js/publisher-pages/pages/Metrics/Metrics.tsx
static/sass/_snapcraft_metrics.scss

- added breadcrumb nav to the metrics page
- go to https://snapcraft-io-4871.demos.haus/<snap-id>/metrics
- see the bread crumb nav
Fixes #[15633](https://warthogs.atlassian.net/browse/WD-15633)

Wd 15633 add breadcrumb nav metrics page

---

webapp/publisher/snaps/build_views.py
webapp/publisher/snaps/views.py

Replaced the builds template view with an endpoint to get builds data and added an endpoint to get GitHub repo data which is necessary for determining which state to show the user and connecting the repo.
This change will break the builds UI which is fine as it is being refactored and subsequent PRs will address this.
This will have to be tested locally as you'll need your GitHub tokens in your `.env.local` file.
`GITHUB_CLIENT_ID=whatever`
`GITHUB_CLIENT_SECRET=whatever`
You can set those here if you don't have them already: https://github.com/settings/applications/new
- Go to a snap which is logged into GitHub and a repo is connected (you will have to connect the repo if you haven't done so already), e.g. http://localhost:8004/api/steve-test-snap/repo
- Check that you see a repo name …

feat: Create endpoints to get repo data and builds data

---

static/js/publisher/release/actions/defaultTrack.js
static/js/publisher/release/actions/defaultTrack.test.js

Adds an error message when `setDefaultTrack` returns a 400.
- Try to set one of your snaps' default tracks to "latest"
- An error message should show up
- Alternatively, check video below of changing default tracks
- Tests should pass
Fixes [WD-15735](https://warthogs.atlassian.net/browse/WD-15735)
[Screencast from 08-10-24 17:54:11.webm](https://github.com/user-attachments/assets/28d6b6ad-a702-4dc9-b58a-2a577421844b)
[WD-15735]: https://warthogs.atlassian.net/browse/WD-15735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: show error when set default track returns 400

---

static/js/publisher/release.tsx
static/js/publisher/release/components/releasesHeading.js
static/js/publisher/release/helpers.test.js
static/js/publisher/release/helpers.ts

- Refactors fetching of track guardrails to use `useQuery` instead of `useEffect` 
- Should mean `packageMetadata` fetch does not run twice and should make the "request"/"add" track buttons more stable
Check the following 3 scenarios:
1. Your own snap (or one you are a collaborator on) that **does not have** guardrails
a. You should see "Request track" in the tracks dropdown
1. Your own snap (or one you are a collaborator on) that **has** guardrails
a. You should see "Add track" in the tracks dropdown 
1. A snap that you do not have any permissions for
a. You should not see any additional buttons in the tracks dropdown
Fixes [WD-15763](https://warthogs.atlassian.net/browse/WD-15763)
[WD-15763]: https://warthogs.atlassian.net/browse/WD-15763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

fix: self serve tracks metadata error

---

.github/workflows/coverage.yml

From the request of the Tiobe team, reducing the number of submissions to once per week. Specifically on Saturday night at 10pm.
- Check back next week to see the job ran on Saturday

Update TiCS workflow to run once per week

---

templates/publisher/publicise/store_buttons.html
templates/store/snap-embedded-card.html

- Updated urls for badges
- Go to 'https://snapcraft-io-4888.demos.haus/lxd/publicise'
- source for both html and markdown should have the correct urls:
- for the dark badge https://snapcraft.io/en/dark/install.svg
- for the light badge https://snapcraft.io/en/light/install.svg
- Go to 'https://snapcraft-io-4888.demos.haus/lxd'
- Click on the "Create embeddable card" button
- Verify dark and light badges are shown

feat: Update badge urls

---

webapp/metrics/helper.py

- When showing the metrics ,  2 days are subtracted from the current day if its Monday or Sunday.
- Go to https://snapcraft-io-4893.demos.haus/lxd/metrics
- Make sure active devices chart doesnt resets to 0
- Make sure country chart isnt empty
Fixes [#WD-15452](https://warthogs.atlassian.net/browse/WD-15452)

feat: add an extra day to fix the reset issue on the metric page

---

static/js/publisher-pages/pages/Publicise/PubliciseButtons.tsx
templates/store/snap-embedded-card.html

- Updated urls for badges
- Go to 'https://snapcraft-io-4892.demos.haus/lxd/publicise'
- source for both html and markdown should have the correct urls:
- for the dark badge https://snapcraft.io/en/dark/install.svg
- for the light badge https://snapcraft.io/en/light/install.svg
- Go to 'https://snapcraft-io-4892.demos.haus/lxd/publicise/cards'
- Verify dark and light badges are shown

Wd 15869 security header badge issue

---

static/js/public/featured-snaps.ts
templates/home/_featured-snaps.html

- Change `category` to `categories` in store url
- 1. Go to [demo](https://snapcraft-io-4903.demos.haus/)
2. click on `Games`
3. click `view all game snaps`
4. Ensure that the snaps displayed are games snaps and `game` is selected in the sidebar
- Repeat steps ii-iv above for `featured`, `development` and `server`
Fixes # https://warthogs.atlassian.net/browse/WD-16692

fix: change 'category' to 'categories' in store filtering url

---

static/js/brand-store/components/Snaps/IncludedSnapsTable.tsx

- Updated a Global snap link in the brand store from  `/<snap_name>/listing` to `/<snap_name>`
- Go to the brand store in [demo](https://snapcraft-io-4904.demos.haus/) and check if the Global snap links to the public page instead of a listing page.
Fixes #https://warthogs.atlassian.net/browse/WD-12915

chore: update admin snap link in brandstore

---

templates/docs/document.html

- Include h3 headings to table of contents (displayed on the right side of the page). H3 contents should nest their parent H2 headings.
- Go to https://snapcraft-io-4918.demos.haus/docs/managing-updates OR https://snapcraft-io-4918.demos.haus/docs/get-started
- Check that the table of contents on the right side of the page load as expected
- It should catch h2 and h3 headings. H3 headings should nest their corresponding H2 parent headings.
Fixes [WD-17314](https://warthogs.atlassian.net/browse/WD-17314)
[WD-17314]: https://warthogs.atlassian.net/browse/WD-17314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include H3 in docs side TOC

---

static/js/publisher-pages/pages/Builds/RepoSelector.tsx

Added the correct labels to the org/repo selectors in the publisher builds page
- Go to the builds tab of a snap that isn't connected to a GitHub repo https://snapcraft-io-4922.demos.haus/<SNAP_NAME>/builds *(you might need to run it locally)*
- Login to your GitHub account
- Check that there is a field for "Select an organization" and "Select a repository"
- **Note**: `lint-js` will still fail as there are errors in other files to be addressed

fix: Fix publisher a11y error in builds section

---

static/js/publisher-pages/pages/Publicise/PubliciseCards.tsx

Added titles to iframes and converted pseudo labels to paragraphs
- Go to https://snapcraft-io-4923.demos.haus/<SNAP_NAME>/publicise/cards
- Check that "Snap Store button", "Options", "Preview" and "HTML" still have titles
- **Note**: `lint-js` will still fail as there are errors in other files that need to be addressed separately

fix: Fix publisher a11y errors in publicise cards section

---

static/js/publisher-pages/pages/Publicise/PubliciseBadges.tsx

Converted pseudo labels to paragraphs
- Go to https://snapcraft-io-4924.demos.haus/<SNAP_NAME>/publicise/badges
- Check that "Snap Store button", "Display", "Preview", "HTML" and "Markdown" still have titles
- **Note**: `lint-js` will still fail as there are errors in other files that need to be addressed separately

fix: Fix publisher a11y errors in publicise badges section

---

static/js/publisher-pages/pages/Publicise/PubliciseButtons.tsx

Converted pseudo labels to paragraphs
- Go to https://snapcraft-io-4925.demos.haus/<SNAP_NAME>/publicise
- Check that "Language", "HTML" and "Markdown" still have titles
- **Note**: `lint-js` will still fail as there are errors in other files that need to be addressed separately

fix: Fix publisher a11y errors in publicise buttons section

---

static/js/publisher-pages/pages/Settings/SettingsForm.tsx

- Converted pseudo labels to paragraphs
- Fixed unsafe optional chaining
- Go to https://snapcraft-io-4926.demos.haus/<SNAP_NAME>/settings
- Check that "Collaboration", "Store" and "Status" rows all have titles
- Check that the "Status" row has a value
- **Note**: `lint-js` will still fail as there are errors in other files that still need to be addressed

fix: Fix publisher a11y errors in settings section

---

static/js/publisher-pages/pages/Listing/AdditionalInformation/LicenseSearch.tsx
static/js/publisher-pages/pages/Listing/ListingDetails/ListingDetails.tsx
static/sass/_patterns_form-multiselect.scss

Converted the remove licence icon to a button
- Go to https://snapcraft-io-4928.demos.haus/<SNAP_NAME>/listing
- Check that the "x" icon on selected licences looks and works as expected

fix: Fix a11y errors in license search

---

static/js/publisher-pages/components/SearchAutocomplete/SearchAutocomplete.tsx

Converted the remove licence icon to a button
- https://snapcraft-io-4929.demos.haus/<SNAP_NAME>/settings
- Check that the "x" icon on selected licences looks and works as expected

fix: Fix a11y errors in search autocomplete

---

static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.ts

Makes tooltip stick to edge of screen when hovering too far right or left.
- Go to any snap's Metrics page, make the page width smaller and hover to the edge of the graph. 
- The tooltip should not float off the edge, it should stick to the right or left so that no information is hidden.
Fixes [WD-17149](https://warthogs.atlassian.net/browse/WD-17149) and [4909](https://github.com/canonical/snapcraft.io/issues/4909)
[WD-17149]: https://warthogs.atlassian.net/browse/WD-17149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: stick metrics tooltip to edge of screen

---

static/js/publisher-pages/pages/Settings/SettingsForm.tsx

Fixed bug where checkboxes and radio buttons were cleared when reverting the settings form data
- Go to https://snapcraft-io-4937.demos.haus/<SNAP_NAME>/settings
- Change the value of any field
- Press the "Revert" button
- Check that the original checkbox or radio button values are restored and not cleared
Fixes https://warthogs.atlassian.net/browse/WD-17681

fix: Fix checkbox values resetting in publisher settings form

---

static/js/publisher-pages/pages/Listing/ContactInformation/PrimaryDomainInput.tsx
static/js/publisher-pages/pages/Listing/ContactInformation/__tests__/PrimaryDomainInput.test.tsx

Fixed bug where the primary domain input is cleared when reverting the listing form
- Go to https://snapcraft-io-4938.demos.haus/<SNAP_NAME>/listing (it must have a populated "Primary domain" field)
- Change the value of any field
- Press the "Revert" button
- Check that the "Primary domain" field has it's original value
Fixes https://warthogs.atlassian.net/browse/WD-17673

fix: Fix primary website field clearing on revert

---

static/js/publisher-pages/pages/Listing/PreviewForm/PreviewForm.tsx
templates/publisher/account-snaps.html
templates/publisher/publicise/store_buttons.html
templates/store/snap-details.html

- Makes sure the Edit button on preview page closes the current tab to take the user back to the `listing` page to make edits
- Removes statements requesting old `publisher.js` and `preview` code
- Go to https://snapcraft-io-4939.demos.haus/<SNAP_NAME>/listing
- Change the value of any field
- Press the "Preview" button
- Click "Edit" at the top of the screen
- Make sure the current tab closes
Fixes [WD-17675](https://warthogs.atlassian.net/browse/WD-17675)
[WD-17675]: https://warthogs.atlassian.net/browse/WD-17675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Make sure Edit button on preview page closes current tab

---

static/js/publisher-pages/pages/Listing/ListingDetails/ImageUpload.tsx
static/js/publisher-pages/pages/Listing/ListingDetails/ListingDetails.tsx

Fixed bug where icon preview wasn't removed if being deleted
- Go to [the demo](https://snapcraft-io-4940.demos.haus/) and visit a listing page with an icon
- Remove the icon and check that it disappears
- Click "Revert" and the icon should reappear
- Go to [the demo](https://snapcraft-io-4940.demos.haus/) and visit a listing page without an icon
- Upload an icon and see that there is a preview
- Click "Rever" and the icon should disappear
Fixes https://warthogs.atlassian.net/browse/WD-17674

fix: Fix deleting icon or banner not activating save button

---

static/js/publisher-pages/pages/Publicise/PubliciseButtons.tsx
webapp/publisher/snaps/publicise_views.py

- Render selected language in HTML and markdown snippets on `Publicise` page
- Removes random print statement
- Go to https://snapcraft-io-4942.demos.haus/<snap_name>/publicise
- Change the language in the dropdown
- Make sure the text changes in the HTML and MD snippets as well as the button
Fixes [WD-17678](https://warthogs.atlassian.net/browse/WD-17678)
[WD-17678]: https://warthogs.atlassian.net/browse/WD-17678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: render selected language in HTML and markdown snippets

---

static/js/publisher-pages/pages/Publicise/PubliciseCards.tsx

- Removes extra whitespace from embeddable card template
- Go to https://snapcraft-io-4943.demos.haus/<snap_name>/publicise/cards
- Check that there is no unnecessary whitespace in the embeddable card preview
- Change the settings and make sure the card resizes
Fixes [WD-17680](https://warthogs.atlassian.net/browse/WD-17680)
[WD-17680]: https://warthogs.atlassian.net/browse/WD-17680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove extra whitespace in embeddable card

---

static/sass/styles-embedded.scss
templates/store/snap-embedded-card.html

Fixed issue where preview card button is squashed
- Go to https://snapcraft-io-4945.demos.haus/<SNAP_NAME>/publicise/cards
- Check that the "Get if from the Snapstore" button looks as expected
Fixes https://warthogs.atlassian.net/browse/WD-17679

fix: Fix preview card button being squashed

---

static/js/publisher-pages/pages/Releases/components/releasesHeading.js
static/sass/styles.scss

Fixed a bug where the releases table scrolled too far leaving excessive whitespace underneath it
- Go to https://snapcraft-io-4946.demos.haus/<SNAP_NAME>/releases
- Check that there is not excessive white space below the table
Fixes https://warthogs.atlassian.net/browse/WD-17165

fix: Fix display of releases table

---

static/js/publisher-pages/pages/Build/Build.tsx
static/js/publisher-pages/pages/Releases/Releases.tsx

Added a loading state to the single build page
- Run the repo locally
- Follow the steps to setup a GitHub application: https://github.com/canonical/snapcraft.io/blob/main/HACKING.md#snap-automated-builds
- Go to a snap with builds, e.g. /<SNAP_NAME>/builds
- Click to a single build page
- Check that there is a loading state before the data loads
Fixes https://warthogs.atlassian.net/browse/WD-17167

fix: Add loading state to single build page

---

webapp/markdown.py

- Ensures `<` and `>` symbols are rendered correctly in preview pages of snaps
- Go to https://snapcraft-io-4948.demos.haus/test-flight-tracker/listing and click "Preview" and check that the symbols are rendered correctly in the Description
- Compare against https://snapcraft-io-4934.demos.haus/test-flight-tracker/listing (again, click "Preview")
- The symbols here are not rendering
- Can also QA with `deno` snap description 
Fixes [WD-17676](https://warthogs.atlassian.net/browse/WD-17676)
[WD-17676]: https://warthogs.atlassian.net/browse/WD-17676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: ensure markdown is rendered correctly

---

static/js/publisher-pages/pages/Listing/ListingDetails/ImageUpload.tsx
static/js/publisher-pages/utils/__tests__/getDefaultListingData.test.ts
static/js/publisher-pages/utils/getDefaultListingData.ts

Fixed bugs where the banner image wasn't being displayed in the listing publisher page and delete icons weren't showing when reverting changes.
- Go to https://snapcraft-io-4950.demos.haus/<SNAP_NAME>/listing
- If a banner is uploaded it should be visible
- Delete the banner and save
- Upload a banner then revert change
- The remove banner icon should be there
Fixes:
- https://warthogs.atlassian.net/browse/WD-17890
- https://warthogs.atlassian.net/browse/WD-17889
- https://warthogs.atlassian.net/browse/WD-17888
- https://warthogs.atlassian.net/browse/WD-17885

fix: Fix missing banner in listing publisher page

---

static/js/publisher-pages/hooks/useMutateListingData.ts
static/js/publisher-pages/utils/__tests__/formatImageChanges.test.ts
static/js/publisher-pages/utils/formatImageChanges.ts
static/js/publisher-pages/utils/getListingChanges.ts

Fixed a bug where changes to images on the publisher listing page were not resetting the form properly when saved
- Go to https://snapcraft-io-4952.demos.haus/<SNAP_NAME>/listing
- Add or remove an icon or banner and save the form
- The page should scroll back to the top and the "Revert" and "Save" buttons should be disabled
Fixes:
- https://warthogs.atlassian.net/browse/WD-17891
- https://warthogs.atlassian.net/browse/WD-17892
- https://warthogs.atlassian.net/browse/WD-17893
- https://warthogs.atlassian.net/browse/WD-17886
- https://warthogs.atlassian.net/browse/WD-17887

fix: Fix form not resetting when making changes to images

---

static/js/brand-store/pages/Snaps/SnapsSearch.tsx

Fixed a bug where the list of snaps to include in a store were not loading
- Go to https://snapcraft-io-4973.demos.haus/admin
- Press the "Include snap" button
- Type into the "Search available snaps" input, e.g. `core`
- Check that results appear

fix: Fix bug where snaps weren't loading when adding to store

---

package.json
static/sass/_patterns_first-snap-flow.scss
static/sass/_snapcraft_p-build.scss
static/sass/_snapcraft_p-progressive-bar.scss
static/sass/styles.scss
webpack.config.rules.js

- silences all sass warnings from dependencies (Vanilla)
- silences all sass warnings related to `import` (they are not urgent and require quite significant changes, automatic migrator doesn't seem to work out of the box https://sass-lang.com/documentation/breaking-changes/import/)
- silences warnings in webpack build as well (also from react-components and store-components)
- updates relevant code around color and other built-in functions to use their latest versions
A follow-up was created to fix warnings upstream in store-components: WD-18313
A follow-up was created to potentially fix import warnings if time allows: WD-18312
- Check the [build logs on CI](https://github.com/canonical/snapcraft.io/actions/runs/12868109724/job/35874131217?pr=4988)
- or pull the branch, run `dotrun build` …

Fix (or silence) Sass warnings

---

tests/publisher/snaps/tests_get_metrics.py
webapp/publisher/snaps/metrics_views.py

Fixes metrics not showing on private snaps metrics pages
- Go to a private snaps metrics page: https://snapcraft-io-4997.demos.haus/<PRIVATE_SNAP_NAME>/metrics
- Check that metrics are available
Fixes https://warthogs.atlassian.net/browse/WD-18363

fix: Fix issue with metrics endpoints returning 404

---

webapp/publisher/snaps/build_views.py
webapp/publisher/snaps/metrics_views.py
webapp/publisher/snaps/publicise_views.py
webapp/publisher/snaps/release_views.py

Make publisher pages 404 if the user doesn't have access to that snap
- Make sure you are signed in: https://snapcraft-io-4998.demos.haus/snaps
- Go to https://snapcraft-io-4998.demos.haus/domotzpro-agent/listing
- Check that the page 404s
- Go to https://snapcraft-io-4998.demos.haus/domotzpro-agent/builds
- Check that the page 404s
- Go to https://snapcraft-io-4998.demos.haus/domotzpro-agent/releases
- Check that the page 404s
- Go to https://snapcraft-io-4998.demos.haus/domotzpro-agent/metrics
- Check that the page 404s
- Go to https://snapcraft-io-4998.demos.haus/domotzpro-agent/publicise
- Check that the page 404s
- Go to https://snapcraft-io-4998.demos.haus/domotzpro-agent/settings
- Check that the page 404s
Fixes https://warthogs.atlassian.net/browse/WD-18600

fix: Make publisher pages 404 with no permissions

---

static/js/publisher/pages/Build/Build.tsx
static/js/publisher/pages/Builds/Builds.tsx
static/js/publisher/pages/Listing/Listing.tsx
static/js/publisher/pages/Metrics/Metrics.tsx
static/js/publisher/pages/Publicise/Publicise.tsx
static/js/publisher/pages/PublisherSettings/PublisherSettings.tsx
static/js/publisher/pages/Releases/Releases.tsx

Added appropriate page titles for publisher pages and added an `aria-live` attribute to page headings to inform screen readers that the page has changed.
- Go to https://snapcraft-io-4999.demos.haus/<SNAP_NAME>/listing
- Click between the tabs and make sure the page title in the browser tab makes sense
Fixes https://warthogs.atlassian.net/browse/WD-18633

chore: Add relevant page titles to snap publisher pages

---

static/js/publisher/utils/__tests__/getSettingsFormData.test.ts
static/js/publisher/utils/__tests__/setPageTitle.test.ts

Added tests for publisher utils
All tests should pass (the inclusive naming check will fail)
Fixes https://warthogs.atlassian.net/browse/WD-18400

chore: Add tests to publisher utils

---

package.json
static/js/base/global-nav.ts
static/sass/styles.scss
templates/_header.html
yarn.lock

Fixes the alignment of top navigation:
- uses navigation 25/75 split from Vanilla
- updates Vanilla (to fix the navigation wrapping issue)
- removes unnecessary navigation customisations that were causing conflicts between Vanilla, global-nav and local responsive breakpoints
- visit home page on demo (https://snapcraft-io-5000.demos.haus/)
- make sure top navigation is well aligned (first item should align with hero content)
- make sure navigation works as expected on all screen sizes
- repeat steps above for documentation (test locally as it's not available on demos) 
Fixes WD-18308
Before
After

Fix top navigation alignment

---

static/js/publisher/pages/Builds/RepoSelector.tsx

fix parameter that is sent to build endpoint
Fixes https://warthogs.atlassian.net/browse/WD-18976

fix parameter that is sent to build endpoint

---

webapp/store/content/publishers/snapcrafters-snaps.yaml

- Updated mattermost logo: reference https://github.com/snapcrafters/mattermost-desktop/issues/118#issuecomment-2647411348
- https://snapcraft-io-5019.demos.haus/publisher/snapcrafters
Fixes #5018

fix: Update mattermost icon on snapcrafters publisher page

---

static/js/publisher/components/Navigation/Navigation.tsx
static/sass/styles.scss

Changes the icon for "My stores" in the brand store navigation
- Go to https://snapcraft-io-5023.demos.haus/admin
- Check that the "My stores" heading in the side navigation uses [the units icon from Vanilla](https://vanillaframework.io/docs/patterns/icons)
Fixes https://warthogs.atlassian.net/browse/WD-14703

chore: Change icon in brand stores navigation

---

static/js/base/navigation.ts
static/js/publisher/components/Navigation/Navigation.tsx
static/js/publisher/components/PrimaryNav/PrimaryNav.tsx
templates/_header.html
webapp/login/views.py

- Adds "Validation sets" link to the brand store navigation if the user has validation sets
- Only shows "Validation sets" link in the account dropdown if the user has validation sets
- Go to https://snapcraft-io-5033.demos.haus/
- Make sure you are logged in
- Click the account dropdown in the right hand side of the navigation
- If you have validation sets you should see a link to them, otherwise you shouldn't
- Go to https://snapcraft-io-5033.demos.haus/admin
- If you have validation sets you should see a link to them in the side navigation, otherwise you shouldn't
- Go to https://snapcraft-io-5033.demos.haus/<SNAP_NAME>/listing
- If you have validation sets you should see a link to them in the side navigation, otherwise you shouldn't
To create a validation set, here are the steps on a …

chore: Add validation sets link to brand store nav

---

static/js/publisher/components/Navigation/Navigation.tsx
static/js/publisher/components/PrimaryNav/PrimaryNav.tsx
static/js/publisher/components/StoreSelector/StoreSelector.tsx
static/js/publisher/components/StoreSelector/index.ts

Adds the brand store selector to the publisher pages navigation
- Go to https://snapcraft-io-5035.demos.haus/<SNAP_NAME>/listing
- Check that there is a store selector in the side navigation (if you have stores)
Fixes https://warthogs.atlassian.net/browse/WD-19513

chore: Add store selector to publisher pages

---

webapp/publisher/snaps/metrics_views.py

Use correct template for publisher metrics page
- Go to https://snapcraft-io-5038.demos.haus/<SNAP_NAME>/metrics
- The page should load with metrics data
Fixes #

fix: Use correct template for metrics views

---

static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx

Fixes issue where "Register a snap name" button doesn't work as it's not part of the publisher SPA
- Go to https://snapcraft-io-5041.demos.haus/snaps
- Click the "Register a snap name" button
- Check that it goes to https://snapcraft-io-5041.demos.haus/register-snap

fix: Fix register snap link

---

webapp/publisher/views.py

Fixes bug where new accounts get caught in a redirect loop when trying to accept the developer agreement programme
- https://snapcraft-io-5048.demos.haus/ and login
- Go to https://snapcraft-io-5048.demos.haus/account/agreement
- Accept the agreement
- You should be taken to https://snapcraft-io-5048.demos.haus/snaps

fix: Remove login which causes redirect loop for new accounts

---

static/sass/styles.scss

- incorrect z-index causing child components to have incorrect layout 
- go to /snaps
- metrics toolbar should be over all other components
Fixes WD-19998 reported here https://chat.canonical.com/canonical/pl/sizwtkcrupydpfe7t7em47iaje

fix: remove unnecessary z-index

---

static/js/publisher/pages/Builds/RepoSelector.tsx

The problem I encountered is that the Organizations dropdown had the list of organizations that my GitHub account is a part of, and then a blank entry that represents the repos owned by my user. I checked out the source code of that page and it uses the `name` attribute of the GH user, which is optional.
My user didn't have it set so the entry was empty. The issue is cosmetic/UX only, as clicking on the black entry still shows the user's own repos and everything is connected successfully.
Added the `login` attribute of the GH user as default value for the label of the dropdown entry representing the user's repos.
Unfortunately, I wasn't able to get a working test environment due to yarn and/or node version issues,  even in a fresh VM, so this change is completely untested either by a …

Builds: default string for Organizations dropdown if user does not have "name"

---

requirements.txt

Updated store-api to fix issue with icons not being removed
- Go to https://snapcraft-io-5062.demos.haus/<SNAP_NAME>/listing
- Remove the icon and save
- The icon should be removed

fix: Update store-api to fix remove icon bug

---

webapp/publisher/cve/cve_views.py

Updates `get_snap_info` call in CVEs API to the new parameters order.
- call https://snapcraft-io-5063.demos.haus/api/snaps/cve/docker/1234
- sign in
- you should get JSON response with ""User is not allowed to see snap's CVE data." error, not default snapcraft "Please try again later" error page

Fixes get_snap_info call in CVEs API

---

static/js/publisher/components/RegisteredSnaps/RegisteredSnaps.tsx

Removes the links from the registered snap names list
- Go to https://snapcraft-io-5072.demos.haus/snaps
- Check that the snaps names in the "Registered snap names" table are not links
Fixes https://warthogs.atlassian.net/browse/WD-20981

chore: Remove links from registered snap names list

---

templates/store/snap-distro-install.html

- Don't index installation instruction pages
- go to an unlisted snap (i.e stress-ng-dev)
- no-index meta tag should be present in the main snap details page
- no-index meta tag should be present in all the installation instruction pages
- listed snaps (code,lxd) should not have those tags
Fixes WD-21065

fix: don't index unlisted snaps

---

static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx
static/js/publisher/components/PublishedSnapSection/PublishedSnapSection.tsx
static/js/publisher/components/RegisteredSnaps/RegisteredSnaps.tsx
static/js/publisher/constants/index.ts
static/js/publisher/types/constants.ts
static/js/publisher/types/shared.ts

- Removes unused type (`CurrentStoreSlice`) which was left over from Redux Toolkit
- Renames `PAGE_NUMBER` constant to `ITEMS_PER_PAGE` to be clearer as to its intent
- Moves constants file from types to a constants directory as it is not a type (there are potentially more constants that could be added to this file in the codebase)
All the checks should pass

chore: Delete unused type and move constants file

---

static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx

Currently if published has no snaps we show both "My published snaps" and "Get started" headings (floated next to one another).
This PR fixes this by hiding "My published snaps" heading if there are no snaps.
- log in to demo with user that doesn't have snaps https://snapcraft-io-5079.demos.haus/snaps
- check if heading displays correctly

fix: Fix welcome heading when publisher has no snaps

---

static/js/publisher/pages/SigningKeys/SigningKeys.tsx

Address compiler warnings from [the TiCS dashboard](https://canonical.tiobe.com/tiobeweb/TICS/TqiDashboard.html#axes=ProjectGroup(PublicRepos),Project(snapcraft.io),Sub(static),Sub(js),Sub(publisher),Sub(pages),Sub(SigningKeys),Sub()&metric=tqiCompWarn)
- Go to https://snapcraft-io-5088.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys
- Check that the page loads as expected

fix: Address Signing Keys compiler warnings from TiCS dashboard

---

static/js/publisher/pages/RegisterSnap/RegistrationError.tsx

Addresses register snap compiler warnings from [the TiCS dashboard](https://canonical.tiobe.com/tiobeweb/TICS/TqiDashboard.html#axes=ProjectGroup(PublicRepos),Project(snapcraft.io),Sub(static),Sub(js),Sub(publisher),Sub(pages),Sub(RegisterSnap),Sub()&metric=tqiCompWarn)
- Go to https://snapcraft-io-5089.demos.haus/register-snap
- Register a snap name that you already own or that already exists
- Check that a notification appears telling you about the error

fix: Address register snap compiler warnings from TiCS dashboard

---

static/js/publisher/pages/RegisterSnap/RegistrationError.tsx
static/js/publisher/pages/RegisterSnap/__tests__/RegisterSnapError.test.tsx

Fixes issue where the correct notification isn't displayed when registering snap names in the global store
- Go to https://snapcraft-io-5095.demos.haus/register-snap
- Register a new snap name that isn't reserved or already existing
- Check that the notification links to the dashboard

fix: Fix incorrect notification when registering snap name in the global store

---

static/js/publisher/utils/__tests__/getSettingsChanges.test.ts
static/js/publisher/utils/__tests__/getSettingsData.test.ts
static/js/publisher/utils/getSettingsChanges.ts

Adds tests for publisher utils
All tests should pass (except the inclusive naming check)

fix: Address code coverage warnings from TiCS dashboard for publisher utils

---

tests/publisher/cve/test_has_cve.py
tests/publisher/cve/test_has_cve_api.py
webapp/publisher/cve/cve_helper.py
webapp/publisher/cve/cve_views.py
webapp/publisher/snaps/views.py

Adds an API endpoint to check if given snap has CVE data available.
If the user is allowed to see the CVE data (is Canonical publisher and has access to said snap), and there is CVE data available in the snap-cves repo, it should return true, otherwise it should error.
- sign in
- assuming you have access to docker snap (https://snapcraft-io-5100.demos.haus/docker/listing)
- go to API endpoint for snap that has CVES: https://snapcraft-io-5100.demos.haus/api/snaps/cve/docker - it should return succecss true
- go to any other snap you have access to that doesn't have CVEs: https://snapcraft-io-5100.demos.haus/api/snaps/cve/firefox - should return error that CVEs data is not available, with 404 status code
- go to API endpoint for non-existent snap: …

feat(CVEs): Adds the API endpoint to check CVEs availability for given snap

---

static/js/base/__tests__/ga.test.ts
static/js/base/contactForm.ts
static/js/base/dropdown-menu-toggle.ts
static/js/base/ga.ts
static/js/base/navigation.ts
static/js/public/ga-scroll-event.ts
static/js/public/snap-details/channelMap.ts

Addressed TiCS coding standards warnings for base JS
- Converted the parameters to an object for the `triggerEvent` function to meet the parameter limit requirement, which makes it clearer what each argument is for when using the function
- Added missing return types to functions
- Marked DOM selector elements as possibly undefined and added appropriate checks for their existence
- Renamed `origin` to `urlLocation` as `origin` is an existing global object
- Removed some unnecessary if conditions
- Fixed some basic linting errors
All JS tests and linter checks should pass

chore: Address TiCS coding standards warnings for base JS

---

tests/publisher/cve/test_has_cve.py
tests/publisher/cve/test_has_cve_api.py
webapp/publisher/cve/cve_helper.py
webapp/publisher/cve/cve_views.py
webapp/publisher/snaps/views.py

- renames previous `/api/cve/[SNAP]` endpoints to `/api/[SNAP]/cves` for consistency with other snap based endpoints
- replaces previous endpoint that only checked for CVEs availability with an endpoint that returns list of revisions that have CVEs data
Current CVEs endpoints are:
- `/api/[SNAP]/cves` - returns list of revisions that have CVEs data, or error if not found
- `/api/[SNAP]/[REVISION/cves` - returns list of revisions for given revision of a snap
- go to [demo](https://snapcraft-io-5108.demos.haus/), and sign in (ideally with canonical account with superuser access)
- check cves endpoint for a snap that doesn't have data, it should error: https://snapcraft-io-5108.demos.haus/api/firefox/cves
- check CVEs endpoint for a snap that has CVE data: …

Add API endpoint to get revisions with CVEs data

---

static/js/publisher/utils/__tests__/getListingChanges.test.ts
static/js/publisher/utils/getListingChanges.ts

Adds tests for the `getListingChanges` utility

chore: Address TiCS code coverage warnings for publisher utils

---

static/js/publisher/pages/PublisherSettings/PublisherSettingsForm.tsx
static/js/publisher/pages/PublisherSettings/__tests__/PublisherSettings.test.tsx
static/js/publisher/pages/PublisherSettings/__tests__/PublisherSettingsForm.test.tsx

Adds tests for the publisher settings page/components

chore: Add tests for publisher settings page

---

static/js/publisher/pages/RegisterNameDispute/__tests__/RegisterNameDispute.test.tsx

Adds tests for the `RegisterNameDispute` component

chore: Add tests for register name dispute component

---

tests/publisher/cve/test_cve_get_by_revision.py
webapp/publisher/cve/cve_helper.py

Exposes CVE status as part of API, to avoid digging this information out of more nested data.
- Code review
- Check if updated python tests pass on CI.

Expose status of CVE in API response

---

static/js/publisher/pages/Metrics/metrics/graphs/activeDevicesGraph/tooltips.ts
static/js/publisher/pages/Releases/Releases.tsx
static/js/publisher/pages/Releases/components/revisionsList.js
static/js/publisher/pages/Releases/components/revisionsListRow.js
static/js/publisher/pages/Releases/releasesState.js

- Updated logic around showing progressive releases
- prettier went ham, sorry
- Visit https://snapcraft-io-5119.demos.haus/snapd/releases and compare progressive release data with https://snapcraft.io/snapd/releases
- The demo should display the data, the live site does not
- Visit https://snapcraft-io-5119.demos.haus/snapd/releases and compare progressive releases data with to `snapcraft status snapd`
- The information in both should match
Fixes #

fix: ensure progressive releases show in release ui

---

package.json
yarn.lock

Adds lodash to resolutions to address Dependabot security notifications, e.g. https://github.com/canonical/snapcraft.io/security/dependabot/4
- All checks should pass
- Can't check if it fixes issue until merged

fix: Add lodash to resolutions to fix security patch

---

package.json
yarn.lock

Adds lodash to resolutions to address Dependabot security notifications, e.g. https://github.com/canonical/snapcraft.io/security/dependabot/46
- All checks should pass
- Can't check if it fixes issue until merged

fix: Update lodash version in resolutions

---

static/js/publisher/components/StoreSelector/StoreSelector.tsx
static/sass/_snapcraft_l-application.scss

- Makes sure "x" button clears input
- Makes sure input text is light in colour
- Go to https://snapcraft-io-5136.demos.haus/snaps
- Click the `My Stores` dropdown
- Search for something - make sure the text input is light in colour
- Click the "X", make sure the input clears
Fixes [WD-18956](https://warthogs.atlassian.net/browse/WD-18956)
[WD-18956]: https://warthogs.atlassian.net/browse/WD-18956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Wd 18956/stores filter

---

README.md

Updates how to install `dotrun` in README

fix: Fix instructions for installing dotrun

---

static/js/publisher/pages/Listing/AdditionalInformation/__tests__/AdditionalInformation.test.tsx
static/js/publisher/pages/Listing/AdditionalInformation/__tests__/LicenseInputs.test.tsx
static/js/publisher/pages/Listing/AdditionalInformation/__tests__/LicenseSearch.test.tsx
static/js/publisher/pages/Listing/ContactInformation/ContactFields.tsx
static/js/publisher/pages/Listing/ContactInformation/__tests__/ContactFields.test.tsx
static/js/publisher/pages/Listing/ContactInformation/__tests__/ContactInformation.test.tsx
static/js/publisher/pages/Listing/ListingDetails/ListingDetails.tsx
static/js/publisher/pages/Listing/ListingDetails/__tests__/ImageUpload.test.tsx
static/js/publisher/pages/Listing/ListingDetails/__tests__/ListingDetails.test.tsx
static/js/publisher/pages/Listing/ListingForm/ListingForm.tsx
static/js/publisher/pages/Listing/ListingForm/__tests__/ListingForm.test.tsx
static/js/publisher/pages/Listing/PreviewForm/PreviewForm.tsx
static/js/publisher/pages/Listing/PreviewForm/__tests__/PreviewForm.test.tsx
static/js/publisher/pages/Listing/__tests__/Listing.test.tsx
static/js/publisher/test-utils/mockListingData.ts
templates/store/snap-details/_snap_heading_data.html
webapp/publisher/snaps/logic.py

- Fixes data not being refreshed in the hidden PreviewForm present in ListingForm.tsx
- Fixes Internal Server Error caused when previewing a snap page when a new icon has been added and there's a blob image only present in the browser.
- Check out this PR
- Execute `dotrun` and access the server at `http://127.0.0.1:8004/`
- Visit any snap listing page, i.e. `http://127.0.0.1:8004/tdhcad/listing`
- Add an icon image from your computer
- Click on the Preview button
Fixes [WD-21811](https://warthogs.atlassian.net/browse/WD-21811)
[WD-21811]: https://warthogs.atlassian.net/browse/WD-21811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-21811 - snap icon causes Internal Server Error

---

redirects.yaml

Removes optional trailing slash from redirects that are currently not working in prod. 
Impossible to QA until merged as these are currently working locally and on staging.

remove trailing slash from broken redirects

---

static/js/publisher/publisher.tsx

Fixes issue where releases data doesn't load when navigating back from another tab
- Go to a snaps release page on the demo: https://snapcraft-io-5153.demos.haus/
- Click to any other tab and wait for it to fully load
- Go back to the releases page using the tabs navigation
- The releases data should be on the page
Fixes #5152

fix: Fix releases data disappearing on second mount

---

webapp/publisher/snaps/listing_views.py

Transform set into dict to fix the error triggered when calling make_response.
You need to own a snap so that you can write changes to it -> [Craft a snap](https://documentation.ubuntu.com/snapcraft/stable/tutorials/craft-a-snap/)
- Run `dotrun`
- Go to your snap listing page: 127.0.0.1:8004/{your-snap}/listing
- Add a valid image
- Open the network tab or check the log output of dotrun
- Click on 'Save'
The network response to the POST should contain a 200.
No error stack trace should be on the output of dotrun.
Fixes [ISSUE-5146](https://github.com/canonical/snapcraft.io/issues/5146)

WD-22439 - change set to dict to fix make_response call

---

redirects.yaml

- Adds missing redirect for /docs/robotics
- Go to https://snapcraft-io-5158.demos.haus/docs/robotics
- Make sure it redirects to https://canonical-robotics.readthedocs-hosted.com/en/latest/explanations/snaps/

chore: add missing redirect for robotics docs

---

redirects.yaml

Now that the old Snapcraft docs are removed from the index, the root page must be redirected to the RTD root.

redirect snapcraft root

---

redirects.yaml

Removed a redirect. This page was retired prematurely and has been restored for customers.

redirects: remove supported-snap-hooks

---

static/sass/_snapcraft_l-application.scss

Fixes text color for search inputs inside the dashboard: previously the text color styles were overwritten and wouldn't respect the application theme (i.e. dark text on light background and vice versa), leading to unreadable text in some cases.
- Go to https://snapcraft-io-5166.demos.haus/snaps
- In the left navigation, open the "My stores" dropdown and write something in the Search input -> text should be light
- Open the ["My validations sets" section](https://snapcraft-io-5166.demos.haus/validation-sets) and write something in the Search input at the top -> text should be dark
- Open the ["Store snaps" section](https://snapcraft-io-5166.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps) of a brand store
- write something in the Search input at the top -> text should be dark
- click on …

Remove search input color overrides

---

static/js/publisher/components/Navigation/Navigation.tsx
static/js/publisher/hooks/__tests__/usePolicies.test.tsx
static/js/publisher/hooks/usePolicies.ts
static/js/publisher/hooks/useSigningKeys.ts
static/js/publisher/pages/Model/CreatePolicyForm.tsx
static/js/publisher/pages/Model/Policies.tsx
static/js/publisher/pages/Model/PoliciesTable.tsx
static/js/publisher/pages/SigningKeys/SigningKeys.tsx
static/js/publisher/pages/SigningKeys/SigningKeysTable.tsx
static/js/publisher/utils/sortByDateDescending.ts
tests/admin/tests_models.py
webapp/admin/views.py

- Extracts call to the store endpoint to a custom hook
- Uses the brand ID rather than the store ID for model service requests
- Go to https://snapcraft-io-5160.demos.haus/admin/ahnuP3quahti9vis8aiw/settings
- Check that you are able to make and save changes
- Go to https://snapcraft-io-5160.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Check that the side navigation has links for "Models" and "Signing keys"
- With the network tab open, click the "Models" link
- Check that the models table loads and is populated
- In the network tab, check that calls to the policies endpoint are successful (not all models have them so won't all show in the table)
- Check that you can successfully create a new model
- Click through to a model with policies (e.g. …

fix: Use brand account ID rather than store ID in model service requests

---

templates/store/snap-distro-install.html

Added a missing "distro-install.js" script in the Distro install page template.
- navigate to https://snapcraft-io-5168.demos.haus/install/pinta/arch
- interact with the image carousel:
- the arrows and swiping (click and drag) should work
- clicking on an image should open the clicked image in full screen
Fixes #5167

fix: add missing "distro-install.js" script

---

static/js/publisher/components/UpdateMetadataModal/UpdateMetadataModal.tsx
static/js/publisher/hooks/__tests__/useMutateListingData.test.ts
static/js/publisher/hooks/useMutateListingData.ts
static/js/publisher/pages/Listing/ListingForm/ListingForm.tsx
static/js/publisher/pages/Listing/ListingForm/__tests__/ListingForm.test.tsx
static/js/publisher/types/index.ts
webapp/publisher/snaps/listing_views.py
webpack.config.rules.js

Add error message when the Save action of a snap listing fails; this way we let the user know what went wrong.
- Go to the [issue](https://github.com/canonical/snapcraft.io/issues/5171) page and download the image in there.
- Go to [Demos](https://snapcraft-io-5172.demos.haus/) and visit the listing of a snap you are able to modify.
- Add the image you downloaded in the first step.
- Click Save.
You should see an error message saying that the aspect ratio is not valid.
Fixes #5171
[WD-23027](https://warthogs.atlassian.net/browse/WD-23027)
[WD-23027]: https://warthogs.atlassian.net/browse/WD-23027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-23027 - feat: add error to snap/listing page when save fails

---

static/js/store/pages/Explore/CardsLoader.tsx
static/js/store/pages/Explore/Explore.tsx
static/js/store/pages/Explore/RecommendationsSection.tsx
static/js/store/pages/Explore/__tests__/Explore.test.tsx
static/js/store/pages/Explore/__tests__/RecommendationsSection.test.tsx
static/js/store/test-utils/index.ts
static/js/store/test-utils/mockRecommendations.ts
static/js/store/types/CardData.ts
static/js/store/types/RecommendationData.ts
static/js/store/types/index.ts
static/js/store/utils/__tests__/formatCardData.test.ts
static/js/store/utils/formatCardData.ts
static/js/store/utils/index.ts
webapp/handlers.py

Adds a recommendations section component to show recommendation categories
- Go to https://snapcraft-io-5173.demos.haus/explore
- Check that there is a section for "Recently updated snaps"
- Check that there is a section for "Most popular snaps"
- Check that there is a section for "Trending snaps"
Fixes:
- https://warthogs.atlassian.net/browse/WD-22662
- https://warthogs.atlassian.net/browse/WD-22663
- https://warthogs.atlassian.net/browse/WD-22664

feat: Add explore page recommendation sections

---

static/js/publisher/pages/Releases/Releases.tsx
static/js/publisher/pages/Releases/actions/__tests__/releases.test.js
static/js/publisher/pages/Releases/actions/defaultTrack.js
static/js/publisher/pages/Releases/actions/releases.ts
static/js/publisher/pages/Releases/api/releases.js
static/js/publisher/pages/Releases/components/defaultTrackModifier.js
static/js/publisher/types/releaseTypes.ts

- Removed csrfToken from the store
- Removed code that was passing csrfToken around as a parameter
- Where csrf token is needed, change to `window.CSRF_TOKEN`
- Load the release ui and use it as normal.
- You should be able to release revision without CSRF issues.
https://warthogs.atlassian.net/browse/WD-23299

fix: use global csrf token

---

static/js/publisher/pages/Releases/actions/pendingReleases.js
static/js/publisher/pages/Releases/actions/releases.ts
static/js/publisher/pages/Releases/api/releases.js
static/js/publisher/pages/Releases/components/releasesTable/cellViews.js
static/js/publisher/pages/Releases/components/releasesTable/channelHeading.tsx
static/js/publisher/pages/Releases/components/releasesTable/droppableRow.tsx
static/js/publisher/pages/Releases/components/releasesTable/row.tsx
static/js/publisher/pages/Releases/helpers.ts

- Allow releasing the same revision over a progressive release.
- This enables progressive release updates (from 30% -> 50% -> 100% for example).
- Create a progressive release, with a revision, create a non-progressive release with the same revision
- Ensure that dragging the revision to the progressive release is allowed, and to the non-progressive release is not allowed
- Test the channel "promote" drop down, revision "promote" drop down, and dagging both a revision and channel all work as expected.
- [] This PR has tests
Fixes https://warthogs.atlassian.net/browse/WD-23302

feat: allow progressive rerelease

---

requirements.txt
tests/publisher/tests_get_package_metadata.py
webapp/publisher/snaps/views.py

Added handlers for errors separately  for 
/api/packages/<snap_name> endpoint returns 500 with " metadata cannot be fetched" error. 
[ttps://snapcraft.io/api/packages/teams-for-linux](https://sentry.is.canonical.com/canonical/snapcraft-io/?query=url%3A%22https%3A%2F%2Fsnapcraft.io%2Fapi%2Fpackages%2Fteams-for-linux%22)
- go to 'https://snapcraft-io-5196.demos.haus/api/packages/some-random-snap-24525235'
- verify the response returns: {"error":"Package not found","success":false}
- go to the same url with the snap id that you have access to 'https://snapcraft-io-5196.demos.haus/api/packages/(your-snap-id)'
- verify the metadata returns
- go to the same url with the snap id that you DONT have access to 'https://snapcraft-io-5196.demos.haus/api/packages/teams-for-linux'
- verify 401 is …

fix:Added handlers for errors separately

---

static/js/publisher/pages/Snaps/Snaps.tsx
static/js/publisher/types/shared.ts

Fixes an issue where the name and ID of a store in the fully included list is not displayed
- Go to https://snapcraft-io-5199.demos.haus/admin/nah4ahShap8aefie6pha/snaps
- Scroll down to "Fully included stores"
- Expand the panel and check that the store in the list displays it's name and ID
Fixes https://warthogs.atlassian.net/browse/WD-23315

fix: Fix empty included stores list

---

static/js/publisher/pages/Releases/actions/__tests__/pendingReleases.test.js
static/js/publisher/pages/Releases/actions/pendingReleases.js
static/js/publisher/pages/Releases/components/progressiveBar.js
static/js/publisher/pages/Releases/components/progressiveBarControl.js
static/js/publisher/pages/Releases/components/releasesConfirmDetails/cancelProgressiveRow.js
static/js/publisher/pages/Releases/components/releasesConfirmDetails/index.js
static/js/publisher/pages/Releases/components/revisionsList.js
static/js/publisher/pages/Releases/reducers/__tests__/pendingReleases.test.js
static/js/publisher/pages/Releases/reducers/pendingReleases.ts
static/js/publisher/pages/Releases/selectors/__tests__/selectors.test.js
static/js/publisher/pages/Releases/selectors/index.ts
static/sass/_snapcraft_p-progressive-bar.scss

- When updating a progressive release, ensure you can't release to a lower percentage than is currently set.
- Added some extra text to the Review panel around minimum progressive releases.
- Updated the way we get the previous release, to ensure that if you:
1. create a progressive release rev 1 -> rev 2
2. overwrite the release with rev 1
3. Create another progressive release rev 1 -> rev 2
The minimum percentage from step 1. isn't shown in step 3.
- Renamed `previousRevisions` to `previousReleases` throughout (as this is what is actually stored in the variable).
- Fixed defaultProp deprecation warning.
- Pull the branch or view the demo
- Play with progressive releases. Create them, remove them, overwrite them. Things should work as expected.
- Try doing some strange things, like …

feat: Improved progressive release experience

---

package.json
yarn.lock

Updates `react-joyride` to the `next` branch so we can upgrade to React 19. The project seems to have stagnated, [see related issue](https://github.com/gilbarbara/react-joyride/issues/1122) but their next branch does support React 19.
- Go to a snaps listing page, e.g. https://snapcraft-io-5216.demos.haus/<SNAP_NAME>/listing
- Click the `?` button in the bottom right of the page
- Check that the tour highlights work the same as in production

chore: Upgrade react-joyride to next version for React 19 upgrade

---

requirements.txt

Unregistering a snap currently returns the following error: “Unregistering snaps requires Snapcraft credentials”
This is because for Snap packages, the `unregister_package` API actually uses SCA's API under the hood: if we pass the authentication header in the wrong format the API errors out. When the name_space is "snap" we should pass the authorization header as if we were calling SCA.
This issue was fixed within the `store_api` package, this PR bumps up its version in the `requirements.txt` file
1. go to https://snapcraft-io-5218.demos.haus/snaps
2. register a new snap name
2.1. you should be redirected to https://snapcraft-io-5218.demos.haus/snaps
3. open the dev tools
4. in the table at the bottom of the page press the "Unregister" button
4.1. the DELETE request should return a 200 …

WD-23838 - update store_api package

---

redirects.yaml

Users on Snapcraft 7 prefer to keep access to the old docs, which are still hosted on the forum.
Fixes https://warthogs.atlassian.net/browse/SNAPCRAFT-1171

redirects: move deleted pages to forum

---

webapp/publisher/snaps/settings_views.py

Fixed a 500 error on calls to https://snapcraft.io/< snap name >/settings caused by an incorrect type conversion:
```
TypeError: unsupported operand type(s) for |: 'NoneType' and 'bool'
```
1. Go to https://snapcraft-io-5226.demos.haus/< snap name >/settings
2. The snap's settings page loads correctly
Fixes #5224

fix: use correct type conversion for None -> bool

---

templates/docs/document.html

Added the | e filter to escape version['version'] in the option text to prevent potential HTML injection and improve security. It converts special characters like <, >, &, and " into their HTML entity equivalents.
Fixes https://github.com/canonical/snapcraft.io/security/code-scanning

fix:escape version values in select dropdown to prevent xss

---

tests/endpoints/tests_get_store.py
webapp/admin/views.py
webapp/endpoints/views.py

Migrates `/api/store/<store_id>` into a dedicated endpoints module
- Go to https://snapcraft-io-5244.demos.haus/api/store/ahnuP3quahti9vis8aiw
- Check that it is the same as https://snapcraft.io/api/store/ahnuP3quahti9vis8aiw
Fixes https://warthogs.atlassian.net/browse/WD-24116

chore: Move store endpoint to endpoints section of app

---

webapp/publisher/snaps/release_views.py
webapp/publisher/snaps/views.py

log stack traces internally, return generic error messages to avoid exposing stack traces
Fixes https://warthogs.atlassian.net/browse/WD-24170

fix: avoid exposing internal errors

---

tests/admin/tests_models.py
tests/endpoints/tests_models.py
tests/endpoints/tests_signing_keys.py
webapp/admin/views.py
webapp/app.py
webapp/endpoints/models.py

Migrates `/api/store/brand-id/models` into a dedicated endpoints module
- Go to https://snapcraft-io-5248.demos.haus/api/store/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that it is the same as https://snapcraft.io/api/store/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
Fixes https://warthogs.atlassian.net/browse/WD-24123

chore: Move models endpoint to the endpoints section of app

---

tests/admin/tests_policies.py
tests/admin/tests_signing_keys.py
tests/endpoints/tests_policies.py
webapp/admin/views.py
webapp/endpoints/models.py

Migrates `/api/store/<brand_id>/models/<model_id>/policies` to dedicated endpoints module
Also patches `get_store` method in signing key tests so they don't break
- Go to https://snapcraft-io-5251.demos.haus/api/store/ahnuP3quahti9vis8aiw/models/test-model/policies
- Check that it is the same as https://snapcraft.io/api/store/ahnuP3quahti9vis8aiw/models/test-model/policies
Fixes https://warthogs.atlassian.net/browse/WD-24126

chore: Move policies endpoint to the endpoint section of app

---

.github/workflows/coverage.yml
.github/workflows/pr.yml

The GITHUB_TOKEN in the workflows have broad write permissions across many scopes (issues, pages, deployments, packages...). Adding permissions limits the token's power and improves CI/CD security.
- Go to https://github.com/canonical/snapcraft.io/actions/runs/16651461029
- Click on the job in the workflow run.
- Expand the “Set up job” step.
- Check the “GITHUB_TOKEN Permissions” section.
- Verify that the required permissions are present:
- If the job only reads repository content, contents: read is enough.
- If it modifies or comments on a pull request, it needs pull-requests: write.
Fixes https://warthogs.atlassian.net/browse/WD-24281

fix: reduce GITHUB_TOKEN scope for the jobs

---

tests/endpoints/tests_dns_verified_status.py
webapp/app.py
webapp/endpoints/snaps.py
webapp/store/snap_details_views.py

Migrate `/api/<snap_id>/verify` to endpoints section of app
- Go to https://snapcraft-io-5252.demos.haus/api/steve-test-snap/verify
- Check that it is the same as https://snapcraft.io/api/steve-test-snap/verify
- Go to https://snapcraft-io-5252.demos.haus/api/fran-snap/verify
- Check that it is the same as https://snapcraft.io/api/fran-snap/verify
Fixes https://warthogs.atlassian.net/browse/WD-24105

chore: Move verify endpoint to the endpoint section of app

---

tests/endpoints/tests_snaps_search.py
webapp/admin/views.py
webapp/app.py
webapp/endpoints/snap_search.py

Moves the snaps search endpoint into the endpoints section of the app
- Go to https://snapcraft-io-5259.demos.haus/api/ahnuP3quahti9vis8aiw/snaps/search
- Check it is the same as https://snapcraft.io/api/ahnuP3quahti9vis8aiw/snaps/search
- Go to https://snapcraft-io-5259.demos.haus/api/ahnuP3quahti9vis8aiw/snaps/search?q=canonical
- Check it is the same as https://snapcraft.io/api/ahnuP3quahti9vis8aiw/snaps/search?q=canonical
Fixes https://warthogs.atlassian.net/browse/WD-24113

chore: Move snap search endpoint to endpoints section of app

---

tests/endpoints/tests_invites.py
webapp/admin/views.py
webapp/endpoints/invites.py

Moves the update invite endpoint to the endpoints section of the app
- Go to https://snapcraft-io-5272.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Go to the invites table and reopen an invite
- It should change the status to "Pending"
Fixes https://warthogs.atlassian.net/browse/WD-24122

chore: Move update invite endpoint to endpoints section of app

---

tests/endpoints/tests_invites.py
webapp/admin/views.py
webapp/endpoints/invites.py

Moves the send invite endpoint to the endpoints section of the app
- Go to https://snapcraft-io-5274.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Add a member with a dummy email address (your.name+whatever@canonical.com)
- Send the invite when it asks you to
- You should receive an invite
- **Note**: There is a bug where sending the invite appears to add the user to the store, although they are not there when refreshing the page. [This is an existing bug](https://warthogs.atlassian.net/browse/WD-24554)
Fixes https://warthogs.atlassian.net/browse/WD-24121

chore: Move send invite endpoint to endpoints section of app

---

webapp/store/content/distros/arch.yaml
webapp/store/content/distros/centos.yaml
webapp/store/content/distros/debian.yaml
webapp/store/content/distros/elementary.yaml
webapp/store/content/distros/fedora.yaml
webapp/store/content/distros/kde-neon.yaml
webapp/store/content/distros/kubuntu.yaml
webapp/store/content/distros/manjaro.yaml
webapp/store/content/distros/opensuse.yaml
webapp/store/content/distros/pop.yaml
webapp/store/content/distros/raspbian.yaml
webapp/store/content/distros/rhel.yaml
webapp/store/content/distros/ubuntu.yaml
webapp/store/logic.py
webapp/store/snap_details_views.py

- added supported archs for every distro
- show 404 if the snap isnt released for the supported arch
- show the correct release date in the distro page
- go to https://snapcraft-io-5273.demos.haus/jami
- verify the latest date is "18 July 2025 - latest/stable
23 July 2025 - latest/edge"
- go to https://snapcraft-io-5273.demos.haus/install/jami/raspbian
- verify the latest date is "17 April 2021 - latest/edge"
- go to https://snapcraft-io-5273.demos.haus/install/jami/ubuntu
- verify the latest update date is "18 July 2025 - latest/stable
23 July 2025 - latest/edge"
(You can check the dates rom the[ releases section](https://snapcraft-io-5273.demos.haus/jami/releases))
Fixes #https://warthogs.atlassian.net/browse/WD-23619

fix: check supported archs when showing last updates

---

tests/endpoints/publisher/tests_builds.py
webapp/endpoints/publisher/builds.py
webapp/publisher/snaps/build_views.py
webapp/publisher/snaps/views.py

Moves the build endpoint to the endpoints section of the app
- Run locally (doesn't work on demos) - you need to [set up your GH tokens locally](https://github.com/canonical/snapcraft.io/blob/main/HACKING.md#snap-automated-builds)
- Go to /<snap_name>/builds
- Click on a build
- Check that it loads the build data
Fixes https://warthogs.atlassian.net/browse/WD-24589

chore: Move get build endpoint to endpoints section of app

---

tests/endpoints/publisher/tests_packages.py
webapp/endpoints/publisher/packages.py
webapp/publisher/snaps/views.py

Moves the snap package metadata endpoint to the endpoints section of the app
- Go to https://snapcraft-io-5286.demos.haus/api/packages/<snap_name>
- Check that it is the same as https://staging.snapcraft.io/api/packages/<snap_name>
Fixes https://warthogs.atlassian.net/browse/WD-24602

chore: Move snap metadata endpoint to endpoints section of app

---

webapp/endpoints/publisher/builds.py
webapp/publisher/snaps/build_views.py
webapp/publisher/snaps/views.py

Moves the validate repo endpoint to the endpoints section of the app. There are intentionally no changes to the logic to minimise the risk of potential issues.
- Run locally (doesn't work on demos) - you need to [set up your GH tokens locally](https://github.com/canonical/snapcraft.io/blob/main/HACKING.md#snap-automated-builds)
- Go to the builds page of a snap you own e.g. /<snap_name>/builds
- Make sure you can connect to the github repo
Fixes https://warthogs.atlassian.net/browse/WD-24590

chore: Move validate repo endpoint to endpoints section of app

---

tests/endpoints/publisher/tests_builds.py
webapp/endpoints/publisher/builds.py
webapp/publisher/snaps/build_views.py
webapp/publisher/snaps/views.py

Moves the trigger build endpoint to the endpoints section of the app. There are intentionally no changes to the logic to minimise the risk of potential issues.
- Run locally (doesn't work on demos) - you need to [set up your GH tokens locally](https://github.com/canonical/snapcraft.io/blob/main/HACKING.md#snap-automated-builds)
- Go to the builds page of a snap you own e.g. /<snap_name>/builds
- Trigger a build
Fixes https://warthogs.atlassian.net/browse/WD-24591

chore: Move trigger build endpoint to endpoints section of app

---

tests/endpoints/publisher/tests_register.py
webapp/endpoints/publisher/register.py
webapp/publisher/snaps/views.py

Moves the register name dispute endpoint to the endpoints section of the app. No logic is changed intentionally to avoid potential issues.
- Go to https://snapcraft-io-5297.demos.haus/register-name-dispute?snap-name=lukewh
- In the comment write "This is a test from the web team. Please do not action this."
- Submit the form
Fixes https://warthogs.atlassian.net/browse/WD-24106

chore: Move register name dispute endpoint to endpoints section of app

---

tests/endpoints/publisher/tests_builds.py
webapp/endpoints/publisher/builds.py
webapp/publisher/snaps/build_views.py
webapp/publisher/snaps/views.py

Moves the disconnect repo endpoint into the endpoints section of the app. There are deliberately no logic changes to prevent potential issues.
- Run locally (doesn't work on demos) - you need to [set up your GH tokens locally](https://github.com/canonical/snapcraft.io/blob/main/HACKING.md#snap-automated-builds)
- Go to the builds page of a snap you own e.g. /<snap_name>/builds
- Disconnect the repo
Fixes https://warthogs.atlassian.net/browse/WD-24595

chore: Move disconnect repo endpoint to endpoints section of app

---

tests/publisher/cve/test_cve_get_by_revision.py
webapp/publisher/cve/cve_helper.py

Fixes Internal Server Error when response is missing `channels_with_fix` key
- Go to https://snapcraft-io-5301.demos.haus/api/docker/3220/cves
- Check that there is data
Fixes https://warthogs.atlassian.net/browse/WD-25533

fix: Fix internal server error when missing CVE key

---

package.json
static/js/libs/declare.ts
static/js/public/about/index.ts
static/js/public/blog.ts
static/js/public/distro-install.ts
static/js/public/featured-snaps.ts
static/js/public/fsf.ts
static/js/public/homepage.ts
static/js/public/modal.ts
static/js/public/publisher-details.ts
static/js/public/store-details.ts
webpack.config.rules.js
yarn.lock

Replaced Webpack's *expose-loader* with explicit declarations for exposing functions in the global scope.
- added a `declareGlobal` function that merges a variable into the `globalThis` object at a path specified by a period-separated string
- replaced `export` declarations in bundle entry points with explicit calls to `declareGlobal`
- removed *expose-loader* rules from webpack.config.rules.js
- removed *expose-loader* dependency from package.json
If the "run-cypress" test action is green most things should be good, but some manual QA is always welcome. Try to visit the demo site and click around on the interactive stuff (cookie popup, header dropdown, first snap flow, /store page, /about/listing page, etc.)
One route that needs manual testing is /blog, automated tests for it have been …

Remove expose-loader

---

templates/index.html

Changed homepage.js bundle to the one build by Vite
- open https://snapcraft-io-5314.demos.haus/#language
- change language
- click the "Show more" button
- these features should work
Fixes [WD-24764](https://warthogs.atlassian.net/browse/WD-24764)
[WD-24764]: https://warthogs.atlassian.net/browse/WD-24764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: use Vite bundle for homepage.js

---

templates/_base-layout.html

Changed base.js bundle to the one built by Vite
- open https://snapcraft-io-5315.demos.haus/
- click the "Contact us" anchor in the footer
- the contact form should appear
- log in with your account
- go back to the home page
- your account name should have appeared in the top right
Fixes WD-24760

chore: use Vite bundle for base.js

---

templates/about/listing.html

Changed about-listing.js bundle to the one built by Vite
- visit https://snapcraft-io-5317.demos.haus/about/listing#icon
- change tabs to "Title", "Category", etc. by either
- clicking the anchors on the left
- clicking the "next"/"previous" buttons
- using the dropdown (mobile layout)
Fixes WD-24770

chore: use Vite bundle for about-listing.js

---

templates/first-snap/_layout_fsf.html

Changed fsf.js bundle to the one built by Vite
- visit https://snapcraft-io-5321.demos.haus/first-snap
- check that changing to another language works
- click the "show more" button
Fixes WD-24767

chore: use Vite bundle for fsf.js

---

templates/store/snap-distro-install.html

Changed distro-install.js bundle to the one built by Vite
- open a distro install page (e.g. https://snapcraft-io-5323.demos.haus/install/pinta/arch)
- check that the images carousel works
- click on one of the images and check that the fullscreen carousel works as well
Fixes WD-24768

chore: use Vite bundle for distro-install.js

---

templates/admin/admin.html

Changed brand-store.js bundle to the one built by Vite
- visit https://snapcraft-io-5328.demos.haus/admin/nah4ahShap8aefie6pha/snaps
- the page should render correctly
Fixes WD-24773

chore: use Vite bundle for brand-store.js

---

templates/store/publisher.html

Changed publisher.js bundle to the one built by Vite
- visit https://snapcraft-io-5329.demos.haus/snaps
- the page should render correctly
Fixes WD-24772

chore: use Vite bundle for publisher.js

---

webapp/app.py
webapp/config.py

Fix an issue where the `webapp.config` module's variables do not reflect those available in the Flask `app.config` object created by flask_base
call `load_plain_env_variables` explicitly in the `webapp.config` module
This can only be tested locally
- checkout this branch
- in the .env.local file, add an env variable prefixed by FLASK_
- a good candidate for this is FLASK_SENTRY_DSN as it is copied in a `<script>` tag on each page
- `dotrun` it
- visit http://localhost:8004
- in the inspector, look for a script that contains `Raven.config`
- the first argument of the function call should be the string that you set as FLASK_SENTRY_DSN
Fixes #

fix: load unprefixed env vars explicitly

---

cypress.config.ts

Fix an issue with Cypress tests failing due to timeout during page loads. Third party scripts would occasionally block the page from launching the "load" event, leading to Cypress hanging. The "blockHosts" Cypress config option automatically returns a 503 response on requests matching any of the hosts in the list, fixing the issue.
- blocked Google tag manager, Google analytics and assets.ubuntu.com hostnames
This PR must be QA'd locally
- check out this branch
- `dotrun` it
- wait for the server to be up
- run `docker run --network="host" -v .:/app -w /app cypress/base:22.18.0 bash "-c" "npx cypress install && yarn run te
st-e2e"`
Fixes #

fix Cypress test timeouts in GH action

---

konf/staging-api.snapcraft.io.yaml

The canonicalwebteam.store_api package uses the DASHBOARD_API_URL env var rather than SNAPSTORE_DASHBOARD_API_URL, which broke the auth flow on staging-api.snapcraft.io
This is just a quick dirty fix for this bug, but there's probably a larger issue we should track and discuss with regard to how we handle env vars
- visit https://staging-api.snapcraft.io/snaps
- you should get redirected
- log in (you need a staging account on https://login.staging.ubuntu.com)
- you should land on the /snaps page
Fixes #

fix: add DASHBOARD_API_URL env var for auth on staging-api env

---

package.json
static/js/public/first-snap-flow.ts
yarn.lock

- Fixed transitive dependency resolution for `minimatch` (it was fixed to 3.0.5 for all packages which broke some transitive dependencies that needed v5 or v9+)
- Removed unused dependencies from package.json:
- `@tarekraafat/autocomplete.js`
- `clipboard` (bundle would get copied to `static/js/modules`, but is never linked in HTML so it's unused)
- `fast-average-color`
- `markdown-it`
- `polylabel`
- `vite-plugin-css-injected-by-js` (leftover from Vite migration phase 1)
- `watch-cli` (leftover from old watch scripts)
- Remove unused `clipboard.js` code in "first snap flow"
- Remove script that copies `d3.min.js` to `static/js/modules` (it's never linked in HTML)
If tests pass and the demo site works it means the JS build was ok
Fixes #

chore: cleanup package.json

---

static/sass/_snapcraft_p-docs.scss

Fixes issue where the footer isn't fixed to the bottom of the screen
- Run locally (`dotrun` or `dotrun -p 5004:5004` on MacOS)
- Go to http://localhost:8004/docs/network-bind-interface
- Check that the footer is fixed to the bottom of the screen
Fixes https://warthogs.atlassian.net/browse/WD-27344
Fixes https://github.com/canonical/snapcraft.io/issues/5378

fix: Fix footer position on docs page

---

static/js/publisher/pages/Builds/RepoSelector.tsx
webapp/endpoints/publisher/builds.py

Fixes the "get started with a template" link when connecting a repo without a `snapcraft.yaml` file
- Must run locally (will need [tokens](https://github.com/canonical/snapcraft.io/blob/main/HACKING.md#snap-automated-builds))
- Go to http://localhost:8004/<SNAP_NAME>/builds (must be a snap without a `snapcraft.yaml` file)
- Connect the repo
- Click the "get started with a template" link
- Check that it opens a page on GitHub where you can create a new `snapcraft.yaml` file
Fixes https://warthogs.atlassian.net/browse/WD-27231

fix: Fix template link on builds page

---

templates/_base-layout.html
templates/_docs_layout.html
templates/_header_docs_macros.html
templates/_header_macros.html

Move the `vite_import` of the global-nav to the header macro. This way we are sure that everywhere the header is used, the necessary global-nav JS lib will be there.
Can't be checked on Demos because of an error with Discourse unrelated to this PR:
```
2025-09-26 12:22:31.946Z ERROR flask.app "Exception on /docs [GET]" service=snapcraft.io pid=11 request_id=db090d0c73e42876f66f235e482798cb
Traceback (most recent call last):
File "/root/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/root/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/root/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = …
```

WD-27333 - Fix bug in docs global navigation

---

HACKING.md
konf/staging-api.snapcraft.io.yaml
requirements.txt

Related to [this PR](https://github.com/canonical/canonicalwebteam.store-api/pull/169), effectively remove the dirty fix added [here](https://github.com/canonical/snapcraft.io/pull/5345)
- updated store-api package
- changed env var name in docs
- removed unused env var from staging-api site config
Fixes #

fix: use correct dashboard env var name

---

static/js/publisher/pages/Builds/RepoSelector.tsx

Rename the `validateRepoInternal` function back to `validateRepoInternal` for readability. Based on unaddressed PR comment from a recently merged PR https://github.com/canonical/snapcraft.io/pull/5347
1. Execute the `dotrun test` command locally to make sure all the tests pass.
Fixes #3319 and pending comment https://github.com/canonical/snapcraft.io/pull/5347#discussion_r2386915660
Not Applicable

refactor(code): update validateRepo function name
