canonical/snapcraft.io

- app.py
- templates/snap-details.html
QA
--
``` bash
./run
```
Go to <http://0.0.0.0:8022/dwarf-fortress/>, check it shows multiple paragraphs
> Split descriptions into paragraphs

- static/sass/_patterns_inline-list--compact.scss
- static/sass/_patterns_social-icons.scss
- static/sass/_patterns_social.scss
- static/sass/styles.scss
- templates/_layout.html
Fixes #33 
Added social icons to footer.
Prepared styles for it as a vanilla pattern that could be proposed.
- ./run
- Go to any snap details page (http://localhost:8022/canonical-livepatch/)
- Footer should contain social icons
> Added social icons to the footer

- templates/index.html
Copied from old repo at:
https://github.com/canonical-websites/snapcraft.io-static-pages/pull/390
> Link to the new directory pages for featured snaps.

- templates/index.html
* Fixes https://github.com/canonical-websites/snapcraft.io-static-pages/issues/387
* Part of https://github.com/canonical-websites/snapcraft.io-static-pages/issues/380
> Add Mint and Manjaro logos to index

- app.py
> Redirect /create to snap building docs

- templates/index.html
For a demo...
QA
--
Check for the comment at the end of the homepage.
``` bash
$ ./run serve --detach
$ curl -s 127.0.0.1:8022 | tail -n 1
$ ./run stop
```
> Add a comment

- static/sass/styles.scss
- templates/_layout.html
- templates/index.html
Fixes #92
QA
--
``` bash
./run
```
Go to <http://localhost:8022/lxd/> and <http://localhost:8022/> and look at the awesome footer text.
> Add powered by CDK

- package.json
- templates/_layout.html
- yarn.lock
Updated Vanilla to 1.6.0.
Small fixes in layout.
> Update vanilla to 1.6.0

- templates/_layout.html
- templates/index.html
Fixes #105
QA
--
Not sure how to QA... You can do `./run` and go to http://127.0.0.1:8004/lxd, view source, and look for the GTM code. Check it look right.
> Add Google Tag Manager snippet

- app.py
- templates/search.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/137
* ./run serve
* Go to http://localhost:8004/search
* A simple page with only a input should be displayed
> Fix search with no query

- templates/index.html
> Fix URL for reporting issues

- app.py
- static/sass/_search-form.scss
- static/sass/_snapcraft_banner.scss
- static/sass/_snapcraft_custom-typography.scss
- static/sass/styles.scss
- templates/discover.html
- templates/search.html
Fixes #148 
Adds basic MVP version of /discover page
http://snapcraft.io-pr-155.run.demo.haus/discover
> Adds basic discover page with search box

- app.py
* `./run`
* [http://0.0.0.0:8004/search](http://0.0.0.0:8004/search)
* Search for snaps, and make sure you have results
> Search snaps in strict and classic confinements

- static/sass/index.scss
It seems that in process of merging new home page old home page CSS file was lost.
This PR brings it back.
./run
go to http://localhost:8004 - old home page should be styled
> Brings old homepage CSS back

- templates/index.html
> Fix the "report a bug on this site" link again

- app.py
> Make newlines display properly in snap details

- app.py
- templates/promoted.html
- Add promoted snaps endpoint
- Checkout to this branch
- `./run`
- Go to http://0.0.0.0:8004/snaps/
- See promoted snaps ;)
I don't know how to center a title with vanilla...
> Add promoted snaps endpoint

- Dockerfile
- `docker build --build-arg COMMIT_ID=test --tag crazyimage .`
- No errors
> Add libsodium-dev dependency to Dockerfile

- app.py
- templates/account.html
Add user account HTML page 
- `./run`
- login
- You should see a page with your details and your snaps
> Add user account page

- app.py
Update metadata for a snap
- `./run`
- http://0.0.0.0:8004/account/snaps/SNAP YOU CAN MODIFY/market/
- Update data
- Apply
- Make sure that the data as been modified on the page
> Add POST endpoint to update snap metadata

- app.py
- templates/account.html
Fixes #230
Small updates to account page layout.
We don't have much more to show there ATM.
> Small updates to account page layout

- app.py
- templates/account.html
- templates/publisher/market.html
- templates/publisher/measure.html
- Visit http://0.0.0.0:8004/account or http://snapcraft.io-pr-236.run.demo.haus/account
- Click on a snap - you should go to the market page
- Click on the measure tab - you should go to the measure page
- Click on the market tab - you should return to the market page
- Click on My snaps - you should return to the account page
Celebrate! 🍾
> Fixup templates

- app.py
I don't have any errors snaps...
- go to market page for snap speed-test
- try to modify it
- should work
> Handle errors when POST metadata

- app.py
Use decorators to check if a user is authenticated or not.
- `./run`
- http://0.0.0.0:8004/logout
- http://0.0.0.0:8004/account/snaps/SNAP/[release|market]
> Use custom decorator to check if user is logged

- app.py
Step by step refactor: Refactor redundant code
- `./run`
- http://0.0.0.0:8004/account/snaps/speed-test/market/
- http://0.0.0.0:8004/speed-test/
- http://0.0.0.0:8004/search?q=web&limit=2&offset=2
- OK
> Refactor redundant API calls

- app.py
Refactor metrics functions
- `./run`
- http://0.0.0.0:8004/account/snaps/speed-test/measure/
- http://0.0.0.0:8004/speed-test/
- The map is still displayed
> Refactor metrics

- app.py
- static/js/public/snap-details/map.js
- static/js/publisher/metrics/graphs/activeDevices.js
- static/sass/_map.scss
- static/sass/_snapcraft_graph-tooltip.scss
- static/sass/_snapcraft_metrics.scss
- templates/publisher/measure.html
- Made map full width
- Removed tooltip text from graph (as it's inaccurate)
- Improved label position on active-devices
- `./run`
- Visit http://0.0.0.0:8004/account
- Ensure all works as expected
> Improved measure page

- templates/account.html
- ./run
- Go to your account page
- List of your snaps should be sorted
> Sorts list snaps for account page

- app.py
- templates/publisher/market.html
Post screenshots and icons for market page
/!\ To avoid conflicts with dashboard for now I need reupload every screenshots/icons.... This will need to be optimized
- `./run`
- http://0.0.0.0:8004/account/snaps/SNAP/market/
- Update the icon
>  Post screenshots and icons for market page

- app.py
- modules/public/api.py
- modules/public/views.py
- templates/publisher/market.html
Refactor all public views on its own module
- `./run`
- Test all pubic and publishers pages and see if they still work :)
> Refactor all public views on its own module

- app.py
- modules/public/api.py
- modules/publisher/api.py
- modules/publisher/views.py
Refactor all publisher views on its own module
- `./run`
- Test all public and publishers pages and see if they still work :)
> Refactor all publisher views on its own module

- app.py
- modules/authentication.py
- modules/cache.py
- modules/public/api.py
- modules/public/views.py
- modules/publisher/api.py
- modules/publisher/views.py
- templates/_layout.html
- templates/index.html
- templates/snap-details.html
* Reorganise app.py
* Refactor account endpoint
- `./run`
- Test all public and publishers pages and see if they still work :)
- http://0.0.0.0:8004/account still accessible
> Refactor app.py and account endpoint

- modules/publisher/api.py
Fix variable build for screenshot url
- `./run`
- Upload image
> Fix variable build for screenshot url

- modules/publisher/views.py
- templates/account.html
- Display message when user has 0 snap account page. Fixes #294 
- `./run`
> Handle user with 0 snap account page

- templates/account.html
- Removed account column
- Added snap icon next to name
- Added 'Private' next to name of private snaps
- `./run`
- Visit http://0.0.0.0:8004/account or [demo url]/account
- Make sure the page still works
> Small changes to account page

- app.py
Add status endpoint for k8s
- `./run`
- http://0.0.0.0:8004/status
> Add status endpoint

- app.py
- modules/publisher/api.py
- modules/publisher/views.py
- static/sass/_snapcraft_custom-typography.scss
- templates/developer_programme_agreement.html
Add terms and conditions page
- With a new user
- `./run`
- http://0.0.0.0:8004/account/agreement
- Accept terms and conditions
- Should be redirected to /account page
> Add terms and conditions page

- modules/cache.py
Remove caching system
- `rm cache.sqlite`
- `./run`
- test @cprov bug
> Remove caching system

- README.md
- app.py
- requirements.txt
The production/staging story involves deploying Sentry in k8s (sentry + redis + postgres), but then it's just the `SENTRY_DSN` we use in those environments.
> Basic sentry integration.

- modules/public/views.py
Handle when API replies an error on search
- `./run`
- http://0.0.0.0:8004/search?q=dvd%3A%3Arip
> Fix no results problem on search

- app.py
Redirect /snaps to /store
- `./run`
- http://0.0.0.0:8004/snaps
- should redirect to /store
> Redirect /snaps to /store

- .babelrc
- package.json
- rollup.config.js
- yarn.lock
To fix the continuing alerts about snapcraft not being defined.
@bartaz can you try and reproduce the error.
> Add babel to rollup

- .babelrc
- .eslintrc.js
- package.json
- static/js/publisher/market/market.js
- static/js/publisher/market/market.test.js
- yarn.lock
Just a POC for unit testing our JavaScript in snapcraft.io.
Uses [jest](https://facebook.github.io/jest/) that is React-ready, "no-configuration" testing framework.
This should help us improve testability of our JS modules and make sure front-end side of things is also well tested (especially that in seems in future we are going to have more and more client side functionality).
Builds on Travis: https://travis-ci.org/bartaz/snapcraft-flask/builds (fails when tests fail)
- checkout branch
- ./run test
- JavaScript tests should run and pass
> Jest JavaScript testing

- app.py
- modules/cache.py
- modules/exceptions.py
- modules/public/api.py
- modules/public/views.py
- templates/404.html
- templates/index.html
- templates/snap-details.html
- templates/store.html
-  Handle errors for homepage and store page for featured snaps
-  Handle errors for snap store
-  Handle errors for metrics page
- Handle errors for search without illegal characters
- Handle timeouts
- `./run`
- http://0.0.0.0:8004/ 
- http://0.0.0.0:8004/toto
- http://0.0.0.0:8004/qsdfsqdf
- http://0.0.0.0:8004/store
- http://0.0.0.0:8004/search?q=%3A%3A 
All should work as usual
> Handle errors public api calls

- modules/public/logic.py
- modules/public/views.py
- Remove all logic from view functions so that the view calls the API, the logic plays with the data and the view returns the template
- `./run`
- http://0.0.0.0:8004/toto
- The descritpion should be displayed properly, the map too
- http://0.0.0.0:8004/search?q=test&limit=10&offset=40
- Play with next, prev, first, last buttons
- Make sure nothing is broken
> Remove logic from views

- static/sass/_patterns_inline-list--compact.scss
- static/sass/_patterns_maas_modal.scss
- static/sass/_patterns_media-object--large.scss
- static/sass/_snapcraft_metrics.scss
- static/sass/_snapcraft_snap-list.scss
Fixes [my own sanity](http://lh5.googleusercontent.com/-T5gHuO5DlUw/TXWCD_ao89I/AAAAAAAAAjo/jIXW7jmCjbk/Tom-Cruise-laughing.jpg).
- Reordered scss properties to be alphabetical
> Reordered SASS to remove linting warnings

- templates/index.html
Fixes https://github.com/canonicalltd/snapcraft-design/issues/300
- Removed section from homepage
- Pull branch
- `./run`
- Visit http://0.0.0.0:8004 or http://snapcraft.io-pr-426.run.demo.haus/
- Scroll down and ensure the offending section has been removed.
> Removed user facing content from homepage

- modules/publisher/api.py
- modules/publisher/views.py
Remove flask.session from publisher API 
- `./run`
- Go to http://0.0.0.0:8004/, browse around a bit in /account
> Remove flask session in api

- modules/publisher/views.py
- package.json
- requirements.txt
- tests_basic.py
- tests_public.py
- tests_publisher.py
- Now the tests are run in the `package.json`
- Keep basic tests for the index page
- Add entire integration test suite for the /account page
- `./run test`
The tests should pass!
> Tests account detail page

- app.py
- templates/publisher/market.html
- templates/publisher/measure.html
- templates/snap-details.html
Docs reference: 
- https://docs.sentry.io/clients/python/integrations/flask/
- https://docs.sentry.io/clients/javascript/
> Add release and environment to sentry calls

- modules/cache.py
All requests using "cache.get" will trigger new prometheus metrics:
- "feed_timeouts" counter will be incremented if we get a
requests.exceptions.Timeout
- "feed_connection_failures" counter will be incremented if we get a
requests.exceptions.ConnectionError
- "feed_latency_seconds" histogram will log how long the request took on
a successful response - in buckets (<0.25, <0.5, <0.75, <1, <2, <3)
Fixes #339
QA
--
``` bash
./run --env TALISKER_NETWORKS=172.16.0.0/12
```
Now browse around the site a bit at http://127.0.0.1:8004.
Then go to http://127.0.0.1:8004/_status/metrics, and see the "feed_latency_seconds" histrogram settings.
If you're feeling ambitious, try changing the `SNAPCRAFT_IO_API` in `modules/public/api.py` to localhost, so feed requests will fail, and then browse around the …
> Add prometheus metrics for feed requests

- modules/publisher/views.py
This is instead of https://github.com/canonical-websites/snapcraft.io/pull/485, as discussed.
QA
--
Follow QA steps from https://github.com/canonical-websites/snapcraft.io/pull/485
> Show empty website field if no website

- templates/account.html
- tests_publisher.py
Checking the `latest_revisions` list directly.
> Stop using snaps `uploaded` flag, it's deprecated.

- decorators.py
- Add public to Cache-Control header
- `./run`
- http://127.0.0.1:8004/
- Make sure Cache control header has `public`
> Add public to Cache Control header

- decorators.py
https://serverfault.com/questions/499993/squid-proxy-not-caching-anything
> Increase max-age to 61 seconds

- templates/index.html
Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/324
- Changed 3rd quote on the homepage
- `./run`
- Visit the homepage
**or**
- Visit [the demo](http://snapcraft.io-pr-530.run.demo.haus/)
- Ensure the quote is changed
> Updated homepage quote

- static/js/publisher/market/market.js
Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/378
- ./run or http://snapcraft.io-pr-535.run.demo.haus/
- click on a link to measure page or any other link to different page in navigation or footer
- link should work as expected without any warning (as there are no changes in the form)
- go back to market page of any snap
- do some changes in the form (edit some value, change image)
- click on any link (measure page, navigation, etc)
- browser should show warning that you have unsaved changes (text of the dialog and buttons depends on browser internal implementation)
- choosing to stay on the page or leaving the page from the dialog should work as expected
- go back to market page of any snap
- do some changes to the form
- click on 'Revert' …
> Warn users when leaving market page with unsaved changes

- modules/publisher/views.py
- tests/test_get_measures.py
- Add integration tests measure page
- `./run test`
> Add integretion tests measure endpoint

- tests/endpoint_testing.py
- tests/test_get_metrics.py
- tests/tests_account_details.py
- tests/tests_account_snaps.py
- tests/tests_agreement.py
- tests/tests_listing.py
- tests/tests_post_listing.py
- tests/tests_username.py
Small improvements testing framenwork
-`./run test`
> Improve testing framework

- modules/publisher/views.py
- templates/publisher/account-snaps.html
- Ensure the info at the top of the listings page is accurate
- Ensure a single snap doesn't break my snaps
> Fixes from pre-live qa

- templates/publisher/metrics.html
> Add an option for "Past 6 months" on metrics

- templates/publisher/listing.html
> Fix typo in help text

- modules/publisher/views.py
- Refactor errors catching from API
Fixes #549 
- `./run`
- http://127.0.0.1:8004/account/details
> Refactor errors catching account details

- modules/public/views.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/313
> Use weekly territories metric

- modules/publisher/views.py
- Use function `_handle_errors` to catch exceptions
- `./run`
- Post a new username
- Post a new agreement
> Use function to catch exceptions API calls

- modules/publisher/logic.py
- modules/publisher/views.py
Move logic from view to logic file for the POST listing endpoint
Fixes #553 
- `./run`
- http://127.0.0.1:8004/account/snaps/toto/listing
- Play with modifications
> Remove logic POST listing

- modules/publisher/logic.py
- templates/publisher/metrics.html
We have access to the weekly by channels metrics, so we should show it
> Add channel graph to metrics

- modules/exceptions.py
- modules/publisher/api.py
- modules/publisher/views.py
Move Agreement and username to api layer
Add exceptions MissingUsername, AgreementNotSigned
Fixes #609 
- `./run`
- Create new account 
- Login
- Should get agreement page
> Add exceptions for username and agreement

- .env
- requirements.txt
- Add `DEVEL=True` to get nice colors in the terminal
- Update Flask to its last version (1.0.2)
- Update Talisker to its last version
Fixes #654 
- `./run`
- Make sure everything works
- Look at the awesome colors in the terminar
> Updatate Flask 1.0.2

- templates/snap-details.html
Fixes https://github.com/canonicalltd/snapcraft-design/issues/436
> Updated styling for snap details page

- static/sass/_patterns_testimonial.scss
- templates/index.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/275
Waiting on an updated logo for JetBrains before being ready to merge (see [#275](https://github.com/canonical-websites/snapcraft.io/issues/275))
> Updated testimonial design on homepage

- templates/snap-details.html
> Small tidy up for unnecessary hrs on snap pages

- templates/snap-details.html
- templates/store.html
Fixes https://github.com/CanonicalLtd/snap-squad/issues/524
- `./run`
- Go to the store page: http://0.0.0.0:8004/store and a snap page: http://0.0.0.0:8004/vlc
- Ensure the meta tags match those in https://docs.google.com/spreadsheets/d/1Td2IxYgXpPwfQivTcKDhrx3197QQ6ZIeUq4mzXrkZqQ/edit#gid=0 that are marked as 'Awaiting release'
> Updated SEO titles and descriptions

- templates/publisher/register-name.html
Fixes #678 
- Improve UX for request name
- `./run`
- http://127.0.0.1:5000/account/register-name
- Register already existing snap
- Like new page :)
> Improve request name view

- templates/blog/index.html
- tests/blog/tests_index.py
- webapp/app.py
- webapp/blog/blog.py
First preparation for blog.
Create blueprint for blog
Add first homepage endpoint
- `./run`
- http://127.0.0.1:5000/blog
- Should have access to a page `Blog is coming`
> Create blog blueprint

- webapp/app.py
- webapp/public/views.py
Make store as blueprint
- `./run`
- Hve fun in the website
> Add store blueprint

- static/js/public/snap-details/channelMap.js
Fixes https://github.com/canonical-websites/snapcraft.io/issues/645
- Implemented `localeCompare` rather than a standard comparison
- `./run`
- Visit http://0.0.0.0:8004/node, http://0.0.0.0:8004/webstorm and http://0.0.0.0:8004/etcd (for a mix of string and number tracks)
- Open the channel map
- Look at the order in the dropdown
I can't add a screenshot because my laptop won't let me open a select input and then take a screenshot... sozzles.
> Order tracks on channel map

- templates/index.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/698
> Name update

- static/sass/_patterns_card.scss
- static/sass/_patterns_testimonial.scss
- static/sass/_snapcraft_distro-chart.scss
- static/sass/_snapcraft_p-beta-notification.scss
- static/sass/_snapcraft_snap-list.scss
- static/sass/_utilities_crop.scss
- static/sass/styles.scss
- templates/blog/index.html
- tests/blog/tests_index.py
- webapp/blog/api.py
- webapp/blog/logic.py
- webapp/blog/views.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/701
Driveby: Fixed sass linting errors
- `./run`
- See a list of blog posts
- Page around using the bottom pagination
- Make sure nothing breaks
> Blog articles list

- templates/_header.html
- webapp/handlers.py
- webapp/template_utils.py
- Fixed small bug in navigation
- `./run`
- Visit public and publisher pages
- Check the navigation is correctly highlighted
> Prevent 'store' being highlighted in nav when on publisher pages

- static/sass/_patterns_blog-post.scss
- static/sass/styles.scss
- templates/_layout.html
- templates/blog/article.html
- templates/blog/index.html
- templates/blog/post.html
- tests/blog/tests_index.py
- webapp/blog/api.py
- webapp/blog/logic.py
- webapp/blog/views.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/702
- Simple blog article page
- Author to blog list items
- SEO metadata
- Related posts
- Tests
- `./run`
- Visit a few articles and see that the formatting is OK
- Made naming consistent in the code - `article` & `articles`
> Blog article

- .circleci/config.yml
Add a quick example config to trigger a flake8 test.
Circle CI test should show and pass
> Add quick CircleCI config

- .env
- webapp/app.py
- webapp/configs/snapcraft.py
Add feature flag for blog
- add in `.env`
`BLOG_ENABLED=false`
- `./run`
- http://127.0.0.1:8004/blog
- Should have a 404
> Add feature flag for blog endpoints

- static/sass/_patterns_logo-links.scss
- static/sass/_patterns_logo-list.scss
- static/sass/styles.scss
- templates/index.html
Fixes https://github.com/CanonicalLtd/snap-squad/issues/523
- `./run`
- Make sure the homepage looks ok!
> Homepage updates

- static/sass/_snapcraft_snap-list.scss
- templates/publisher/account-snaps.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/760
- Updated markup to remove extra sections
- Updated a style for custom element to add bottom margin
- `./run`
- Take a look at http://0.0.0.0:8004/account/snaps and all it's permutations.
- I've provided screenshots below to help ease the pain
> My snaps tidy-up

- webapp/api/blog.py
Use the `snapcraft.io` tag, rather then `Snaps`
> Update blog tag id

- static/sass/_patterns_nested-inputs.scss
- static/sass/_snapcraft_market.scss
- static/sass/_snapcraft_p-tabs.scss
- static/sass/styles.scss
- templates/publisher/_header.html
- templates/publisher/listing.html
See https://github.com/canonical-websites/snapcraft.io/pull/793
> Snap listing redo

- package.json
- static/js/public/snap-details/screenshots.js
- static/sass/_base_image-grid.scss
- static/sass/_patterns_featured-snaps.scss
- static/sass/_patterns_logo-list.scss
- static/sass/_patterns_nested-inputs.scss
- static/sass/_patterns_table-key-value.scss
- static/sass/_search-form.scss
- static/sass/_snapcraft_details_heading.scss
- static/sass/_snapcraft_footer.scss
- static/sass/_snapcraft_market.scss
- static/sass/_snapcraft_market_screenshots.scss
- static/sass/_snapcraft_p-navigation.scss
- static/sass/_snapcraft_p-tabs.scss
- static/sass/_snapcraft_snap-list.scss
- static/sass/styles.scss
- templates/_header.html
- templates/index.html
- templates/publisher/_beta-notification.html
- templates/publisher/_header.html
- templates/publisher/account-snaps.html
- templates/publisher/listing.html
- templates/publisher/metrics.html
- templates/search.html
- templates/snap-details.html
- templates/snap-details/_channel_map.html
- templates/store.html
- yarn.lock
Updates Vanilla to 1.7.1
We need to QA it and fix any layout issues found.
> Updates snapcraft.io Vanilla to 1.7.1

- .circleci/config.yml
- tests/blog/tests_index.py
- tests/endpoint_testing.py
- tests/tests_public.py
- tests/tests_publisher.py
Add test job to circleCI
- Check that the jobs works :P
> Add tests job to circle ci configuration

- webapp/api/public.py
- webapp/public/views.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/803
- Added the fields to the API calls
- Passed the fields through to the templates
- `./run`
- Visit http://0.0.0.0:8004/search?q=gnome
- Check the verified icon appears next to 'Canonical'
- Click on one of the snaps
- Check the verified icon appears next to 'Canonical'
> Final pieces for v1 of verified publishers

- static/sass/_snapcraft_graph-tooltip.scss
> Don't text-transform the version number in the metrics graph

- README.md
Fixes https://github.com/CanonicalLtd/snap-squad/issues/577
Update README to explain how to deploy a brandstore
- Read the readme and try to deploy a store
- If you want an example of query's that work the ENV var `STORE_QUERY` can be setted with `limeNET`
> Update readme to create brand stores

- templates/developer_programme_agreement.html
Fixes https://github.com/canonicalltd/snap-squad/issues/570
> Added privacy notice link to developer agreement

- templates/index.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/826
> Message on homepage

- static/sass/_snapcraft_p-navigation.scss
- templates/_header.html
- templates/blog/index.html
- webapp/template_utils.py
In preparation for the blog going live, add it to the nav.
Also fixed:
- Selected colour
- Slug logic
- Blog heading spacing
> Add blog to nav, plus extra fixes

- webapp/store/views.py
- Brand store will have a different homepage
- Add custom route to define what function should the homepage be
- `./run`
- /store should work
- `WEPAPP=lime` in `.env`
- `./run`
- / should be the home page
> Add custom route rule for store homepage

- webapp/api/store.py
- add funciton to get all snaps
- `./run`
- try function on an endpoint
> Add get all snaps api endpoint

- webapp/api/store.py
Update header to v2
- `./run`
- On lime make sure it works
- http://127.0.0.1:8004/pocket-epc
> Update headers for v2 of API

- tests/publisher/tests_publisher.py
- webapp/app.py
- webapp/configs/snapcraft.py
Remove `BLOG_ENABLED` feature flag since blog is on production now
- `./run`
- 0.0.0.0:8004/blog
- Should have the blog
> Remove blog enable feature flag

- webapp/publisher/snaps/logic.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/884 and https://github.com/canonical-websites/snapcraft.io/issues/885
> Fix icon error messages

- static/sass/_snapcraft_p-navigation.scss
- templates/_header.html
Fixes #859 
* Replaced `Sign in / Register` with `Developer account`
* Added user icon next to `Developer account`
1. Pull the branch
2. `./run`
3. Visit `https://0.0.0.0:8004` logged out (log out if need be)
4. Notice changes on the header at the top right
5. Log in and log out
6. Changes should still be there
> Add more explicit account navigation icon and message on the header

- templates/store/snap-details/_channel_map.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/917
... Potentially
> Remove extra closing <div>

- templates/_header-brandstore.html
- templates/_layout-brandstore.html
- webapp/configs/limenet.py
- Change `.env` store to `limenet`
- `./run`
- Go to the homepage and see limenet store
> limenet update

- templates/_header.html
Partially fixes https://github.com/canonical-websites/snapcraft.io/issues/592
build.snapcraft.io will be sorted by https://github.com/CanonicalLtd/snap-squad/issues/640
- `./run`
- Click around (within this codebase)
- The navigation should be full width
> Make navigation full width

- static/js/public/snap-details/channelMap.js
- templates/store/snap-details/_channel_map.html
Attempt to fix `innerHTML is not defined` issue.
> Fallback for querySelectoring channel map templates

- tests/publisher/snaps/tests_post_binary_metadata.py
- webapp/api/dashboard.py
The missing piece for sending images and making them not conflict.
> conflict_on_update for binary-metadata

- webapp/api/blog.py
- webapp/blog/views.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/962
- Filter by the right tag
- Replace 'Ubuntu Blog' with 'Snapcraft Blog' throughout
- `./run`
- Visit http://0.0.0.0:8004/blog/feed
- See the wonders of an RSS feed
> get the right blog posts and set the right titles

- static/sass/_search-form.scss
- templates/store/search.html
1. [Search for something that will lead to 0 results](http://snapcraft.io-pr-926.run.demo.haus/search?category=&q=asdfg)
1. See the help text
1. Do not see the categories
> 0 search results

- .gitignore
- package.json
- requirements.txt
- tests/blog/tests_index.py
- webapp/app.py
- webapp/blog/views.py
- webapp/extensions.py
Add cache layer to /blog and /article endpoint
This is a PR that will need discussion
I putted a timeout of 50sec
- `./run`
- http://0.0.0.0:8004/blog
> Add caching layer to blog

- webapp/configs/limenet.py
Update copyright footer
- `./run`
- Make sure copyright is ok
> Limenet: Update copyright footer

- static/js/publisher/metrics/graphs/activeDevices.js
> Keep OS versions to avoid os aggregation on metrics

- templates/_header.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/996
- `./run`
- Visit various pages, make sure the header is fixed width
> Fixed width nav

- static/sass/_snapcraft_p-navigation.scss
- templates/_header.html
Fixes #591 
1. Pull the branch or launch the demo
2. Check the navigation item is highlighted
**Note:** This PR should be merged alongside [this PR](https://github.com/canonical-docs/snappy-docs/pull/436/) from `snappy-docs` to make sure the changes are synced.
> Highlight item selected on navigation

- templates/store/categories/iot.html
* Fingbox case study link was linking nowhere.
> Broken link to Fingbox CS on the IoT page

- static/js/public/public.js
- static/js/public/snap-details/blog-posts.js
- static/sass/_patterns_blog-list.scss
- static/sass/_patterns_blog-post.scss
- static/sass/styles.scss
- templates/blog/article.html
- webapp/api/blog.py
- webapp/blog/views.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/911
- `./run`
- Visit http://0.0.0.0:8004/blog/your-first-robot-a-beginners-guide-to-ros-and-ubuntu-core-1-5
- See a list of the other blogs in the series on the right-hand side
- Visit http://0.0.0.0:8004/vscode and ensure the related blog posts appear there still
> Blog series

- static/sass/_snapcraft_p-notifications.scss
- static/sass/styles.scss
- templates/index.html
- webapp/snapcraft/views.py
Fixes https://github.com/canonicalltd/snap-squad/issues/706
- `./run`
- Visit http://0.0.0.0:8004?nps=true
- See the banner at the top of the homepage
> Add nps notification

- templates/partials/search-bar.html
> millions of people rather than millions of users

- templates/index.html
1. Pull the branch or launch the demo site
2. Visit the homepage
3. Check the image on the analytics section is showing real values (20k ~ 10k)
> Updated analytics image

- templates/publisher/listing.html
- templates/store/_category-partial.html
- tests/publisher/snaps/tests_listing.py
- webapp/publisher/snaps/views.py
Add username diplayed in the listing page
> Add username listing page

- static/sass/_global-nav.scss
- static/sass/_snapcraft_p-navigation.scss
- static/sass/styles.scss
1. Pull the branch or open the demo link
2. Open `https://0.0.0.0:8004/` and `https://ubuntu.com` on 2 different tabs
3. Cycle between the 2 and notice no style difference
> Fixed styling for global nav

- webapp/template_utils.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1126
Caused by https://github.com/canonical-websites/snapcraft.io/pull/1101
- `./run`
- Visit all the pages and make sure the correct thing is highlighted in the nav
> Ensure correct nav is highlighted for the new endpoints

- webapp/snapcraft/views.py
Add robots.txt endpoint
/robots.txt
> Add robots.txt endpoint

- static/sass/_snapcraft_market.scss
- templates/publisher/settings.html
- templates/store/store.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1131
- Visit http://0.0.0.0:8004/<snap_name>/settings
- See extra information in the sticky bar
> Show extra metadata

- static/sass/_global-nav.scss
- static/sass/_snapcraft_footer.scss
- static/sass/_snapcraft_p-navigation.scss
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1157
Supercedes https://github.com/canonical-websites/snapcraft.io/pull/1149
- Pull branch
- `./run`
- Ensure the global-nav and footer looks ok
> Header and footer update

- templates/partials/blog-card.html
- templates/store/snap-details.html
- Visit http://0.0.0.0:8004/skype
- Compare page size to https://snapcraft.io/skype
- Ensure the images don't look worse
> Optimize images from cloudinary

- package.json
- `./run exec yarn lint-scss`
- SCSS should be linted
> Ensure scss is linted recursively

- webapp/app.py
- webapp/first_snap/views.py
Fixes #1189 
Add basic blueprint for first snap flow
- `./run`
- http://127.0.0.1:8004/first-snap/
- http://127.0.0.1:8004/first-snap/python
- http://127.0.0.1:8004/first-snap/python/mac/test
- http://127.0.0.1:8004/first-snap/python/mac/package
- http://127.0.0.1:8004/first-snap/python/mac/push
- http://127.0.0.1:8004/first-snap/python/mac/build
All pages should work!
kis kiss :heart:
> Add first snap flow blueprint

- tests/first_snap/tests.py
> Add first snap flow tests

- tests/blog/tests_index.py
- webapp/api/blog.py
Increase cache for every api call since it's not changing a lot
- `./run clean`
- `./run`
- Make sure blog works
> Increase cache for get_articles

- README.md
Just a small improvement on the readme for the description of the project.
Make sure there is no typo
> Change project description in readme

- requirements.txt
fix vulnerability on requests module found by github
- `./run`
- make sure it works as usual
> Upgrade requests to v2.20.0

- webapp/app.py
- webapp/decorators.py
- webapp/login/views.py
Move csrf since we changed the pattern of managing extensions on flask
- `./run`
- Try to login
- It should work as usual
> Move crsf exemption

- static/js/base/base.js
- static/js/base/ga.js
- static/js/public/snap-details/channelMap.js
- templates/_layout-brandstore.html
- templates/_layout.html
Fixes https://github.com/canonicalltd/snap-squad/issues/759
Added generic tracking as per @caldav spec.
- Add `console.log(category, from, to, label);` to `static/js/base/ga.js:24`
- `./run`
- Open http://0.0.0.0:8004 and open the console, enable "Persistent logs"
- Browse around the site, seeing that the correct 'events' are being triggered
> Add global ga-tracking

- static/js/public/first-snap-flow.js
- static/sass/_snapcraft_p-notifications.scss
- templates/first-snap/_install-macos.html
- templates/first-snap/build.html
- templates/first-snap/install-snapcraft.html
- templates/first-snap/language.html
- templates/first-snap/package.html
- templates/first-snap/push.html
- templates/first-snap/test.html
- templates/home/_fsf_python.html
- templates/index.html
- templates/partials/fsf_language.html
- templates/publisher/_header.html
- templates/publisher/listing.html
- tests/publisher/snaps/tests_listing.py
- webapp/first_snap/content/python/build.yaml
- webapp/first_snap/content/python/package.yaml
- webapp/first_snap/content/python/test.yaml
- webapp/first_snap/logic.py
- webapp/publisher/snaps/views.py
Changes requested
- Visit http://0.0.0.0:8004/first-snap
- Follow the instructions and ensure everything works and looks correct
> Updated python flow

- templates/brand-store/store.html
- templates/store/snap-details.html
- templates/store/store.html
1. Pull the branch or open the demo URL
2. Visit store page
3. Check the title metatg is `Install Linux apps using the Snap Store | Snapcraft`
4. Visit a few snap details page
5. Check the title metatag is `Install {{ snap_title }} for Linux using the Snap Store | Snapcraft`
> Updated store and snap details pages

- webapp/first_snap/content/python/build.yaml
> Updated offlineimap instructions

- templates/home/_fsf_go.html
- templates/partials/fsf_language.html
- webapp/first_snap/content/golang/build.yaml
- webapp/first_snap/content/golang/package.yaml
- webapp/first_snap/content/golang/test.yaml
Give Python some company with a Golang guide.
> Add a Go first-snap guide

- templates/_layout.html
- templates/first-snap/package.html
- templates/home/_fsf_go.html
- templates/home/_fsf_python.html
- webapp/first_snap/content/golang/package.yaml
- webapp/first_snap/content/python/package.yaml
Fixes #1296, #1297, #1304
1. Run this branch or open the Demo server
2. Check for content updated following the [copydoc](https://docs.google.com/spreadsheets/d/1gN_xcaAFFP_ckDvWeNDpD9ogbRXFgcXN0w0ITZQB0e4/edit#gid=779498506) or content in #1296 , #1297, #1304
Fixes also #417 
1. Run this branch or open the Demo server on an apple device (iphone or ipad)
2. Save the homepage on your iOS device home screen
3. Check the snapcraft logo appears as an icon
> Updated copy for FSF / Apple touch icon

- static/js/public/snap-details/screenshots.js
- static/js/publisher/market/lightbox.js
- static/sass/_patterns_carousel.scss
- templates/store/snap-details.html
This PR uses Cloudinary to convert animated gifs to videos, and a fallback static jpg image.
- `./run`
- Visit http://0.0.0.0:8004/gitkraken
- Open the browsers Network logs and see how large the page is (disable cache etc)
- Do the same thing on https://snapcraft.io/gitkraken
> Optimise gifs

- static/sass/_patterns_carousel.scss
Fixes a problem with SCSS not building properly.
- ./run
- SCSS should build properly
- go check some carousel (screenshots on details page or featured snaps)
- everything should work as before
> Remove unnecessary broken SCSS

- static/js/publisher/release/releasesController.js
Fixes #1214 
Fixes the way pending releases are counted.
- go to releases page of any snap with multiple architectures
- Have some revisions released to a channel (for example revisions X,Y in beta)
- Have same revisions (except one) released to different channel (for example Z,Y in edge)
- Promote edge to beta
- Release table should correctly show that there is only one changed revision (X -> Z), and confirmation text (and tooltip) should show only one revisions as pending release
- Cancel X->Z release by clicking X button in a table
- Confirmation (Apply/Cancel) should hide as there is no pending revisions
> Correctly counts pending releases (skips already released revisions)

- templates/_footer.html
> Resolve comments from previous PR

- templates/index.html
1. Pull the branch or run the demo
2. Visit homepage
3. Check there are 2 code snippets at the very end of the code:
```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-1018242-33', 'auto');
ga('require', 'GTM-M3ZH88Z');
ga('send', 'pageview');
</script>
```
```
<style>.async-hide { opacity: 0 !important} </style>
<script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')}; …
```
> Added snippet for uk experiment

- templates/index.html
Remove experiment and add it to template directly
- `./run`
- http://127.0.0.1:8004 
- Make sure content is there
> Remove experiment and add directly to template

- templates/index.html
Closes a script tag on the homepage
> Unclosed script tag

- .gitignore
- package.json
- ./run exec yarn test-js
- tests should pass and show coverage report
> Configure jest to collect coverage data

- templates/publisher/publicise.html
Remove useless character in publicise page
Do we really need QA for this :smile:
> Remove useless character

- templates/index.html
1. Pull the branch or run the demo server
2. Go to the homepage
3. Notice the eventbrite banner is just below the quotes from Microsoft, Heroku and JetBrains
> Removed extra HR and moved eventbrite banner to the top below the quotes

- templates/home/_fsf_python.html
- templates/publisher/account-snaps.html
2. Use an account with no snaps (new account)
3. Notice you that you can:
* Register a new snap name with no snaps
* Getting started section on the left links to the [Getting started guide](https://docs.snapcraft.io/getting-started/3876) from docs
> Update empty snaps

- templates/home/_fsf_python.html
Fixes #1295 
2. Go to the homepage
3. Click/Tap on Publish your app
4. Click/Tap on python
5. Notice that on the yaml section of the example:
* `offlineimap` links to its [snap details page](https://snapcraft.io/offlineimap) 
* `snapcraft.yaml` is updated to `./snapcraft.yaml`
* `./snapcraft.yaml` links to the yaml file in the github repo
> Example yaml update

- templates/home/_fsf_pre-built.html
- templates/partials/fsf_language.html
- webapp/first_snap/content/pre-built/build.yaml
- webapp/first_snap/content/pre-built/package.yaml
- webapp/first_snap/content/pre-built/test.yaml
Add a first snap flow for pre-built apps.
@sergiusens @popey @flexiondotorg @igorljubuncic @degville I'd appreciate any copy review.
> Add a first snap flow for pre-built apps

- templates/store/snap-details.html
- tests/store/tests_details.py
- webapp/store/views.py
Add link to listing page if the snap belongs to you
- `./run`
- login
- Go on a snap that belongs to you
- Check if you have the link to the listing page under the title like this
- Go on  a snap that doen't belongs to you
- This link should exist
> Add link to listing page on own snaps

- static/js/base/notification-dismiss.js
- static/js/public/nps.js
- static/js/public/public.js
- static/sass/_snapcraft_p-notifications.scss
- templates/index.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1385
- `./run`
- Visit http://0.0.0.0:8004/?nps=true
- Open the network tab of the dev console
- Click "Provide further comments" in the notification
- Add some text
- Click Send
- The button should show a spinner, followed by a Thanks message.
- Check the network tab of the dev console to see the POST to marketo
> NPS comments

- static/js/base/polyfills.js
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1464
> Polyfills e.matches fix

- static/js/base/ga.js
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1462
> GA event fix

- requirements.txt
- Remove unused pyhton requirements (stastd, prometheus-flask-exporter, gunicorn[gevent] * 2 (lol) )
- Reorder requirements in alphabetical order
-` ./run`
- Make sure snapcraft is still running
> Clean python requirements

- static/js/base/polyfills.js
Hopefully fixes https://github.com/canonical-websites/snapcraft.io/issues/1480
> Object.assign polyfill

- static/js/public/nps.js
- templates/index.html
- `./run`
- Visit http://0.0.0.0:8004?nps=true
- See the notification at the top of the page
- Click the link
- See the links to the privacy
- Click 'em!
- If you've received the NPS email (@evandandrea) click through from the email, change the host (to http://0.0.0.0:8004, or the demo)
- Write a comment
- See marketo update
> nps privacy notice, bug fixing

- static/js/publisher/market/markdown.js
- static/js/publisher/publisher.js
- templates/publisher/listing.html
It's nice to show the markdown available :).
- `./run`
- Scroll down to the description
- Click the link below the textarea to see the available markdown
> Available markdown

- templates/_footer.html
1. Pull the branch or run the demo service URL
2. Open any snapcraft.io page
3. Check the year in footer is 2019
4. #winning
> Updated year in footer

- static/sass/_patterns_sticky_footer.scss
1. Pull the branch
2. Change appearance settings of your browser to use any colour different to white
3. Check all pages maintain a white colour
4. Approve the PR
5. #winning
> Change root element bkg colour to white

- static/js/libs/throttle.js
- static/js/publisher/market/stickyListingBar.js
- static/js/publisher/publisher.js
- static/sass/_snapcraft_market.scss
- templates/publisher/_header.html
- templates/publisher/listing.html
Fixes #635
2. Log in to your Developer account
3. Visit the /listing of any snap you own
4. Scroll up and down and notice there is a box shadow on the sticky element in the page
> Make sticky element visually different on edit listing page

- static/sass/_patterns_social-icons.scss
- templates/_footer.html
- templates/_layout-brandstore.html
- templates/_layout.html
2. Check on every page there is no Google Plus in the footer
3. #winning
> Removed google plus

- templates/index.html
Fixes #1551 
2. Check the heading in "Measure growth and retention" is now "Measure use growth"
3. #winning
> Updated heading

- templates/first-snap/build.html
- templates/first-snap/install-snapcraft.html
- templates/first-snap/language.html
- templates/first-snap/package.html
- templates/first-snap/push.html
- templates/first-snap/test.html
As discussed when reviewing the first snap flows, let's do a trial of intercom to dig deeper into where and why people are falling off.
Test this PR by going into Python on the first snap flows and clicking the circle in the bottom right.
> Replace usabilla with intercom

- codecov.yaml
- requirements.txt
- templates/index.html
- templates/partials/livestream-notification.html
- templates/partials/search-bar.html
- webapp/handlers.py
- webapp/template_utils.py
see https://github.com/canonical-websites/snapcraft.io/pull/1564
> Added notification bar to store and homepage

- static/js/publisher/state.js
- static/js/publisher/state.test.js
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1546#event-2111721475
- Pull branch
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/settings
- Update the whitelist/ blacklist territories
- Save the page
- No errors :+1:
> Update state commaSeperatedStringToArray function to trim values

- templates/publisher/publicise.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1347
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/publicise
- Try changing languages and clicking the "copy code" button on the various code examples.
> Copyable code blocks for publicise snap page

- templates/home/_fsf_node.html
- webapp/first_snap/content/node/build.yaml
- webapp/first_snap/content/node/package.yaml
- webapp/first_snap/content/node/test.yaml
> FSF Node added

- templates/first-snap/package.html
> first snap flow: fix Base appearing when the language doesn't use them

- static/js/publisher/form.js
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1597
> Don't try and add previewForm eventListener on settings page

- static/js/libs/arrays.js
- static/js/libs/arrays.test.js
- static/js/publisher/form.js
- static/js/publisher/form.test.js
- static/js/publisher/market/categories.js
- static/js/publisher/market/categories.test.js
- static/js/publisher/state.js
- templates/publisher/listing.html
- webapp/publisher/snaps/logic.py
- webapp/publisher/snaps/views.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1483
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1612
Also:
- filters out "Featured" (non-selectable) category.
- improves array equality checking for objects
- `./run`
- Modify the categories for the snap, save etc.
- When finished, remove categories
> Improve categories, and fix some issues

- static/js/publisher/form.test.js
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1482
- The CircleCI tests should pass :)
> Tidied form tests, spy rather then mock external dep

- templates/index.html
2. [Check the content is similar to the copydoc](https://docs.google.com/document/d/1_uwPkHmAgV6_uE9ISqIgXjZGJxXPBD90vdeO95h7ikE/edit#)
3. #winning
> Updated copy for homepage

- static/js/publisher/metrics/graphs/activeDevices.js
- static/js/publisher/metrics/metrics.js
- static/sass/_snapcraft_metrics.scss
- templates/publisher/metrics.html
- tests/publisher/snaps/tests_get_metrics.py
- webapp/publisher/snaps/logic.py
- webapp/publisher/snaps/views.py
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/metrics or https://snapcraft-io-canonical-websites-pr-1493.run.demo.haus/
(example https://snapcraft-io-canonical-websites-pr-1493.run.demo.haus/slack/metrics)
- Change the period of time a few times
> Show categories as annotations on metrics

- templates/_header-brandstore.html
- templates/brand-store/store.html
- templates/partials/search-bar.html
- Sit next to Luke and look @therealjuan
> Brandstore updates

- tests/tests_badge_counter.py
Fix warning output we were getting when running python tests.
> Fix python tests warning

- tests/store/tests_search.py
Add basic set of tests for search endpoint
No error handling tested yet
Make sure search endoint is tested (check coverage)
> Add basic tests for search endpoint

- static/js/public/first-snap-flow.js
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1669
- `./run`
- Visit http://0.0.0.0:8004/first-snap/python
- The OS selector should still work
> Convert NodeList to array in first snap flow

- webapp/store/content/publishers/jetbrains.yaml
## QA Steps
2. Visit `/publisher/jetbrains`
3. Notice the pycharm edu icon has the right image
4. #winning
> Updated edu python

- static/sass/_patterns_featured-snap.scss
- static/sass/_snapcraft-publisher.scss
- static/sass/_snapcraft_details_heading.scss
- static/sass/styles.scss
- templates/store/publisher-details.html
Fixes:
https://github.com/canonical-websites/snapcraft.io/issues/1714
https://github.com/canonical-websites/snapcraft.io/issues/1715
https://github.com/canonical-websites/snapcraft.io/issues/1716
2. Visit JetBrains publisher page: `/publisher/jetbrains`
3. Fixed:
- Update hero-image height on JetBrains publisher page
- Mobile fix 'Featured snaps' margin-bottom on JetBrains publisher page
- Mobile fix 'Snap list' remove placeholder snap on JetBrains publisher page
4. #winning
> Updated publisher template style

- templates/home/_fsf_ros2.html
- webapp/first_snap/content/ros2/package.yaml
A new pull request as the last one is closed. Added small description changed based on Kyle's comments.
@evandandrea the previous pull request had questions on:
* snap directory holding snapcraft.yaml vs top-level directory; I commented this should be top-level to keep it in line with the other examples.
* the mention of --devmode --dangerous is correctly reflected in the shown instructions.
* the mention of docker is not visible in the wizard.
* @kyrofa had a question on name uniqueness warning showing twice.
@kyrofa:
* please add the yaml (based on the template) to the top-level of the repo.
* following what we discussed earlier, please take a look at the rest of the changes - there should be nothing outstanding.
> FSF ROS2 description changes

- static/sass/_snapcraft_market.scss
- static/sass/_snapcraft_p-form-help-text.scss
- templates/publisher/listing.html
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1705
- `./run`
- Visit http://0.0.0.0:8004/<snap>/listing
or
- Use the demo
- See the new layout - ensure fields and combinations still work as expected
- :+1:
> Updated layout for listing page

- templates/home/_fsf_rust.html
This PR is for a small description change.
> FSF Rust description changes

- templates/home/_fsf_python.html
This PR is for small description changes in the Python language guide.
> FSF Python description changes

- templates/home/_fsf_go.html
This PR is for small description changes in the Go language guide.
> FSF Go description changes

- templates/home/_fsf_node.html
This PR proposes small description changes to the Node language guide.
> FSF Node small description changes

- templates/home/_fsf_java.html
This PR is for small description changes in the Java language guide:
title definition
removal of backslash newline in the commands
+separate PR for snapcraft.yaml changes
> FSF Java small description changes

- templates/home/_fsf_c.html
This PR is for small description changes to the C guide.
> FSF C small description changes

- templates/index.html
Not convinced by how it looks at the top, but this PR will at least give us something to debate around.
> Move the FSF up on the page

- webapp/configs/sdrsatcom.py
Fixes https://github.com/CanonicalLtd/snap-squad/issues/955
> new header link

- static/js/publisher/form/fileInput.js
- static/js/publisher/form/fileInput.test.js
- static/js/publisher/form/media.js
- static/js/publisher/form/media.test.js
- static/sass/_snapcraft_market.scss
- static/sass/_snapcraft_market_screenshots.scss
- static/sass/_snapcraft_p-file-input.scss
- static/sass/styles.scss
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1703
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1672
Fixes https://github.com/canonicalltd/snap-squad/issues/915
- `./run`
- Drag a file onto the browser window
- Drop it somewhere other than the dropzone
- Drag another file onto the browser window
- Drop it on the dropzone, should upload
- Try again with different sized images, different number of images etc.
> Drag to upload files

- tests/blog/tests_logic.py
- webapp/blog/logic.py
- webapp/blog/views.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1791
- Pull the branch or use the demo
- `./run` if you've pulled
- Visit http://0.0.0.0:8004/code
- See that the blog posts are related to vscode
Also check other snaps like http://0.0.0.0:8004/gitkraken to ensure their posts still come through
> Better blog post filtering

- tests/tests_templates_utils.py
- webapp/template_utils.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1771#event-2255170623
- `./run`
- Visit http://0.0.0.0:8004/first-snap (or visit the demo)
- Make sure no header item is highlighted
- Do the same for all publisher pages (your name in the top right should be highlighted)
> Update route mappings for new endpoints

- static/js/libs/fileValidation.js
- static/js/libs/fileValidation.test.js
- static/js/publisher/form.js
- static/js/publisher/form.test.js
- static/js/publisher/form/fileInput.js
- static/js/publisher/form/icon.js
- static/js/publisher/form/icon.test.js
- static/js/publisher/market/initIcon.js
- static/js/publisher/market/initIcon.test.js
- static/js/publisher/market/restrictions.js
- static/sass/_snapcraft_market.scss
- static/sass/_snapcraft_market_screenshots.scss
- static/sass/_snapcraft_p-file-input.scss
- templates/publisher/listing.html
- webapp/publisher/snaps/logic.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1704
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1766
- `./run`
- Drag and upload some files to use as an icon
- Delete the icon
- Click the icon to edit and upload a new icon
- Save a few times
- Revert
- etc.
- Ensure the screenshots still work as expected
> Icon to react component

- static/js/libs/formHelpers.js
- static/js/public/newsletter.js
- static/js/public/public.js
- static/js/public/snap-details/reportSnap.js
- static/sass/_patterns_card.scss
- templates/blog/article.html
- templates/blog/index.html
- templates/partials/_newsletter-signup.html
- tests/blog/tests_index.py
- webapp/api/blog.py
- webapp/blog/views.py
- webapp/handlers.py
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1807
- Pull branch
- `./run`
- Visit http://0.0.0.0:8004/blog or https://snapcraft-io-canonical-websites-pr-1809.run.demo.haus/blog
- Sign up to the newsletter - you should see a "subscibed" message next to the button
> Newsletter signup on blog

- webapp/handlers.py
> Send data to sentry if 500

- README.md
- static/sass/_patterns_card.scss
- static/sass/_patterns_maas_modal.scss
- static/sass/_utilities_crop.scss
- templates/503.html
- templates/50X.html
- templates/_footer.html
- webapp/metrics/helper.py
- webpack.config.js
- check if Circle CI and codecov badges in README work
- check if "this site" link in footer work
- check if external issues links in code comments work
> Update repository links with new organisation

- templates/index.html
- webapp/store/content/publishers/kde.yaml
- webapp/store/views.py
Fixes #1817 
2. Visit `/publisher/kde`
3. #winning
> KDE publisher page

- codecov.yaml
- requirements.txt
- templates/index.html
- templates/partials/livestream-notification.html
- templates/partials/search-bar.html
- webapp/handlers.py
- webapp/template_utils.py
2. Visit /homepage or /store to see a notification on the live stream happening Tonight
3. #winning
> Added notification for youtube live stream

- webapp/store/content/publishers/kde.yaml
Added kbreakout to KDE publisher page
2. Visit KDE publisher page
3. Notice kbreakout in the list of snaps
4. #winning
> Added kbreakout to KDE

- tests/publisher/tests_register_name_json.py
- webapp/publisher/snaps/views.py
Adds a JSON endpoint to register snap name (to be used in first snap flow).
- make sure tests pass
> Add JSON endpoint to register snap name

- templates/partials/livestream-notification.html
Removal of LIVE from Live Stream notification
2. Visit homepage or /store
3. Notice LIVE is not in the notification anymore
> Removed LIVE

- webapp/store/content/publishers/kde.yaml
1. Run the demo service or pull the branch
2. Open `/publisher/kde`
3. Click on `Contact` and you should be redirected to https://kde.org/support/
> Updated KDE contact details

- requirements.txt
This fixes the page reloading issue
- `./run`
- http://0.0.0.0:8004/
- Reload the page, the styling should be there.
> Update talisker to v0.14.3

- codecov.yaml
- requirements.txt
- templates/index.html
- templates/partials/livestream-notification.html
- templates/partials/search-bar.html
- webapp/handlers.py
- webapp/template_utils.py
2. Notice the live stream notification is not appearing either on /store or homepage
3. #winning
4. It might haunt us back at night... again.... so I created this issue [#1854](https://github.com/canonical-web-and-design/snapcraft.io/issues/1854)
> Removed livestream notification

- templates/index.html
2. Visit the homepage
3. Notice the `Showcase to millions` image is updated with the latest style on the snap details page
4. #winning
> Updated showcase to millions image

- static/js/libs/fileValidation.js
- static/js/libs/fileValidation.test.js
- static/js/publisher/form.js
- static/js/publisher/form/AccordionHelp.js
- static/js/publisher/form/AccordionHelp.test.js
- static/js/publisher/form/banner.js
- static/js/publisher/form/banner.test.js
- static/js/publisher/form/fileInput.js
- static/js/publisher/form/icon.js
- static/js/publisher/form/media.js
- static/js/publisher/form/media.test.js
- static/js/publisher/form/mediaItem.js
- static/js/publisher/form/mediaList.js
- static/js/publisher/market/initBanner.js
- static/js/publisher/market/initBanner.test.js
- static/js/publisher/market/restrictions.js
- static/sass/_snapcraft_market.scss
- static/sass/_snapcraft_market_screenshots.scss
- static/sass/_snapcraft_p-file-input.scss
- static/sass/_snapcraft_p-form-help-text.scss
- static/sass/_snapcraft_patterns_icons.scss
- templates/publisher/listing.html
- tests/publisher/snaps/tests_listing.py
- webapp/publisher/snaps/logic.py
- webapp/publisher/snaps/views.py
- yarn.lock
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1689
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1690
- `./run`
- Follow the guidance displayed below the banner area "Show banner restrictions"
- Any file that doesn't meet the restrictions should fail with an error
- You should be able to set, remove and change the image
> Upload and edit banners

- templates/partials/_video.html
1. Pull the branch or runt the demo service
2. Visit a snap with a youtube video like /code
3. Wait for the video to finish and video should not loop at the end
4. #winning
Tidier version of https://github.com/canonical-web-and-design/snapcraft.io/pull/1827
> Don't loop videos

- webapp/store/content/publishers/kde.yaml
- Pull branch
- `./run`
- Visit http://0.0.0.0:8004/publisher/kde
- See all the icons in all their glory
> More icons for the kde publisher page

- webapp/first_snap/content/moos/build.yaml
- webapp/first_snap/content/moos/test.yaml
Fixes #1888
- go to first snap flow MOOS guides
- go to build step
- everything should work as expected
- make sure everything works for both linux and macos paths
> Add missing name to MOOS yaml files

- static/js/public/snap-details/blog-posts.js
- templates/partials/blog-card--minimal.html
- templates/store/snap-details.html
Fixes https://github.com/CanonicalLtd/snap-squad/issues/984
- `./run`
- Visit http://0.0.0.0:8004/hiri
- See the link to the case study in place of the first blog post
> Hiri case study

- static/js/public/snap-details/blog-posts.js
- `./run`
- Visit http://0.0.0.0:8004/clion
- Make sure the related blog posts don't look funky
> Defend against unset limit for related blog posts

- templates/partials/_publisher-featured-snap.html
- templates/store/_media-object-snap-partial.html
- templates/store/_snap-header-information.html
- templates/store/publisher-details.html
- templates/store/snap-details.html
- webapp/helpers.py
- webapp/store/logic.py
- webapp/store/snap_details_views.py
- webapp/store/views.py
- webapp/template_utils.py
2. Open any snap from either `kde` or `jetbrains` (e.g. `/pycharm-community`, `/kcalc`, `/rubymine`...)
Optional: Visit `/publisher/kde` or `/publisher/jetbrains` for inspiration
3. You should notice the following:
a) Notice a link to the publisher page
b) Be able to see featured snaps if there are any (jetbrains snaps are good for this)
c) See a sample selection of four snaps 
d) If there are less than four snaps, it shouldn't apper
5. 🏆 **#winning** 🏆
> Publisher link on snaps

- webapp/snapcraft/views.py
2. Visit `/iot`
3. Notice Domotz Pro has been moved to the top section
4. Updated publisher names to usernames
5. #winning
> Updated IoT page

- webapp/snapcraft/views.py
2. Visit `/iot`
3. Notice Domotz snap title is `Domotz Pro Agent - Remote Network monitoring and Management`
4. #winning
> Updated title for Domotz

- templates/partials/search-bar.html
"Search thousand of snaps" doesn't make grammatical sense.
> Pluralise "Thousand"

- package.json
- static/js/publisher/metrics/graphs/snapInstalls.js
- static/js/publisher/metrics/metrics.js
- static/js/publisher/publisher.js
- static/sass/_snapcraft-publisher.scss
- templates/publisher/account-snaps.html
- templates/publisher/metrics.html
- tests/publisher/tests_account_snaps_metrics.py
- webapp/metrics/helper.py
- webapp/publisher/snaps/views.py
- yarn.lock
Adds snap installs graph to the publisher homepage.
TODO:
> Add snap installs graph to publisher page

- webapp/snapcraft/content/snapcraft_live.yaml
Add text and url for this week's snapcraft live.
> Update live banner

- webapp/snapcraft/content/snapcraft_live.yaml
> Add details for today's snapcraft live

- webapp/store/content/distros/centos.yaml
- go to https://snapcraft-io-canonical-web-and-design-pr-1981.run.demo.haus/install/skype/centos
- enjoy colors
> Update CentOS background gradient

- webapp/store/content/distros/opensuse.yaml
> Fix capitalisation of openSUSE

- yarn.lock
- go to snap listing page and releases page of some snaps
- make sure everything still works, no errors in console etc
> Upgrade React for react-dnd compatibility

- templates/store/snap-details/_channel_map.html
- templates/store/snap-distro-install.html
- tests/tests_templates_utils.py
- webapp/handlers.py
- webapp/template_utils.py
Fixes #1995 
2. Visit a snap details page (i.e. `/node`) and check the instructions are similar on its distro page instructions (i.e. `/install/node/fedora`) 
3. #winning
> Updated snippet value adding a template function

- static/js/base/polyfills.js
- static/js/libs/shallowDiff.js
- static/js/libs/shallowDiff.test.js
- static/js/publisher/publisher.js
- static/js/publisher/submitEnabler.js
- static/js/publisher/submitEnabler.test.js
- templates/publisher/account-details.html
- tests/api/test_marketo_api.py
- tests/blog/tests_index.py
- tests/publisher/tests_account_details.py
- tests/publisher/tests_post_account_details.py
- webapp/api/marketo.py
- webapp/authentication.py
- webapp/blog/views.py
- webapp/first_snap/views.py
- webapp/helpers.py
- webapp/login/views.py
- webapp/publisher/snaps/logic.py
- webapp/publisher/views.py
- webapp/snapcraft/views.py
- webapp/store/logic.py
- webapp/store/snap_details_views.py
- webapp/store/views.py
Show's whether a publisher is signed up to the blog newsletter and allows them to toggle their subscription.
- You'll need `MARKETO_URL`, `MARKETO_CLIENT_ID` and `MARKET_CLIENT_SECRET` in your `.env.local` (if you're familiar with Marketo, go ahead and get them - otherwise ask me :))
- `./run`
- Visit http://0.0.0.0:8004/account/details
- You should see an "Email preferences" section at the bottom of the page with a toggle for subscribing
- Toggle the checkbox and save
- Ensure toggling/ untoggling and saving works as you'd expect
> Email preferences

- templates/_layout-brandstore.html
- templates/_layout-embedded.html
- templates/_layout.html
2. Check the page source of `/embedded` includes the `NOINDEX` meta tag
3. Check the meta google site verification code is present on any page of the site
4. #winning
> Added google site verification and removed embedded from indexing

- templates/blog/article.html
> Remove bad formatted json

- templates/store/snap-details/_channel_map.html
- templates/store/snap-distro-install.html
Fixes #2026 
2. Open redis-desktop-manager
3. Check install instructions are `sudo snap install redis-desktop-manager`
4. #winning
> Updated install instructions

- static/js/public/first-snap-flow.js
- templates/first-snap/_install-linux.html
- templates/first-snap/_install-macos.html
- templates/first-snap/_install-windows.html
- templates/first-snap/_layout_fsf.html
- templates/first-snap/build.html
- templates/first-snap/install-snapcraft.html
- templates/first-snap/package.html
- templates/first-snap/push.html
- templates/first-snap/test.html
- templates/home/_fsf_c.html
- templates/home/_fsf_electron.html
- templates/home/_fsf_go.html
- templates/home/_fsf_java.html
- templates/home/_fsf_moos.html
- templates/home/_fsf_node.html
- templates/home/_fsf_pre-built.html
- templates/home/_fsf_python.html
- templates/home/_fsf_ros.html
- templates/home/_fsf_ros2.html
- templates/home/_fsf_ruby.html
- templates/home/_fsf_rust.html
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/1969
- Pull branch
- `./run`
- Visit http://0.0.0.0:8004/first-snap
- Go through the flow with both linux and macos
- Ensure everything works as expected
- Yay!
> FSF - pagination as buttons

- static/humans.txt
- templates/_layout.html
- templates/snapcraft/humans.txt
- webapp/snapcraft/views.py
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2034
- `./run`
- Visit http://0.0.0.0:8004/humans.txt
- Ensure pages within the site have `<link type="author" href="/humans.txt" />` in the header
> Add humans.txt

- static/js/public/ga-scroll-event.js
Fixes #2057
Fixes sentry error #2057
I wasn't able to reproduce the bug, but:
- go to distro page
- make sure that there are no JS errors
> Fix undefined origin

- static/js/base/ga.js
From Sentry https://sentry.is.canonical.com/canonical/snapcraftio/issues/212
- click around, make sure google analytics events are triggered as expected (can be checked in `dataLayer`, compare with prod)
- go to page with code snippets (first snap flow or distro page)
- copy them, check for analytics events as well
> Fix errors when trimming undefined innerText

- tests/publisher/tests_account_logout.py
- webapp/login/views.py
Logs user out of SSO when logging out of snapcraft.
Fixes #1986
> Logout of SSO when logging out of snapcraft

- requirements.txt
- templates/publisher/account-details.html
- tests/builder/tests_github_oauth.py
- webapp/api/github.py
- webapp/app.py
- webapp/builder/views.py
- webapp/database.py
- webapp/models/user.py
- webapp/publisher/views.py
Adds the possibility of connecting a github account to your snapcraft.io account.
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1031
> GitHub accounts connect

- static/js/publisher/release.js
- static/js/publisher/release/actions/branches.js
- static/js/publisher/release/actions/branches.test.js
- static/js/publisher/release/actions/history.js
- static/js/publisher/release/components/channelMenu.js
- static/js/publisher/release/components/contextualMenu.js
- static/js/publisher/release/components/releasesTable.js
- static/js/publisher/release/components/releasesTableCell.js
- static/js/publisher/release/components/releasesTableRow.js
- static/js/publisher/release/components/revisionsList.js
- static/js/publisher/release/helpers.js
- static/js/publisher/release/helpers.test.js
- static/js/publisher/release/reducers/branches.js
- static/js/publisher/release/reducers/branches.test.js
- static/js/publisher/release/reducers/channelMap.js
- static/js/publisher/release/reducers/index.js
- static/js/publisher/release/releasesController.js
- static/js/publisher/release/releasesState.js
- static/js/publisher/release/selectors/index.js
- static/js/publisher/release/selectors/selectors.test.js
- static/sass/_snapcraft_patterns_icons.scss
- static/sass/_snapcraft_release.scss
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2076
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2079
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2081
You'll need a snap with branches. The easiest way to open a branch, that I've found, is to release a snap into a branch: `snapcraft release <snap_name> <revision_number> <branch (e.g. latest/stable/test)>`.
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/releases
- Release revisions to branches
- Close revisions in branches
- Promote to and from branches
- Drag things around
- Check the history of branch architectures
- Generally just click and drag things around as a normal user would
> Release UI branches

- static/js/publisher/release/actions/defaultTrack.js
- static/js/publisher/release/components/defaultTrackModifier.js
- static/js/publisher/release/components/releasesHeading.js
- Set environment to staging as described in the README
- `./run`
- Visit http://0.0.0.0:8004/lukewh-test/releases
- Change the track dropdown
- Set the default track and check all messaging makes sense
- Repeat for clearing the default track
> Updated default track messaging

- webapp/store/snap_details_views.py
- `./run`
- Visit http://0.0.0.0:8004/slack
- The channel map should not say "None/None None"
> "latest" if default track is null

- webapp/publisher/views.py
Add sentry reporting to marketo exception handling so we know what is failing.
> Report marketo API exceptions to Sentry

- webapp/api/marketo.py
Add more context to the Marketo API errors.
> Improve marketo API exception message

- static/js/publisher/release/components/releasesHeading.js
just a pause on being able to set a default track until everyone is ready.
> don't set default tracks

- templates/_layout.html
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1094
- Increase the global-nav width
- `./run`
- See the global nav as the same width as the content
> Vanilla breakpoints

- static/js/base/ga.js
- static/js/publisher/release/components/availableRevisionsMenu.js
- static/js/publisher/release/components/defaultTrackModifier.js
- static/js/publisher/release/components/modal.js
- static/js/publisher/release/components/revisionsList.js
- static/sass/_snapcraft_footer.scss
- static/sass/styles.scss
- templates/_footer-brandstore.html
- templates/_footer.html
- templates/first-snap/_layout_fsf.html
- templates/first-snap/build.html
- templates/first-snap/install-snapcraft.html
- templates/first-snap/package.html
- templates/first-snap/push.html
- templates/first-snap/test.html
- templates/index.html
- templates/publisher/_header.html
- templates/publisher/account-details.html
- templates/publisher/account-snaps.html
- templates/publisher/metrics.html
- templates/publisher/register-name-dispute.html
- templates/publisher/request-reserved-name.html
- templates/publisher/username.html
- templates/store/search.html
- templates/store/snap-details.html
- templates/store/snap-distro-install.html
- templates/store/store.html
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1095
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1096
- Remove `p-footer`
- `u-float--*` changed to `u-float-*`
- Ensure `p-form--stacked` `label`s and `input`s are wrapped in `row`s and `col`s
- Ensure the SCSS builds
> Remove/ update deprecated components

- run
- `./run`
- Did that work still?
- Does the site still load at http://0.0.0.0:8004?
- Well done, you've successfully QA'd this PR
> update docker image to 1.6.4

- requirements.txt
- static/sass/_snapcraft_snap-builds.scss
- static/sass/styles.scss
- templates/publisher/_header.html
- templates/publisher/build-enable.html
- templates/publisher/build-list.html
- webapp/api/launchpad.py
- webapp/models/snap.py
- webapp/publisher/snaps/views.py
Add a tab in snap details page where the user can see a list of builds for the snap.
> Build list snap builds

- static/js/public/fsf-language-select.js
- static/sass/_patterns_logo-links.scss
- static/sass/_snapcraft_market.scss
- static/sass/_snapcraft_p-featured-snap.scss
- static/sass/_snapcraft_p-navigation.scss
- static/sass/styles.scss
- templates/_header.html
- templates/store/_category-partial.html
- templates/store/categories/iot.html
- templates/store/search.html
- templates/store/snap-distro-install.html
- templates/store/store.html
Fixes #2131 
Go to and review pages for any functionality and visual issues.
Demo: https://snapcraft-io-canonical-web-and-design-pr-2143.run.demo.haus/
This includes:
- navigation - make sure hover styles are good
- home page - make sure clicking on language selector for first snap flow works correctly
- IoT
- store and category pages
- search results
> Vanilla fixes for public pages

- static/js/publisher/release/components/releasesTableRow.js
- static/js/publisher/release/components/revisionsList.js
- static/js/publisher/release/components/revisionsListRow.js
- static/sass/_snapcraft_release.scss
- yarn.lock
Fixes #2136
- fixed broken history icon
- fixed hover on transparent table cells
- fixed column widths in revisions list
- fixed label spacing in table
- go to releases page of some snaps, try the ones with single arch, multiple archs, branches
- open history panels
- try hover on things
- use drag and drop on things
- release something
- make sure nothing breaks and looks good
> Vanilla releases

- templates/publisher/metrics.html
Fixes #2137 
- go to metrics page of some snaps
- check if graphs look ok
- check if tooltips render correctly
> Fix tooltips positioning on metrics page

- package.json
- yarn.lock
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2169
Does it fix:
> Update to vanilla-2.3.0

- static/js/publisher/release/selectors/selectors.test.js
> Don't use hardcoded dates in test that compare to now()

- webapp/first_snap/views.py
> snaprcaft.yaml -> snapcraft.yaml

- static/js/base/dropdown-menu-toggle.js
- static/sass/_snapcraft_p-navigation.scss
- static/sass/styles.scss
- templates/_header.html
Fixes #2175 
- ./run or https://snapcraft-io-canonical-web-and-design-pr-2183.run.demo.haus/
- sign out to check if developer account link shows correctly in navigation
- sign in
- check developer dropdown
- make sure all links in navigation work correclty
> Use Vanilla sub navigation

- static/sass/styles.scss
- templates/_footer.html
- look at footer
- it should look well
- there should be no dead hiring link
- social icon color should match background
> Small fixes for Vanilla 2 footer

- static/js/public/fsf-language-select.js
- templates/first-snap/_layout_fsf.html
- templates/home/_fsf_c.html
- templates/home/_fsf_electron.html
- templates/home/_fsf_go.html
- templates/home/_fsf_java.html
- templates/home/_fsf_moos.html
- templates/home/_fsf_node.html
- templates/home/_fsf_pre-built.html
- templates/home/_fsf_python.html
- templates/home/_fsf_ros.html
- templates/home/_fsf_ros2.html
- templates/home/_fsf_ruby.html
- templates/home/_fsf_rust.html
- templates/publisher/account-details.html
- templates/publisher/account-snaps.html
- templates/publisher/listing.html
- templates/publisher/register-name-dispute.html
- templates/publisher/register-snap.html
- templates/publisher/request-reserved-name.html
- templates/publisher/username.html
- templates/store/publisher-details.html
- templates/store/search.html
- templates/store/snap-details.html
- templates/store/store.html
Fixes #2176
Various fixes around `u-fixed-width` and new grid.
Most notably:
- adding u-clearfix then floats are used in `u-fixed-width`
- removing nested padding from caused by rows in u-fixed-width 
- click through some pages: home, store, search, snap details
- check if everything is in place
- go to publisher pages, obvious ones (snaps, listing, account, etc) and less obvious (name register, name dispute)
- on home page click on first snap flow language selector, check if spacing is correct (expanded panel should take whole width of the page and not have any nested paddings)
> Fixes and updates around `u-fixed-width`

- static/js/publisher/form/AccordionHelp.js
- static/js/publisher/form/banner.js
- static/js/publisher/form/media.js
- static/sass/_snapcraft_market.scss
- static/sass/_snapcraft_market_screenshots.scss
- templates/publisher/account-details.html
- templates/publisher/listing.html
- templates/publisher/settings.html
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2177
- Updated both listing and settings forms to use `p-form p-form--stacked`
- `./run`
- Visit http://0.0.0.0:8004/snap_name/listing
- Make sure things look and work as expected (in relation to field spacing &  help text / error text spacing)
- Try and raise some errors on fields
- Visit http://0.0.0.0:8004/snap_name/settings
- Make sure things look and work as expected (as for the listing page)
> Vanillarise forms

- static/js/publisher/tour/__mocks__/constants.js
- static/js/publisher/tour/constants.js
- static/js/publisher/tour/helpers.js
- static/js/publisher/tour/metricsEvents.test.js
- static/js/publisher/tour/tour.test.js
- static/js/publisher/tour/tourOverlay.js
- static/js/publisher/tour/tourOverlay.test.js
- static/js/publisher/tour/tourStepCard.test.js
Adds tests to Tour components.
- ./run test
- tests should pass
> Adds basic tests for Tour component.

- static/js/public/scroll-to.js
Fixes #2235 
Fixes #2237 
Fixes #2238 
Fixes sentry errors caused by `scrollTo`.
- go to distro page of any snap
- click on install button
- make sure animated scroll works as before
- bonus points for testing in Edge (fallback to not animated scroll)
> Fix issues with scrollTo

- templates/publisher/publicise/_publisher_publicise_layout.html
> Close a tag

- requirements.txt
- webapp/blog/views.py
Bumped the blog module to it's latest version.
- `./run` or demo
- Make sure blog pages work fine and related articles still show on snap detail pages.
> Bump canonicalwebteam.blog to 4.0.0

- templates/blog/article.html
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2283
- Pull branch
- `./run`
- Visit http://0.0.0.0:8004/blog/your-first-robot-a-beginners-guide-to-ros-and-ubuntu-core-1-5
- Ensure the list of the series is below the newsletter box
> Blog series in right column

- templates/index.html
publisher.js should not be downloaded on home page
> Remove publisher.js from home page

- BRANDSTORES.md
- HACKING.md
- README.md
- Updated readme.md to be more new user friendly
- Created a hacking.md for how to develop on snapcraft.io
- Created a brandstore.md for how to work on brand variations of snapcraft.io
- View the file in this branch (e.g. https://github.com/canonical-web-and-design/snapcraft.io/blob/d8415e5ffb2f515ed77be086e87c796c2867fa91/README.md)
- Make sure the content it good, the links work, you agree with the work
- I likely need a better image @kwm14
> Update the readme, hacking, and brandstores

- tests/publisher/endpoint_testing.py
- webapp/api/dashboard.py
Update if check as per https://dashboard.snapcraft.io/docs/api/account.html.
> Fix error message check for missing username

- static/js/publisher/release/api/releases.js
- make sure revisions can be released ("Apply" button should work and save changes without errors)
> Fix body in release API call

- requirements.txt
- webapp/login/views.py
Add `is_canonical` flag to session.
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1135
> Add is_canonical flag to session

- static/js/publisher/release/actions/pendingReleases.js
- static/js/publisher/release/actions/pendingReleases.test.js
- static/js/publisher/release/actions/releases.js
- static/js/publisher/release/actions/releases.test.js
- static/js/publisher/release/components/progressiveBar.js
- static/js/publisher/release/components/progressiveConfirm.js
- static/js/publisher/release/components/releasesConfirm.js
- static/js/publisher/release/components/releasesTable/cellViews.js
- static/js/publisher/release/components/releasesTable/releaseCell.js
- static/js/publisher/release/components/revisionsList.js
- static/js/publisher/release/components/revisionsListRow.js
- static/js/publisher/release/components/revisionsListRowProgressive.js
- static/js/publisher/release/reducers/history.js
- static/js/publisher/release/reducers/history.test.js
- static/js/publisher/release/reducers/pendingReleases.js
- static/js/publisher/release/reducers/pendingReleases.test.js
- static/js/publisher/release/releasesState.js
- static/js/publisher/release/selectors/index.js
- static/js/publisher/release/selectors/selectors.test.js
- static/sass/_snapcraft_p-progressive-bar.scss
- static/sass/_snapcraft_release.scss
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2241
QA:
- `./run`
- Visit a snaps release page
- Make a progressive release
- Open the history for a revision and update the percentage
- Save your changes
- Try multiple different releases at once. closing channels etc.
> Update progressive releases

- static/js/publisher/release/actions/pendingReleases.js
- static/js/publisher/release/actions/pendingReleases.test.js
- static/js/publisher/release/components/releasesConfirm.js
- static/js/publisher/release/components/revisionsListRow.js
- static/js/publisher/release/components/revisionsListRowProgressive.js
- static/js/publisher/release/reducers/pendingReleases.js
- static/js/publisher/release/reducers/pendingReleases.test.js
- static/js/publisher/release/selectors/index.js
- static/js/publisher/release/selectors/selectors.test.js
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2342
- Pull branch
- `./run`
- If you don't have a progressive release - create one and save
- Cancel the progressive release
- See a new item in the save bar regarding "cancelling" a progressive release
> Progressive release cancelation UI

- static/js/publisher/release/actions/releases.js
- static/js/publisher/release/actions/releases.test.js
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2341
- `./run`
- Do some releases using the same revisions on multiple channels, some progressive some not
- Keep an eye on the network tab of dev tools while you save the changes, see that some revision releases can be grouped by revision, with multiple channels to release to
> Dedupe non-progressive releases on release

- tests/publisher/snaps/test_builds.py
- webapp/publisher/snaps/builds.py
- webapp/publisher/snaps/views.py
Combine the two status into a single user facing status.
> Combine builds LP status and store upload status into one

- templates/publisher/metrics.html
The snapstore is currently having issues - this is a little message to let people know.
> Metrics messaging

- templates/publisher/metrics.html
Metrics are back - don't need the message anymore.
> Metrics are back, remove message

- static/sass/_patterns_button_spinner.scss
- static/sass/_patterns_carousel.scss
- static/sass/_patterns_distro_banner.scss
- static/sass/_patterns_logo-links.scss
- static/sass/_patterns_maas_modal.scss
- static/sass/_snapcraft_market.scss
- static/sass/_snapcraft_p-form-validation.scss
- static/sass/_snapcraft_patterns_icons.scss
- static/sass/_snapcraft_release.scss
Fixes #1560 
- `./run`
- Visit http://0.0.0.0:8004/ and make sure everything looks the same as previously
> Change px values to vanilla variables or rem

- static/js/public/snap-details/videos.js
Add extra null check when getting src as this errors with asciinema 
- View the site locally in your web browser at: http://0.0.0.0:8004/multipass
- Check that there is no console error as there is [in production](https://snapcraft.io/multipass)
> Add extra null check when getting src

- webapp/store/content/distros/mint.yaml
- Add latest versions of Linux Mint
Fixes #
- Navigate to any app install instructions for Linux Mint and check if the text is correct.
> Add latest Linux Mint versions (Tina and Tricia) to mint.yaml

- templates/store/_media-object-snap-partial.html
- webapp/snapcraft/views.py
Fixes #1656 
- View the site locally in your web browser at: http://0.0.0.0:8004/store and then to http://0.0.0.0:8004/blender
- Notice the publisher name is consistent (i.e. `Blender Foundation` on http://0.0.0.0:8004/store and `Blender Foundation (blenderfoundation)` on http://0.0.0.0:8004/blender)
> Display publisher name on /store page

- package.json
- static/sass/_patterns_media-object--snap.scss
- static/sass/_snapcraft-publisher.scss
- static/sass/_snapcraft_details_heading.scss
- static/sass/_snapcraft_p-docs.scss
- static/sass/_snapcraft_p-navigation.scss
- static/sass/_snapcraft_tour.scss
- static/sass/styles.scss
- templates/_header.html
- yarn.lock
- Upgrade to vanilla 2.5.0
Fixes #
- Have a general QA of as many pages you can
> Upgrade to vanilla 2.5.0

- static/js/publisher/form.js
- webapp/helpers.py
- webapp/store-licenses.json
- Use the store whitelisted SPDX's
Fixes #1329 
- Visit http://0.0.0.0:8004/snap_name/listing and scroll down to the license section
- Add and remove licenses - you shouldn't get errors or duplicate licenses
> Duplicate licenses

- entrypoint
- requirements.txt
- static/sass/_snapcraft_p-build.scss
- templates/publisher/builds.html
- webapp/api/dashboard.py
- webapp/api/github.py
- webapp/api/marketo.py
- webapp/api/requests.py
- webapp/api/sso.py
- webapp/app.py
- webapp/login/oauth_views.py
- webapp/publisher/snaps/builds.py
- webapp/publisher/snaps/views.py
- Allow user to authenticate on GitHub
- List all the user repositories on GitHub
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2419
- Login as a publisher
- Go to http://0.0.0.0:8004/<your_snap>/builds and check to you can:
- Login with GitHub
- See your GitHub repos from your account
> GitHub Authentication

- webapp/publisher/snaps/views.py
- webapp/publisher/views.py
- webapp/store/views.py
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2466
> Replace _handle_errors function

- templates/publisher/builds.html
- tests/api/cassettes/LaunchapdAPITest.test_get_snap_by_store_name.yaml
- tests/api/cassettes/LaunchapdAPITest.test_new_snap.yaml
- tests/api/cassettes/LaunchapdAPITest.test_trigger_build.yaml
- tests/api/test_launchpad.py
- webapp/api/launchpad.py
- webapp/publisher/snaps/views.py
Trigger a build on launchpad manually 
Fixes #2476
- Go to snap and click on the trigger new build button, if you refresh the page you should see new builds in the table.
> Launchpad API Call to launch a build

- static/js/publisher/builds/index.js
- static/sass/_snapcraft_builds.scss
- templates/publisher/builds.html
- Update the current build list to be the new design
- Work a bit better on mobile
Fixes #2487 
- Visit http://0.0.0.0:8004/snap_name/builds
> Build list

- static/js/public/fsf-expandable-yaml-details.js
- static/js/public/fsf-language-select.js
- Replace forEach with regular for loops for showMore elements
Fixes #2497 
- Click on any language icons and then click "Show more"
- Note it works as expected
> Replace forEach with regular for loops for showMore elements

- static/js/publisher/builds/helpers.js
- static/js/publisher/builds/index.js
- templates/publisher/builds.html
- webapp/api/launchpad.py
- webapp/publisher/snaps/views.py
- Added endpoint that filters results
- Refactored python to separate function
Fixes #2496
- Visit http://0.0.0.0:8004/snap_name/builds
- See the list of builds - 15 should show
- Click show more, more should show
> Dynamic build list

- requirements.txt
Update discourse-docs module
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2517 and https://github.com/canonical-web-and-design/snapcraft.io/issues/2516
- Go to http://0.0.0.0:8004/docs/writing-local-plugins and check that you can see the page
> Fix AttributeError in doc pages

- tests/api/cassettes/GitHubAPITest.test_check_permissions_over_repo.yaml
- tests/api/test_github.py
- webapp/api/github.py
- webapp/publisher/snaps/views.py
This added some extra checks before linking the Snap in Launchpad. We will check that:
- The user has permissions over the repo
- snapcraft.yaml is present
- The name inside the snapcraft.yaml is valid
- Log in as a publisher and try to link a GitHub repo with a Snap, you should get an error when:
- You don't have permissions over the repo
- snapcraft.yaml is not present
- The name inside the snapcraft.yaml doesn't match the Snap name.
> GitHub checks when saving a repo

- tests/api/cassettes/GitHubAPITest.test_get_org_repositories.yaml
- tests/api/cassettes/GitHubAPITest.test_get_snapcraft_yaml_name.yaml
- tests/api/cassettes/GitHubAPITest.test_get_user_repositories.yaml
- tests/api/test_github.py
- webapp/api/github.py
- webapp/publisher/snaps/build_views.py
- webapp/publisher/snaps/views.py
Refactor build views to be in one file.
Also small changes for the frontend:
- Return GitHub repository names without owner/org.
- Return error messages in the backend.
> Refactor code

- static/sass/_patterns_annotated_code.scss
- templates/first-snap/package.html
- Include yaml file name in fsf
Fixes #1991 
- View the site locally in your web browser at: http://0.0.0.0:8004/[snap_name]/python/linux/package
- Compare to [design](https://github.com/canonical-web-and-design/snapcraft.io/issues/1991)
> Include yaml file name in fsf

- static/js/publisher/release/releasesController.js
> Fix styling of release change row

- requirements.txt
- tests/first_snap/tests_views.py
- webapp/app.py
- webapp/handlers.py
Migrate to flask-base
Fixes #2463
> Use flask-base

- requirements.txt
- tests/first_snap/tests_views.py
- webapp/app.py
- webapp/handlers.py
Reverts canonical-web-and-design/snapcraft.io#2551
There is a redirect loop after login only happening in staging.snapcraft.io
> Revert "Use flask-base"

- templates/publisher/builds.html
- webapp/api/github.py
- webapp/publisher/snaps/build_views.py
- webapp/publisher/snaps/views.py
Create webhooks in GitHub repos
Fixes #2523
- Ask me for the secrets
- Link a Snap with a repository.
- Go to the GitHub repository settings and check that the webhook was created.
> Create GitHub Webhook for users

- requirements.txt
- static/js/publisher/builds/index.js
- templates/_footer.html
- templates/publisher/_header.html
- templates/publisher/build.html
- webapp/api/github.py
- webapp/publisher/snaps/build_views.py
- webapp/publisher/snaps/views.py
- Add single build page
Fixes #2488 
- Visit http://0.0.0.0:8004/snap_name/builds for a snap that has builds
- Click on one of the build numbers from the table
- See the build details page in all its glory
> Build pages with logs

- tests/api/cassettes/GitHubTest.test_get_snapcraft_yaml_name.yaml
- webapp/api/github.py
Fix cache issues with GitHub
Fixes #2576
- Validate snapcraft.yaml
> Fix cache issue with GitHub

- requirements.txt
Update launchpad version to fix build issue.
Fixes #2575
- Trigger a build in a Snap that have defined architectures in the snapcraft.yaml
> Update launchpad library

- templates/publisher/release-history.html
> Disable progressive releases for all

- templates/home/_fsf_go.html
- templates/home/_fsf_java.html
- templates/home/_fsf_node.html
- templates/home/_fsf_python.html
- templates/home/_fsf_ruby.html
- templates/home/_fsf_rust.html
- webapp/first_snap/content/golang/snapcraft.yaml
- webapp/first_snap/content/java/snapcraft.yaml
- webapp/first_snap/content/node/snapcraft.yaml
- webapp/first_snap/content/python/snapcraft.yaml
- webapp/first_snap/content/ruby/snapcraft.yaml
- webapp/first_snap/content/rust/snapcraft.yaml
- Update `yaml` files for: go, java, node, python, ruby, rust
Fixes #2571 
- View the site locally in your web browser at: http://0.0.0.0:8004/first-snap#python
> Update yaml files

- tests/publisher/snaps/tests_get_metrics.py
- webapp/metrics/metrics.py
- webapp/publisher/snaps/views.py
- Capitalise OS names
Fixes #898 
- Go to `/postman` and note capitalized OS names
- Go to `/<snap_name>/metrics?active-devices=os` and note capitalized OS names
> Capitalise OS names

- requirements.txt
- webapp/api/dashboard.py
- webapp/authentication.py
- webapp/publisher/snaps/build_views.py
Fix issue building snaps
Fixes #2577
- Register a new snap
- Link a valid repo for the snap
- The snap should be published
> Fix publish issue

- .github/workflows/main.yml
Github action CI to test docker image
> Github action to test docker image

- webapp/publisher/snaps/build_views.py
> Change webhook check

- static/js/publisher/builds/index.js
- templates/publisher/builds.html
> Always show the table on the builds page.

- webapp/publisher/snaps/build_views.py
Redirect user to login when package_upload_request is missing
Fixes #2610
- Make sure you are logout in 0.0.0.0:8004
- Modify webapp/authentication.py:72 and comment that line, like:
`# "package_upload_request",`
- Login as a publisher with your user
- Now you have a session without the needed permissions to use the new feature.
- Modify again webapp/authentication.py:72 and uncomment the line, because we want new sessions to include this permission.
- Go to any of your snaps and click in the new builds tab, you should be redirected to …
> Redirect user to login when package_upload_request is missing

- requirements.txt
- Update launchpad module with the following changes: https://github.com/canonical-web-and-design/canonicalwebteam.launchpad/pull/14
- This should fix https://github.com/canonical-web-and-design/canonicalwebteam.launchpad/issues/13
- Build some snaps with GitHub
> Launchpad module 0.2.7 -> 0.2.8

- webapp/publisher/snaps/listing_views.py
- webapp/publisher/snaps/metrics_views.py
- webapp/publisher/snaps/publicise_views.py
- webapp/publisher/snaps/release_views.py
- webapp/publisher/snaps/settings_views.py
- webapp/publisher/snaps/views.py
- webapp/publisher/views.py
Split the publisher views into different files for the features that we offer when managing a Snap.
Fixes #2519
- Make sure everything work when editing a Snap.
> Refactor publisher views

- webapp/publisher/views.py
Include macaroon-authorization-required
> Include macaroon-authorization-required

- templates/store/categories/iot.html
- Added Domotz case study link to /iot
Fixes #2623 
- View the site locally in your web browser at: http://0.0.0.0:8004/iot
- There should be another case study
> add domotz to iot page

- templates/store/categories/iot.html
- Go to http://0.0.0.0:8004/iot
- The domotz case study image should look better
> Domotz case study image

- entrypoint
Reverts canonical-web-and-design/snapcraft.io#2630
> Revert "Temporarily disable gevent"

- requirements.txt
- webapp/publisher/snaps/build_views.py
- webapp/publisher/snaps/views.py
Backend changes to disconnect a GitHub repo
Fixes #1294
> Backend changes to disconnect a repo

- templates/publisher/settings.html
> webook -> webhook

- requirements.txt
- static/js/publisher/builds/repoDisconnect.js
- static/js/publisher/publisher.js
- static/sass/_patterns_modal.scss
- templates/publisher/_repo-disconnect-modal.html
- templates/publisher/builds.html
- webapp/api/github.py
- webapp/publisher/snaps/build_views.py
- webapp/publisher/snaps/views.py
- Add disconnect repo from snap option
N/A
- Disconnect the repo, check webhooks, reconnect the repo again, see it all works fine
- Code was already reviewed so no label
> Disconnect snap

- .dockerignore
- .github/workflows/main.yml
Update GitHub action to read .env
- All the PR checks pass
> GitHub Docker use .env

- .circleci/config.yml
- requirements.txt
Update flask-base to 0.5.1
Fixes #2664
- Check the site is working as expected
> Update flask-base to 0.5.1

- webapp/publisher/snaps/build_views.py
- No longer directly modify the context dict
- Remove endpoint specific keys from the dict (and move them to the appropriate method)
Fixes #2550 
- Visit http://0.0.0.0:8004/snap_name/builds and ensure your list of builds loads as before
> Simplify get_builds method

- templates/first-snap/build-and-test.html
- Add clipboard init to script section of build-and-test part of the FSF
Fixes #2669
- Run through the FSF ensuring all clipboard copy buttons copy the contents correctly
> Ensure copy-to-clipboard works for FSF steps

- webapp/api/github.py
- webapp/publisher/snaps/build_views.py
Added error for invalid yaml file
> Added error for invalid yaml file

- templates/snapcraft/build.html
- Update build page with new messaging and design
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1181
- Visit http://0.0.0.0:8004/build
> New build page

- templates/publisher/account-snaps.html
- Added notification to snap list
Fixes #2678
- Visit http://0.0.0.0:8004/snaps
- See the notification
- Dismiss the notification "X"
- notification is no-more
> Add message to snap list

- webapp/store/content/distros/rhel.yaml
- Update the RHEL install instructions
Fixes #2646
- Visit http://0.0.0.0:8004/install/vlc/rhel
> Update RHEL distro specific install page

- static/js/public/expandable-area.js
- Don't try to remove an element that has already been removed
Fixes #2682 
> Don't try and remove an element that doesn't exist

- webapp/publisher/snaps/build_views.py
Show an error message to users if Launchpad fail to trigger the build.
Fixes #2631
- Use the dotrun snap
- Open `.venv/lib/python3.6/site-packages/canonicalwebteam/launchpad/models.py`
- Add after line 74:
```
response.status_code = 408
```
- Trigger a build manually
- You should see the error
> Show a better error if launchpad return a timeout

- templates/_header-brandstore.html
- Update nav classes for brand stores
Fixes #2684
> Fix brandstore nav

- static/js/public/expandable-area.js
- static/sass/_snapcraft_show-more.scss
- Don't remove elements with JS, use CSS instead
> hide show-more with CSS

- .dockerignore
- Dockerfile
Use multistage for docker image
Remove webapp part to integrate to environment instead
**Before merge warn so we can update Jenkins job**
- Build the image:  `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag snapcraft.io .`
- Run snapcraft: `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key snapcraft.io`
- Run limenet: `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key --env WEBAPP=limenet snapcraft.io`
- Run sdratcom: `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key --env WEBAPP=sdrsatcom snapcraft.io`
- Access sites on http://localhost:8006
- Have fun and check if all seems fine
> Update to use multistage

- templates/_layout-brandstore.html
- templates/_layout.html
> Move to different GTM code

- static/sass/_patterns_strip_slanted.scss
- static/sass/styles.scss
- templates/snapcraft/build.html
> Update suru on /build

- webapp/snapcraft/views.py
This was transferred to the Mosquitto Team user, which is a verified user.
> Update mosquitto snap publisher, and set to verified.

- webapp/publisher/snaps/build_views.py
Changed build endpoint to return a JSON object
Fixes #2745
- As a publisher go to a Snap using the builds feature
- Trigger a new build
- The reponse should be a json object in your browser
> Changed build endpoint to return a JSON

- templates/docs/base.html
- Added usabilla script
- Go to a docs page, see that the script is loaded in the network tab of console
> Add usabilla to docs

- static/js/publisher/builds/components/triggerBuild.js
- static/js/publisher/builds/helpers.js
- static/js/publisher/builds/index.js
- templates/publisher/builds.html
- webapp/publisher/snaps/build_views.py
- `Trigger new build` on the frontend
Fixes #2746
- Click the `Trigger new build` button and see the button is disable with a spinner until the table is reloaded
> 2746 create trigger new build component

- package.json
- yarn.lock
Updates global-nav to latest version
- Make sure global nav works correctly on different pages and different screens sizes
> Update global-nav to latest version

- static/js/publisher/builds/components/triggerBuild.js
- static/js/publisher/builds/index.js
- Show build error message if it exists
Fixes #2780 
- Replace line `153` in `static/publisher/builds/index.js` with: `"X-CSRFToken": "dsffgjfdiogjdfoijgd"` and then trigger a build
- Note there is an error message saying there is an issue with the token
> Show build error message if it exists

- .webpack/entry.js
- .webpack/rules.js
- package.json
- webpack.config.js
- yarn.lock
- Update webpack config it is inline with other projects
- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8004
- Check that there is a `static/js/dist` directory which contains all the built JS files
- Check that the following commands work as expected:
- `dotrun exec yarn lint-js`
- `dotrun exec yarn test-js`
- `dotrun exec yarn build-js`
- `dotrun exec yarn watch-js`
> Update webpack config

- .eslintrc.js
- webpack.config.entry.js
- webpack.config.js
- webpack.config.rules.js
- Fix webpack config includes
Fixes #
- Visit a few pages and check if everything looks normally. Keep an eye on any errors in the console
> Fix webpack config includes

- static/js/publisher/publicise.js
- Change embedded cards height
Fixes #
> Change embedded cards height

- static/js/public/snap-details/channelMap.js
- templates/store/snap-details/_channel_map.html
- Added a couple of messages to the channel map dropdown, where appropriate.
Fixes #1247
- Visit http://0.0.0.0:8004/deno and see the channel map has warning
- Visit a few other snaps from /store or search and see what it looks like!
> Show warning about unstable channels

- .github/pull_request_template.md
- requirements.txt
Small PR to check the new demo service in Snapcraft
> Changes for new demo service

- deploy/limenet.snapcraft.io.yaml
- deploy/sdrsatcom.snapcraft.io.yaml
- deploy/staging-api.snapcraft.io.yaml
K8s config for limenet, sdrsatcom and staging-api
> K8s config for limenet, sdrsatcom and staging-api

- static/js/public/snap-details/channelMap.js
- templates/410.html
> Fix warning bug

- templates/store/snap-details/_channel_map.html
- Change label to paragraph
Fixes #2908 
> Change label to paragraph

- requirements.txt
- webapp/blog/views.py
Update canonicalwebteam.blog to 6.0.0
Fixes #2917
- Check that http://0.0.0.0:8004/blog is working as expected
- Check also the "Related blog posts" section in snaps like http://0.0.0.0:8004/maas
> Update canonicalwebteam.blog to 6.0.0

- templates/_layout.html
* Anti-flicker snippet for Google Optimize
- Run Optimize diagnostics on the demo (done, see screenshots)
> Add Optimize anti-flicker snippet

- templates/_layout.html
This reverts commit a7352b2a38f1e3374b5565f3256f8a239b0e1b34.
> Revert "Add Optimize anti-flicker snippet (#2926)"

- webapp/blog/views.py
- Add exception to catch no tags error
Fixes #2946 
- View the site locally in your web browser at: http://0.0.0.0:8004/scrcpy
- See there are no errors in the console
> Catch the no tag found error

- webapp/first_snap/content/ros/build.yaml
- webapp/first_snap/content/ros/snapcraft.yaml
- webapp/first_snap/content/ros/test.yaml
Also remove the broken docker instructions.
> ros1 fsf: properly test the snap

- webapp/first_snap/content/ros2/build.yaml
- webapp/first_snap/content/ros2/snapcraft.yaml
- webapp/first_snap/content/ros2/test.yaml
Dashing is the ROS 2 LTS that runs on 18.04 (core18).
> ros2 fsf: update to use dashing

- package.json
- webpack.config.rules.js
- yarn.lock
- Update some dependencies
Fixes #
- See everything works as expected
> Update some dependencies

- webapp/store/content/distros/mint.yaml
Updated Linux Mint snapd install instructions.
Fixes #
> Updated Mint snapd install instructions.

- requirements.txt
- templates/partials/blog-card.html
- webapp/blog/views.py
Update blog module version.
Browse to https://snapcraft-io-2996.demos.haus
Check that thumbnails are ok. Click on some articles, check the images are fine.
> Update blog module version

- requirements.txt
Update blog to 6.2.2
Browse to: https://snapcraft.io/blog/api/snap-posts/konversation
Page is broken
Browse to: https://snapcraft-io-3011.demos.haus/blog/api/snap-posts/konversation
You get page
> Update blog to 6.2.2

- webapp/publisher/snaps/build_views.py
Update success message.
Fixes #2890
> Update success message

- renovate.json
> Use Webteam Renovate config

- requirements.txt
- Fix error when auth is stale
Fixes #3040 
> Fix error when auth is stale

- webapp/api/requests.py
Set a default 6s timeout
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1632
> Set a default timeout

- webapp/api/github.py
- webapp/publisher/snaps/build_views.py
- The first call from the webhook doesn't contain the branch. This PR fix the error 
- Ping me for the QA process
> Fix 500 error after webhook creation

- .github/workflows/master.yml
- README.md
> Add Github actions badge to readme

- HACKING.md
- konf/site.yaml
- templates/publisher/builds.html
- templates/publisher/settings.html
- webapp/login/oauth_views.py
- webapp/publisher/snaps/build_views.py
- webapp/publisher/snaps/views.py
- Install webhook button under snap settings
- Go to your snap settings and try to install the GitHub webhook click on the link
> Install webhook button

- HACKING.md
Update HACKING.md file to include instructions for the Snap automated builds feature.
> HACKING.md - Snap automated builds

- templates/store/search.html
Fixed issue #2777. Changed pagination links to buttons.
> Changed pagination links to buttons

- .github/workflows/pr.yml
- requirements.txt
- tests/api/test_marketo_api.py
- tests/publisher/snaps/tests_post_settings.py
- tests/publisher/snaps/tests_publicise_badges.py
- tests/publisher/snaps/tests_settings.py
- tests/publisher/tests_publisher.py
- tests/store/tests_distro_page.py
- tests/store/tests_get_store_view.py
- tests/store/tests_publisher.py
- tests/store/tests_search.py
- Updated `responses` library
- Updated query string on mocked responses for tests
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3103
- Check tests are passing
> Update query string for tests

- webapp/api/requests.py
- webapp/helpers.py
- webapp/login/views.py
- webapp/publisher/snaps/build_views.py
- webapp/publisher/snaps/listing_views.py
- webapp/publisher/snaps/metrics_views.py
- webapp/publisher/snaps/publicise_views.py
- webapp/publisher/snaps/release_views.py
- webapp/publisher/snaps/settings_views.py
- webapp/publisher/snaps/views.py
- webapp/publisher/views.py
- Remove timeout limit for publishers
> Remove timeout limit

- .env
- tests/publisher/snaps/tests_post_settings.py
- tests/publisher/snaps/tests_settings.py
> Env variable for tests

- webapp/app.py
Configure talisker session for publisher API
> Configure talisker session for publisher API

- webapp/publisher/snaps/build_views.py
- Show error message for collaborators
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3117
- Link a Snap with a repository where you are a collaborator.
- Go to the settings tab and try to create the webhook.
- An error message should appear.
> Show error message for collaborators

- package.json
- yarn.lock
- Migrate from LibSass to Dart Sass
Fixes #3156 
> Migrate from LibSass to Dart Sass

- package.json
- static/sass/_snapcraft_l-application.scss
- static/sass/styles.scss
- templates/admin/admin.html
- webapp/store/views.py
- Fix issue with broken husky config (drive-by)
- Add view for admin page
- Add application layout to admin page
Fixes #3200
- View the site locally in your web browser at: http://0.0.0.0:8004/admin
- Check that there is a skeleton page at this URL
- Check that it uses the [Vanilla application layout](https://vanillaframework.io/docs/layouts/application)
> Build admin template

- webapp/admin/views.py
- webapp/app.py
- webapp/store/views.py
- Added flask blueprint for admin pages
- http://0.0.0.0:8004/admin should return a 200 status code
> Added flask blueprint for admin pages

- templates/admin/_navigation.html
- templates/admin/admin.html
- webapp/admin/logic.py
- webapp/admin/views.py
- Get stores where the user is an administrator from the API
> Get stores and list them

- static/sass/_snapcraft_l-application.scss
- static/sass/styles.scss
- templates/admin/_navigation.html
- templates/admin/members.html
- webapp/admin/views.py
Added a view for a store members page
- View the site locally in your web browser at: http://0.0.0.0:8004/admin/ahnuP3quahti9vis8aiw/members
- Check that "Members" is highlighted in the navigation
- Check that the page contains a table with dummy data
> Add members view

- templates/admin/_navigation.html
- templates/admin/members.html
- webapp/admin/views.py
- Get store members
- Check http://0.0.0.0:8004/admin/ahnuP3quahti9vis8aiw/members
> Get store members API data

- templates/admin/admin_layout.html
- templates/admin/manage_members.html
- templates/admin/members.html
- webapp/admin/views.py
- Members API
Fixes #3189
- Change user roles
- Invite new members
> Members API

- webapp/store/snap_details_views.py
Remove bleach for the description
Let mistune take care of making the response safe
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3037
- View the site locally in your web browser at: http://0.0.0.0:8004/tbmb-bsi-test
- Try to put stuff in the description like code snippets or else. Make sure that we are displaying the code and not executing it
> Remove bleach for descirption

- templates/admin/manage_members.html
- Added info icons with role descriptions to manage member table headers
- Added functionality to submit role change data
Fixes #3210
- View the site locally in your web browser at: http://localhost:8004/admin/ahnuP3quahti9vis8aiw/members/manage
- Check that submitting the form and changing roles sends the correct data
> Add functionality to submit role change data

- templates/admin/manage_members.html
> Fix broken members form

- webapp/admin/views.py
> Manage members backend

- templates/admin/_navigation.html
- templates/admin/models.html
- webapp/admin/views.py
Add view for models
Fixes #3208
- View the site locally in your web browser at: http://localhost:8004/admin/ahnuP3quahti9vis8aiw/models
- Check that there is a models table with hardcoded data
> Add models view

- templates/admin/manage_members.html
Updated manage members form to only submit changed data
- View the site locally in your web browser at: http://localhost:8004/admin/ahnuP3quahti9vis8aiw/members/manage
- Change the data and submit
- Check that it is successful
- Revert data to default state
- Check that submit button is disabled unless there are any changes
> Update only changed members

- konf/limenet.snapcraft.io.yaml
- konf/sdrsatcom.snapcraft.io.yaml
- konf/site.yaml
- konf/staging-api.snapcraft.io.yaml
> Reduce memory limit to 256Mi

- templates/admin/settings.html
- webapp/admin/views.py
- List brand store settings
- Edit brand store settings
Fixes #3187
> Settings API

- static/js/public/manage-members.js
- static/js/public/modal.js
- static/sass/_snapcraft_l-application.scss
- templates/admin/admin_layout.html
- templates/admin/manage_members.html
- webpack.config.entry.js
- webpack.config.rules.js
- Some refactoring (moving JS to own files)
- Add invite member modal
Fixes #3242
- View the site locally in your web browser at: http://localhost:8004/admin/ahnuP3quahti9vis8aiw/members/manage
- Check that you are able to invite a member
> Add invite member

- templates/brand-store/search.html
- templates/partials/_verified_developer.html
- templates/store/_media-object-snap-partial.html
- templates/store/_snap-header-information.html
- templates/store/publisher-details.html
- templates/store/snap-embedded-card.html
Refactor duplicate code into partial
- http://0.0.0.0:8004/eks
- http://0.0.0.0:8004/store
- Test an embedded card 
- Navigate in the site to make sure that we don't have icons going crazy
> Extract verified developer into partial

- tests/store/tests_public_logic.py
- webapp/store/logic.py
- webapp/store/snap_details_views.py
Merge loops for version and confinment finder.
- View the site locally in your web browser at: http://0.0.0.0:8004/eks
- test a few snaps and make sure that the data is correct
> Merge loop for version and confinement finder

- static/js/public/hero-tabpanel.js
Add cloudinary to homepage
- Make sure that icons load well on the caroussel
> Add cloudinary to caroussel

- templates/admin/_snaps_section.html
Updated the admin pages snaps table to be more inline with the design
- View the site locally in your web browser at: http://localhost:8004/admin/ahnuP3quahti9vis8aiw/snaps
- Check that the "PUBLISHED IN" column is as tall as all the other columns combined
> Update snaps admin table

- requirements.txt
> Update store API module

- .github/pull_request_template.md
- HACKING.md
- README.md
- _Update GitHub PR template_
- _Update `Readme` file_
- _Update `Hacking` file_
- To run the project locally, please refer to the [Readme](https://github.com/canonical-web-and-design/snapcraft.io/blob/master/README.md#local-development) file for more information
Fixes #3284
> Update PR template

- requirements.txt
- tests/publisher/snaps/tests_post_settings.py
- tests/publisher/snaps/tests_settings.py
- Update Launchpad to 0.8.1 (Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3320)
- Check you have admin rights to see other people snaps, this snap will show an error: https://snapcraft.io/null/builds
- Now check https://snapcraft-io-3333.demos.haus/null/builds, it should work
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3320
> Update Launchpad to 0.8.1

- static/images/yt_play_btn.svg
- static/sass/_snapcraft-p-videos.scss
- static/sass/styles.scss
- templates/partials/_video.html
Show YouTube thumbnail by default then load the video on hover to improve performance
- Go to https://snapcraft-io-3353.demos.haus/code
- Hover over the video section and see that the YouTube video loads
Fixes #3341
> Load YouTube video only when needed

- templates/admin/manage_snaps.html
- webapp/admin/views.py
Added the manage snaps view and listed existing snaps
- Go to https://snapcraft-io-3394.demos.haus/admin
- Click the "Manage snaps" button on the top right
- Check that there is a table identical to the one on the snaps page
- This view doesn't do anything as yet, that is expected
Fixes #3206, #3373
> Build manage snaps section

- requirements.txt
- webapp/admin/views.py
- Added post_manage_store_snaps
- Steve knows
> Added post_manage_store_snaps

- static/js/public/manage-snaps.js
- templates/admin/manage_snaps.html
- webpack.config.entry.js
- webpack.config.rules.js
Add manage snaps UI
- Go to https://snapcraft-io-3395.demos.haus/admin
- Click on "Manage snaps"
- Check that the table has checkboxes for each snap
- Check that the form works (although there will be an error because no snaps are being sent)
Fixes #3374
> Allow adding and removing of snaps from store

- static/js/public/manage-members.js
- templates/admin/manage_members.html
Added a filter to the members table
- Go to https://snapcraft-io-3398.demos.haus/admin/ahnuP3quahti9vis8aiw/members/manage
- Use the filter to search by display name, username or email
- Check that only the appropriate table rows are present
- Use the filter to search by role
- Check that only the appropriate table rows are present
- Change some roles and save
- Check that the form still works
Fixes #3241
> Filter members

- static/sass/_snapcraft_l-application.scss
- templates/admin/manage_members.html
- templates/admin/manage_snaps.html
Made amends to the manage members page based on design feedback
- Go to https://snapcraft-io-3400.demos.haus/admin/ahnuP3quahti9vis8aiw/members/manage
> Design amends for manage members page

- static/js/public/manage-members.js
- static/sass/_snapcraft_custom-checkboxes.scss
- static/sass/styles.scss
- templates/admin/manage_members.html
Added custom checkboxes on the manage members page to be inline with RBAC (http://10.48.131.152:5000/r/policies)
- Go to https://snapcraft-io-3415.demos.haus/admin/ahnuP3quahti9vis8aiw/members/manage
- If you uncheck a checked field, you should see a yellow box with a white "X"
- If you check an unchecked field you should see a green box with a white "+"
Fixes #3411
> Add changed state to manage member checkboxes

- templates/admin/_snaps_section.html
The first snap is not an exception anymore
Remove broken logic
- Or you can run the project locally using the [dotrun](https://snapcraft.io/dotrun) snap with `$ dotrun` and view it in your web browser at: http://0.0.0.0:8004/admin
- Make sure it works as usual
> Remove exception for first snap on the list

- static/js/public/invite-members.js
- static/js/public/manage-invites.js
- static/js/public/manage-members.js
- static/js/public/modal.js
- static/sass/styles.scss
- templates/admin/_invites_modal.html
- templates/admin/_manage_invites_form.html
- templates/admin/invites.html
- templates/admin/manage_members.html
- webapp/admin/views.py
- webpack.config.entry.js
- webpack.config.rules.js
- Added invite member form to invites page
- Refactored `modals.js` so it works with more than one modal per page
- Go to https://snapcraft-io-3418.demos.haus/admin/ahnuP3quahti9vis8aiw/members/invites
- Click the "Invite member" button on the top right of the screen
- Fill out the form and check that it works
- Go to https://snapcraft-io-3418.demos.haus/admin/ahnuP3quahti9vis8aiw/members/manage
- Click the "Invite member" button on the top right of the screen
- Fill out the form and check that it works
Fixes #3414
> Add invite member form to invites page

- webapp/login/views.py
- Enable Candid authentication
**Demo link will not work with Candid**
Set up all the staging APIs in the `.env.local`:
```
LOGIN_URL=https://login.staging.ubuntu.com
SNAPSTORE_DASHBOARD_API_URL=https://dashboard.staging.snapcraft.io/
CANDID_API_URL=https://api.staging.jujucharms.com/identity/
```
- `dotrun`
- Visit `localhost:8004/login-beta`
- Use your SSO staging account
- All the publisher part should work as usual
> Enable Candid authentication

- static/js/publisher/publicise.js
Fix sentry error
- Go to https://snapcraft-io-3464.demos.haus/lukewh-test/publicise/cards
- Open the browser console
- Resize and check that there are no console errors
Fixes #3463
> Fix sentry error

- templates/snapcraft/build.html
- Update header for snapcraft.io/build with ESM announcement
-  http://0.0.0.0:8004/build
- Make sure header is using the new wordings
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3459
> Update header build snapcraft.io

- static/js/public/hero-tabpanel.js
- _Fix sentry error [11651](https://sentry.is.canonical.com/canonical/snapcraft-io/issues/11651/)_
- Go to https://snapcraft-io-3483.demos.haus
- See that the carousel works fine
Fixes #3462 
> Fix sentry error 11651

- templates/_header.html
- update link to forum to have same behaviour than snapcraft forum
- forum link should link to forum.snapcraft.io
> Update header link

- static/sass/_snapcraft_l-application.scss
Fixed the height of the application layout to prevent scrolling
- Go to https://snapcraft-io-3506.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- When you scroll the page check that the header doesn't move
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3507
> Fix height of application layout

- static/js/public/manage-members.js
- static/sass/_snapcraft_custom-checkboxes.scss
- templates/admin/manage_members.html
Disabled the admin checkbox in the members table for the logged in user
- Go to https://snapcraft-io-3522.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Check that the admin role checkbox is disabled for the logged in user
Fixes #3515
> Disable loggedin users admin input

- package.json
- static/js/public/manage-snaps.js
- static/js/public/utilities/build-snaps-table-row.js
- static/sass/_snapcraft_p-search-results.scss
- static/sass/_snapcraft_p-side-panel.scss
- static/sass/styles.scss
- templates/admin/snaps.html
- webapp/admin/views.py
- yarn.lock
Added snaps search
- Go to https://snapcraft-io-3534.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Click the "Add snap" button in the top right of the app
- Search for a snap (the list should appear after you have typed two characters)
- Click on any of the results and check that it is added to a list beneath the search box
- Click the bin icon in the top right of any snap in that list and check that it is removed
- Click the "Add snaps" button at the bottom of the column and check that those snaps are added to the snaps table
- Click the bin icon at the end of the table row for any snaps you have added and check that it is removed
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2029
> Add search field

- konf/staging-api.snapcraft.io.yaml
- Add missing secrets for the Staging API
> Add missing secrets for the Staging API

- templates/store/snap-details.html
-  Update title according [to brief](https://docs.google.com/document/d/1sR6vIWUxXv6VWMTsc0rm8GvcJrtEQvISbCalORJtPOA/edit).
- Title should be: `Install x on Linux | Snap Store` 
- `dotrun`
- http://0.0.0.0:8004/toto
- Title of the page should be:  `Install toto on Linux | Snap Store`
> Update title snap details page

- templates/publisher/metrics.html
- Fix template code
- On any snap visit `/<SNAP-NAME>/metrics?active-devices=channel`
- eg: https://snapcraft-io-3586.demos.haus/test-snap-amd64/metrics?active-devices=channel
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3584
> Fix metrics by channel

- templates/store/categories/iot.html
- webapp/snapcraft/views.py
Updated the copy on the IoT page as per [the copy doc](https://docs.google.com/document/d/1yfnQ5pXu5tDTG3M7Yv_gpjd894NUzSBKcvhB_pZqrMo/edit#)
- Go to https://snapcraft-io-3587.demos.haus/iot
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1yfnQ5pXu5tDTG3M7Yv_gpjd894NUzSBKcvhB_pZqrMo/edit#)
Fixes #3581
> IoT copy updates

- konf/site.yaml
- konf/staging-api.snapcraft.io.yaml
- requirements.txt
- templates/docs/document.html
- templates/tutorials/index.html
- webapp/docs/views.py
- webapp/tutorials/views.py
- Upgrade docs and tutorials
- Docs topic: https://forum.snapcraft.io/t/snap-documentation-temp/25750
- Visit https://snapcraft-io-3613.demos.haus/docs
- Visit https://snapcraft-io-3613.demos.haus/tutorials
> Upgrade docs and tutorials

- webapp/docs/views.py
- Use original Discourse topic for docs
- https://snapcraft-io-3615.demos.haus/docs should work as usual
> Use original Discourse topic

- konf/site.yaml
- konf/staging-api.snapcraft.io.yaml
- requirements.txt
- templates/docs/document.html
- templates/tutorials/index.html
- webapp/docs/views.py
- webapp/tutorials/views.py
Reverts canonical-web-and-design/snapcraft.io#3613
> Revert "Upgrade docs and tutorials"

- static/js/public/manage-snaps.js
- static/js/public/utilities/build-snaps-table-row.js
- static/sass/_snapcraft_l-application.scss
- templates/admin/_navigation.html
- templates/admin/snaps.html
- webapp/admin/views.py
- Default to snaps page
- Remove admin actions if only a viewer
- Show icons in navigation sidebar
- Go to https://snapcraft-io-3633.demos.haus/admin/testGahNg0wohVae8aY4/snaps (you must be a viewer only)
- Check that there are icons in the side navigation
- Check that there are no sub-navigation items in the side navigation for that store
- Check that there is no "Add snaps" button for that store
- Check that there is no delete button in the table for the snaps in that store
Fixes #2166
> Admin pages side navigation

- static/js/brand-store/Settings/Settings.test.js
Write tests for the brand store settings view
- Run `yarn test-brand-store`
- Check that the tests pass
> Write brand store settings form tests

- static/js/brand-store/Members/Members.js
- static/js/brand-store/selectors/index.js
- static/js/brand-store/slices/invitesSlice.js
- static/js/brand-store/slices/membersSlice.js
- static/js/brand-store/store/index.js
- static/sass/styles.scss
- webapp/admin/views.py
Added the members and invites tables
- Go to https://snapcraft-io-3702.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Check that there is a members and invites table in an accordion
Fixes #3654, #3658
> Add members and invites table

- static/js/brand-store/Members/Members.js
Added the members table filter
- Go to https://snapcraft-io-3703.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Use the search and filter input to filter members by name or email address
Fixes #3655
> Add members filter

- templates/docs/base.html
Removed usabilla code as it is injected via GTM
Check that the usabilla code is not in the template
> Remove usabilla code

- static/js/brand-store/Members/InvitesTable.js
- static/js/brand-store/Members/Members.js
- static/js/brand-store/Members/MembersTable.js
- static/sass/_snapcraft_p-autocomplete.scss
- webapp/admin/views.py
- Go to
- Click the "Add a member" button
- Type in an email of someone already available to the store, e.g. peter.mahnke@canonica.com
- Select roles
- Submit the form and check that the member is added to the table with the roles you assigned selected
- Click the "Add a member" button
- Type in your email address with a random string e.g. your.name+asdfasdfads@canonical.com
- Check that you get prompted to send an invite
- Send the invite and you should receive that as an email
Fixes #3657
> Add members invite form

- static/js/brand-store/App/App.js
- static/js/brand-store/Invites/Invites.js
- static/js/brand-store/Invites/index.js
- static/js/brand-store/Members/InvitesTable.js
- static/js/brand-store/Members/Members.js
- static/js/brand-store/Members/MembersTable.js
- static/js/brand-store/Members/memberRoles.js
- static/sass/_snapcraft_l-application.scss
Added the ability to manage members roles in the brand store
- Go to https://snapcraft-io-3715.demos.haus/admin/ahnuP3quahti9vis8aiw/members
- Make changes to member roles
- Check that the save bar appears at the bottom of the page
- Save the form and the changes should persist
- Make more changes, then undo those changes
- Check that the save bar disappears
Fixes #3715
> Add member role management

- templates/home/_fsf_ros.html
- webapp/first_snap/content/ros/snapcraft.yaml
- Update snapcraft.yaml for ROS, see https://github.com/canonical-web-and-design/snapcraft.io/issues/3732
- https://snapcraft-io-3760.demos.haus/first-snap/ros/linux/package
- Compare the snapcraft.yaml with the one in https://forum.snapcraft.io/t/ros-applications/7822
Fixes #3732
> Update snapcraft.yaml for ROS

- templates/index.html
Updated copy and image on homepage
- Go to https://snapcraft-io-3759.demos.haus/
- Check that Gabriel's comments in [the copy doc](https://docs.google.com/document/d/1_uwPkHmAgV6_uE9ISqIgXjZGJxXPBD90vdeO95h7ikE/edit#) have been addressed (please resolve them)
Fixes #3757
> Copy update

- package.json
- static/js/brand-store/Snaps/Snaps.js
- tsconfig.json
- webpack.config.rules.js
- yarn.lock
Added TypeScript to the project for brand store (and ignored so can be converted gradually)
**Note**: This PR contains a bug fix from [another PR](https://github.com/canonical-web-and-design/snapcraft.io/pull/3775).
- Go to https://snapcraft-io-3776.demos.haus/admin
- Check that the app still works
> Setup typescript for brandstore

- webapp/blog/views.py
- Fix related blog posts
- Visit the following demo URLs:
- `/wekan` should have 2 blog posts
- `/weka` shouldn't have any blog post
Fixes #3762
> Fix related blog posts

- static/js/brand-store/Settings/Settings.test.tsx
- static/js/brand-store/Settings/Settings.tsx
- static/js/brand-store/brand-store.js
- static/js/brand-store/hooks/index.ts
- static/js/brand-store/slices/brandStoreSlice.ts
- static/js/brand-store/slices/currentStoreSlice.ts
- static/js/brand-store/slices/invitesSlice.ts
- static/js/brand-store/slices/membersSlice.ts
- static/js/brand-store/slices/snapsSlice.ts
- static/js/brand-store/store/index.ts
Converted brand store slices to TypeScript
- Go to https://snapcraft-io-3803.demos.haus/admin
- Check the each view loads
Fixes #3802
> Convert brand store slices to TypeScript

- static/js/publisher/preview.js
Fixed the video preview for snaps
- Go to https://snapcraft-io-3828.demos.haus/jenkins/listing
- Click on the "Preview" button
- The video should not be overlapping the content below it
Fixes #3807
> Fix video preview for snaps

- konf/site.yaml
- Split services on snapcraft.io
> Split services on snapcraft.io

- .github/workflows/pr.yml
- konf/site.yaml
> Split publisher

- entrypoint
- Remove gunicorn max-requests
> Remove gunicorn max-requests

- entrypoint
> Use two gunicorn workers

- requirements.txt
- webapp/config.py
- Upgrade flask-base to v1
- Set session cookie to `SameSite=None Secure`. To avoid issues with Firefox, see:
https://bugs.launchpad.net/canonical-identity-provider/+bug/1895734/
- `dotrun` and login
> Upgrade flask-base and set session cookie to SameSite=None Secure

- static/js/publisher/release/components/channelMenu.js
- static/js/publisher/release/components/contextualMenu.js
- static/js/publisher/release/components/releasesTable/channelHeading.js
- static/sass/_snapcraft_release.scss
- Show hover state on whole row when channel cell is hovered
- Change gear icon to small button which only shows on hover
- Changed colour of dragging state for the row
- Go to https://snapcraft-io-3864.demos.haus/danieltest-snap/releases
- Hover over the channel cell (first one) in the table
- The whole row should be highlighted
- A button should appear to promote or close the channel
- Drag the row and it should turn light blue
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2315
> Build release UI channel cell changes

- webapp/api/requests.py
- webapp/app.py
- Remove extra logging DEBUG line (START)
- Remove gevent.Timeout
> Revert debugging changes

- webapp/store/views.py
- Display 404 for not supported publishers
- Visit the demo in your browser, check current publishers work:
- /publisher/snapcrafters or /publisher/kde
- Check that other publishers are not causing a 500 error /publisher/foobarbaz
Fixes #3874
> Display 404 for not supported publishers

- requirements.txt
- Upgrade flask-base
- Run `dotrun`
> Upgrade flask-base

- tests/login/tests_login_handler.py
- tests/publisher/endpoint_testing.py
- tests/publisher/snaps/tests_post_listing.py
- tests/publisher/snaps/tests_post_release.py
- webapp/publisher/snaps/release_views.py
> Fix Python tests

- templates/blog/index.html
- templates/store/search.html
- templates/store/snap-details.html
- templates/tutorials/tutorial.html
- Fix next/prev page buttons
- Visit the demo /blog and check the pagination
Fixes #3929
> Fix next/prev page buttons

- requirements.txt
- Fix docker image
- Checks should pass
- `pybadges` was updated check `https://snapcraft-io-3935.demos.haus/<SNAP>/publicise/badges` is working as expected
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2437
> Fix docker image

- static/js/public/accordion.js
- static/js/public/accordion.test.js
- static/js/public/first-snap-flow.js
- static/sass/_patterns_first-snap-flow.scss
- templates/first-snap/build-and-test.html
- templates/first-snap/package.html
- templates/first-snap/upload.html
- Stepped through each step in the first user flow and fixes the use of the accordion pattern.
- Fixed a number of a11y issues across the pages
- Replace classes with Vanilla ones where possible 
- Go to /first-snap/flutter
- Step through the steps
- Check the steps match [the design](https://zpl.io/2ZDWkAL)
- Try the accordions work as expected
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3925
> Fix first user flow package snap

- templates/home/_fsf_ros2.html
- webapp/first_snap/content/ros2/snapcraft.yaml
- Remove already installed build pacakges
> fix(ros2-first-snap): remove already satisfied dependencies

- static/js/brand-store/Publisher/Publisher.tsx
- static/js/brand-store/Reviewer/Reviewer.tsx
- static/js/brand-store/ReviewerAndPublisher/ReviewerAndPublisher.tsx
- static/js/brand-store/Snaps/Snaps.js
- Update reviewer/publisher messages
- Check the messages are working as mentioned in the reported issue: https://github.com/canonical-web-and-design/snapcraft.io/issues/3940
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3940
> Update reviewer/publisher messages

- static/js/publisher/builds/components/repoConnect.js
- Snapcraft Builds: Fix spinner position
- Try to connect one of you snaps to any repo from here: `https://snapcraft-io-3966.demos.haus/<snap>/builds`
- See that every time you switch between different GitHub Orgs of your username the spin appears on the disabled box while loading.
Fixes #3939
> Snapcraft Builds: Fix spinner position

- static/js/brand-store/Snaps/SnapsTable.js
- static/js/brand-store/Snaps/SnapsTableRow.js
- static/sass/styles.scss
- Fixed brand store snaps table mobile cards
- Resized column widths on snaps table
- Go to https://snapcraft-io-3975.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Check that the snaps table column widths are OK
- Resize your browser to smaller screen sizes
- Check that the mobile cards look OK
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3747, https://github.com/canonical-web-and-design/snapcraft.io/issues/3726
> Fix brand store snaps table on mobile

- requirements.txt
- security.txt
- Added security.txt. The expiration date is a mandatory field so put 2024 to match with the next LTS 🤷🏽‍♂️ 
Check https://snapcraft-io-3980.demos.haus/.well-known/security.txt
> Add security.txt

- static/js/brand-store/Snaps/Snaps.js
- static/js/brand-store/Snaps/SnapsTable.js
Show other stores containing snaps in the brand store
- Go to https://snapcraft-io-3983.demos.haus/admin/testGahNg0wohVae8aY4/snaps
- Check that the "Web and Design" store is included in the table
- Go to https://snapcraft-io-3983.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Check that "Test Store Team Store" and "Test Store Team Appliance" are included in the table
Fixes #2529
> Show all brand stores

- webapp/publisher/snaps/listing_views.py
- Fix listing page
As a publisher visit a snap listing page.
> Fix listing page

- static/js/publisher/release/components/releasesTable/cellViews.js
- static/js/publisher/release/components/releasesTable/droppableRow.js
- static/js/publisher/release/components/releasesTable/index.js
- static/js/publisher/release/components/releasesTable/releaseCell.js
- static/js/publisher/release/components/releasesTable/revisionCell.js
- static/js/publisher/release/components/releasesTable/revisionsRow.js
- static/js/publisher/release/components/revisionsList.js
- static/js/publisher/release/components/revisionsListRow.js
- static/sass/_snapcraft_release.scss
- static/sass/styles.scss
Implemented mobile designs for the release UI
- Go to https://snapcraft-io-3990.demos.haus/core/releases
- Resize to mobile size
- Check that it matches [the designs](https://app.zeplin.io/project/61b3231e21194c4a48005226/screen/61ddabca6985e510c8505f0a)
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2481, https://github.com/canonical-web-and-design/marketplace-tribe/issues/2483
> Split release table by channel

- templates/index.html
- templates/snapcraft/build.html
- templates/store/snap-details/_distro-instructions-for-snap-support.html
- webapp/store/content/distros/pop.yaml
- Added Pop!_OS
- Visit the demo
- Pop!_OS logo should be on the homepage
- Pop!_OS logo and link should be on the details pages
- https://snapcraft-io-4008.demos.haus/install/vlc/pop should work
> Add Pop!_OS

- requirements.txt
Update search to fix no results issue. This will unblock future `canonicalwebteam.search` renovate updates
- Go to https://snapcraft-io-4017.demos.haus/docs and use the search box to do a search e.g. "application"
- It should return results.
Fixes #
> Update search to fix no results issue

- static/sass/_patterns_icons.scss
- templates/store/snap-details/_details.html
Added new icons for the detail page metadata links
- Go to https://snapcraft-io-4025.demos.haus/notion-snap?show_metadata_links=true
- Check that the icons in the metadata links section look good
> Update icons for metadata links

- static/js/publisher/listing/components/App/App.test.tsx
- static/js/publisher/listing/components/App/App.tsx
- static/js/publisher/listing/components/CategoriesInput/CategoriesInput.test.tsx
- static/js/publisher/listing/components/CategoriesInput/CategoriesInput.tsx
- static/js/publisher/listing/components/CategoriesInput/index.ts
- static/js/publisher/listing/components/ListingDescriptionField/ListingDescriptionField.tsx
- static/js/publisher/listing/components/ListingFormInput/ListingFormInput.tsx
Added the categories component to the listing page form
- Go to https://snapcraft-io-4053.demos.haus/steve-test-snap/listing?show_react_listing=true (or any other snap)
- Check that there are category fields in the form
- Check that you can add and remove the second category fields
- Check that you can change the categories and that they save
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2646
> Add listing page category fields

- templates/brand-store/search.html
- templates/store/_media-object-snap-partial.html
- templates/store/_snap-header-information.html
- templates/store/publisher-details.html
- templates/store/snap-embedded-card.html
Removed the check for the show_star_dev arg. 
- Navigate to /josm
- MVO should have a star next to his name
Relevant to #2549
> Launch star developer feature

- .github/workflows/main.yml
- README.md
Updated master actions to main so it uses the correct branch
Fixes #4059
> Change master checks to main as they are failing

- static/js/publisher/listing/components/App/App.tsx
- static/js/publisher/listing/components/LicenseInputs/LicenseInputs.tsx
- static/js/publisher/listing/components/LicenseInputs/LicenseSearch.tsx
- static/js/publisher/listing/components/LicenseInputs/index.ts
- static/js/publisher/listing/components/ListingDescriptionField/ListingDescriptionField.tsx
- static/js/publisher/listing/components/MetricsInputs/MetricsInputs.test.tsx
- static/js/publisher/listing/components/MetricsInputs/MetricsInputs.tsx
- static/js/publisher/listing/components/MetricsInputs/index.ts
- static/js/publisher/listing/sections/AdditionalInformationSection/AdditionalInformationSection.tsx
- static/js/publisher/listing/sections/AdditionalInformationSection/index.ts
- static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
- static/js/publisher/listing/sections/ContactInformationSection/index.ts
- static/js/publisher/listing/sections/ListingDetailsSection/ListingDetailsSection.tsx
- static/js/publisher/listing/sections/ListingDetailsSection/index.ts
- static/sass/_snapcraft_p-autocomplete.scss
- static/sass/styles.scss
- webapp/licenses.json
- Created sections for each group of listing form fields
- Added the "Additional information" form fields
- Go to https://snapcraft-io-4064.demos.haus/steve-test-snap/listing?show_react_listing=true (or any snap)
- Change the licenses and check that they work as expected
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2651
> Add listing page metrics fields

- static/js/publisher/listing/components/App/App.tsx
Added the update metadata information to the React version of the listing page
- Go to a snap settings page (e.g. https://snapcraft-io-4070.demos.haus/steve-test-snap/settings)
- Make sure "Update metadata on release" is enabled
- Go to the snap listing page with the `?show_react_listing=true` query string (e.g. https://snapcraft-io-4070.demos.haus/steve-test-snap/listing?show_react_listing=true)
- Check that there is a warning notification on the page
- Make a change and click the "Save" button
- Check that you see a modal explaining the change to the snap metadata
- Click save changes and once the form has saved check that there is no warning notification on the page
- Go to the snap settings page (e.g. https://snapcraft-io-4070.demos.haus/steve-test-snap/settings)
- Check that "Update …
> Add update metadata messages

- static/js/publisher/listing/components/App/App.tsx
- static/js/publisher/listing/components/PreviewForm/PreviewForm.tsx
- static/js/publisher/listing/components/SnapIcon/SnapIcon.tsx
- static/js/publisher/listing/components/SnapIcon/index.ts
- static/js/publisher/listing/sections/ListingDetailsSection/ListingDetailsSection.tsx
- static/js/publisher/listing/utils/getChanges.ts
- static/js/publisher/listing/utils/getFormData.ts
- static/js/publisher/listing/utils/getListingData.ts
- static/js/publisher/listing/utils/index.ts
- static/js/publisher/listing/utils/validateImageDimensions.ts
- static/sass/_snapcraft_snap-icon.scss
- static/sass/styles.scss
- webapp/metrics/metrics.py
Added the snap icon upload component
- Go to https://snapcraft-io-4066.demos.haus/<SNAP_NAME>/listing?show_react_listing=true
- Check that you can upload and remove the icon and it saves
Fixes https://github.com/canonical/marketplace-tribe/issues/2642
> Add snap icon upload component

- static/js/publisher/listing/components/App/App.tsx
- static/js/publisher/listing/components/Screenshots/Screenshots.tsx
- static/js/publisher/listing/components/Screenshots/index.ts
- static/js/publisher/listing/sections/ListingDetailsSection/ListingDetailsSection.tsx
- static/js/publisher/listing/utils/getChanges.ts
- static/js/publisher/listing/utils/getFormData.ts
- static/js/publisher/listing/utils/getListingData.ts
- static/sass/_snapcraft_market_screenshots.scss
- static/sass/_snapcraft_snap-image-upload.scss
Added the image component to the listing page
- Go to: https://snapcraft-io-4080.demos.haus/[SNAP_NAME]/listing?show_react_listing=true
- Check that you can upload and remove screenshots
Fixes https://github.com/canonical/marketplace-tribe/issues/2643
> Add listing page screenshot component

- static/js/publisher/listing/components/App/App.tsx
- static/js/publisher/listing/components/CategoriesInput/CategoriesInput.tsx
- static/js/publisher/listing/components/ImageUpload/ImageUpload.tsx
- static/js/publisher/listing/components/ListingDescriptionField/ListingDescriptionField.tsx
- static/js/publisher/listing/components/ListingFormInput/ListingFormInput.tsx
- static/js/publisher/listing/components/SaveAndPreview/SaveAndPreview.tsx
- static/js/publisher/listing/components/Screenshots/Screenshots.tsx
- static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
- static/js/publisher/listing/sections/ListingDetailsSection/ListingDetailsSection.tsx
- static/js/publisher/listing/types/index.d.ts
- static/js/publisher/listing/utils/getListingData.ts
- templates/publisher/listing.html
Reinstated the listing page tour
- Go to https://snapcraft-io-4082.demos.haus/SNAP_NAME/listing?show_react_listing=true
- Check that the tour works
Fixes https://github.com/canonical/marketplace-tribe/issues/2652
> Reinstate listing page tour

- static/js/publisher/listing/components/Screenshots/Screenshot.tsx
- static/js/publisher/listing/components/Screenshots/ScreenshotList.tsx
- static/sass/_snapcraft_snap-image-upload.scss
- Fixed image upload square being dragged when empty
- Fixed broken remove button
- Go to https://snapcraft-io-4084.demos.haus/SNAP_NAME/listing?show_react_listing=true
- Check that you cannot drag empty screenshot squares
- Check that you can remove screenshots
> Fix screenshot thumbnails

- .github/pull_request_template.md
Removed the noise from the PR template
@Lukewh @jkfran if you have an objection to this that's fine, we can just close the PR
> Remove noise from PR template

- package.json
- yarn.lock
Reverted global nav version as the new one isn't showing on the site
- Go to https://snapcraft-io-4087.demos.haus/
- Check that global nav is there
> Revert global nav version

- static/js/publisher/listing/components/Screenshots/ScreenshotList.tsx
Fixed JS error for listing page screenshots
- Go to https://snapcraft-io-4091.demos.haus/SNAP_NAME/listing
- Open the browser console
- When opening the file selector to add a new screen shot, check that there is no related error in the console
Fixes https://sentry.is.canonical.com/canonical/snapcraft-io/issues/28450/?query=is%3Aunresolved and https://sentry.is.canonical.com/canonical/snapcraft-io/issues/28451/?query=is%3Aunresolved
> Fix JS error

- package.json
Bump Percy CLI version
Deploy and wait until the run tomorrow :D
Fixes #
> Update percy SDK version

- static/js/publisher/listing/components/ImageUpload/ImageUpload.tsx
Fixed a bug uploading a snap icon on the listing page
- Go to https://snapcraft-io-4097.demos.haus/SNAP_NAME/listing
- Upload a square icon
- It should work and not show an error message
Fixes #4095
> Fix image upload aspect ratio bug

- static/js/brand-store/Snaps/SnapsTable.js
- static/js/brand-store/Snaps/SnapsTableRow.js
- Updated checkboxes to contain labels
- Visit the demo and go to your stores page
- Select a store an ensure checkboxes in the table are properly aligned
Fixes #4092
> Update brand store checkboxes

- static/js/brand-store/Snaps/SnapsTable.js
- static/sass/styles.scss
- yarn.lock
Added a caption element to the snaps table
- Go to https://snapcraft-io-4102.demos.haus/admin
- Check that there is a `caption` element as the first child of the snaps table
- Check that the `caption` element is not visible on the screen
Fixes #4094
> Add a caption to the snaps table

- static/js/brand-store/Snaps/SnapsTable.js
- static/js/brand-store/Snaps/SnapsTableRow.js
- static/sass/_snapcraft_l-application.scss
- Fixed a z-index issue with the brand store side navigation and the global nav
- Fixed the toggle state of the brand store snaps table checkboxes
- Go to https://snapcraft-io-4103.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Check that the checkboxes on the table work as expected
Fixes #4093
> Brand store table checkboxes

- static/js/publisher/metrics/graphs/activeDevicesGraph/dataProcessing.js
- static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.js
Fixed metrics not showing on `/snaps` page
- Go to https://snapcraft-io-4110.demos.haus/snaps
Fixes #3669
> Fix empty metrics view

- static/js/brand-store/Snaps/SnapsTable.js
Fixed blank page when loading brand store admin page
- Go to https://snapcraft-io-4126.demos.haus/admin
- Check that you are redirected to the first store in your list which isn't the global store
Fixes #4124
> Fix brand store blank page

- static/js/brand-store/Members/Members.js
- static/js/publisher/collaboration/components/App/App.tsx
- static/sass/styles.scss
- webapp/publisher/snaps/collaboration_views.py
Built the active shares table for the collaborations tab
- Go to https://snapcraft-io-4139.demos.haus/<SNAP_NAME>/collaboration
- Check that there is an "Active shares" table inside an accordion
- **Note**: There is no data in the table as the endpoint isn't implemented
Fixes #4114
> Build active shares table

- static/js/publisher/collaboration/components/App/App.tsx
- webapp/publisher/snaps/collaboration_views.py
Built the collaborator invites table
- Go to https://snapcraft-io-4140.demos.haus/SNAP_NAME/collaboration
- Check that there is an "Invites" panel which contains a table
Fixes #4115
> Built collaborator invites table

- templates/_footer.html
> Remove link

- requirements.txt
> Remove sub dependencies from requirements.txt

- templates/store/community-publisher-details.html
- tests/store/tests_publisher.py
- webapp/store/views.py
- Added publisher pages for all publishers
- Visit https://snapcraft-io-4174.demos.haus/publisher/kde, https://snapcraft-io-4174.demos.haus/publisher/jetbrains, https://snapcraft-io-4174.demos.haus/publisher/snapcrafters and ensure they all work as expected (as before).
- Visit https://snapcraft-io-4174.demos.haus/publisher/lukewh, ensure the most important snaps in the snap universe are listed
- Visit https://snapcraft-io-4174.demos.haus/publisher/spotify, ensure only 1 snap is listed - spotify. Also see that the verified publisher icon is shown
- Visit https://snapcraft-io-4174.demos.haus/publisher/imamadeuppublisher, see that there are 0 snaps
- Visit https://snapcraft-io-4174.demos.haus/publisher/mvo and see that the star developer icon is shown
Fixes …
> feat(publishers): Publisher pages

- package.json
- yarn.lock
Vanilla patch update to fix logo bug referenced in the attached issue
- Go to https://snapcraft-io-4177.demos.haus/
- Resize to a mobile view
- Check that the logo is no longer under the global navigation
Fixes #4176
> Vanilla patch update

- webapp/authentication.py
- webapp/decorators.py
- Empty session data when use is not authenticated
Fixes: #3838
> fix(login): Clear all session data when login fails

- webapp/admin/views.py
- webapp/app.py
- webapp/handlers.py
- webapp/login/views.py
- webapp/publisher/snaps/build_views.py
- webapp/publisher/snaps/collaboration_views.py
- webapp/publisher/snaps/listing_views.py
- webapp/publisher/snaps/metrics_views.py
- webapp/publisher/snaps/publicise_views.py
- webapp/publisher/snaps/release_views.py
- webapp/publisher/snaps/settings_views.py
- webapp/publisher/snaps/views.py
- webapp/publisher/views.py
- webapp/store/snap_details_views.py
- webapp/store/views.py
- Register `StoreAPI`, `API` and `PublisherAPI` error handlers
- Remove all try... except blocks whose exceptions have been handled in the error handlers
-  Visit https://snapcraft-io-4180.demos.haus/
- This PR does not add or update any feature, neither does it fix a bug, it is a chore that can simply be validated by ensuring all routes still works as expected
- Also, by triggering an error in the application and checking to ensure the app does not crash but rather catches and handles the error(s) appropriately
Fixes #3230
> Wd 856 refactor try except

- requirements.txt
Added flake8 and black as dependencies
> Add flake8 and black as dependencies

- package.json
- static/js/base/dropdown-menu-toggle.js
- static/js/base/global-nav.js
- static/sass/styles.scss
- templates/_base-layout.html
- templates/_header.html
- yarn.lock
Updated the site navigation
- Go to https://snapcraft-io-4209.demos.haus/
- Check that the site navigation looks and works as expected
> Update site navigation

- webapp/admin/views.py
- append embedded-stores (stores that included) in the store snaps list
- go to /admin/store/nah4ahShap8aefie6pha/snaps
Fixes #4127
> append embedded-stores to snaps list

- static/js/brand-store/Snaps/Snaps.js
- webapp/admin/views.py
- Show included stores
- Visit https://snapcraft-io-4214.demos.haus/admin/nah4ahShap8aefie6pha/snaps
- See the list of stores below
- Visit another store, see the list is not there.
Fixes https://warthogs.atlassian.net/browse/WD-1256
> append embedded-store to snaps list

- webapp/store/views.py
- Add conditional for getting "media" object
- Run the app with the brandstore config (see BRANDSTORE.md for details).
> Fix issue with brand-store homepage

- tests/publisher/endpoint_testing.py
- tests/publisher/tests_agreement.py
- webapp/authentication.py
- webapp/publisher/views.py
- Redirecting to a page that requires you to be logged in when you are not logged in, isn't a great idea – redirect loop fun
- Visit https://snapcraft.io
- create a new account
- verify email address
- forever-redirect
- Visit [this demo](https://snapcraft-io-4238.demos.haus/)
- Login with your new account
- see agreement screen
- agree
- be logged in
- :rocket: 
Fixes #4232
Fixes #3838 
https://warthogs.atlassian.net/browse/WD-3153
https://warthogs.atlassian.net/browse/WD-1251
> Allow access to TOC page

- static/sass/_patterns_carousel.scss
- static/sass/_snapcraft_details_heading.scss
- static/sass/_snapcraft_show-more.scss
- static/sass/styles.scss
- templates/partials/_snap-details-image-layout.html
- templates/store/snap-details.html
- templates/store/snap-details/_details.html
- templates/store/snap-details/_distro-instructions-for-snap-support.html
- templates/store/snap-details/_snap_heading_data.html
Applied new design to snap details page
- Go to https://snapcraft-io-4244.demos.haus/spotify
- Compare the page to the [desktop](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/641089e2535a410e24e23467) and [mobile](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/64218ee29613f722d3e051c2) designs
Fixes https://warthogs.atlassian.net/browse/WD-2973
> Rebrand details page

- templates/_footer.html
- templates/about/publish.html
Applied new design to about publish page
- Go to https://snapcraft-io-4245.demos.haus/about/publish
- Compare the page to the [desktop](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/64108872f399ec0ea49d82f1) and [mobile](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/64217734ec18fe22449bc06a) designs
Fixes https://warthogs.atlassian.net/browse/WD-2959
> Add new design to about publish page

- templates/about/publicise.html
Applied the design on the about publicise page
- Go to https://snapcraft-io-4250.demos.haus/about/publicise
- Compare to the [desktop](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/64108883e570d80fd0acd4b5) and [mobile](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/6421773d2b57ee2256a95743) designs
Fixes https://warthogs.atlassian.net/browse/WD-2962
> Update design on about publicise page

- templates/store/categories/iot.html
- Go to https://snapcraft-io-4256.demos.haus/iot
- Check that the hero section matches [the design](https://www.figma.com/file/F7C9LauiU5INJxTkU4o9zy/23.04-Snapcraft-rebranding?node-id=759-45790&t=sCLbJRnuSxH19x5U-0)
> Add new design to IoT page hero section

- webapp/app.py
- webapp/config.py
Tidied up `app.py`, removing brand-store specific code
Visit the demo and make sure everything runs and the tests are ok
Fixes https://warthogs.atlassian.net/browse/WD-3705
> WD-3705 - Clean up initialisation

- templates/_footer.html
Add link to snapcraft.io github new issue
Visit the [demo](https://snapcraft-io-4267.demos.haus/), see the link in the footer.
Fixes #4242
> Add issue link

- requirements.txt
Revert the discourse module to the last known working version
> Revert discourse module

- webapp/store/content/publishers/snapcrafters.yaml
Updated snapcrafters to be starred
Visit https://snapcraft-io-4281.demos.haus/publisher/snapcrafters see the star next to the snapcrafters name
Fixes https://warthogs.atlassian.net/browse/WD-4423
Fixes https://github.com/canonical/snapcraft.io/issues/4236
> Update snapcrafters publisher page to be starred

- templates/snapcraft/build.html
Update message on /build
Visit https://snapcraft-io-4282.demos.haus/build
See the message at the top mentions 18.04
Fixes https://github.com/canonical/snapcraft.io/issues/4272
> Update /build message

- konf/site.yaml
Reverts canonical/snapcraft.io#4284
> Revert "Update site.yaml"

- static/js/publisher/release/components/releasesTable/cellViews.js
- static/js/publisher/release/components/releasesTable/releaseCell.js
- static/js/publisher/release/releasesState.js
Fixed issue where all channels showed as progressive releases
- Go to https://snapcraft-io-4290.demos.haus/pc/releases
- Select track "22" from dropdown on top left
- Only the first cell in the "AMD64" column should say progressive
Fixes https://warthogs.atlassian.net/browse/WD-4492
> Fix bug where all channels showing as progressive

- static/js/publisher/release/components/releasesTable/cellViews.js
- static/js/publisher/release/components/revisionsListRow.js
Fixed a bug where releases were not visible
- Go to https://snapcraft-io-4293.demos.haus/tdhnet/releases
- Check that releases are there
Fixes #4292
Fixes https://warthogs.atlassian.net/browse/WD-4555
> Fix missing releases

- static/sass/_snapcraft_market.scss
Fixed z-index issue with global nav and sticky bar
- Go to https://snapcraft-io-4295.demos.haus/<SNAP_NAME>/settings
- Open "All Canonical" from the top navigation
- The sticky bar shouldn't be showing through the dropdown menu
Fixes https://warthogs.atlassian.net/browse/WD-4591
> Fix sticky bar z-index

- static/js/brand-store/App/App.js
- static/js/brand-store/Model/Model.tsx
- static/js/brand-store/Model/ModelNav.tsx
- static/js/brand-store/Model/Policies.tsx
- static/js/brand-store/Model/index.ts
- static/js/brand-store/Models/Models.tsx
- static/js/brand-store/Models/index.ts
- static/js/brand-store/SectionNav/SectionNav.tsx
- static/js/brand-store/SigningKeys/SigningKeys.tsx
- static/js/brand-store/SigningKeys/index.ts
Added initial views for the model service UI
- Go to https://snapcraft-io-4299.demos.haus/admin/ahnuP3quahti9vis8aiw/models
- Go to https://snapcraft-io-4299.demos.haus/admin/ahnuP3quahti9vis8aiw/models/fakemodelid
- Go to https://snapcraft-io-4299.demos.haus/admin/ahnuP3quahti9vis8aiw/models/fakemodelid/policies
Fixes https://warthogs.atlassian.net/browse/WD-4733
Fixes https://warthogs.atlassian.net/browse/WD-4737
Fixes https://warthogs.atlassian.net/browse/WD-4741
> Add views for model service UI

- package.json
- static/js/brand-store/brand-store.js
- yarn.lock
Added Recoil JS to the brand store
- Go to https://snapcraft-io-4303.demos.haus/admin
- Check that the page renders without errors
> Setup recoil

- static/js/brand-store/components/App/App.tsx
- static/js/brand-store/components/Members/InvitesTable.tsx
- static/js/brand-store/components/Members/Members.tsx
- static/js/brand-store/components/Snaps/Snaps.tsx
- static/js/brand-store/components/Snaps/SnapsTable.tsx
- static/js/brand-store/components/Snaps/index.ts
- static/js/brand-store/selectors/index.ts
- static/js/brand-store/types/shared.ts
Renamed brand store types for consistency
- Go to https://snapcraft-io-4313.demos.haus/admin
- Make sure the app loads without errors
Fixes https://warthogs.atlassian.net/browse/WD-4872
> Rename brand store types for consistency

- static/js/brand-store/components/App/App.tsx
- static/js/brand-store/components/Model/Policies.test.tsx
- static/js/brand-store/components/Model/Policies.tsx
- static/js/brand-store/components/Model/policies-data.js
- static/js/brand-store/components/Models/Models.test.tsx
- static/js/brand-store/components/Models/Models.tsx
- static/js/brand-store/types/shared.ts
- static/js/brand-store/utils/getFilteredPolicies.test.ts
- static/js/brand-store/utils/getFilteredPolicies.ts
- static/js/brand-store/utils/index.ts
Added policies view
- Go to https://snapcraft-io-4322.demos.haus/admin/<STORE_ID>/models/<MODEL_ID>/policies
- Check that clicking the "Create policy" button opens a side panel
- Check that when the side panel is open the URL ends with "/create"
- Check that the side panel select field is disabled
- Check that the side panel "Add policy" button is disabled
- Check that the policies table is sortable by "Revision" and "Creation date"
- Check that the "Search policies" input filters the table and adds a "filter=" query parameter to the URL
Fixes https://warthogs.atlassian.net/browse/WD-4738
> Add policies view

- templates/index.html
Added link to survey on homepage
- Go to https://snapcraft-io-4323.demos.haus/
- Check that there is a "Give feedback" fixed to the right of the screen
- Check that that button takes you to a TypeForm survey
- Go to any other page of the site and make sure the button is not there
> Add link to survey

- templates/index.html
Reverts canonical/snapcraft.io#4323
User Research has already set this up through Google Tag Manager.
> Revert "Add link to survey"

- webapp/login/views.py
- Add a `developer_token` to session in`/login-beta`
- `developer_token` is for authenticating to the publisher gate way API
- Go to https://snapcraft-io-4320.demos.haus/login-beta and ensure that you're able to login normally
- Further QA will be done when the `model_services` endpoints are added
Fixes #
> add developer_token to session for /login-beta

- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/Models/Models.tsx
Fixed issue where validation error showed on create model form after new model created
- Go to https://snapcraft-io-4343.demos.haus/login-beta and login
- Go to https://snapcraft-io-4343.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Create a new model
- You should not see a validation error before the side panel closes
> Fix create model form validation error

- static/js/brand-store/components/Model/PoliciesFilter.test.tsx
- static/js/brand-store/components/Model/PoliciesFilter.tsx
- static/js/brand-store/components/Model/PoliciesTable.tsx
- static/js/brand-store/components/Models/ModelsFilter.test.tsx
- static/js/brand-store/components/Models/ModelsFilter.tsx
- Added tests for the models list filter and the policies list filter
- Drive by: Removed unused variables in policies table
> Model service tests

- static/js/brand-store/components/Model/ModelNav.test.tsx
Added tests for the `ModelNav` component
> Add tests for model service navigation

- static/js/brand-store/components/Model/PoliciesTable.test.tsx
- static/js/brand-store/components/Models/ModelsTable.test.tsx
Added tests for the model service models table and policies table
> Add tests for model service tables

- static/js/brand-store/components/Model/CreatePolicyForm.tsx
- static/js/brand-store/components/Model/Model.tsx
- static/js/brand-store/components/Model/Policies.tsx
- static/js/brand-store/components/Models/Models.tsx
- static/js/brand-store/components/Models/ModelsTable.test.tsx
- static/js/brand-store/hooks/index.ts
- static/js/brand-store/types/shared.ts
Converted queries for the model service to custom hooks so logic doesn't need to be duplicated
- Go to https://snapcraft-io-4352.demos.haus/login-beta and login
- Go to https://snapcraft-io-4352.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that models data loads as expected
- Go to a model page and check that the data loads as expected
- Go to a model policies page and check that the data loads as expected
> Model service hooks

- static/js/brand-store/components/Model/CreatePolicyForm.test.tsx
- static/js/brand-store/components/Model/Model.test.tsx
- static/js/brand-store/components/Models/CreateModelForm.test.tsx
- static/js/brand-store/components/Models/Models.test.tsx
Added tests for the model service creation forms
> Add tests for model service create forms

- static/js/brand-store/components/Members/Members.tsx
- static/js/brand-store/components/Model/CreatePolicyForm.tsx
- static/js/brand-store/components/Model/Model.tsx
- static/js/brand-store/components/Model/Policies.test.tsx
- static/js/brand-store/components/Model/Policies.tsx
- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/Models/Models.test.tsx
- static/js/brand-store/components/Models/Models.tsx
- static/js/brand-store/components/Settings/Settings.test.tsx
- static/js/brand-store/components/Settings/Settings.tsx
- static/js/brand-store/components/Snaps/Snaps.tsx
- static/js/brand-store/components/StoreNotFound/StoreNotFound.tsx
- static/js/brand-store/selectors/index.ts
- static/js/brand-store/types/shared.ts
- static/js/brand-store/utils/index.ts
- static/js/brand-store/utils/setPageTitle.ts
Added page titles for brand store views
- Go to https://snapcraft-io-4356.demos.haus/admin
- Go to various views and check they have an appropriate page title
> Set page titles in brand store

- static/js/brand-store/atoms/index.ts
- static/js/brand-store/components/App/App.tsx
- static/js/brand-store/components/Model/PoliciesTable.tsx
- static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
- static/js/brand-store/components/SigningKeys/DeactivateSigningKeyModal.tsx
- static/js/brand-store/components/SigningKeys/SigningKeys.tsx
- static/js/brand-store/components/SigningKeys/SigningKeysFilter.tsx
- static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
- static/js/brand-store/selectors/index.ts
- static/js/brand-store/types/shared.ts
- static/js/brand-store/utils/checkSigningKeyExists.test.ts
- static/js/brand-store/utils/checkSigningKeyExists.ts
- static/js/brand-store/utils/getFilteredPolicies.test.ts
- static/js/brand-store/utils/getFilteredSigningKeys.test.ts
- static/js/brand-store/utils/getFilteredSigningKeys.ts
- static/js/brand-store/utils/index.ts
- static/js/brand-store/utils/sortByDateDescending.test.ts
- static/js/brand-store/utils/sortByDateDescending.ts
Built the signing keys view in the models service
- Go to https://snapcraft-io-4361.demos.haus/login-beta and log in
- Go to https://snapcraft-io-4361.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys 
- Check that you can filter keys
- Check that you get a modal if you try to deactivate a key with models/policies
- Check that you can create a key
- Check that you can deactivate that key
Fixes https://warthogs.atlassian.net/browse/WD-4742
Fixes https://warthogs.atlassian.net/browse/WD-4743
Fixes https://warthogs.atlassian.net/browse/WD-4744
> Build signing keys view in the models service

- static/js/brand-store/components/Snaps/SnapsTableRow.tsx
- Go to https://snapcraft-io-4368.demos.haus/admin
- Check that there are no console errors
- Check that the "Latest release" column either has a value or a "-"
Fixes https://sentry.is.canonical.com/canonical/snapcraft-io/issues/38605/
> Safeguard version column in snaps table

- static/js/brand-store/components/Snaps/Snaps.tsx
Fixed bug where an undefined store stopped snaps table from rendering
- Go to https://snapcraft-io-4369.demos.haus/admin/test1LaNg1xi6eonae5R/snaps
- Check that the snaps table loads
> Fix undefined store in loop

- static/js/brand-store/components/Model/Policies.tsx
- static/js/brand-store/components/Models/Models.tsx
- static/js/brand-store/components/SigningKeys/SigningKeys.tsx
Change primary CTA in the model service
- Go to https://snapcraft-io-4372.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that the "Create new model" button is green
- Go to https://snapcraft-io-4372.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/steve_test_model_37/policies
- Check that the "Create policy" button is green
- Go to https://snapcraft-io-4372.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys
- Check that the "Create new signing key" button is green
Fixes https://warthogs.atlassian.net/browse/WD-5630
> Change colour of model service CTA

- static/js/brand-store/components/Model/CreatePolicyForm.tsx
- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
- static/sass/_snapcraft_l-application.scss
Changed styles of create panels in the models service
- Go to https://snapcraft-io-4375.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/create
- Check that the CTA is not pinned to the bottom of the viewport
- Go to https://snapcraft-io-4375.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/alimot_test_model_a/policies/create
- Check that the CTA is not pinned to the bottom of the viewport
- Go to https://snapcraft-io-4375.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys/create
- Check that the CTA is not pinned to the bottom of the viewport
Fixes https://warthogs.atlassian.net/browse/WD-5633
> Update styles of models service panels

- static/js/brand-store/components/Models/ModelsTable.tsx
- static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
- static/js/brand-store/utils/maskString.test.ts
- static/js/brand-store/utils/maskString.ts
Changed the width of the columns in the models and signing keys tables to better fit the content
- Go to https://snapcraft-io-4374.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that the table columns fit the content more appropriately
- **Note**: The space between the name and API key looks a bit weird, but we have to mask the API key so not sure what the best solution to this would be?
- Go to https://snapcraft-io-4374.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys
- Check that the table columns fit the content more appropriately
Fixes https://warthogs.atlassian.net/browse/WD-5639
> Change width of model service table columns

- static/js/brand-store/components/Model/Policies.tsx
- static/js/brand-store/components/Model/PoliciesTable.test.tsx
- static/js/brand-store/components/Model/PoliciesTable.tsx
- static/js/brand-store/selectors/index.ts
- webapp/admin/views.py
Added the ability to delete policies
- Go to https://snapcraft-io-4381.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/alimot_test_model_a/policies
- Check that you can delete a policy
> Enable delete policies

- static/js/brand-store/components/Model/Policies.test.tsx
- static/js/brand-store/components/Model/Policies.tsx
- static/js/brand-store/components/Models/Models.test.tsx
- static/js/brand-store/components/Models/Models.tsx
- static/js/brand-store/components/SigningKeys/DeactivateSigningKeyModal.tsx
- static/js/brand-store/components/SigningKeys/SigningKeys.tsx
- static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
Made sure that signing keys can be deleted and added some minor UX enhancements around loading tables
- Go to https://snapcraft-io-4382.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys
- Check that you can delete a signing key if it has no models or policies
Fixes https://warthogs.atlassian.net/browse/WD-5592
> Enable delete signing keys

- webapp/metrics/metrics.py
Update map colours as defined on https://app.zeplin.io/project/64107f86ec62b30f2acff2de/screen/6410888369eac80e60ef6309 
- Visit https://snapcraft-io-4387.demos.haus/
- Click on some snaps and check the maps at the bottom of the page
- Go to a snap you own, check the metrics page
- Compare to the listings page to make sure they're somewhat similar (there will be slight variation)
Fixes https://warthogs.atlassian.net/browse/WD-3418
> Update map colours

- webapp/metrics/metrics.py
- Fixed out of range error with metrics map
- Visit https://snapcraft-io-4390.demos.haus/vice-jz the page should load and display the metrics map
Fixes #4389
> Fix metrics out of range issue

- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/Models/Models.tsx
Fixed issue where the "Create model" form didn't submit when the enter key was pressed
- Go to https://snapcraft-io-4396.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/create
- Add a new model name
- Whilst still focused in the input, press "Enter"
- The form should submit and a new model should be created
Fixes https://warthogs.atlassian.net/browse/WD-5587
> Fix model form submission

- static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
- static/js/brand-store/components/SigningKeys/SigningKeys.tsx
Fixed issue where the "Create signing key" form didn't submit when the enter key was pressed
- Go to https://snapcraft-io-4395.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys/create
- Add a signing key name
- Whilst still focused in the input, press "Enter"
- The form should submit and either a new key will be created or there will be an error if the name exists
Fixes https://warthogs.atlassian.net/browse/WD-5591
> Fix signing key form submission

- static/js/brand-store/components/AppPagination/AppPagination.tsx
- static/js/brand-store/components/AppPagination/index.ts
- static/js/brand-store/components/Model/Policies.tsx
- static/js/brand-store/components/Model/PoliciesTable.tsx
- static/js/brand-store/components/Models/Models.tsx
- static/js/brand-store/components/Models/ModelsTable.tsx
- static/js/brand-store/components/SigningKeys/SigningKeys.tsx
- static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
- static/sass/_snapcraft_l-application.scss
- static/sass/_snapcraft_p-app-pagination.scss
- static/sass/styles.scss
Added new pagination to model service tables
- Go to https://snapcraft-io-4400.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that there is pagination and that it works as expected
- Go to https://snapcraft-io-4400.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/alimot_test_model_a/policies
- Check that there is pagination and that it works as expected
- Go to https://snapcraft-io-4400.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys
- Check that there is pagination and that it works as expected
Fixes https://warthogs.atlassian.net/browse/WD-5632
> Add new pagination to model service pages

- static/js/brand-store/components/Model/CreatePolicyForm.tsx
- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
Added a saving state when creating models, policies and signing keys
- Go to https://snapcraft-io-4403.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/create
- Create a model
- Check that the side panel form doesn't close until the model has been created
- Go to https://snapcraft-io-4403.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/policies/create
- Create a policy
- Check that the side panel form doesn't close until the policy has been created
- Go to https://snapcraft-io-4403.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys/create
- Create a signing key
- Check that the side panel form doesn't close until the signing key has been created
Fixes https://warthogs.atlassian.net/browse/WD-5586
Fixes https://warthogs.atlassian.net/browse/WD-5588
Fixes …
> Add saving state in model service

- static/js/brand-store/components/Model/CreatePolicyForm.tsx
- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
Fixed page titles in the model service
- Go to https://snapcraft-io-4404.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Open and close the create model panel
- Check that the page title changes appropriately
- Go to https://snapcraft-io-4404.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/alimot_test_model_a/policies
- Open and close the create policy panel
- Check that the page title changes appropriately
- Go to https://snapcraft-io-4404.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys
- Open and close the create signing key panel
- Check that the page title changes appropriately
Fixes https://warthogs.atlassian.net/browse/WD-6240
> Fix page titles in models service

- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/Models/ModelsTable.tsx
- static/js/brand-store/hooks/index.ts
- static/js/brand-store/types/shared.ts
Refactored the code for creating new models to use the [optimistic updates pattern from React Query](https://tanstack.com/query/latest/docs/react/guides/optimistic-updates) correctly
- Go to https://snapcraft-io-4408.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/create
- Create a model
- Check that the model is at the top of the table
- Check that the model is still at the top of the table
Fixes https://warthogs.atlassian.net/browse/WD-6318
> Refactor create model to use optimistic updates correctly

- static/js/brand-store/components/Model/CreatePolicyForm.tsx
- static/js/brand-store/components/Model/PoliciesTable.tsx
Refactored the code for creating new policies to use the [optimistic updates pattern from React Query](https://tanstack.com/query/latest/docs/react/guides/optimistic-updates) correctly
- Go to https://snapcraft-io-4409.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/i_am_creating_a_model_12/policies/create
- Create a policy
- Check that the policy is at the top of the table
- Check that the policy is still at the top of the table
Fixes https://warthogs.atlassian.net/browse/WD-6319
> Refactor create policy to use optimistic updates correctly

- static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
- static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
Refactored the code for creating new signing keys to use the [optimistic updates pattern from React Query](https://tanstack.com/query/latest/docs/react/guides/optimistic-updates) correctly
- Go to https://snapcraft-io-4410.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys/create
- Create a signing key
- Check that the signing key is at the top of the table
- Check that the signing key is still at the top of the table
Fixes https://warthogs.atlassian.net/browse/WD-6320
> Refactor create signing key to use optimistic updates correctly

- static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
- static/js/publisher/listing/utils/getChanges.ts
- static/js/publisher/listing/utils/getListingData.ts
- templates/store/snap-details/_details.html
- tests/publisher/snaps/tests_listing.py
- tests/publisher/snaps/tests_post_listing.py
- tests/publisher/snaps/tests_post_settings.py
- webapp/publisher/snaps/listing_views.py
- webapp/publisher/snaps/logic.py
- Go to https://snapcraft-io-4414.demos.haus/<SNAP_NAME>/listing
- Check that you can add and remove fields in the "Contact information" section and save the form
- Go to https://snapcraft-io-4414.demos.haus/<SNAP_NAME>
- Check that those links are present in the "Details for <SNAP_NAME>" sidebar
Fixes https://warthogs.atlassian.net/browse/WD-4432
> Enable metadata links

- static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts
- static/js/publisher/settings/components/App/App.tsx
- static/js/publisher/settings/utils/getFormData.ts
This reverts commit 1a02e6234a32a93d52321e830fceaa4a0ce0d62a.
> Revert "Save selected territories (#4420)"

- requirements.txt
Bumped discourse
- Make sure docs still work
Fixes #
> Bump discourse to 5.4.4

- static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
- static/js/publisher/listing/utils/getListingData.ts
- Fixed an issue where source code links weren't being displaying on the listing page
- Removed some unused code
- Go to https://snapcraft-io-4448.demos.haus/<SNAP_NAME>/listing
- Add a "Source code" link and save
- Check that the new link is displayed
Fixes https://warthogs.atlassian.net/browse/WD-7305
Fixes https://github.com/canonical/snapcraft.io/issues/4447
> Fix source code links not showing on the listing page

- templates/store/snap-details/_details.html
Fixed a bug where the listing page preview showed an internal server error
- Go to https://snapcraft-io-4449.demos.haus/<SNAP_NAME>/listing
- Click the "Preview" button
- Check that the page loads
Fixes https://warthogs.atlassian.net/browse/WD-7306
Fixes https://github.com/canonical/snapcraft.io/issues/4446
> Fix broken preview

- static/js/publisher/listing/components/App/App.tsx
- static/js/publisher/listing/utils/getListingData.ts
- static/js/publisher/preview.js
- static/js/publisher/state.js
- templates/store/snap-details.html
- templates/store/snap-details/_details.html
Fix the discrepancies between the preview listing page and the live listing page 
- Go to https://snapcraft-io-4450.demos.haus/<SNAP_NAME>/listing
- Click "Preview"
- Check that the screenshots/video section and the sidebar appear the same
Fixes https://warthogs.atlassian.net/browse/WD-7313
> Fix display of listing preview

- templates/store/beta.html
- webapp/store/views.py
Added a view for the beta store
- Go to https://snapcraft-io-4451.demos.haus/beta-store
- Check that there is a page there
Fixes https://warthogs.atlassian.net/browse/WD-7380
> Add beta store page

- static/js/store/components/Banner/Banner.tsx
- static/js/store/components/Banner/index.ts
- static/js/store/components/Packages/Packages.tsx
Add search to the beta store page
- Go to https://snapcraft-io-4455.demos.haus/beta-store
- Check that there is a search and it works as expected
Fixes https://warthogs.atlassian.net/browse/WD-7383
> Add beta store search

- package.json
- static/js/store/components/Packages/Packages.tsx
- static/js/store/data/categories.js
- static/sass/_patterns_p-filter-panel.scss
- static/sass/styles.scss
- yarn.lock
Added category filters to the beta store
- Go to https://snapcraft-io-4457.demos.haus/beta-store
- Check that there are category checkboxes and that they work as expected
- **Note**: _Books and reference_, _Finance_ and _Health and fitness_ return no results which is a [separate issue](https://warthogs.atlassian.net/browse/WD-7483)
Fixes https://warthogs.atlassian.net/browse/WD-7382
> Add filters to beta store

- static/sass/styles.scss
Fixed overflow issues for inline code
- Go to https://snapcraft-io-4459.demos.haus/docker
- Check that the inline code looks OK
- Go to https://snapcraft-io-4459.demos.haus/ondra-snap-ssh-debug
- Check that the inline code looks OK
Fixes https://warthogs.atlassian.net/browse/WD-7523
> Remove inline code overrides

- static/js/store/components/Packages/Packages.tsx
Fixed issue with pagination showing too many pages and pages being doubled
- Go to https://snapcraft-io-4460.demos.haus/beta-store
- Check that the pagination works as expected
Fixes https://warthogs.atlassian.net/browse/WD-7534
> Fix pagination issues

- package.json
- static/js/store/components/Packages/Packages.tsx
- static/js/store/types/index.d.ts
- static/js/store/types/shared.ts
- templates/store/beta.html
- webapp/store/views.py
- yarn.lock
Added featured snaps to beta store
- Go to https://snapcraft-io-4463.demos.haus/beta-store
- Check that there are featured snaps, similar to https://snapcraft.io/store
Fixes https://warthogs.atlassian.net/browse/WD-7479
> Add featured snaps to beta store

- static/js/base/navigation.js
If the call to /account.json fails - show sign in button
Fixes #
> If call to account.json fails - show sign in button

- package.json
- yarn.lock
Updated the store components package
> Update store components

- static/js/store/components/Packages/Packages.tsx
Added a non-functional sort by relevance filter
- Go to https://snapcraft-io-4482.demos.haus/beta-store
- Check that there is a "Sort by relevance" filter
> Add non-functional relevance filter

- package.json
- static/js/store/components/Packages/Packages.tsx
- yarn.lock
Added an architecture filter to the beta store
- Go to https://snapcraft-io-4488.demos.haus/beta-store
- Check that there is an architecture filter
Fixes https://warthogs.atlassian.net/browse/WD-7856
> Add architecture filter

- package.json
- static/js/store/components/Packages/Packages.tsx
- yarn.lock
Handled the categories on the beta store page
- Go to https://snapcraft-io-4487.demos.haus/beta-store
- Check that by default featured snaps are shown
- Check that searching, filtering and changing categories works as expected
> Handle categories

- templates/home/_fsf_ros2.html
- webapp/first_snap/content/ros2/package.yaml
- webapp/first_snap/content/ros2/snapcraft.yaml
- webapp/first_snap/content/ros2/test.yaml
- Update ros2 first snap example with core22 humble snap
- Fix typo in ros2 first snap test instructions
> update ros2 first snap with core22 humble snap

- Dockerfile
- Updated to node 20 in dockerfile from node 16
- Ensure the demo works as expected
Fixes #
> feat: update node from 16 to 20

- .github/workflows/pr.yml
- Ensure JS related checks succeed below
Fixes #
> feat: bump node in workflow to 20

- requirements.txt
Bumped canonicalwebteam.launchpad version to latest
Bumped humanize version to latest
- All checks pass
- The demo functions as intended
Fixes #
> chore: update canonicalwebteam.launchpad version and humanize version

- static/js/publisher/listing/components/App/App.tsx
- static/js/publisher/listing/components/MultipleInputs/MultipleInputs.tsx
- static/js/publisher/listing/components/UrlInput/UrlInput.tsx
- static/js/publisher/listing/components/UrlInput/index.ts
- static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
- static/js/publisher/listing/utils/getChanges.ts
Changed the `type` attribute on inputs of the listing page which should be `url`
- Go to https://snapcraft-io-4520.demos.haus/<SNAP_NAME>/listing
- Type a string which isn't a valid URL into either the "Websites", "Donations", "Source code", or "Issues" inputs
- Check that the field shows an error
Fixes https://warthogs.atlassian.net/browse/WD-8418
Fixes #4508
> Make inputs for websites on listing page URL

- static/js/brand-store/components/Snaps/Snaps.tsx
- static/js/brand-store/slices/membersSlice.ts
- static/js/brand-store/slices/snapsSlice.ts
- static/js/brand-store/store/index.ts
Made changing stores loading state more obvious and added title
- Go to https://snapcraft-io-4523.demos.haus/admin
- Change stores several times
- Check that each store has a title of the store name
- Check that when changing stores a loading state is shown
Fixes https://warthogs.atlassian.net/browse/WD-8187
> Show loading state when switching stores

- static/js/brand-store/components/App/App.tsx
- static/js/brand-store/components/Navigation/Navigation.tsx
- static/js/brand-store/components/NewTables/NewTables.tsx
- static/js/brand-store/components/NewTables/index.ts
- static/js/brand-store/components/SectionNav/SectionNav.tsx
- static/js/brand-store/components/Snaps/Snaps.tsx
Added new experimental table layout for snaps in the brand store behind a feature flag
- Go to https://snapcraft-io-4525.demos.haus/admin?showNewTables=true
- Check that the tables look and work as expected
Fixes https://warthogs.atlassian.net/browse/WD-8725
> New tables for brand store snaps page

- webapp/store/snap_details_views.py
- webapp/store/views.py
- 404 for `snap-quarantine` publisher page and snap pages
- The site should 404 for:
- https://snapcraft-io-4540.demos.haus/exodus
- https://snapcraft-io-4540.demos.haus/publisher/snap-quarantine
> feat: quarantine

- templates/home/_fsf_c.html
- templates/home/_fsf_electron.html
- templates/home/_fsf_flutter.html
- templates/home/_fsf_go.html
- templates/home/_fsf_java.html
- templates/home/_fsf_moos.html
- templates/home/_fsf_node.html
- templates/home/_fsf_pre-built.html
- templates/home/_fsf_python.html
- templates/home/_fsf_ros.html
- templates/home/_fsf_ros2.html
- templates/home/_fsf_ruby.html
- templates/home/_fsf_rust.html
- match first-snap-flow example code to documentation code
- Go to https://snapcraft-io-4539.demos.haus/
- Check if each language's first-snap-flow code matches to documentation code below:
- Python: https://snapcraft.io/docs/python-apps
- Pre-built apps: https://snapcraft.io/docs/pre-built-apps
- C/C++: https://snapcraft.io/docs/c-c-applications
- Go: https://snapcraft.io/docs/go-applications
- Java: https://snapcraft.io/docs/java-applications
- Node.js: https://snapcraft.io/docs/node-apps
- Electron: https://snapcraft.io/docs/electron-apps
- Flutter: https://snapcraft.io/docs/flutter-applications
- Ruby: https://snapcraft.io/docs/ruby-applications
- Rust: https://snapcraft.io/docs/rust-applications
- Moos: https://snapcraft.io/docs/moos-applications
- ROS: …
> match first-snap-flow code to documentation code

- static/js/publisher/listing/utils/getFormData.ts
On form submit, with new screenshots, rename all images to include a timestamp. There have been [reports](https://forum.snapcraft.io/t/possible-bug-in-image-management-in-the-snap-store/38516/5) of conflicting names such as "Screenshot.png" being uploaded on the same date being mixed up.
1. Go to your test snap, upload a new screenshot
2. When uploaded and saved visit your snap page, click the image to open in the lightbox
3. Right click on the image and ensure the image is suffixed with a string like `1709561589`.
4. Delete this image from your snap and save.
5. Upload the image again, save and follow 2 and 3 again. You should see a different string suffix.
Fixes https://warthogs.atlassian.net/browse/WD-8343
> fix: add timestamp to screenshots on upload

- webapp/publisher/snaps/metrics_views.py
- Hoisted default channel check to top of the method
- Removed "fix" for https://forum.snapcraft.io/t/metrics-by-channel-broken/26188/3
- if viewing "weekly_installed_base_by_channel" prefix any channel without a "/" with "latest":
- "stable", "candidate", "beta", and "edge"
- Compare multiple snap metrics to those on snapcraft.io some examples (that were part of the original issue and the forum post above):
| Snap | Demo | Production |
| --- | --- | --- |
| zoom-client | https://snapcraft-io-4551.demos.haus/zoom-client/metrics?active-devices=channel | https://snapcraft.io/zoom-client/metrics?active-devices=channel |
| ubuntu-frame | https://snapcraft-io-4551.demos.haus/ubuntu-frame/metrics?active-devices=channel | https://snapcraft.io/ubuntu-frame/metrics?active-devices=channel |
| code …
> fix: by-channel metrics legend missing latest track

- package.json
- static/sass/styles.scss
- yarn.lock
Update global nav to the latest version
- Go to https://snapcraft-io-4557.demos.haus/
- Open the global nav ("All Canonical")
- Check that the text is all visible
> Update global nav

- static/js/brand-store/components/Model/Model.tsx
- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/Navigation/Navigation.tsx
- static/sass/styles.scss
Updated the model views to match latest designs
- Go to https://snapcraft-io-4563.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/create
- Check that the "Create new model" side panel matches [the design](https://app.zeplin.io/project/659574cda0730e724877bf7d/screen/65ccf575d2088035c9ab4922)
- **Note**: The "Brand" section won't be visible as this isn't a "proper" store
- Go to https://snapcraft-io-4563.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models/testing
- Check that it matches [the design](https://app.zeplin.io/project/659574cda0730e724877bf7d/screen/65ccf5775c5b3df29e492452)
Fixes https://warthogs.atlassian.net/browse/WD-9960
> Update model view design

- static/js/brand-store/components/Snaps/IncludedSnapsTable.tsx
- static/js/brand-store/components/Snaps/PublishedSnapsTable.tsx
- static/js/brand-store/components/Snaps/Snaps.tsx
- static/sass/styles.scss
Applied [new design](https://app.zeplin.io/project/659574cda0730e724877bf7d/screen/65ccf575c11ebde092e501cf) to brand store snaps view
- Go to https://snapcraft-io-4559.demos.haus/admin
- Check that the tables for published and included snaps are inside accordions
Fixes https://warthogs.atlassian.net/browse/WD-9515
> Update brand store snaps view

- static/js/base/navigation.js
- static/js/brand-store/hooks/index.ts
- webapp/snapcraft/views.py
Removed `/account.json` endpoint in favour of `/account/publisher`
- Go to https://snapcraft-io-4569.demos.haus/ and login
- Check that your name is displayed in the header
- Go to https://snapcraft-io-4569.demos.haus/admin
- Check that your name is displayed at the bottom of the side navigation
> Remove account json endpoint

- webapp/store/views.py
Adds method to call create_track endpoint in StoreAPI repo ([StoreAPI PR](https://github.com/canonical/canonicalwebteam.store-api/pull/114)) 
I tested this endpoint with https://snapcraft.io/fran-snap/listing as I have permissions to do so. Please check attached images to verify that:
- tracks can be created (with `v\\.[0-9]+` guardrail)
- a track that already exists returns the expected response
- a track that does not conform to the guardrails returns an invalid response
Fixes https://warthogs.atlassian.net/browse/WD-9842
> WIP: Add post_create_track method

- webapp/publisher/views.py
Fix an error where the user agreement wasn't able to be accepted
- Go to https://snapcraft-io-4575.demos.haus/account/agreement whilst **not** logged in
- Check that you are taken to the login screen
- Login
- Check that you are taken back to /account/accept and are able to accept the agreement
Fixes #4572
> Fix unauthenticated agreement acceptance issue

- requirements.txt
- tests/admin/admin_endpoint_testing.py
- tests/admin/test_brand_store.py
- tests/admin/tests_models.py
- tests/admin/tests_update_featured_snaps.py
- webapp/admin/views.py
- webapp/authentication.py
- Add tests for update-featured-snaps endpoint
- Ensure all python tests are passing
Fixes #
> add tests for update-featured-snaps endpoint

- webapp/publisher/views.py
This reverts commit 31e82cdb7234537f2b721246fcde8303421418fb.
- Go to https://snapcraft-io-4578.demos.haus/account/agreement
- You should be redirected to login
> Revert "Fix unauthenticated agreement acceptance issue (#4575)"

- static/js/brand-store/components/AccountDetails/AccountDetails.tsx
- static/js/brand-store/components/AccountDetails/index.ts
- static/js/brand-store/components/App/App.tsx
- static/js/brand-store/components/Navigation/Navigation.tsx
Only show store navigation if user has stores
- Go to https://snapcraft-io-4584.demos.haus/admin
- Login with an account that has stores
- Check that there is a store selector in the sidebar and the relevant navigation items
- Go to https://snapcraft-io-4584.demos.haus/admin/account
- Check that there is a store selector in the sidebar and the relevant navigation items
- Go to https://snapcraft-io-4584.demos.haus/admin
- Login with an account that doesn't have any stores
- Check that there is no store selector in the sidebar or store related navigation items
- Go to https://snapcraft-io-4584.demos.haus/admin/account
- Check that there is no store selector in the sidebar or store related navigation items
Fixes https://warthogs.atlassian.net/browse/WD-9992
> Only show stores is publisher has stores

- redirects.yaml
- static/js/brand-store/components/Navigation/Navigation.tsx
- templates/_header.html
Updated links to the account details section
- Go to https://snapcraft-io-4587.demos.haus/
- Login, click on your username and then click "Account details"
- Check that you are taken to https://snapcraft-io-4587.demos.haus/admin/account
- Click on your username in the side navigation
- Check that you stay on the same page
> Update account details links

- static/js/publisher/release/actions/releases.js
- static/js/publisher/release/components/notification.js
- static/js/publisher/release/releasesController.js
- webapp/publisher/snaps/release_views.py
Fixed the error message display for releases
- Go to https://snapcraft-io-4593.demos.haus/landscape-client/releases
- Try to "Promote" any of the "latest/beta" to "latest/stable" and save (Don't worry, it won't work)
- Check that there is a real error message rather than `[object Object]`
> Fix error message for releases

- static/js/store/components/Packages/Packages.tsx
- Fix issue with beta store featured packages pagination
- Drive by: Fix issue with `ref` being passed to function component which doesn't work)
- Go to https://snapcraft-io-4598.demos.haus/beta-store
- Check that going to page 2 with the pagination retains featured snaps
Fixes https://warthogs.atlassian.net/browse/WD-10418
> Fix beta store featured snaps

- templates/store/snap-details/_report_snap_modal.html
Update the form that responses get sent to
Visit any snap on the demo and click the "report this snap" link towards the bottom of the page
Fill the form out
Let me know
Fixes https://warthogs.atlassian.net/browse/WD-10742
> Update snap feedback form to post to correct Google Form

- .github/workflows/pr.yml
- codecov.yml
Use codecov.yml
See the tests pass
Fixes #
> feat: use codecov config

- .github/pull_request_template.md
Modifies template to include a testing section
Check `.github/pull_request_template.md` and make sure testing section is included
Fixes https://warthogs.atlassian.net/browse/WD-11279
> Modify Github PR template for testing

- .github/pull_request_template.md
Updated the markdown in the PR template so checkboxes are shown
Check that the testing section of this template has checkboxes
> fix: Update markdown for PR template for checkboxes

- .github/workflows/coverage.yml
- jest.config.js
> feat: tics worflow

- .github/workflows/coverage.yml
> fix: workflow-typo

- .github/workflows/coverage.yml
Updated from lxd-ui to snapcraft.io 🙄
Fixes #
> fix: tics upload workflow

- .github/.jira_sync_config.yaml
> fix: Update .jira_sync_config.yaml

- .github/workflows/coverage.yml
> use main branch

- .github/workflows/coverage.yml
> Fix tics workflow

- codecov.yml
- Set threshold for test coverage
Test is not needed for this, as it is not a code change
Fixes #
> set coverage threshold

- package.json
- static/js/store/components/Packages/Packages.tsx
- static/js/store/components/Packages/__tests__/Packages.test.tsx
- static/js/store/mocks/index.ts
- static/js/store/mocks/test-categories.ts
- yarn.lock
Expanded categories filter when hidden categories are selected
- Go to https://snapcraft-io-4641.demos.haus/store
- Click "Show more" and select on of the lower categories
- Reload the page and the filters should already be expanded
Fixes https://warthogs.atlassian.net/browse/WD-11388
> fix: Expand category filters if selected not visible

- .github/workflows/pr.yml
The run dotrun test succeeds for this PR
Fixes #
> ci: dotrun-run pr check

- .github/workflows/pr.yml
- Added some additional checks using https://github.com/marketplace/actions/paths-changes-filter
- I QA'd by pushing changes to various files to ensure the linting and tests are triggered.
Fixes #
> ci: lint and test based on changed files

- .github/workflows/coverage.yml
- jest.config.js
Added python checks to be uploaded to tics
- Confirm that https://github.com/canonical/snapcraft.io/actions/runs/9283938138/job/25545330980 passed
- Check the TICS dashboard and see that on the 29th May the coverage bumped up
Fixes https://warthogs.atlassian.net/browse/WD-11385
> ci: add python coverage upload to tics

- README.md
Added links to python and JavaScript coverage
Fixes #
> docs: add links to coverage reports

- static/js/libs/debounce.ts
- static/js/libs/iframeSize.ts
- static/js/libs/mobile.ts
Converted some libs JS files to TypeScript to fix compiler errors
Fixes https://warthogs.atlassian.net/browse/WD-11623
> fix: Fix compiler warnings in libs JS

- static/js/base/dropdown-menu-toggle.ts
Converted file into an isolatedModule to fix a compiler error in the TiCS dashboard
Fixes https://warthogs.atlassian.net/browse/WD-11621
> fix: Made dropdown js an isoloated module to fix compiler error

- static/js/publisher/collaboration/components/App/App.tsx
- static/js/publisher/collaboration/index.tsx
Fixed the compiler errors in the publisher collaboration JS. The lines in question can be ignored as this isn't a fully developed/working feature yet.
The checks should all pass
Fixes https://warthogs.atlassian.net/browse/WD-11715
> fix: Fix compiler errors in publisher collaborators JS

- static/js/publisher/builds/components/repoConnect.js
- static/js/publisher/builds/repoDisconnect.js
- templates/publisher/_repo-disconnect-modal.html
Fixed compiler errors in publisher builds JS
Fixes https://warthogs.atlassian.net/browse/WD-11716
> fix: Fix compiler errors in publisher builds JS

- static/js/publisher/form/banner.js
Fixed compiler errors in publisher form JS
Fixes https://warthogs.atlassian.net/browse/WD-11718
> fix: Fix compiler errors in publisher form JS

- static/js/publisher/listing/components/CategoriesInput/CategoriesInput.test.tsx
- static/js/publisher/listing/components/CategoriesInput/CategoriesInput.tsx
- static/js/publisher/listing/components/ImageUpload/ImageUpload.tsx
- static/js/publisher/listing/components/LicenseInputs/LicenseInputs.tsx
- static/js/publisher/listing/components/LicenseInputs/LicenseSearch.tsx
- static/js/publisher/listing/components/ListingDescriptionField/ListingDescriptionField.tsx
- static/js/publisher/listing/components/ListingFormInput/ListingFormInput.tsx
- static/js/publisher/listing/components/MetricsInputs/MetricsInputs.test.tsx
- static/js/publisher/listing/components/MetricsInputs/MetricsInputs.tsx
- static/js/publisher/listing/components/MultipleInputs/MultipleInputs.tsx
- static/js/publisher/listing/components/PreviewForm/PreviewForm.tsx
- static/js/publisher/listing/components/Screenshots/Screenshot.tsx
- static/js/publisher/listing/components/Screenshots/ScreenshotList.tsx
- static/js/publisher/listing/components/Screenshots/Screenshots.tsx
- static/js/publisher/listing/components/UrlInput/UrlInput.tsx
- static/js/publisher/listing/index.tsx
- static/js/publisher/listing/sections/AdditionalInformationSection/AdditionalInformationSection.tsx
- static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
- static/js/publisher/listing/sections/ListingDetailsSection/ListingDetailsSection.tsx
Fixed compiler errors in publisher listing JS
Fixes https://warthogs.atlassian.net/browse/WD-11719
> fix: Fix compiler warnings in publisher listing JS

- static/js/publisher/builds/repoDisconnect.ts
Fixed compiler warnings is repoDisconnect.js
Fixes https://warthogs.atlassian.net/browse/WD-11716
> fix: Fix compiler warnings in repoDisconnect JS

- static/js/publisher/metrics/graphs/activeDevicesGraph/index.js
- static/js/publisher/metrics/metrics.ts
Fixed compiler warnings is metrics.js
> fix: Fix compiler errors for metrics JS

- static/js/publisher/metrics/graphs/installs.ts
Fixed compiler warnings is installs.js
> fix: Fix compiler warnings in publisher installs js

- static/js/publisher/metrics/graphs/activeDevicesGraph/dataProcessing.ts
Fixed compiler warnings is publisher active device graph data processing JS
> fix: Fix compiler warnings in active device graph data processing JS

- static/js/libs/channels.js
- static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.ts
Fixed compiler warnings is publisher active device graphs tooltips JS
> fix: Fix compiler warnings in active device graphs tooltips js

- static/js/publisher/metrics/graphs/activeDevicesGraph/dataProcessing.ts
- static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.ts
- static/js/publisher/metrics/metrics.ts
Fixed compiler warnings metrics graphs JS
> fix: Fix compiler warnings in metrics graphs JS

- static/js/publisher/release/helpers.ts
Fixed compiler warnings release helpers
> fix: Fix compiler warnings in release helpers

- static/js/publisher/release/actions/releases.ts
Fixed compiler warnings actions releases JS
> fix: Fix compiler warnings in actions releases JS

- static/js/publisher/release/components/ProgressiveReleaseProgressChart.tsx
- static/js/publisher/release/components/dnd.tsx
- static/js/publisher/release/components/releasesConfirm.tsx
Fixed compiler warnings releases components JS
> fix: Fix compiler warnings in releases components

- static/js/publisher/release/components/releasesTable/channelHeading.tsx
- static/js/publisher/release/components/releasesTable/droppableRow.tsx
- static/js/publisher/release/components/releasesTable/row.tsx
- static/js/publisher/release/helpers.ts
Fixed compiler warnings releases table JS
> fix: Fix compiler warnings in releases table JS

- static/js/publisher/tour/tourOverlay.tsx
Fixed compiler warnings publisher tour JS
> fix: Fix compiler warnings in publisher tour JS

- static/js/publisher/release/reducers/pendingReleases.ts
- static/js/publisher/release/selectors/index.ts
Fixed compiler warnings publisher release JS
> fix: Fix compiler warnings in publisher release JS

- package.json
- static/js/global.d.ts
- static/js/publisher/form.ts
- static/js/publisher/preview.ts
- static/js/publisher/publicise.ts
- static/js/publisher/release.tsx
- static/js/publisher/submitEnabler.ts
- webpack.config.entry.js
- webpack.config.rules.js
- yarn.lock
Fixed compiler warnings publisher JS
> fix: Fix compiler warnings in publisher JS

- static/js/global.d.ts
- static/js/public/snap-details/channelMap.ts
- static/js/public/snap-details/embeddedCard.ts
- static/js/public/snap-details/videos.ts
Fixed compiler warnings public snap details JS
> fix: Fix compiler warnings in public snap details JS

- webapp_beta/beta_app.py
Fixed the last Python compiler warning in TiCS
The checks should all pass
> fix: Fix last python compiler warning

- static/js/brand-store/components/AccountDetails/__tests__/AccountDetails.test.tsx
- static/js/brand-store/components/Members/__tests__/InviteModal.test.tsx
- static/js/brand-store/components/Navigation/__tests__/Navigation.test.tsx
- static/js/brand-store/components/Publisher/__tests__/Publisher.test.tsx
- static/js/brand-store/components/Reviewer/__tests__/Reviewer.test.tsx
- static/js/brand-store/components/ReviewerAndPublisher/__tests__/ReviewerAndPubliser.test.tsx
- static/js/brand-store/components/StoreNotFound/__tests__/StoreNotFound.test.tsx
- static/js/brand-store/hooks/__tests__/useBrand.test.ts
- static/js/brand-store/hooks/__tests__/useModels.test.ts
- static/js/brand-store/hooks/__tests__/usePolicies.test.ts
- static/js/brand-store/hooks/__tests__/usePublisher.test.ts
- static/js/brand-store/hooks/__tests__/useSigningKeys.test.ts
Increased the test coverage for the brand store JS
The tests should pass
Fixes https://warthogs.atlassian.net/browse/WD-11628
> chore: Increase code coverage for brand store JS

- static/js/publisher/listing/sections/AdditionalInformationSection/__tests__/AdditionalInformationSection.test.tsx
- static/js/publisher/listing/utils/__tests__/getChanges.test.ts
- static/js/publisher/listing/utils/__tests__/getFormData.test.ts
- static/js/publisher/listing/utils/__tests__/getListingData.test.ts
- static/js/publisher/listing/utils/__tests__/shouldShowUpdateMetadataWarning.test.ts
- static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts
- static/js/publisher/shared/SaveAndPreview/SaveAndPreview.test.tsx
- static/js/publisher/shared/UpdateMetadataModal/__tests__/UpdateMetadataModal.test.tsx
Increase test coverage for publisher JS
The tests should pass
> chore: Increase publisher JS code coverage

- .github/workflows/coverage.yml
Added `yarn install --immutable` step to the tics report workflow
Fixes #
> ci: install js deps for tics

- static/js/brand-store/components/Model/ModelBreadcrumb.tsx
- Fixed coding standard violations in brandstore model breadcrumb
- All checks should pass
Fixes #https://warthogs.atlassian.net/browse/WD-12469
> fix: fix coding standard violations in brandstore model breadcrumb

- static/js/brand-store/utils/checkModelNameExists.ts
- static/js/brand-store/utils/checkSigningKeyExists.ts
- static/js/brand-store/utils/isClosedPanel.ts
- static/js/brand-store/utils/setPageTitle.ts
- Added missing types on return functions in /static/js/brandstore
- All tests should pass 
Fixes #https://warthogs.atlassian.net/browse/WD-12528
> fix: add missing types on return functions in /static/js/brandstore

- static/js/publisher/listing/utils/formatFileSize.ts
- static/js/publisher/listing/utils/validateAspectRatio.ts
- Added missing return types on functions in /static/js/publisher/listing
- All tests should pass
Fixes #https://warthogs.atlassian.net/browse/WD-12529
> fix: add missing return types on functions in /static/js/publisher/listing

- requirements.txt
> chore: update storeapi version

- konf/site.yaml
> Update dns key name

- webapp/config.py
- webapp/handlers.py
Fix DNS verification token
- Go to https://snapcraft-io-4721.demos.haus/api/steve-test-snap/verify
- Check that the `primary_domain` field is `true`
- Go to https://snapcraft-io-4721.demos.haus/api/code/verify
- Check that the `primary_domain` field is `false`
> fix: Fix DNS verification token

- static/js/public/snap-details/videos.ts
- Added missing return types and avoided using any type in /static/js/public/snap-details
- All tests should pass
Fixes #https://warthogs.atlassian.net/browse/WD-12598
> fix: add missing return types and avoid using any in /static/js/public/snap-details

- static/js/global.d.ts
- static/js/publisher/release.tsx
- static/js/publisher/types/releaseTypes.d.ts
- Added interface definitions
- Added a missing function return type
- Added error handling when the container is not found 
- All checks should pass 
Fixes #https://warthogs.atlassian.net/browse/WD-12468
> fix: fix coding standard violations in /static/js/publisher/release.tsx

- static/js/publisher/listing/components/PrimaryDomainInput/PrimaryDomainInput.tsx
- static/js/publisher/listing/components/PrimaryDomainInput/__tests__/PrimaryDomainInput.test.tsx
- webapp/publisher/snaps/listing_views.py
Fixed bug where snap listing pages with no links don't show
- Go to https://snapcraft-io-4733.demos.haus/ros2-cli/listing
- Check that the page loads as expected
- Go to https://snapcraft-io-4733.demos.haus/steve-test-snap/listing
- Check that the page loads as expected
- Go to https://snapcraft-io-4733.demos.haus/code/listing
- Check that the page loads as expected
> fix: Fix DNS validation breaking snap page with no domain

- static/js/publisher/listing/components/PrimaryDomainInput/PrimaryDomainInput.tsx
- static/js/publisher/listing/components/PrimaryDomainInput/__tests__/PrimaryDomainInput.test.tsx
Uncommented previously broken test
Tests should all pass
> Enable all tests for primary domain

- static/js/publisher/listing/components/App/App.tsx
- static/js/publisher/listing/components/App/__tests__/App.test.tsx
- static/js/publisher/listing/components/App/mocks/mockListingData.js
- static/js/publisher/listing/components/ImageUpload/ImageUpload.tsx
- static/js/publisher/listing/components/MetricsInputs/MetricsInputs.test.tsx
- static/js/publisher/listing/components/MetricsInputs/MetricsInputs.tsx
- static/js/publisher/listing/components/PreviewForm/PreviewForm.tsx
- static/js/publisher/listing/components/PrimaryDomainInput/PrimaryDomainInput.tsx
- static/js/publisher/listing/sections/AdditionalInformationSection/AdditionalInformationSection.tsx
- static/js/publisher/listing/sections/AdditionalInformationSection/__tests__/AdditionalInformationSection.test.tsx
- static/js/publisher/listing/utils/getDefaultValues.ts
- static/js/publisher/listing/utils/index.ts
Fixed a bug where the save and revert buttons weren't disabled once a change had been reverted
- Go to https://snapcraft-io-4736.demos.haus/<snap_name>/listing
- Check that you can change fields, change them back to their original value and the "Save" and "Revert" buttons go back to being disabled
- It is known that it doesn't work for the licences field due to its complexity
Fixes https://warthogs.atlassian.net/browse/WD-12782
> fix: Fix form state bug on listing page

- requirements.txt
Bumps canonicalwebteam.discourse minor version
> chore: Bumps canonicalwebteam.discourse version

- static/js/store/pages/Packages/__tests__/Packages.test.tsx
Increased the code coverage for store JS
The tests should pass
> chore: Increase code coverage for store JS

- static/js/base/__tests__/ga.test.ts
Increased test coverage for base JS
> chore: Increase code coverage for base JS

- static/js/publisher/form.ts
- static/js/publisher/preview.ts
- static/js/publisher/release/components/releasesHeading.js
- static/js/store/pages/Packages/Packages.tsx
Fixed the remaining [compiler warnings from the TiCS dashboard](https://canonical.tiobe.com/tiobeweb/TICS/TqiDashboard.html#axes=ProjectGroup(PublicRepos),Project(snapcraft.io),Sub(static),Sub(js),Sub()&metric=tqiCompWarn)
- All checks should pass
> fix: Fix remaining JS compiler warnings from TiCS

- static/js/publisher/settings/components/App/App.tsx
> fix: Fix JS compiler warning from TiCS dashboard

- static/js/brand-store/components/AccountDetails/AccountDetails.tsx
- static/js/brand-store/components/App/App.tsx
- static/js/brand-store/components/AppPagination/AppPagination.tsx
- static/js/brand-store/components/Filter/Filter.tsx
- static/js/brand-store/components/Members/InviteModal.tsx
- static/js/brand-store/components/Members/InvitesTable.tsx
- static/js/brand-store/components/Members/Members.tsx
- static/js/brand-store/components/Members/MembersTable.tsx
- static/js/brand-store/components/Model/CreatePolicyForm.tsx
- static/js/brand-store/components/Model/ModelNav.tsx
- static/js/brand-store/components/Model/Policies.tsx
- static/js/brand-store/components/Model/PoliciesTable.tsx
- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/Models/Models.tsx
- static/js/brand-store/components/Models/ModelsTable.tsx
- static/js/brand-store/components/Navigation/Logo.tsx
- static/js/brand-store/components/Navigation/Navigation.tsx
- static/js/brand-store/components/Publisher/Publisher.tsx
- static/js/brand-store/components/Reviewer/Reviewer.tsx
- static/js/brand-store/components/ReviewerAndPublisher/ReviewerAndPublisher.tsx
- static/js/brand-store/components/Settings/Settings.tsx
- static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
- static/js/brand-store/components/SigningKeys/DeactivateSigningKeyModal.tsx
- static/js/brand-store/components/SigningKeys/SigningKeys.tsx
- static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
- static/js/brand-store/components/Snaps/PublishedSnapsTable.tsx
- static/js/brand-store/components/Snaps/Snaps.tsx
- static/js/brand-store/components/Snaps/SnapsFilter.tsx
- static/js/brand-store/components/Snaps/SnapsSearch.tsx
- static/js/brand-store/components/StoreNotFound/StoreNotFound.tsx
Address coding standards warnings from TiCS dashboard
> fix: Fix coding standards warnings from TiCS dashboard

- static/js/base/dropdown-menu-toggle.ts
- static/js/base/ga.ts
Fixed coding standards warnings from the TiCS dashboard in base JS
> fix: Fix base JS code standard warnings

- static/js/libs/debounce.ts
- static/js/libs/iframeSize.ts
- static/js/libs/mobile.ts
Fixed libs JS coding standards warnings from TiCS
> fix: Fix libs JS coding standards warnings from TiCS

- static/js/store/components/App/App.tsx
- static/js/store/components/Banner/Banner.tsx
- static/js/store/pages/Packages/Packages.tsx
- static/js/store/utils/getArchitectures.ts
- static/js/store/utils/getCategoryOrder.ts
Fix store JS coding standard warnings from TiCS
> fix: Fix store JS coding standards warnings from TiCS

- webapp/handlers.py
> fix: sentry - allow all errors

- static/js/public/about/listing.ts
- static/js/public/accordion.ts
- static/js/public/featured-snaps.ts
- static/js/public/first-snap-flow.ts
- static/js/public/fsf-language-select.ts
- static/js/public/ga-scroll-event.ts
- static/js/public/modal.ts
- static/js/public/nps.ts
Fixed coding standards warnings from TiCS dashboard in public JS
> fix: Fix TiCS coding standards warnings in public JS

- static/js/libs/debounce.ts
Fixed coding standards warnings in libs JS
> fix: Fix libs JS coding standards warnings

- static/js/store/pages/Packages/Packages.tsx
Fixed coding standards warnings in store JS
> fix: Fix store JS coding standards warning

- static/js/public/accordion.ts
- static/js/public/first-snap-flow.ts
- static/js/public/ga-scroll-event.ts
Fix coding standards warnings in public JS
> fix: FIx coding stanards warnings in public JS

- static/js/public/snap-details/channelMap.ts
- static/js/public/snap-details/embeddedCard.ts
- static/js/public/snap-details/videos.ts
- static/js/publisher/publicise.ts
Fixed coding standards warnings from TiCS dashboard in public JS
> fix: Fix coding standards warnings in public JS

- .github/workflows/coverage.yml
No need to upload TICs artifact
Fixes #
> fix: coverage.yml

- tsconfig.json
Add flag to ignore deprecations in TypeScript config
> fix: Update tsconfig to ignore deprecations

- static/js/publisher/listing/components/PrimaryDomainInput/PrimaryDomainInput.tsx
- webapp/store/snap_details_views.py
Fixed 500 when no website field
- Go to https://snapcraft-io-4772.demos.haus/api/yuki-iptv-unofficial/verify
- Check that there is a JSON response
Fixes https://warthogs.atlassian.net/browse/WD-13529
> fix: Fix 500 for verify endpoint

- static/js/libs/__tests__/arrays.test.ts
- static/js/libs/__tests__/events.test.ts
- static/js/libs/__tests__/shallowDiff.test.ts
- static/js/libs/arrays.ts
- static/js/libs/events.ts
- static/js/libs/formHelpers.ts
- static/js/libs/mouse.ts
- static/js/libs/shallowDiff.ts
- static/js/libs/throttle.ts
- static/js/public/snap-details/channelMap.ts
- static/js/publisher/metrics/metrics.ts
Converted libs JS to TypeScript
Fixes https://warthogs.atlassian.net/browse/WD-13492
> chore: Convert remaining libs JS to TypeScript

- static/js/config/swiper.config.ts
- static/js/public/featured-snaps.ts
- static/js/public/snap-details/reportSnap.ts
- static/js/public/snap-details/screenshots.ts
- templates/store/snap-details.html
Fixed compiler warnings and converted public JS to TypeScript
> fix: Fix public JS compiler warnings

- static/js/libs/fileValidation.ts
Converted filevalidation to TS
All checks should pass with the exception of the inclusive naming check
> chore: Convert libs JS to TS

- static/js/libs/events.ts
- static/js/public/snap-details/map.ts
Converted `map.js` to `map.ts`
> Convert map JS to TypeScript

- entrypoint
Removed production check from `entrypoint`
Checks should pass
Fixes https://warthogs.atlassian.net/browse/WD-13871
> fix: Remove production check in entryfile

- static/js/brand-store/components/Model/CreatePolicyForm.test.tsx
- static/js/brand-store/components/Model/Model.test.tsx
- static/js/brand-store/components/Models/CreateModelForm.test.tsx
- static/js/brand-store/components/Settings/Settings.test.tsx
- static/js/publisher/form/banner.test.js
- static/js/publisher/form/media.test.js
- static/js/publisher/listing/components/App/__tests__/App.test.tsx
- static/js/publisher/settings/components/App/__tests__/UnregisterSnapModal.test.tsx
- static/js/publisher/shared/SaveAndPreview/SaveAndPreview.test.tsx
Fixes failing tests
Fixes [WD-14127](https://warthogs.atlassian.net/browse/WD-14127)
> chore: fix failing tests

- package.json
- static/js/validation-sets/index.tsx
- static/js/validation-sets/pages/ValidationSet/ValidationSet.tsx
- static/js/validation-sets/pages/ValidationSet/index.ts
- static/js/validation-sets/pages/ValidationSets/ValidationSets.tsx
- static/js/validation-sets/pages/ValidationSets/index.ts
- static/js/validation-sets/routes/root.tsx
- templates/store/validation-sets.html
- webapp/store/views.py
- webpack.config.entry.js
- yarn.lock
Created an app shell for validation sets
**Note**: I know the logo isn't quite right - the app layout doesn't support the newer logo style so I'll address this separately.
- Go to https://snapcraft-io-4803.demos.haus/validation-sets
- Check that there is an empty application layout
- Go to https://snapcraft-io-4803.demos.haus/validation-sets/abc
- Check that there is an empty application layout
Fixes https://warthogs.atlassian.net/browse/WD-14112
> feat: Create validation sets app shell

- static/js/validation-sets/hooks/__tests__/useValidationSets.test.ts
- static/js/validation-sets/hooks/index.ts
- static/js/validation-sets/hooks/useValidationSets.ts
- static/js/validation-sets/index.tsx
- static/js/validation-sets/pages/ValidationSets/ValidationSets.tsx
- static/js/validation-sets/pages/ValidationSets/__tests__/ValidationSets.test.tsx
Added validation sets table and filter
- Go to https://snapcraft-io-4804.demos.haus/validation-sets
- You won't see the table unless you have validation sets so you'll have to trust the screenshot
Fixes https://warthogs.atlassian.net/browse/WD-14113
Fixes https://warthogs.atlassian.net/browse/WD-14114
> feat: Add validation sets table

- requirements.txt
- static/js/validation-sets/hooks/__tests__/useValidationSet.test.ts
- static/js/validation-sets/hooks/index.ts
- static/js/validation-sets/hooks/useValidationSet.ts
- static/js/validation-sets/pages/ValidationSet/ValidationSet.tsx
- static/js/validation-sets/pages/ValidationSet/__tests__/ValidationSet.test.tsx
- static/js/validation-sets/pages/ValidationSet/index.ts
- static/js/validation-sets/pages/ValidationSets/ValidationSets.tsx
- static/js/validation-sets/types/index.d.ts
- webapp/store/views.py
Created the validation sets page with a sequence selector
You can't QA without validation sets so you will have to trust the screenshot
Fixes https://warthogs.atlassian.net/browse/WD-14115
Fixes https://warthogs.atlassian.net/browse/WD-14116
> feat: Create validation set table

- security.txt
Updated the security email address
> chore: Update security email address

- static/js/validation-sets/pages/ValidationSet/ValidationSet.tsx
Fixed issue with stale data briefly showing when switching validation sets
See videos below
Before:
https://github.com/user-attachments/assets/2cc24b95-2daf-41df-8e83-34d27e01c233
After:
https://github.com/user-attachments/assets/dfe81156-e4a7-4cee-9c49-3542465a350a
> fix: Fix stale data error in validation sets

- security.txt
Updated the security expires date
Check that the expires date is in the future
> fix: Updated security expires date

- static/js/store/utils/getArchitectures.ts
Enabled RISC-V builds
- Go to https://snapcraft-io-4819.demos.haus/steve-can-test/builds/2576040
- The build result should be "Released"
Fixes https://warthogs.atlassian.net/browse/WD-8477
> chore: Enable support for RISC-V builds

- webapp_beta/beta_app.py
Fixed search
- Go to https://snapcraft-io-4820.demos.haus/
- Search for anything
> fix: Fix broken store search

- static/sass/_patterns_media-object--snap.scss
- templates/store/_media-object-snap-partial.html
- templates/store/categories/iot.html
- webapp/snapcraft/views.py
- Built /iot page according to the copy doc 
- Go to https://snapcraft-io-4815.demos.haus/iot and compare the page with the [copy doc](https://docs.google.com/document/d/1xP7yt-pVoKNCnV0eRoex6VitHN5SilDR5ArglKzlpUg/edit)
Fixes #https://warthogs.atlassian.net/browse/WD-6472
> feat: build /iot page

- webapp/handlers.py
update embedder policy to allow iframes
- Go to https://snapcraft-io-4841.demos.haus/lxd
- Verify the video loads
Fixes #[14425](https://warthogs.atlassian.net/browse/WD-14425)
> Update embedder policy to allow iframes

- webapp/handlers.py
Added the missing csp
- go to https://snapcraft-io-4852.demos.haus/grype
- Verify the gif is loaded correctly
- go to https://snapcraft-io-4852.demos.haus/syft
- Verify the gif is loaded correctly
Fixes [#14936](https://warthogs.atlassian.net/browse/WD-14936)
Fixes #4850
> feat: updated csp

- webapp/handlers.py
Update CORP so that other websites can use resources from snapcraft such as badges.
Fixes #[15591](https://warthogs.atlassian.net/browse/WD-15591)
> feat: Update Corp policy

- webapp/handlers.py
- Removed the security headers temporarily
- Make sure the demo doesnt crash
> feat: remove security headers temporarily

- webapp/handlers.py
- Removed the caching headers temporarily
- Make sure the demo doesnt crash
- [ x] No testing required (explain why):
> feat: remove caching temporarily

- webapp/handlers.py
- added the security headers and enabled caching
- make sure demo doesnt crash
> chore: added security headers back

- static/js/public/snap-details/channelMap.ts
updated the ChannelMap's type and updated the code that uses this type
- go to https://snapcraft-io-4905.demos.haus/lxd
- Verify that the channel  dropdown works
Fixes [#16882](https://warthogs.atlassian.net/browse/WD-16882)
> fix: Fixed the channel map type

- static/js/store/components/Banner/Banner.tsx
- static/js/store/components/EmptyResultSection/EmptyResultSection.tsx
- static/js/store/components/EmptyResultSection/index.ts
- static/js/store/components/PackageFilter/PackageFilter.tsx
- static/js/store/components/PackageFilter/index.ts
- static/js/store/components/PackageList/PackageList.tsx
- static/js/store/components/SearchInput/SearchInput.tsx
- static/js/store/components/SearchInput/index.ts
- static/js/store/pages/Packages/EmptyPackageSearch.tsx
- static/js/store/pages/Packages/Packages.tsx
- static/js/store/types/components/Store.d.ts
- static/js/store/types/index.d.ts
- static/sass/_snapcraft_packages.scss
- static/sass/styles.scss
Added empty state for the packages page. ([design](https://warthogs.atlassian.net/browse/WD-13856?focusedCommentId=546471))
- Go to https://snapcraft-io-4906.demos.haus/store
- Enter a search word that returns a result such as "test"
- Verify results snaps are shown
- Apply filters
- Verify proper results are shown
- Enter a search term that doesnt returns any result
- Verify the empty view is shown
Fixes [#13856](https://warthogs.atlassian.net/browse/WD-13856)
> feat: add empty state to the packages page

- package.json
- yarn.lock
updated store-components to fix starred developer issue
- go to https://snapcraft-io-4907.demos.haus/
- enter "Halloy" to the search
- verify the developer has star
Fixes [#WD-12776](https://warthogs.atlassian.net/browse/WD-12776)
> fix: updated store-components to fix starred developer issue

- webapp/publisher/snaps/publicise_views.py
Show a disabled view rather than 404 when viewing the publicise page of a private snap
- Go to the publicise page of a private snap: https://snapcraft-io-4914.demos.haus/<SNAP_NAME>/publicise
- Check that the page is disabled and has a notification
Fixes https://warthogs.atlassian.net/browse/WD-17101
> fix: Fix publicise view for private snaps

- package.json
- static/js/publisher-pages/components/Tour/Tour.tsx
- static/js/publisher-pages/components/Tour/TourStep.tsx
- static/js/publisher-pages/components/Tour/index.ts
- static/js/publisher-pages/pages/Listing/ListingDetails/ImageUpload.tsx
- static/js/publisher-pages/pages/Listing/ListingDetails/ListingDetails.tsx
- static/js/publisher-pages/pages/Listing/ListingDetails/Screenshots.tsx
- static/js/publisher-pages/pages/Listing/ListingForm/ListingForm.tsx
- static/js/publisher-pages/utils/index.ts
- static/js/publisher-pages/utils/listingTourSteps.tsx
- yarn.lock
Implemented a third-part library to handle the tour to combat styling issues and to make the component reusable
- Go to https://snapcraft-io-4916.demos.haus/<SNAP_NAME>/listing
- Check that the tour opens
- Click through the tour and check that it works as expected
- Once you have finished the tour and closed it, check that the question mark button in the bottom right re-opens the tour
Fixes https://warthogs.atlassian.net/browse/WD-17012
> Wd 17012 fix tour whitespace

- static/js/publisher/listing/components/ListingDetails/ListingDetails.tsx
- Fix error in listing page markdown
Fixes # https://github.com/canonical/snapcraft.io/issues/4611
> fix: fix bug in listing page markdown

- .eslintrc.js
- static/js/public/snap-details/lightbox.ts
Ignored metrics and publicise from the old publisher app as they will need significant refactoring and most likely structural changes across many files to prevent the TypeScript compiler from showing errors.
All checks (except inclusive naming) should pass
> fix: Fix TypeScript errors

- static/js/brand-store/components/Members/InvitesTable.tsx
- static/js/brand-store/components/Members/Members.tsx
- static/js/brand-store/components/Model/CreatePolicyForm.tsx
- static/js/brand-store/components/Model/Model.tsx
- static/js/brand-store/components/Model/PoliciesTable.tsx
- static/js/brand-store/components/Models/CreateModelForm.tsx
- static/js/brand-store/components/Settings/Settings.tsx
- static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
- static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
- static/js/brand-store/components/Snaps/Snaps.tsx
- static/js/brand-store/hooks/index.ts
- static/js/brand-store/slices/brandStoreSlice.ts
- static/js/brand-store/slices/currentStoreSlice.ts
- static/js/brand-store/slices/invitesSlice.ts
- static/js/brand-store/slices/membersSlice.ts
- static/js/brand-store/slices/snapsSlice.ts
- static/js/brand-store/utils/getPolicies.ts
- tests/admin/test_brand_store.py
- tests/admin/tests_models.py
- tests/admin/tests_policies.py
- tests/admin/tests_signing_keys.py
- webapp/admin/views.py
Changed the brand store API URL format to be consistent with other parts of the application
- Go to https://snapcraft-io-4961.demos.haus/admin
- Check that stores and snaps still load
Fixes https://warthogs.atlassian.net/browse/WD-18024
> chore: Change URL format for brand store API

- .github/workflows/pr.yml
- package.json
- tests/publisher/tests_get_package_metadata.py
- webapp/api/github.py
- updated python lint job 
- handle gzip responses
- make sure lint-python job runs and successfully finishes
- make sure test-python job runs and successfully finishes
https://warthogs.atlassian.net/browse/WD-17991
> fix python lint and test jobs

- webapp/publisher/snaps/metrics_views.py
Changed the template for the metrics view
- Go to https://snapcraft-io-4979.demos.haus/<SNAP_NAME>/metrics
- The page should load as expected
> fix: Fix metrics view

- static/js/publisher/hooks/__tests__/useBrandStores.test.ts
- static/js/publisher/hooks/__tests__/useInvites.test.tsx
- static/js/publisher/hooks/__tests__/useLatestActiveDevicesMetric.test.ts
- static/js/publisher/hooks/__tests__/useMembers.test.ts
- static/js/publisher/hooks/__tests__/useSnaps.test.ts
Added tests for publisher hooks
Fixes https://warthogs.atlassian.net/browse/WD-18398
> chore: Add tests for publisher hooks

- static/js/publisher/pages/Builds/RepoSelector.tsx
- static/js/publisher/types/index.ts
use orgs github name to connect them to github
Fixes [#WD-18902](https://warthogs.atlassian.net/browse/WD-18902)
> fix: use orgs github name to connect them to github

- static/js/publisher/pages/Build/__tests__/Build.test.tsx
Adds tests for the publisher build page
Fixes https://warthogs.atlassian.net/browse/WD-18828
> chore: Add tests for publisher build page

- jest.config.js
- package.json
- static/js/publisher/pages/Builds/__tests__/Builds.test.tsx
- yarn.lock
Adds test for publisher builds page
- All tests should pass
Fixes https://warthogs.atlassian.net/browse/WD-18829
> chore: Add tests for publisher builds page

- static/js/publisher/pages/Snaps/SnapsFilter.tsx
- static/js/publisher/pages/Snaps/__tests__/Snaps.test.tsx
- static/js/publisher/test-utils/RecoilObserver.tsx
- static/js/publisher/test-utils/brand-store-requests.ts
- static/js/publisher/test-utils/brand-store-responses.ts
- static/js/publisher/test-utils/index.ts
- static/js/publisher/types/shared.ts
Adds tests for the brand store snaps
Fixes https://warthogs.atlassian.net/browse/WD-18835
> chore: Add tests to brand store snaps

- static/js/publisher/pages/Listing/ListingDetails/ImageUpload.tsx
- static/js/publisher/pages/Listing/ListingDetails/ListingDetails.tsx
- static/js/publisher/pages/Listing/__tests__/Listing.test.tsx
Adds tests for publisher listing page
All tests (other than inclusive naming check) should pass
Fixes https://warthogs.atlassian.net/browse/WD-18835
> chore: Add tests for publisher listing page

- templates/publisher/metrics.html
Remove unused template
Fixes #
> fix: Remove unused metrics template

- static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx
- static/js/publisher/components/PublishedSnapSection/PublishedSnapSection.tsx
- static/js/publisher/components/PublisherMetrics/PublisherMetrics.tsx
- static/js/publisher/components/RegisteredSnaps/RegisteredSnaps.tsx
- static/js/publisher/pages/AccountSnaps/AccountSnaps.tsx
- static/js/publisher/pages/Snaps/Snaps.tsx
- static/sass/_snapcraft_metrics.scss
- static/sass/styles.scss
Update design of published snaps page
- Go to https://snapcraft-io-5040.demos.haus/snaps
- Check that each section is within an accordion [as per design](https://app.zeplin.io/project/659574cda0730e724877bf7d/screen/65ccf576441ff5de65c8de7c)
Fixes https://warthogs.atlassian.net/browse/WD-19670
> chore: Update design of published snaps page

- security.md
- security.txt
> chore: Update security.txt for SSDLC

- static/js/config/swiper.config.ts
- static/js/publisher/components/AppPagination/AppPagination.tsx
- static/js/publisher/components/EmptySnapList/EmptySnapList.tsx
- static/js/publisher/components/Filter/Filter.tsx
- static/js/publisher/components/NewSnapNotification/NewSnapNotification.tsx
- static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx
- static/js/publisher/components/PublishedSnapList/SnapNameEntry.tsx
- static/js/publisher/components/PublishedSnapSection/PublishedSnapSection.tsx
- static/js/publisher/components/PublisherMetrics/PublisherMetrics.tsx
- static/js/publisher/components/RegisteredSnaps/RegisteredSnaps.tsx
- static/js/publisher/components/SaveAndPreview/SaveAndPreview.tsx
- static/js/publisher/components/SaveStateNotifications/SaveStateNotifications.tsx
- static/js/publisher/components/SearchAutocomplete/SearchAutocomplete.tsx
- static/js/publisher/components/SectionNav/SectionNav.tsx
- static/js/publisher/components/StoreSelector/StoreSelector.tsx
- static/js/publisher/components/Tour/Tour.tsx
- static/js/publisher/components/Tour/TourStep.tsx
- static/js/publisher/components/UpdateMetadataModal/UpdateMetadataModal.tsx
- static/js/publisher/publisher.tsx
- static/js/store/components/Banner/Banner.tsx
- static/js/store/components/PackageFilter/PackageFilter.tsx
- static/js/store/components/PackageList/PackageList.tsx
- static/js/store/components/SearchInput/SearchInput.tsx
- static/js/store/hooks/usePackages.ts
- static/js/store/index.tsx
- static/js/store/utils/getArchitectures.ts
Addresses coding standards warnings from TiCS dashboard
> fix: Address coding standards warnings from TiCS dashboard

- webapp/publisher/cve/cve_views.py
Allows access to CVE API for users that have access to snap publisher info (publishers, admins, etc), who are Canonical team members.
- open demo, sign in with your Canonical account https://snapcraft-io-5093.demos.haus/
- make sure you can access docker snap: https://snapcraft-io-5093.demos.haus/docker/listing
- check if you get the CVE response for specific revision: https://snapcraft-io-5093.demos.haus/api/snaps/cve/docker/3180
> Allow access to CVE API for Canonical publishers

- static/js/base/ga.ts
- static/js/public/scroll-to.ts
- static/js/public/snap-details/embeddedCard.ts
Addressed TiCS coding standards warnings for public JS
- Added return types to functions
- Minor linting issues
- Removing unnecessary if statements
- All required checks should pass
- Go to https://snapcraft-io-5106.demos.haus/install/code/arch
- Click "Install"
- Page should scroll down
- Go to https://snapcraft-io-5106.demos.haus/code
- Click "Create embeddable card"
- A modal should open
> chore: Address TiCS coding standards warnings for public JS

- static/js/publisher/pages/Members/__tests__/InvitesTable.test.tsx
- static/js/publisher/pages/Members/__tests__/MembersTable.test.tsx
Adds tests for the publisher members and invites tables
Fixes https://warthogs.atlassian.net/browse/WD-21699
> chore: Add tests for publisher members

- static/js/publisher/pages/Members/__tests__/Members.test.tsx
- static/js/publisher/test-utils/brand-store-requests.ts
- static/js/publisher/test-utils/brand-store-responses.ts
Adds tests for publisher members
> chore: Add publisher members tests

- redirects.yaml
- Reorder redirects that don't work in prod
- Can't QA until merged (these are working locally and in demos but not in production)
> reorder redirects that are not working in prod

- static/js/store/components/SearchInput/SearchInput.tsx
- static/js/store/index.tsx
- static/js/store/pages/Explore/Explore.tsx
- static/js/store/pages/Explore/index.ts
- webapp/store/views.py
Adds template for explore page
- Go to https://snapcraft-io-5170.demos.haus/explore
- Check that there is a page at this URL
- Check that the search works and shows results on the /store page
Fixes https://warthogs.atlassian.net/browse/WD-22661
> feat: Add template for explore page

- requirements.txt
Updates store API package to include [this fix](https://github.com/canonical/canonicalwebteam.store-api/pull/152)
> chore: Update store API package

- package.json
- static/js/publisher/brand-store.tsx
- static/js/publisher/publisher.tsx
- yarn.lock
Installs Jotai and wraps brand store and publisher applications in a [Provider](https://jotai.org/docs/core/provider)
- Go to any brand store and publisher pages on the demo
- They should load and work as expected
Fixes https://warthogs.atlassian.net/browse/WD-23491
> chore: Install Jotai and add Provider

- redirects.yaml
Multiple doc sets link to these legacy paths.
> redirects: add snapcraft tutorial and reference roots

- static/js/publisher/components/Navigation/Navigation.tsx
- static/js/publisher/pages/AccountDetails/AccountDetails.tsx
- static/js/publisher/pages/AccountDetails/__tests__/AccountDetails.test.tsx
- static/js/publisher/state/publisherState.ts
- static/js/publisher/test-utils/JotaiTestProvider.tsx
- static/js/publisher/test-utils/index.ts
- static/js/publisher/test-utils/publisher-response.ts
Converts the publisher state from Recoil to Jotai
- Go to https://snapcraft-io-5209.demos.haus/admin/account
- Check that the page renders the appropriate account information
Fixes https://warthogs.atlassian.net/browse/WD-23495
> chore: Convert publisher state from Recoil to Jotai

- webapp/login/views.py
-  deleted a cookie that isnt used
- Verify you can login
- Verify you can logout
Fixes https://warthogs.atlassian.net/browse/WD-24169
> fix: deleted a cookie that isnt used

- tests/endpoints/tests_members.py
- webapp/admin/views.py
- webapp/app.py
- webapp/endpoints/members.py
Moves the snap store members endpoint to the endpoints section of the app
- Go to https://snapcraft-io-5261.demos.haus/api/store/ahnuP3quahti9vis8aiw/members
- Check that it is the same as https://snapcraft.io/api/store/ahnuP3quahti9vis8aiw/members
Fixes https://warthogs.atlassian.net/browse/WD-24119
> chore: Move snap store members endpoint to endpoints section of app

- tests/endpoints/tests_snaps.py
- webapp/admin/views.py
- webapp/endpoints/snaps.py
Moves the snap store snaps endpoint to the endpoints section of app
- Go to https://snapcraft-io-5262.demos.haus/api/store/ahnuP3quahti9vis8aiw/snaps
- Check that it is the same as https://snapcraft.io/api/store/ahnuP3quahti9vis8aiw/snaps
Fixes https://warthogs.atlassian.net/browse/WD-24117
> chore: Move snap store snaps endpoint to endpoints section of app

- tests/admin/tests_models.py
- tests/endpoints/tests_models.py
- webapp/admin/views.py
- webapp/endpoints/models.py
Moves the update model endpoint to the endpoints section of the app
- Go to https://snapcraft-io-5268.demos.haus/admin/ahnuP3quahti9vis8aiw/models/steve_test_model_2999933
- Generate a new API key and save
Fixes https://warthogs.atlassian.net/browse/WD-24125
> chore: Move update model endpoint to endpoints section of app

- tests/endpoints/publisher/tests_settings.py
- webapp/endpoints/publisher/settings.py
- webapp/publisher/snaps/settings_views.py
- webapp/publisher/snaps/views.py
Moves publisher settings endpoint to the endpoints section of the app
- Go to https://snapcraft-io-5278.demos.haus/api/steve-test-snap/settings
- Check that it is the same as https://snapcraft.io/api/steve-test-snap/settings
Fixes https://warthogs.atlassian.net/browse/WD-24598
> chore: Move publisher settings endpoint to endpoints section of app

- tests/endpoints/publisher/tests_settings.py
- webapp/endpoints/publisher/settings.py
- webapp/publisher/snaps/settings_views.py
- webapp/publisher/snaps/views.py
Moves the post publisher settings endpoint to the endpoints section of the app
- Go to https://snapcraft-io-5279.demos.haus/<snap_name>/settings
- Make changes and save them
Fixes https://warthogs.atlassian.net/browse/WD-24597
> chore: Move post publisher settings endpoint to endpoints section of app

- webapp/publisher/snaps/settings_views.py
Fixed an issue related to the one reported [here](https://github.com/canonical/snapcraft.io/pull/5181#issuecomment-3223247244) by @alvaromateo 
- visit https://snapcraft-io-5337.demos.haus/snaps
- pick one of your snaps
- go to the "settings" tab
- the form should be visible
- refresh the page
- the page should render correctly
Fixes #
> fix: do correct bool conversion on /<snap>/settings view

- webapp/vite_integration/impl/prod.py
changed variable names and changed a nested list comprehension into a more readable for loop to address @bartaz's [comment on the previous PR](https://github.com/canonical/snapcraft.io/pull/5349#discussion_r2324464932)
no need to QA
Fixes #
> fix: improve variable names

- tests/store/tests_publisher.py
Fix tests so that they work without internet connection.
- Get the changes in this branch
- Update your dotrun image for snapcraft.io by running `dotrun test` (you can CTRL+c when the tests start running)
- Disconnect your internet
- Run `dotrun test` and check that all the tests pass
Fixes [WD-24362](https://warthogs.atlassian.net/browse/WD-24362)
[WD-24362]: https://warthogs.atlassian.net/browse/WD-24362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-24362 - Fix test so that it works offline
